### ISSUE TITLE
Use PNG as tray icon under Linux

### ISSUE THREAD

**Issue by mrbiber** [wireapp/wire-desktop#1]
I've just tried to build the desktop app for Linux, but it crashes because it can't set the .ico file as tray icon. Replacing it with a PNG file works.

**Comment by bennyn** [comment]
@mrbiber Thanks for reaching out to us! Can you open a pull request with your PNG fix?

**Comment by lipis** [comment]
That didn't take too long! @bennyn we might need to get this PNG from our designers though..

**Comment by mrbiber** [comment]
I'm not really familiar with Node. I just replaced they file name in electron/js/menu/tray.js. But you'd probably want to keep the .ico for the other OSes, so there should be some conditionals in there. Sorry that I'm not of more help!

Perhaps like this:
`
   if (process.platform === 'linux') {
	appIcon = new Tray(pngIconPath);
    }
    else {
	appIcon = new Tray(iconPath);
    }`

But that's just me wildly guessing.

**Comment by mrbiber** [comment]
Under Ubuntu Unity,  `wire.internal.128.png` works fine as an icon

**Comment by lipis** [comment]
I think it will be safer to not support the tray icon at all on Linux than having something broken. So here is the fix #2 :D

**Comment by lipis** [comment]
Thanks @mrbiber 🐧

**Comment by lipis** [comment]
We just published our first Linux version [medium.com/wire-news/get-your-linux-on](https://medium.com/wire-news/get-your-linux-on-999403a1a4fe) :) Give it a shot..
