### ISSUE TITLE
Android: Unable to see/use text chat while in audio/video call

### ISSUE THREAD

**Issue by DetlevCM** [wireapp/wire-desktop#1000]
Something that has been an issue on Wire Android for a while:
When in an audio call, it is not possible to see or use the text chat. This makes sense if the user uses the phone like a phone, however becomes a problem when a headset is used.
The same is true for video calls.
So when I am sent a link while talking on Wire, there is no way for me to read it until I end the call...

As much as I dislike Skype in its current catastrophic form, this aspect is solved better there, as the user can chose to view the video/call screen or chat.

**Comment by mythsunwind** [comment]
This repository is dedicated to the desktop application. Please use the repository that is dedicated to the Android client for issues related to it: https://github.com/wireapp/wire-android

The mentioned issue has been addressed on the Android issue tracker several times:
https://github.com/wireapp/wire-android/issues/750
https://github.com/wireapp/wire-android/issues/829
https://github.com/wireapp/wire-android/issues/1056
