### ISSUE TITLE
BUG Desktop sharing

### ISSUE THREAD

**Issue by TheAresjej** [wireapp/wire-desktop#101]
Screen: http://imgur.com/b2cqLbQ

**Comment by ConorIA** [comment]
What does the picture show? The screen is lighter at the edge? Or that section is cut off?

**Comment by TheAresjej** [comment]
screen is cut off

**Comment by gregor** [comment]
You can switch between the fill modes by double clicking on the video.

**Comment by TheAresjej** [comment]
double clicking resizes vertical... this not solves the problem

**Comment by TheAresjej** [comment]
screen is cut off on the right side and glued to the left

**Comment by gregor** [comment]
As we have not been able to reproduce and have not had any additional reports, I am closing this for now.
