### ISSUE TITLE
Wire optimization for PureOS-based Librem 5 privacy-focused phone

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1011]
Purism has just reached its funding goal of $1.500.000 for the Librem 5, a new security and privacy focused phone. I would like to be able to use Wire on this phone and would like to encourage the Wire team to get in touch with Purism (if not already done) to optimize the app usage on PureOS. Would be great to leave this issue open so that others can tune in with suggestions.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have forwarded it internally for consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
