### ISSUE TITLE
Implement timer/reminder

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1017]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

When being in a audio or video chat session with clients there is currently no way to schedule reminders of the session length (e.g. after 45 or 50 minutes). Ideally, there would be an option to be reminded through an acoustic signal to be globally defined for an account. This is very important, especially for audio conversations, as I would not be looking at the screen to see how many minutes have passed or always having to check manually in a video conversation is distracting as well.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository, not a discussion board, and all developers get notified by each comment and will take time for reading and answering questions. We mainly want to keep this as a place to track bugs in our code.
