### ISSUE TITLE
Add whiteboard feature to discuss presentation materials

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1018]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

Very often I have to discuss presentation and lesson/lecture materials and it would be great to have a whiteboard feature where I could simply upload material to be visible for all parties in the video chat session. This is very different from a screen-sharing option. Ideally, the available screen space should be rearranged as well so that _both_ video screens, chat space and whiteboard space are equally visible during an active session.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
