### ISSUE TITLE
Display own video screen when being in chat mode

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1019]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

When being in chat-mode during a video chat session, only the video chat window of my conversational partner is visible. It would be great to offer an option to also see myself. This function is critical for any language teaching purposes. Currently, I have to constantly switch between chat mode and full screen video mode.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository, not a discussion board, and all developers get notified by each comment and will take time for reading and answering questions. We mainly want to keep this as a place to track bugs in our code.
