### ISSUE TITLE
Wire for Linux by default in German

### ISSUE THREAD

**Issue by matttbe** [wireapp/wire-desktop#102]
Hello,

First, thank you for developing Wire with a good GNU/Linux port!

I just updated Wire for Linux (wire-2.11.2663-amd64.deb) and now when I launch it, everything is in German :-)

A workaround exists as I was able to change the language via the Wire menu but it could be difficult for some people :-)

```bash
$ echo $LANG
fr_BE.UTF-8
$ echo $LANGUAGE
fr_BE:fr
```

**Comment by ConorIA** [comment]
It does seem that on a fresh build/install, the default language is German!

**Comment by matttbe** [comment]
> It does seem that on a fresh build/install, the default language is German!

Good way to force people to learn German :-)

**Comment by matttbe** [comment]
Note that my previous version was 2.11.2661 and I didn't have the problem.

**Comment by ConorIA** [comment]
2.11.2663 Introduced a bunch of new languages (thanks, Wire devs!), so something probably got switched by accident.

**Comment by matttbe** [comment]
Could maybe be due to that change: https://github.com/wireapp/wire-desktop/commit/aa9a45b8e6c49671b8ee3eacb63444bf5dc2058f#diff-1a1317cf782cfed75b185b163bc25533R63 → 'en' is no longer the first one.

**Comment by jacksarrocco** [comment]
Same issue

**Comment by lipis** [comment]
Fixed it in #98 (among other things)

**Comment by lipis** [comment]
deployed..

**Comment by matttbe** [comment]
Thanks!
