### ISSUE TITLE
Wire opens many tabs in Firefox on startup 

### ISSUE THREAD

**Issue by zorbathegreek** [wireapp/wire-desktop#1024]
Wire Version: wire-2.12.2729-x86_64.AppImage
OS: Fedora 26, 4.13.5-200.fc26.x86_64 fully updated
Do you have an antivirus software installed: No 

What steps will reproduce the problem?
1. Start Firefox (ver 56.0 64bit)

What is the expected result?
Firefox opens the homepage(s)

What happens instead?
Firefox opens the homepage(s) PLUS a wire.com tab Plus a wire.com tab Plus a wire.com ad infinitum
with this text:

"This browser is not supported.
Download the latest version of Google Chrome, Mozilla Firefox, Opera or MS Edge. Wire for macOS and Microsoft Windows are available from get.wire.com."

Please provide any additional information below. Attach a screenshot if
possible.

I clicked "Yes" lately when Wire asked me if I would like it to start Wire every time on start-up. Not sure if that question referred to "start the laptop/OS" or "start Firefox".  Clicking CTR+W closes these tabs one by one but new ones keep on opening. Pushing the mouse cursor into the bottom left screen corner opens a dialog where I can right click and quit Wire, which stops new browser tabs popping open (and shuts down Wire). 
Restarting Wire (ALT+F1, "wire", Enter) makes the browser tabs popping up once again. 
The latest App version is 2.17.2813-x86-64 
I'll try if using that fixes the issue.

**Comment by gregor** [comment]
Please update to the latest app version. We are at 2.17 as of today. The tab opening is unfortunate and we are looking into improving the experience for users running outdated versions.

**Comment by zorbathegreek** [comment]
Downloaded version 2.17.2813-x86-64, chmoded it with +x, and ran it with ./
It didn't open properly.
Here is the terminal output
[user@localhost ~]$ ls -lah wire*
-rwxrwxrwx. 1 user user  61M Mar 11  2017 wire-2.12.2729-x86_64.AppImage
-rw-rw-r--. 1 user user 104M Oct 11 12:36 wire-2.17.2813-x86_64.AppImage
[user@localhost ~]$ chmod +x wire-2.17.2813-x86_64.AppImage 
[user@localhost ~]$ ./wi
wire-2.12.2729-x86_64.AppImage
wire-2.17.2813-x86_64.AppImage
[user@localhost ~]$ ./wire-2.17.2813-x86_64.AppImage 
Failed to read log directory with error: ENOENT: no such file or directory, scandir '/home/user/.config/Wire/logs'
and Wire opened with an empty blue screen (!) see screenshot
![screenshot from 2017-10-11 12-42-16](https://user-images.githubusercontent.com/19348109/31436205-7b788e72-ae82-11e7-946c-e74911113fdc.jpg)
But when I do ls for that directory there is actually a file present: 
[user@localhost ~]$ ls .config/Wire/logs
68b27d3d-2c9a-4ab0-bda6-b54e1ff75838
(was that probably just created now?!)
Closing Wire from the terminal with CTR+C and restarting it with ./ at first gave me the same empty blue screen, but it "came alive" and reloaded my contacts and conversations. 

The new version of Firefox (freshly updated system see above) and me selecting the first tab in the Wire Window (named "Wire") then selecting "Lauch Wire on Startup" may have lead to a faulty behaviour. I am not going to select  "Lauch Wire on Startup" again now, unless someone (a developer?) ask me to do so, if it were to see if the faulty behaviour can be reproduced by that. At the moment it's working. I'll close this issue if no one replies within a while. 
Thanks for this app, I like it; not many people are using it it seems.
