### ISSUE TITLE
Encrypt account name and password and offer option to secure Wire with a master password

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1025]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

Currently, account name and password are stored unencrypted on the local hard drive. An attacker gaining access to the computer would have access to all Wire accounts and chat logs. Related to this is also an issue I've previously raised that there is no additional authentication when logging in to Wire. Instead one is not only connected instantly to the programme when starting the programme but also to all accounts which are stored on a specific computer without any further authentication. 

Proposed solution: 
1. Encrypt account name and password locally on the computer.
2. Enable option to key in master password to access the application. 
3. Enable option to individually authenticate each account and choose in the settings whether this should happen automatically (which is a good idea **if** a master password for the entire application can be set, so I am not against this per se) or manually (in case one doesn't opt for a master password and instead chooses to access Wire without master password).

**Comment by gregor** [comment]
Password is never stored locally - not encrypted nor unencrypted. When you login to the desktop app we authenticate with the backend and get a cookie with a certain lifetime which is later on used to authenticate and request tokens that are in turn used to authenticate individual backend requests.
