### ISSUE TITLE
Open source Wire servers

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1026]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

Currently, only the Wire client is open source whereas the server side is not, making independent and community-based security audits impossible.

**Comment by lipis** [comment]
What about this https://github.com/wireapp/wire-server?

**Comment by baimafeima** [comment]
@gregor My original post should have been called "not fully" opened sourced. As far as I understand the open source process is in progress but not completed. Do you have any ETA? Please advise. Thank you.

**Comment by lipis** [comment]
https://medium.com/@wireapp/wire-server-code-now-100-open-source-the-journey-continues-88e24164309c
