### ISSUE TITLE
Anonymity breach across multiple accounts

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1028]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

#278 
From one account I can see the connections I have in another account. On top it says "Top People" and below that it says "Connections". As part of these connections there appear people who are not in my account but in another. Please advise as soon as possible.

**Comment by gregor** [comment]
Please contact our support via the usual channel at https://support.wire.com so they can look at both of your accounts.  What you describe is technically not possible though in our implementation. Accounts do not talk to each other or share contacts with each other. There is no information leaks between accounts. Even if you use multiple accounts within the same desktop app, they run in completely independent environments on different browser sessions that do not even know the other exists. What you describe is technically not possible.

Are you using Wire on a mobile device? If you did share your address book with both accounts you might have been autoconnected to users of Wire who's phone number is matching a number in your address book.

**Comment by baimafeima** [comment]
> Even if you use multiple accounts within the same desktop app, they run in completely independent environments on different browser sessions that do not even know the other exists. What you describe is technically not possible.

Yes, I run multiple accounts within the same desktop app. 

> Are you using Wire on a mobile device? If you did share your address book with both accounts you might have been autoconnected to users of Wire who's phone number is matching a number in your address book.
No, I use the desktop version. 

I think I have tracked down the issue. I had previously added one contact in account A, then deleted that contact and added it in another account B. Despite having deleted the contact in account A, it is still visible under _Connections_ which should not be the case. It seems that after deleting a contact server data is **not** actually deleted.

**Comment by gregor** [comment]
There is no way to delete a contact. In Wire you can Block contacts. You probably only deleted the conversation content with said contact - the contact will then continue to remain in your list of connections. If you want to remove him from there, chose to block him.

**Comment by baimafeima** [comment]
> There is no way to delete a contact in Wire - you can Block contacts instead.

Why wouldn't you implement an option to delete a contact?

**Comment by gregor** [comment]
Because blocking has the same effect. You can no longer write to your contact. Your contact can no longer write to you. This was an early design decision from pre-launch 2014 that has not been changed and would have to be addresed by all clients at the same time.

**Comment by baimafeima** [comment]
Thanks for the clarification. This is quite confusing, especially since one cannot clearly tell from looking at the _Delete_ tag whether this will only delete a particular conversation or the actual contact. Had I known this earlier, I wouldn't have thought that there is an anonymity breach in the first place. Would be great to reconsider this design decision and implement an actual delete contact option.

**Comment by janedough1331** [comment]
This is absolutely not the same effect, and this is totally crazy that you say so.

Say I want to **remove any trace of contact between me and another party** but I don't want to block them. It is impossible, and it is not the same as blocking them. This is a huge privacy issue.
