### ISSUE TITLE
macOS file download could not overwrite existing files on save

### ISSUE THREAD

**Issue by garaboncias** [wireapp/wire-desktop#103]
on macOS when i download a file from a chat and i select an existing destination, wire wont overwrite it, just silently ignore, however "overwrite question" is popup and i select replace

**Comment by herrmannplatz** [comment]
Thanks for report, will have a look.

**Comment by helenakos** [comment]
@garaboncias This should be fixed with the new macOS release (coming soon).

**Comment by ffflorian** [comment]
@garaboncias We released a new version for macOS: https://itunes.apple.com/us/app/wire-private-messenger/id931134707. Can you check if the the error is fixed for you, too? Thanks!

**Comment by garaboncias** [comment]
unfortunately not, i select an existing file, select "replace" option, but
its only beep once and nothing happens.
L

**Comment by bennyn** [comment]
@garaboncias Can you please verify if the problem still exists with our latest macOS version ([2.15.2750](https://itunes.apple.com/app/wire/id931134707))? Because we cannot reproduce it.

**Comment by garaboncias** [comment]
first I had pre appstore version 2.13 and i cant update to 2.15 only from appstore. But after i update it i can still say that unfortunately it do not overwrite the existing file.

**Comment by ffflorian** [comment]
This should be fixed by now. If not, feel free to comment here and I'll re-open.
