### ISSUE TITLE
[Mac OS] Unsupported browser infinite loop

### ISSUE THREAD

**Issue by kennymalac** [wireapp/wire-desktop#1039]
Wire Version: 2.10.2652
Wire for Web Version: N/A
OS: Mac OS El Capitan 10.11.6 (15G31)
Do you have an antivirus software installed: No.

What steps will reproduce the problem?
1. Open wire
2. Shows unsupported screen, issue starts happening.

What is the expected result?
I want it to let me update software to newest version instead of saying browser is unsupported. I am using the native app. Redownloading entire app is not good at the moment because I am travelling so this kind of sucks!

What happens instead?
It shows the screen with the below text ON the app. My default browser is firefox and the app will open the wire.com/unsupported page multiple times and will keep doing so until I quit the app.
"
This browser is not supported.

Download the latest version of Google Chrome, Mozilla Firefox, Opera or MS Edge. Wire for macOS and Microsoft Windows are available from get.wire.com.
"

Please provide any additional information below. Attach a screenshot if
possible.
I would if I was not on 2G. :P

**Comment by gregor** [comment]
This is an unfortunate side effect of us blocking outdated browser versions. Please update to the latest release of Wire from the App Store. You are still running a version from August 2016.

**Comment by kennymalac** [comment]
Okay yeah, thanks, I updated through the app store. I was pretty confused because I had updated the app recently, i.e. this year thru the app and yet I am still on the old version. There is probably an issue with your auto-update service. Still strange that it would keep opening new tabs for old versions IMO.

**Comment by gregor** [comment]
We are working on improvements to our update experience. The update banner is not explaning well enough what it does. You only find that information by clicking on the link. Only the webapp component used within is updated using this mechanism. It is essentially a restart of the app triggering a fresh start with the latest webapp fround at https://app.wire.com. The actual app will have to be updated though the app store. We defintely need to improve how we communicate this.
