### ISSUE TITLE
Feature Request: Pop-up to answer, in-call pop-up (Linux Client)

### ISSUE THREAD

**Issue by MaCroX95** [wireapp/wire-desktop#106]
Hey guys!

It would be nice to see the Wire app to have some kind of pop-up setting when the call is incoming so we could answer the call from the system without having to open the app first and also a pop-up that is present on the screen when we're in the call to mute our microphone or end the call from there, also perhaps switch between Camera and Screen sharing!

Best regards,
MaCroX95

**Comment by shvchk** [comment]
I think Wire would benefit of this on all platforms, not only Linux.

**Comment by gregor** [comment]
Thanks again for your feature request. We will continue to track this internally. At this time we do not have any immediate plans to implement this feature. We will continue to evaluate on if and when to put a feature like this on the roadmap.
