### ISSUE TITLE
"Unsupported browser" Leads to a loop opening an infinite amount of tabs in the Linux desktop client

### ISSUE THREAD

**Issue by ekianjo** [wireapp/wire-desktop#1060]
Wire Version: Cannot find it, because of the mentioned bug that forces me to kill it, but I installed the latest package from wire.com (64 bits version) and the same problems occurs
OS: Linux Mint 17.3 (based on Ubuntu 14.04 LTS)
Do you have an antivirus software installed: None

What steps will reproduce the problem?
1. open the app
2. wait 2 seconds
3. pull your hairs out seeing your browser opening hundreds of tabs

What is the expected result?
Wire should start normally.

What happens instead?
Browser opens tons of tabs showing that "your browser is unsupported" even though I started the client application and not the web app version.

**Comment by ekianjo** [comment]
i have reproduced this issue on two different computers so this is probably not just related to my config.

**Comment by mythsunwind** [comment]
Can you check which package version you have installed? You can use the command `apt-cache show wire-desktop` for it.

**Comment by ekianjo** [comment]
I checked:
2.17.2813-2813
Description-md5: fb80b7f4a569d9dcec8cea05ffa2d378

**Comment by mythsunwind** [comment]
This is indeed the newest. Can you check if this is really the one that is opened? By running `which wire-desktop`

**Comment by ekianjo** [comment]
/usr/bin/wire-desktop

**Comment by nstoeckigt** [comment]
I have the same issue on several Debian machines:

```
> apt-cache policy wire
wire:
  Installiert:           2.11.2670-13
  Installationskandidat: 2.11.2670-13
  Versionstabelle:
 *** 2.11.2670-13 100
        100 /var/lib/dpkg/status
     0~20161027~0git287d8ca-1 990
        990 http://ftp5.gwdg.de/pub/linux/debian/debian stretch/main amd64 Packages
```

**Comment by gregor** [comment]
@nstoeckigt Please update to the latest release. The version 2.11 you are using is from February this year and is now exhibiting the unwanted experience as a side effect of updates to the webapp. It should work with 2.17 versions and we do not yet understand why @ekianjo is having the problem anyway.

**Comment by mythsunwind** [comment]
@nstoeckigt If you use debian you should definitely consider using our repository: https://github.com/wireapp/wire-desktop/wiki/How-to-install-Wire-for-Desktop-on-Linux#installation-on-debian-based-distributions

**Comment by ekianjo** [comment]
Still happening with Debian repository and all other downloads methods (amd64) - I tried removing, purging the package, remove all config files, etc... still nothing fixes this issue even with the latest 3.x version released 18 days ago.

**Comment by durumbumbum** [comment]
Same here, I've just downloaded the latest version from their website, opened it and same loop. Ubuntu 17.10

**Comment by Mr-Ples** [comment]
Same issue here, how do I stop the infinite loop without logging out?

**Comment by gregor** [comment]
Is this still happening to anyone?
