### ISSUE TITLE
collapse / move conversation list

### ISSUE THREAD

**Issue by kmwoley** [wireapp/wire-desktop#1069]
Wire Version: 2.17.2808
Wire for Web Version: 2017.10.19.1045
OS: Windows 10
Do you have an antivirus software installed: Avast

What steps will reproduce the problem?
1. No steps required - this is a feature request.

What is the expected result?
As a user, I want to have more of the screen space dedicated to conversation than the conversation list. This is particularly noticable with the window is small (i.e. snapped to the side of the screen)

What happens instead?
A lot of empty/unusable space.

Please provide any additional information below. Attach a screenshot if
possible.
![image](https://user-images.githubusercontent.com/6120312/31789180-22a3f5d0-b4c6-11e7-92af-2168fd8d4196.png)

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration and have certainly heard it before. At this time there are no plans to make changes to the current design.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository, not a discussion board, and all developers get notified by each comment and will take time for reading and answering questions. We mainly want to keep this as a place to track bugs in our code.
