### ISSUE TITLE
Significant battery drain on macOS

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#1071]
Wire Version: 2.15.2750
OS: macOS 10.13
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Run Wire

What is the expected result?

No significant battery drain.

What happens instead?

Significant battery drain.

Please provide any additional information below. Attach a screenshot if possible.

Wire consumes a lot of processing resources sitting idle doing nothing. This is a problem that I filed before, and is made worse when timed messages are present. For me it's to the point of choosing to quit wire because it's killing the laptop battery, or run wire and let it kill the laptop battery and so not be able to run anything.

Obviously this is not a good choice and you have some significant design issues to overcome.

This situation should never happen as shown below where there are no messages and Wire is consuming significant power resources. Even if there are timed messages, idle apps should not suck processor. Running timers is not significantly CPU draining if they are implemented correctly. If you implement them poorly they can suck a lot of power and cycles which is what seems to be the case.

Install iStat Menus in order to track processor usage and get battery drain reports.

<img width="248" alt="screen shot 2017-10-20 at 15 49 28" src="https://user-images.githubusercontent.com/5317653/31839670-23acd574-b5b0-11e7-8f2a-5908ee6a6e07.png">
<img width="757" alt="screen shot 2017-10-20 at 15 49 35" src="https://user-images.githubusercontent.com/5317653/31839671-23c58452-b5b0-11e7-84c8-d2c5617a2018.png">

**Comment by rbieb** [comment]
Same here. I'd much prefer a native app.

**Comment by tschoof** [comment]
![untitled](https://user-images.githubusercontent.com/750370/34103761-397b067a-e3ee-11e7-90ee-d15e526d7f44.png)
Agreed, that's not what you want to see from your **messaging app**

**Comment by vvv** [comment]
Wire desktop app version 3.1.2822; macOS Sierra 10.12.6.

`WindowsServer`, `Wire Helper`, and `Wire` processes consume too much of CPU during screen sharing (for both sides of the call): ‘Wire Helper’ and ‘Wire’ processes can reach 65%,  ‘WindowsServer’ is at 70–90%.  🔥 

<img width="561" alt="wire-cpu" src="https://user-images.githubusercontent.com/17462/34176766-d937c858-e509-11e7-8ca8-c1830597085f.png">

The app looks really nice, but I would be happy to use it. But I prefer conversations without the accompaniment of roaring fan. :)

**Comment by kmisiunas** [comment]
Same here. macOS 10.13.3

<img width="423" alt="screen shot 2018-02-15 at 17 15 23" src="https://user-images.githubusercontent.com/4820843/36270554-e045de0e-1273-11e8-8dc6-a494c58829d7.png">

<img width="445" alt="screen shot 2018-02-15 at 17 15 36" src="https://user-images.githubusercontent.com/4820843/36270563-e49ed726-1273-11e8-8f2a-d104aad24eb0.png">

**Comment by lamelas** [comment]
Bump. Same here. The only app consuming more power than Wire is Firefox. Anything that can be done?

**Comment by timmygee** [comment]
I also have High CPU utilisation when using Wire video chat on the macOS app.

Basically as soon as I start a video chat the CPU utilisation goes up significantly, the fans start becoming audible on my laptop and the battery drain is greatly increased.

I am running a Late 2015 Macbook Pro so it still has plenty of grunt so it's not that the computer can't cope with the extra demand, but no application should be performing like that.

It's not the first electron based app that seems to have this effect when running, so perhaps part of the blame is on the efficiency of Google's V8 engine but it's not ideal for Wire to be doing this and I feel like I'm reducing the lifespan of my laptop every time I start the program up.

**Comment by dbquarrel** [comment]
Doesn't even have to be video. 

Wire was just sitting there doing nothing and using 30% of my CPU. I quit and restarted it and went down to 10%. Even at 10% on a 2017 MBP this is way too much CPU use for idle state (of everything running on the computer, at 10% it's consuming the most energy of any app). 

Instant Messaging is a concept that has been around forever and we used to run things like AIM on crappy pentium boxes running Windows 3.1 without such problems. 

There shouldn't be any new features being developed or rolled out while this CPU issue is ongoing.

It's just as bad on the iPhone as my phone gets physically hot to the touch, bordering on painfully so, if I'm actively using Wire on it with 1 day expirations. You should be able to send instant messages without worrying if your phone is going to explode and catch fire. 

This has been an open issue forever and there is nothing on the horizon that says any effort will be made to address it. If Wire is going to blame electron for it, we should maybe post this thread over on electron and see what they have to say. If electron is really the problem then basically it's a terrible design decision to use this toolkit if it's going to burn out people's batteries. 

More people need to post this as feedback on the app store since there seems to be no desire to do anything about it here, or any other really major usability issue, in favor of adding bells and whistles for marketing purposes. 

Core functionality should never fall by the wayside for marketing item checklists.

**Comment by rbieb** [comment]
I have to agree.

I opened this issue a year ago: https://github.com/wireapp/wire-desktop/issues/598

First electron was blamed, but even after that turned out to be false, the wire guys never actually dealt with it. Instead, the problem still persists to this day.

It's a shame that very important issues like these are ignored, when they deal with the very basis of the app, and wire itself. These kinds of issues are making wire completely unsuable for a lot of people and I agree with you: they should be worked on with the highest priority.

**Comment by gregor** [comment]
Thanks for your feedback. We will continue to make incremental improvements in this area - but they are not the focus for us at this time.
