### ISSUE TITLE
File extension gets lost when downloading/saving files

### ISSUE THREAD

**Issue by kroerig** [wireapp/wire-desktop#1072]
Wire Version: 3.0.2828
Wire for Web Version: 2017.10.19.1045
OS: Windows 10 Pro / 1703
Do you have an antivirus software installed: Avast Free Antivirus

What steps will reproduce the problem?
1. Download/ Save a shared file (image/ video)

What is the expected result?
Wire should present a file name with a correct extension, e.g. jpg for an image

What happens instead?
Wire presents a filename without any extension. (s. screenshot)

![wire 2017-10-22 at 14 50 10](https://user-images.githubusercontent.com/5148795/31862191-2e52b80a-b73a-11e7-8b5b-4a930af83a12.png)

**Comment by gregor** [comment]
Fixed #1023 via https://github.com/electron/electron/pull/10469 in https://github.com/electron/electron/pull/10586.

This is part of the [3.1.2822](https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.1.2822) release
