### ISSUE TITLE
Can't build on Debian - 

### ISSUE THREAD

**Issue by tkrahn** [wireapp/wire-desktop#1074]
Wire Version: latest Git version (Oct 24. 2017)
Wire for Web Version: 
OS: Debian GNU/Linux buster/sid 64-bit 
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. git clone https://github.com/wireapp/wire-desktop.git
2. cd wire-desktop
3. npm install

What is the expected result?
A successful build of Wire Desktop

What happens instead?
The build process halts when compiling wire-desktop/electron with a Syntax error:

``
> wire-desktop@ install /home/thomas/src/wire-desktop
> cd electron && npm run rebuild-native-modules

> wireinternal@ rebuild-native-modules /home/thomas/src/wire-desktop/electron
> node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"

/home/thomas/src/wire-desktop/electron/rebuild-native-modules.js:37
let args = process.argv.slice(2);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wireinternal@ rebuild-native-modules: `node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wireinternal@ rebuild-native-modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2017-10-23T23_42_56_643Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wire-desktop@ install: `cd electron && npm run rebuild-native-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wire-desktop@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2017-10-23T23_42_56_716Z-debug.log

It seems like my version of node doesn't like the let statement.

/usr/bin/env node -v
v4.8.4

Any thoughts how to fix this?

**Comment by ffflorian** [comment]
> Any thoughts how to fix this?

Yes, please update to node >= 7.
