### ISSUE TITLE
--portable flag useless on Linux when installing from deb

### ISSUE THREAD

**Issue by linluc** [wireapp/wire-desktop#1075]
Wire Version: 3.0.2816
Wire for Web Version: 2017.10.19.1045
OS: Linux Mint 18.1, 64bit
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Download wire deb package. Here "wire_3.0.2816_amd64.deb" was used.
2. Install Wire from the deb package using either system built-in tools or manually via dpkg in terminal.
3. Run "wire-desktop --portable" as regular user

What is the expected result?

Wire starts up normally.  --portable flag should only change the location of the "data" directory.

What happens instead?

Nothing happens, Wire does not start.

Please provide any additional information below. Attach a screenshot if
possible.

Executing `strace -e trace=file wire-desktop --portable` shows the following lines at the end:

stat("/opt/wire-desktop/Data", 0x7ffc86051b40) = -1 ENOENT (No such file or directory)
mkdir("/opt/wire-desktop/Data", 0700)   = -1 EACCES (Permission denied)
stat("/opt/wire-desktop/Data", 0x7ffc86051b40) = -1 ENOENT (No such file or directory)
readlink("/opt/wire-desktop/Data/SS", 0x7ffc860505d0, 4096) = -1 ENOENT (No such file or directory)
readlink("/opt/wire-desktop/Data/SingletonLock", 0x7ffc860503d0, 4096) = -1 ENOENT (No such file or directory)
symlink("mint-twin1-4122", "/opt/wire-desktop/Data/SingletonLock") = -1 ENOENT (No such file or directory)
readlink("/opt/wire-desktop/Data/SingletonLock", 0x7ffc8604fff0, 4096) = -1 ENOENT (No such file or directory)
readlink("/opt/wire-desktop/Data/SS", 0x7ffc860505d0, 4096) = -1 ENOENT (No such file or directory)
readlink("/opt/wire-desktop/Data/SingletonLock", 0x7ffc860503d0, 4096) = -1 ENOENT (No such file or directory)
+++ exited with 0 +++

The reason of that behavior is that the directory where Wire got installed i.e. "/opt/wire-desktop" can only be written to by root. 3 possible solutions:

1. Allow Wire install in any user provided directory. Currently it seems impossible with a deb package as /opt/wire-desktop is hardcoded. At least I was unable to overwrite it with dpkg switches.

2. Add an internal option to specify user data directory for Wire. This is a more elegant solution. Firefox does this on both Windows and Linux - it separates program directory from user-specific data directory, the latter can be any path available to OS and is user configurable. 

3. Add another Wire switch e.g. "--data-path=" for providing custom data directory at start.

My goal is, if still not clear, to take full control over the Wire data directory and place it on an encrypted partition. Easy to do with Firefox, hopefully easy to do with Wire soon.

**Comment by ffflorian** [comment]
Forwarding this to @ConorIA, he implemented it in #427 :slightly_smiling_face:

**Comment by ConorIA** [comment]
Third option is the winner! #1078

**Comment by linluc** [comment]
Thanks! As soon as it makes the deb package I'll test it.

**Comment by gregor** [comment]
The feature was added in the latest release we published earlier today (3.3.2872).
