### ISSUE TITLE
Heart emojis displays in an incorrect way

### ISSUE THREAD

**Issue by pinki3** [wireapp/wire-desktop#1076]
Wire Version: 2.17.2808
Wire for Web Version: 2017.10.19.1045
OS: Windows 10 Enterprise
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?
1. Open a conversation
2. Type `:Heart:` or `<3` and space
3. Send message

What is the expected result?
The emoji shows up centered and not cropped as other emojis do.

What happens instead?
The emoji looks like in the attached image.
![wire bug](https://user-images.githubusercontent.com/6010328/31934021-2b0e3062-b8ab-11e7-87fd-db317ad74d92.PNG)

**Comment by maximbaz** [comment]
That's an interesting bug, but I'm afraid this is an issue in the Segoe UI Emoji font that Microsoft has to fix. 

Details: 

The font handles the heart _glyph_ correctly (try copy-pasting this `❤`, it will be rendered correctly), but according to the standard the heard _emoji_ must consist of the _two_ glyphs, the heart glyph above joined with the invisible glyph indicating that it is a colorful emoji (here are they ready for copy-paste `❤️`, this is rendered incorrectly on Windows 10). 

It would be a bad idea to ignore the standard and attempt to go with one glyph, strange things may happen, for example the heart could be black or have a wrong size. The proper way is to somehow let the people responsible for the font know about this problem and ask them to fix it.

**Comment by pinki3** [comment]
@maximbaz I guess it's on them to fix it then. I'll report it to MS.

(I tried pasting the one glyph, and sure enough it was handled correctly)
