### ISSUE TITLE
Feature Request: Facility to re-recognise old devices from back ups after data apocalypse.

### ISSUE THREAD

**Issue by OznipSlaugh** [wireapp/wire-desktop#1079]
Please implement a way to force Wire to take in a previous version of Wire from a back-up.

Or to force recognise an old device.

Make the feature 2FA. Jesus, Make it 3FA, I don't care, but please work a mechanism in that allows a user to make wire do this.

This is not backing up chat. That can be done with copy and paste. 

Previous points on this matter have had it very well if you lose them you lose them. But errors happen on boxes, terminals, laptops, beyond user control even when very careful.

A sort of stark all or nothing privacy crypto "Tough" does not work when a secure 

"Wire does not recognise this device, is this new or old, Y/N" "Y" 

"Please complete security procedure before Wire scans for previous" 
*Password
*Password
*Secret fuckin' riddle
*Long quest

"Wire will update from copy found on back-up*

Some times conversations happen before people can do their own backup and the people they were with are gone.

It is meaningful to be able to at least tell the thing it's not installed for the first time when there has been  a catastrophic data error.

And if you do implement it please allow it to work for previous versions.

**Comment by gregor** [comment]
Thank you very much for your feature request. This is definitely something we have heard before and that we have committed on adding to our team offering in 2018 (https://wire.com/features/).

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by OznipSlaugh** [comment]
This is a bug Gregor.

If you cannot redirect the program to reabsorb old logs after a forced reinstall or something. That is an unintended loss of data and therefore a bug, at least to me.
