### ISSUE TITLE
Temporary/disappearing messages still do not completely disappear on the senders side after the timer ran out.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-desktop#1081]
Wire version: 3.0.2828
Wire for web version: 2017.10.25.0708
Operating system: Win7x64

I've noticed a similar issue to this android-issue: https://github.com/wireapp/wire-android/issues/1077

When I send a temporary message which is about to expire after 1 day, it will turn into colored squiggles but retain the same word length and spaces. This is still a lot of information which we don't want to retain.

I would expect that the message gets completely deleted after the timer expired. Not only on the receivers side, but also on the senders side.

What kind of explanation justifies this behaviour when we want to rely on temporary messages for security reasons?

**Comment by gregor** [comment]
This is a reminder that there was a message on the sender side. It is a product/design decision to keep it there until it was also removed on the receiver side. We have no intentions of changing this. The conversation will clean it self up after time.
