### ISSUE TITLE
Click on the tray icon does not show/hide the window

### ISSUE THREAD

**Issue by rprots** [wireapp/wire-desktop#1085]
Wire version: 3.0.2816
Wire for web version: 3.0.2816
Operating system: Kubuntu 16.04

What steps will reproduce the problem?
1. Wire window is not shown.
2. Click on Wire tray icon.

What is the expected result?
Wire window is shown.

What is the actual result?
Wire window is not shown.

Please provide any additional information below. Attach a screenshot if
possible.
Related to https://github.com/electron/electron/issues/6773 problem.

**Comment by gregor** [comment]
This works as designed on other platforms. As this is related to an issue in electron itself, there will be no work done from our end.
