### ISSUE TITLE
Pulseaudio up to 43.8%

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1087]
Wire Version: 2.17.0-undefined
Wire for Web Version: 2017.10.25.0708
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

Even after finishing a video call pulseaudio remains extremely resource-heavy and is currently up to 43.8% when Wire is idle. This makes using Wire as a daily communication tool nearly impossible. 
```

 847     20   0 8492968  26988  21028 S  41.4  0.3 159:07.65 pulseaudio  
 7951     20   0 7906228 145112  85520 S  36.8  1.8  33:58.41 wire-deskt+ 
 8007     20   0 1781128 395528 119420 S   7.6  4.9  60:18.18 wire-deskt+
``` 

Wire-desktop itself is up to 36.8% as well.

**Comment by maximbaz** [comment]
The most annoying bug in the desktop app in my mind. 
I did some investigation on this issue a while ago and posted results in #598.

**Comment by baimafeima** [comment]
@maximbaz Thanks for cross-linking, looks like I've already posted in the other issue as well. Hope the Wire team can sort this out quickly. As of now, Wire is practically unusable on the desktop.

**Comment by gregor** [comment]
Well continue to monitor this in the linked issue.
