### ISSUE TITLE
[Linux] Notification tray icon is a square instead of circle

### ISSUE THREAD

**Issue by emuNAND** [wireapp/wire-desktop#1088]
Wire version: Any
Wire for web version: Any
Operating system: Linux, Distro is KDE Neon
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. Launch Wire
2. Examine the notification tray

What is the expected result?
The tray icon is the full Wire logo, the same one used in Windows and MacOS.

What is the actual result?
The tray icon is a square.

Please provide any additional information below. Attach a screenshot if
possible.
![image](https://user-images.githubusercontent.com/22921456/32401227-52125786-c0e1-11e7-96fa-8856e07de52b.png)
I've noticed this bug since Wire 2, and on different desktop environments including Gnome, KDE, Cinnamon, XFCE, and Mate.

**Comment by ElvisPresly** [comment]
Deepin 15.5
not accurate icon
![deepinscreenshot_ - _20171110145910](https://user-images.githubusercontent.com/18265958/32657979-e86b3256-c628-11e7-9ca0-b4d2b61a34d1.png)

**Comment by shvchk** [comment]
Can confirm (Ubuntu 17.04 and 17.10 + KDE)

**Comment by AtomicCons** [comment]
Gnome looks good on various flavours.
![image](https://user-images.githubusercontent.com/22971111/34637742-f3950d64-f279-11e7-9c61-1d716da5f166.png)
Side note, with Unity being dropped, created a pull request to fix notification. 
https://github.com/wireapp/wire-desktop/pull/1187

**Comment by gregor** [comment]
Closing this as it seems to be an issue with a very specific Linux distro setup.
