### ISSUE TITLE
Linux version ignores FHS

### ISSUE THREAD

**Issue by timur-davletshin** [wireapp/wire-desktop#109]
Current Linux version places nearly all files in `wire` folder of `/usr/share/` which is for architecture-independent data according to [FHS](http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf). Binary files like `Wire` executable and various `*.so` should be places in `/usr/lib/wire`.

P.S. Or there is another choice (not the best one, IMO) is to place everything in `opt`.

**Comment by 3n-mb** [comment]
@timur-davletshin "nearly all files" are, probably, Electron's files. Hypothetically, electron's engine can be shared.
Most of Wire's actual app files, like crypto things, are downloaded from a web page every single time. Which begs a question: is it a desktop app?

**Comment by lipis** [comment]
We are using  https://github.com/electron-userland/electron-builder to build the Linux executables so if there is something needs to be changed please escalate it there, as we don't have that in our priority list..
