### ISSUE TITLE
[macOS] Client is loading abnormally long

### ISSUE THREAD

**Issue by apfelbox** [wireapp/wire-desktop#1092]
**Wire version:** 3.0.2814
**Wire for web version:** 2017.10.25.0708
**Operating system:** macOS 10.13.0
**Which antivirus software do you have installed:** none

**What steps will reproduce the problem?**
1. Open client
2. wait

**What is the expected result?**
It should open.

**What is the actual result?**
It takes a very long time to load

**Please provide any additional information below. Attach a screenshot if
possible.**

I have wire clients installed on three MacBooks and on my personal notebook Wire loads extremely long on startup. It takes about 1-2 Minutes until the first loading screen is gone.

![2017-11-07 at 06 53](https://user-images.githubusercontent.com/1032411/32479138-b59fa084-c388-11e7-9675-9b9c3b8482f7.png)

In the the time it took me to open Github, search the repository, write and reformat this issue, the loading bar crawled to this new position:
![2017-11-07 at 06 57](https://user-images.githubusercontent.com/1032411/32479201-00dfe590-c389-11e7-9160-85d54fab6600.png)
This illustrates exactly how long it loads.

Any idea? Can I provide any additional info?
Please note, that this wasn't this bad in the past. I can't say for sure whether it came from the macOS update or from a Wire update or something else though.

**Comment by gregor** [comment]
When did you last use this particular client? How many messsages did you receive in the meantime and how many actions did you do yourself on one of your other clients if you have a mobile phone or another computer? What happens between those to screenshots is the decryption of events. The more actions you missed while you where not logged in, the longer it will take. We are aware of some cases where decryption takes much longer than it should but if you had not used the client for a couple of days a few minutes is actually expected at this point in time. We are continueously working to improve this.

**Comment by apfelbox** [comment]
I didn't use it for about 2-3 weeks. The decryption is especially slow on this MacBook, but I have another machine, which is a beefy Windows i7 6i00K and even there it isn't exactly fast.

Ok, but if these are known "issues" (or at least pain points) I guess we can close this issue.

Thanks for your response. 👍

**Comment by gregor** [comment]
Thanks for the update. We know that it is a pain and will continue our efforts to improve the experience.
