### ISSUE TITLE
Option to choose custom notification sounds

### ISSUE THREAD

**Issue by zaari** [wireapp/wire-desktop#1094]
The mobile app lets you to choose ringtone, text tone and ping sound. Having the same freedom on the desktop app would be great.

**Comment by gregor** [comment]
I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code and not for feature requests.

**Comment by rauldipeas** [comment]
Would be great if we have this option.
