### ISSUE TITLE
Language choice gets forgotten in case of logout with Wire still open

### ISSUE THREAD

**Issue by Plastikente** [wireapp/wire-desktop#1097]
Wire version: 3.0.2816 (AppImage)
Wire for web version: 2017.11.07.0850
Operating system: openSUSE 42.3
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. Change Wire's language
2. Logout from your DE session (Plasma, Xfce, ...) without closing Wire
3. Login and launch Wire again

What is the expected result?
Wire should be in the previously selected language.

What is the actual result?
Wire is in English.

If I quit Wire before logout, it remains in the correct language.

**Comment by shvchk** [comment]
Same problem on multiple computers running Ubuntu 17.04 and 17.10, Wire installed from official repo `deb https://wire-app.wire.com/linux/debian stable main` (now on 3.0.2816-2816). Users on these computers don't log out, they reboot instead. The problem does not always appear, but I've noticed that when it does, `~/.config/Wire/init.json` (which is where `locale` setting is stored) is empty, so probably Wire does not handle forceful process termination well, wiping this file and causing this. I've tried to reproduce this killing Wire processes manually, but haven't succeeded (but then again, it does not always reproduce on reboot either, could need 10 reboots to happen).

**Comment by shvchk** [comment]
Still having problems with this. @gregor might be interested as he tried to fix this back in November. Is there anything we could help to fix this?

Now using a simple script in autostart as a workaround:

```bash
#!/bin/bash

FILE="${HOME}/.config/Wire/init.json"
[[ -s $FILE ]] || echo '{"locale":"ru"}' > $FILE
```

**Comment by shvchk** [comment]
On Windows 10 (tested on 3 machines) it's even worse: language choice is not saved even after proper Wire exit.

1. Start Wire
2. Choose language other than English
3. Quit Wire
4. Start Wire again

I workaround this writing `{"locale":"ru"}` to `%APPDATA%\Wire\init.json` and making it read-only.

**Comment by gregor** [comment]
We changed the settings persistation with the releases we published today. This issue should have been addressed as well. Can you confirm?

**Comment by Plastikente** [comment]
It has been fixed, indeed! Thank you very much. I had to restart Wire twice before the selected language was effective, but since then it works fine.
