### ISSUE TITLE
Camera light on before video call is accepted

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1100]
Wire Version: 2.17.0-undefined
Wire for Web Version: 2017.10.25.0708
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

I observed that for incoming video calls, the camera light is already on before the video call is accepted. It is on the moment another party launches a video call.

**Comment by gregor** [comment]
Yes, this is by design. You can see yourself in a preview window and decide if you really want to accept the call with video. Your video is not shared with the remote side at this time.

**Comment by baimafeima** [comment]
@gregor Thanks for the clarification. This is quite an unusual design decision. Would be great for a user to be able to opt in or opt out of that in the settings menu.
