### ISSUE TITLE
see who is online, offline, away etc

### ISSUE THREAD

**Issue by jonno2002** [wireapp/wire-desktop#1109]
why is there no user status displayed, i have no way of knowing who is online, i would have thought this would be an obvious feature ? and the ability to set status online/away/busy etc etc

**Comment by gkua** [comment]
Already been discussed, and will not be added.

**Comment by jonno2002** [comment]
that really sux, is it a privacy thing im guessing ?

**Comment by mat1th** [comment]
Yes, see https://github.com/wireapp/wire-desktop/issues/900
