### ISSUE TITLE
Default font for application

### ISSUE THREAD

**Issue by timur-davletshin** [wireapp/wire-desktop#111]
Current webapp and, as far as I understand, desktop versions are using this line to define default font `BlinkMacSystemFont,-apple-system,"Helvetica Neue",Arial,sans-serif` which is clearly Mac-oriented and gives visually different results when compared to Windows and Linux. First three fonts are not available neither in Windows nor in Linux distributions (where Arial is a question too).

IMHO web fonts will provide more consistent design across all platforms. AFAIK all WebRTC-compatible browsers support some sort of web fonts.

E.g. Open Sans is available in wide range of weights/widths and uses more or less the same "light" glyph style. And it is used by Telegram as default fonts. Roboto/Fira are available in number of weights as well.

**Comment by timur-davletshin** [comment]
Or, just as another idea, do like DuckDuckGo does in its' [settings](https://duckduckgo.com/settings#) allowing user to choose style he likes.

**Comment by shvchk** [comment]
Or maybe bundle some good UI font like [Fira Sans](https://github.com/mozilla/Fira) or [Open Sans](https://fonts.google.com/specimen/Open+Sans), and use it.

**Comment by lipis** [comment]
We used to have a custom font, but we decided to go with the system fonts for various reasons. The most important reason is the support for multiple languages is handled much better since we don't have to worry about it. But you are right that they are macOS oriented.. here is a suggestion: https://github.com/wireapp/wire-webapp/pull/438

**Comment by lipis** [comment]
So it looks like we tried with Segoe but it wasn't very nice so we switched to Helvetica -> Arial.

**Comment by mohammadrafigh** [comment]
+1 for Open Sans which is really nice in many languages.

**Comment by flipswitchingmonkey** [comment]
Why not just make it configurable per install? Me for example, I prefer fixed-width fonts for chat, and I'd love to be able to set this up easily on a system where I know which fonts are available.

**Comment by h4tr3d** [comment]
+1 for configurable fonts. On my Linux laptop with 140PPI fonts too big. Also, like @flipswitchingmonkey  I prefer fixed-width fonts for chats.

**Comment by timur-davletshin** [comment]
DuckDuckGo's approach is the best IMO, you are free to choose font you like. But since this bug is opened I have to use Stylish 🙂

**Comment by akkuman** [comment]
i want to know how to change the wire's  font on windows

**Comment by helenakos** [comment]
We don't have plans to make changes to fonts in the next months so will close this issue.

**Comment by meteorpublish** [comment]
I'm visually impaired and as my vision is getting worse, I find it harder and harder to read anything in Wire.

> We don't have plans to make changes to fonts in the next months so will close this issue.

How about in the next years? How long is Wire going to be stuck to a fixed 12px font when more and more screens are becoming 4K?
