### ISSUE TITLE
[Feature Request] Public chat rooms

### ISSUE THREAD

**Issue by Strit** [wireapp/wire-desktop#1119]
This might have been suggested before, but I can't find any issues regarding it when searching. You might have it in your internal "todo list".

I'd like Public chat room support. Meaning a way to create chatrooms, and invite people by either a link or a form of search directory.
Matrix.org has this functionality, with optional encryption. I'd like Wire to have it, since encryption is mandatory in Wire.
But creating a "public" chatroom in Wire is hard, because you have to personally invite people into the chat.

**Comment by gregor** [comment]
Thanks for you feature request. We will note it down for possible future inclusion in our product. This is not a commitment to the feature request itself or a timeline expectation.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board or a channel for feature requests as stated in our issue template. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by Strit** [comment]
I can see that. And that's fine.
So where should future feature requests be made then?

**Comment by gregor** [comment]
Feature requests most of the time concern the product in general - as in all our different clients are affected. You can file these at https://github.com/wireapp/wire/issues or get in touch with the team via our regular social media and customer support channels. They are definitely tracked and evaluated if you voice your feedback using these channels.
