### ISSUE TITLE
Wire will not load using DNScrypt + Acrylic

### ISSUE THREAD

**Issue by Fluffkin** [wireapp/wire-desktop#1122]
Wire version: 3.0.2828 Windows Desktop
Operating system: Win7
Which antivirus software do you have installed: Kaspersky

What steps will reproduce the problem?
1. Install DNScrypt (and optionally Acrylic as a cache pointing at DNScrypt)
1a. Set it as network adapter DNS server
2. Run Wire
3. Loading bar never finishes loading

What is the expected result?
Wire should (like absolutely everything else I run) be able to run using DNScrypt.

What is the actual result?
Wire will not load.

It will load fine if I change to my ISP DNS server, but if I change to DNScrypt + Acrylic it just won't load at all. Why? As far as I am aware, Wire is the only program that can't run using DNScrypt.

When I run it, I can see it trying to make connections to:
wire-webapp-prod.elasticbeanstalk.com
ec2-46-137-98-255.eu-west-1.compute.amazonaws.com
ec2-46-137-98-255.eu-west-1.compute.amazonaws.com
etc...
(and then various other amazonaws servers if I leave it trying to load up)

I'm not aware of anything else having problems with amazonaws servers.
It has been this way for several days. Which is long enough for Acrylic to reload the DNS entries several times. Does anybody have any idea what's going on?

**Comment by Fluffkin** [comment]
Very strange. But purging the acrylic DNS cache solved it ... at least temporarily.

**Comment by Fluffkin** [comment]
Nope. It gets weirder.
Set yourself with dnscrypt-proxy as your only DNS provider.
99.999% of the internet works fine. But...
Wire will not load. Even if you restart (flush) the dnscrypt-proxy cache.
So this is a "secure communication platform" that requires you to use a non encrypted, logging DNS fallback server to access it.
Hm...

**Comment by m4rkusxxl** [comment]
Running dnscrypt-proxy for quite some time. I dont see this problem. You could try to enable logging in dnscrypt to check what is requested and how its resolved...

**Comment by Fluffkin** [comment]
Well that's strange. It works today. 18 days ago (when I reopened this issue), it was 100% reproducible. I had to add a fall back DNS resolver or Wire just wouldn't load. Remove the fall back, reboot, no wire, replace fallback, reboot, wire worked. I'm still not 100% convinced this is reliable yet, but I'll leave it with no fallback and see how long it takes it to fail again.

**Comment by ffflorian** [comment]
Hi @Fluffkin, sorry for the (very) late response. This is a very special case which I can't reproduce because the error seems to be in your DNS resolver. Fo you have an idea how we could solve that?
