### ISSUE TITLE
Archived Conversations

### ISSUE THREAD

**Issue by AyelGoth** [wireapp/wire-desktop#1124]
An option to manage archived conversations in the linux application is missing. The option to manage archived conversations is not found. I would add it next to the setup button at the bottom.

**Comment by Strit** [comment]
What do you mean "manage archived conversations"? I can click on the "Archive" icon and manage each conversation from in there on the Linux client.

**Comment by AyelGoth** [comment]
The icon does not appear in Wire Desktop Linux, I have archived conversations but I cannot manage them later because the icon for managing archived conversations does not appear.

**Comment by gregor** [comment]
Are you sure you are archiving and not deleting them? We have not been able to reproduce this problem at all so far.

**Comment by AyelGoth** [comment]
Yeah, I'm sure. In the list of conversations, I delete a conversation, when OK, the conversation moves to the archived conversations box.

**Comment by Strit** [comment]
In mine there are 2 options.
Archive and Delete.
If you press Delete you can't get it back. If I press Delete, it does not get moved to Archived.
