### ISSUE TITLE
[mac] should store account credentials in keychain

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#1127]
Wire version: Version 3.1.2822
Operating system: 10.13.1 (17B1003)

What steps will reproduce the problem?
1. Reinstall MacOS from TimeMachine Backup
2. Start Wire for the first time
3. Notice that it doesn't have it's credentials.

What is the expected result?
It should have taken it's credentials from the System KeyChain.

What is the actual result?
I have to find out that I should have saved them manually to reenter them again. This is bad.

**Comment by gregor** [comment]
Thanks for you feature request. We will note it down for possible future inclusion in our product. This is not a commitment to the feature request itself or a timeline expectation.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by dwt** [comment]
That is ok - I am however a little surprised that you close this issue. If it is something you would take as a feature, just not something that you are doing right now, shouldn't you leave it open so the community knows it is wished for and can take it on?

**Comment by dwt** [comment]
I'd like to reiterate this point, as I today have been annoyed by this bug again.

If you consider this a feature you would like to have, you should re-open the bugs so the community can see it and know that this is something that will a) change at some point and b) contributions are welcome for this.
