### ISSUE TITLE
[mac] Message history lost after restore from encrypted backup

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#1128]
Wire version: Version 3.1.2822
Operating system: 10.13.1 (17B1003)

What steps will reproduce the problem?
1. Restore mac from encrypted time machine backup
2. start wire again for the first time
3. Notice that it identifies as a new device and has thus lost all message history.

What is the expected result?
It should retain full message history and the device key so it does not appear as a new device to all my pals that have authenticated me

What is the actual result?
Message history is lost.

**Comment by gregor** [comment]
This is currently not a supported scenario. If you restore your device from a time machine backup you will have a client in a very invalid state. The cryptographic sessions to all other clients change their state with each new message. Simply restoring an old one will definitely have you end up in a very out of sync state that we cannot recover from. Currently we cannot offer any backup solution but it is planned for our business customers in 2018.
