### ISSUE TITLE
Launcher icon should not animate - or there should be the option to turn off the animation - when notifications are switched off

### ISSUE THREAD

**Issue by ysim** [wireapp/wire-desktop#1130]
Wire version:  3.0.2816
Wire for web version: 2017.11.10.1041
Operating system: Ubuntu 16.04.3 LTS
Which antivirus software do you have installed: None

This is not a bug, but a feature request. 

At least for the Linux (Debian) desktop app, turning off all the notifications in the options section doesn't entail that the launcher icon doesn't animate when messages come in. The animation should be switched off when all notifications are off, or there should be an option to turn off the animation.

**Comment by gregor** [comment]
Thanks for you feature request. We will note it down for possible future inclusion in our product. This is not a commitment to the feature request itself or a timeline expectation.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source code repository and not a discussion board or a channel for feature requests as stated in our issue template. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by ysim** [comment]
@gregor Oh, I'm so sorry! I must have missed that in the issue template. Thanks for the explanation and for noting it down anyway.
