### ISSUE TITLE
Incorect langage in tooltip

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#114]
With english language selected in Wire desktop 2.10.2652, the tooltip on timed message delay icon is displayed in german and not in english.

**Comment by ConorIA** [comment]
Some language bugs were fixed since that release.  Try 2.11.2665.

**Comment by IpsmLorem** [comment]
I'll try the new version then, as soon as I get it ( #115 )

**Comment by ConorIA** [comment]
Uups, looks like I spoke too soon. It is indeed still incorrect in 2.11.2665. But I think this is an issue for wireapp/wire-webapp.

**Comment by gregor** [comment]
@IpsmLorem  Thank you for your report. As mentioned we have already fixed on the webapp side of things and this will be part of the next release.

**Comment by gregor** [comment]
We have fast tracked the fix for this. This is now llive and available the next time the page in the wrapper reloads (eg. on logout or restart)
