### ISSUE TITLE
You cannot call because your computer does not have a microphone

### ISSUE THREAD

**Issue by CorvusCorax** [wireapp/wire-desktop#1143]
wire-desktop is affected by bug in wire-webapp:

https://github.com/wireapp/wire-webapp/issues/2021

**Comment by lipis** [comment]
I'm closing this issue here since it's the same basically a duplicate. We are the same team that is dealing with it on webapp. Thank you.

**Comment by mHatsune** [comment]
https://github.com/wireapp/wire-webapp/issues/7018
