### ISSUE TITLE
Accepting video calls silently fails if no camera -  no error message to either caller or receiver

### ISSUE THREAD

**Issue by CorvusCorax** [wireapp/wire-desktop#1144]
On a system with no camera attached, making or accepting video calls is not possible. There are no error messages to either caller or callee

Version 3.0.2816
Wire for Web Version 2017.11.10.1041
Operating system: Ubuntu 16.04 LTS  (and others)

What steps will reproduce the problem?
1. Use a system with no webcam/camera installed
2. Attempt to make a video call
OR
2. Attempt to receive a video call

What is the expected result?

1. Call is established, but only blackness or no video is recorded from the system with no camera
2. Optional: Error message informing the user that camera has been detected

(similar to the video of the mobile phone app if there is no access to camera device)

What is the actual result?

On clicking the video call button on a system with no camera, nothing happens. Wire does not attempt to make a call.

When one receives a video call, attempting to accept the call has no effect. The button to accept the call goes away but the caller is never notified and his status remains on "ringing" until he gives up or a timeout is reached.

**Comment by gregor** [comment]
We have added a call log features option in your account preferences. If you still see these problems please get in touch with our customer support providing them with logs. I am going to close the issue here.
