### ISSUE TITLE
Voice activation

### ISSUE THREAD

**Issue by dotWAVE** [wireapp/wire-desktop#1146]
I'm not a fan of the always recording nature of call system. During moments of silence, there is always either white noise, or background audio from microphones. Voice activation would be a nice to have feature, as transmitting static is a waste of bandwidth.

**Comment by gregor** [comment]
That is a feature of webRTC which is already enabled in our product if supported by the browser. If you use our mobile clients on iOS or Android, which rely on our own implementation you will benefit even further from this optimization in bandwidth and improvement in call quality.

**Comment by dotWAVE** [comment]
The feature still seems absent on the desktop program. If it is implemented on the wire-desktop program as you suggest, it would be nice to provide settings for the option. Now as I am testing it with wire-desktop (2.15.2751) installed on linux, it does not appear to be using any form of voice activation.

**Comment by gregor** [comment]
While looking through the code for some other adjustments I noticed that the feature was not enabled in case you were on the ANSWER side of the SDP connection.

This is fixed with wireapp/wire-webapp#3598. Experience should improve with the next release.
