### ISSUE TITLE
Wire .desktop launcher displays wrong name

### ISSUE THREAD

**Issue by davidhaller** [wireapp/wire-desktop#1161]
Wire version: Version 3.0.2816
Wire for web version: 2017.12.07.1113
Operating system: Ubuntu 17.10
Which antivirus software do you have installed: ClamAV

What steps will reproduce the problem?
1. Open application menu
2. Search for wire

What is the expected result?
Launcher name should be: Wire

What is the actual result?
Launcher name is: wire-desktop

In file /usr/share/applications/wire-desktop.desktop the line Name=wire-desktop should be replaced with Name=Wire.

**Comment by mythsunwind** [comment]
This is already fixed in master with https://github.com/wireapp/wire-desktop/pull/1089 and will be released with the next version.
