### ISSUE TITLE
Provide a "snap" as software package — for Linux systems

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#1168]
Snaps are containerized software packages that are simple to create and install. They auto-update and are safe to run. And because they bundle their dependencies, they work on all major Linux systems without modification.

For more information, see [here](https://snapcraft.io/).

**Comment by gregor** [comment]
We do not intend to support additional Linux distribution methods and packages at this time.

**Comment by bitinerant** [comment]
A snap package is available. Install via:
```
sudo snap install wire
snap connect wire:camera core:camera
```
