### ISSUE TITLE
Support of UTF-8 Open Graph tags content

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#117]
When parsing UTF-8 content on og:title tag of an URL, Wire desktop doesn't correctly display the content:
![cap](https://cloud.githubusercontent.com/assets/1250795/19720960/a00a8360-9b70-11e6-8ff6-6ca5d8772f34.png)

**Comment by ffflorian** [comment]
This should be fixed by now. If not, feel free to comment here.
