### ISSUE TITLE
[macOS] App Store Icon is not transparent around the Wire logo

### ISSUE THREAD

**Issue by agottschling** [wireapp/wire-desktop#118]
When downloading the app from the App Store, when the icon flies from the page to launchpad, and in launchpad until it has finished downloading, The icon has a black circle around it and then a white border to fill the square image.

**Comment by lipis** [comment]
![5fb1dd96-2b73-4653-804a-2dca08ff33a6](https://cloud.githubusercontent.com/assets/125676/22284387/61a0d160-e2e7-11e6-9db2-1861f1003fd0.png)
![77c3eb04-5ab5-4bab-b459-604d917f0084](https://cloud.githubusercontent.com/assets/125676/22284390/62c97592-e2e7-11e6-81d2-3822af5252c8.png)

We haven't noticed anything and it's hard to reproduce it. Also we verified our icons and they all transparent and they seem correct. I will close this issue as minor, but if you manage to get a screenshot of the issue (if still exists) that would be the best. Thank you..
