### ISSUE TITLE
Matrix Bridge

### ISSUE THREAD

**Issue by ehussong** [wireapp/wire-desktop#1184]
Is a Matrix Bridge possible with Wire? It's a project that seems to have some decent traction and has similar, though distinctly different, goals. It would be great to have interaction between the two.

**Comment by colans** [comment]
This is currently blocked by https://github.com/wireapp/wire/issues/160.

**Comment by gregor** [comment]
There are no current plans to change our TOS. As such I am going to close the issue.

**Comment by colans** [comment]
This contradicts what was said in #160.
