### ISSUE TITLE
Push-to-talk feature does not exist

### ISSUE THREAD

**Issue by AlexFolland** [wireapp/wire-desktop#1188]
I'm interested in having a push-to-talk and push-to-mute button, but not just for gaming. I want to be able to be silent unless I'm talking, so I can sniffle or sneeze without disrupting the conversation.  My breathing is a little messed up from a deviated septum, so it's loud when I'm not speaking.

**Comment by gregor** [comment]
Thank you very much for your feedback. We will keep it in mind but have no plans on implementing it at this time. With the nature of the issue being a feature request I am going to close the it.

**Comment by AlexFolland** [comment]
Closing it is not appropriate.  You're inviting someone else to make another one.  Notice how there are 3 "thumbs up" here.  Also, every other voice chat program has this.  It seems less like a feature request and more like an essential fix to me.  It seems unusable without this.

**Comment by AlexFolland** [comment]
Please reopen the issue, as https://github.com/isaacs/github/issues/583 is not implemented yet.  Otherwise, I will have to create a duplicate issue that references this one, which is tedious and noisy.
