### ISSUE TITLE
Windows 10 - Wire window size and position not restored after OS restart

### ISSUE THREAD

**Issue by loscamilos** [wireapp/wire-desktop#1189]
Wire version: Version 3.0.2828
Wire for web version: Wire for Web Version 2017.12.20.1248
Operating system: Windows 10 Pro, 1703, build 15063.786
Which antivirus software do you have installed: Avast Free 17.4.2294, build 17.4.3482.0

What steps will reproduce the problem?
1. Position Wire window on UHD 1-display (bottom right in my case) - connected with DisplayPort
2. Shut down/restart the system
3. Wire window is resized and positioned in a different place (closer to center)

What is the expected result?
Exactly the same Wire window size and position.

What is the actual result?
Wire window size and position is different than it was before restarting the OS.

**Comment by gregor** [comment]
This is most likely caused by electron itself. Improvements they have made and will make in the product will be made available to Wire users eventually.
