### ISSUE TITLE
Focus shifts from text area to sidebar upon sending or receiving a message, requiring refocus

### ISSUE THREAD

**Issue by manasb** [wireapp/wire-desktop#1194]
**Wire version:** `Version 3.1.0-d3e054a`
**Wire for web version:** `Wire for Web Version 2017.12.20.1248`
**Operating system:** `Fedora 25`
**Which antivirus software do you have installed:** none

## What steps will reproduce the problem?
1. Build `wire-desktop` from source (node version `v9.3.0`, npm version `5.6.0`)
```shell
npm install && grunt -v --arch=x64 --target=appImage linux-other
```
2. Send a contact a message
3. Continue typing another message after hitting `enter`

## What is the expected result?
Focus should remain on the text area so that the message which is being typed can be completed and sent.

## What is the actual result?
Focus shifts to the sidebar. A thin vertical yellow line appears on the right-side edge of the vertical bar containing the account photo, focus is not on the text area and has to be re-assigned.

**Comment by gregor** [comment]
Thanks for the report. We are aware of the issue that was introduced lately (presumably 
#1178) and is not part of any release build.

**Comment by manasb** [comment]
@gregor 

lovely. thank you
