### ISSUE TITLE
Bug after markdown table was sent

### ISSUE THREAD

**Issue by iw381** [wireapp/wire-desktop#1195]
Wire version: 3.0.2828
Wire for web version: 2017.12.20.1248
Operating system: Windows 8.1 Pro
Which antivirus software do you have installed: Defender, Avira Antivir

What steps will reproduce the problem?
1. Sending a markdown table via Wire Desktop.

What is the expected result?
A table in the messaging window. 

What is the actual result?
The table is not properly displayed (see screenshot) and Wire seems to stop working. New messages are only displayed in the contacts column, but not in the actual message window.
The table cannot be deleted and new messages cannot be sent.

![tableerror](https://user-images.githubusercontent.com/5732162/34649985-780a73aa-f3b9-11e7-8f2f-8ebf4da61ae7.png)

**Comment by gregor** [comment]
Thanks for reporting. We will take a look and make sure we fix this.
