### ISSUE TITLE
Max 15mb for sending files.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#12]
This doesn't seem to be a limitation of WebRTC since Webtorrent handles files up to 500Mb just fine.

Do you expect to increase this soon?

**Comment by gregor** [comment]
The maximum is currently at 25MB across platforms which we think covers most use cases. For which purposes do you need an increased file size?

The limit was choosen to ensure performace as the whole file needs to be encrypted/decrypted which has different performance implications on our various platforms. We will continue to monitor customer requirements and reconsider the size limit accordingly.

**Comment by tmikaeld** [comment]
We use it in a commercial setting and are trying to convert both clients and partners to Wire, but this poses an issue when Skype allows sending of large files but Wire does not.

At least 100Mb should be possible on desktop.

**Comment by tmikaeld** [comment]
And Wire 2.9 (latest) on OS X still says 15Mb as the limit.

**Comment by gregor** [comment]
@tmikaeld There are two diffferent size limits. If you post an image to the conversation, this is limited to 15MB as the image gets compressed even before we encrypt it. On older machines we are seeing major performance problems with this that even result in app crashes. You can send an image using the file transfer option up to 25MB. This way the image is also not touched at all before compression.

I do see the need for larger file transfers in your scenarios and will bring this up for disucssion internally.

**Comment by tmikaeld** [comment]
Pre-compressing images before sending them are murder for businesses and design agencies. I would advice that you do not do that - at all, if you ever want those kind of users.

If it crashes because of encryption, there must be something wrong with the method. Even on a slow computer, encryption shouldn't crash anything - just take a longer time. Have you tried encrypting using chunks  (Like Webtorrent) for large files? Limiting CPU priority if you encrypt async? Surely there must be a working solution here.

**Comment by gregor** [comment]
Personally I agree you regarding the images. I will make sure that our product management reads your comments.

There are definitely technical solutions. Encryption does not crash the app, it just takes long, just as you mentioned. Touching the image results in crashes due to memory problems when file size increases. Due to this the current limits are conscious decisions that take customer needs and performance limitations into account. So far we have not tackled them as other issues got priority. The increasing customer demand from users like you and awareness of expected use cases will definitely be taken into account for our reevaluation of the size limits and priorities.

**Comment by tmikaeld** [comment]
That would be great, since sending images are 99% of what we and our clients do via Skype at the moment.

**Comment by tmikaeld** [comment]
Sorry, wrong button.

**Comment by lucianabdiel** [comment]
I am also in a situation where large file transfer over a local lan would be advantageous.  We primarily deal with large video files such as 2-4 gb mpeg files.  This would be the ultimate solution to our growing communication problem if this could be implemented.  Thanks in advance.

**Comment by tmikaeld** [comment]
@lucianabdiel WebRTC uses the RAM for storing the files while it's encrypting/decrypting the stream, so the amount of RAM would run out quickly for video files. Another limitation is that the amount of available local storage is different between browers. Webtorrent have had this issue for quite a while and not been able to solve it.

**Comment by tmikaeld** [comment]
@lucianabdiel To answer your your question about LAN, yes it would be possible.

See: https://github.com/cjb/serverless-webrtc/ as an example.

**Comment by fenrig** [comment]
Do the encryption in small parts, for example just encrypt in parts of 25mb and assemble it when it gets there. You can do the assembling with filesystem api...

**Comment by fenrig** [comment]
Allthough the filesystem api is still a w3c draft: https://w3c.github.io/filesystem-api/

**Comment by 3n-mb** [comment]
@fenrig electron's main thread has full access to filesystem. Saving chunks in temp folder on disk at least to recover from broken connection, is trivial in electron.
The only excuse for makers is that current version did almost nothing to take advantage of this closer integration: #17 . No time. Rush, rush. I wonder, if this is a good excuse users' eyes.

**Comment by fenrig** [comment]
Correct me if I'm wrong, but isnt electron used as a browser. Isnt it running the same web code (html + css + js) as its using in the browser (chrome, firefox, edge, ...). So they probably want a cross browser solution?

**Comment by tmikaeld** [comment]
@fenrig The issues is that Wire load the resources from **their** server instead of locally, this is indeed a security issue.

**Comment by tmikaeld** [comment]
Not that i would consider it a great one, any App update framework is a security issue if compromised.

**Comment by 3n-mb** [comment]
@fenrig I do not know what wire wants. But, I can share my observations.

[Mega](https://mega.nz/) security promise initially came out as site. This was criticized, and they provided an extension. Read: crypto + filesystem code is not inside of a web-page.

[Cryptocat](https://crypto.cat/) has always been an extension, i.e. not a pure web-page. Now it is an electron-based mew.

Now, electron is not just a web-page. There is node located underneath. 
But, Wire app is right now just a web-page, shown in electron. Wire is not realizing node's powers at the moment. As a result, there is even no good reason to download desktop app at this point. UX is that of a page in a browser, security is at best the same (if no-node-integration flag keeps original chrome sandbox as water-tight, or else, it is less water-tight).

**Comment by helenakos** [comment]
Hey @tmikaeld, we are looking into increasing the file size limit. Thanks for your feedback!

**Comment by helenakos** [comment]
@tmikaeld if you want to talk more about how you use Wire for business, contact siim@wire.com or add him on wire siim@wire.com.

**Comment by tmikaeld** [comment]
@helenakos Added.

**Comment by aaronrosenberg** [comment]
Is there an update on this?  With the newer phones producing much higher level video, the file size is now an issue more than ever.  Thanks.
