### ISSUE TITLE
GIFs should play only after they are clicked

### ISSUE THREAD

**Issue by DragonzMaster** [wireapp/wire-desktop#120]
When a GIF sent/received it should not play automatically but it should be clicked first to play and clicked again to stop (show last frame when it is stopped)

Maybe not all people have the same opinion but plz Can you add an option (checkbox in settings) to enable it or not.

**Comment by ConorIA** [comment]
This might also help fix some of the CPU issues. (#135)
Wire typically is around <1% CPU usage for me, unless I'm in a conversation in which I've sent or received a gif. Even when the gif is offscreen (scrolled past), Wire still uses ~25% CPU.

**Comment by DragonzMaster** [comment]
Yup, that is the point of opening this issue as the GIFs keep playing it causes CPU usage beside consuming internet bandwidth.

**Comment by ConorIA** [comment]
Given how the desktop app wraps the webapp, I wonder if this issue would have a better home on the webapp repo.

**Comment by lipis** [comment]
There are many issues like that.. but since we are the same team it's fine..  Also it would be messy to start closing and opening issues.. We are thankful for all these issues regardless of where they are landing :)

**Comment by Sopsys** [comment]
Title is a bit misleading, at first I thought that OP wants them to autoplay but they won't.

Maybe change the title to prevent further confusion? Something like "GIFs should play only after they are clicked" would be good I think.

**Comment by helenakos** [comment]
There are no plans to implement this right now so will close and reopen if fixed later on.
