### ISSUE TITLE
Full markdown support

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#121]
When I send this message:
`;*jN+>c*b`

The recipient receive, with the "j" in italic:
`;jN+>cb`

**Comment by IpsmLorem** [comment]
My bad, Wire support some forme of Markdonw syntaxing :p

**Comment by lipis** [comment]
We will not support headers and links because people will go nuts with huge letters and links could be good source for spam and fake URLs.. as for the issues we are working on it: https://github.com/wireapp/wire-webapp/pull/405

**Comment by IpsmLorem** [comment]
Agree with headers and links. I think the missed one is lists (unordered and ordered)

**Comment by lipis** [comment]
Also not sure about that if we want to include them.. :/ We'll see :)

**Comment by IpsmLorem** [comment]
I think "list" are more useful than "code coloration syntaxing" in wire ;)

**Comment by orange-buffalo** [comment]
How about [Blockquotes](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes)? 
It would be super nice to support `>`.

**Comment by gregor** [comment]
Thanks again for your feature request. We will continue to track this internally. At this time we do not have any immediate plans to improve our markdown implementation on desktop We will continue to evaluate if and when to schedule an improvement like this on the roadmap.
