### ISSUE TITLE
MacOS Version using too much battery

### ISSUE THREAD

**Issue by Nuruddinjr** [wireapp/wire-desktop#122]
<img width="283" alt="screen shot 2016-10-28 at 16 29 36" src="https://cloud.githubusercontent.com/assets/9083431/19805124/06f0bce0-9d2c-11e6-95de-2111922a83a3.png">
I use Wire for about 2 months long, so I noticed it is using too much battery in recent weeks, So if possible, please make it battery -friendly =) `Feature request`

**Comment by lipis** [comment]
Will close this one in favour of #135
