### ISSUE TITLE
git clean destroys login data

### ISSUE THREAD

**Issue by rbu** [wireapp/wire-desktop#1225]
Wire version: Version Development (git 56a3658)
Wire for web version: Wire for Web Version 2018.01.18.1054
Operating system: Fedora 27
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. git pull ; git clean -f -x
2. Start wire

What is the expected result?
I am still logged in because login information is stored outside of the git working directory.

What is the actual result?
I am logged out.

**Comment by gregor** [comment]
Login data is not stored in the git directory thus we cannot explain the link you describe. I will go ahead and close this as all authentication storage is handled by Chromium and not us.
