### ISSUE TITLE
Toggle main window visibility on tray icon click

### ISSUE THREAD

**Issue by Steef435** [wireapp/wire-desktop#1234]
Hi,

Not sure if this is a bug or a feature, but currently clicking on the tray icon while the window is visible just focuses it instead of closing/hiding it like other apps (e.g. Telegram desktop) do. (This is useful to open the window, take a quick glance at the conversations and then close it after without having to move the mouse)

What steps will reproduce the problem?
1. Close/hide the window
2. Click on the tray icon (shows window)
3. Click on the tray icon again

What is the expected result?
The window gets closed/hidden

What is the actual result?
The window gets focused

I've already implemented this behavior [in a fork](https://github.com/Steef435/wire-desktop/commit/07b4ff612fb98ffed98f86185eddd41ee7bf1a0a) (little testing). Should I PR or is the current behavior intended?

**Comment by gregor** [comment]
@Steef435 Thanks for your feedback and detailed explanation. The current behavior by design as there are also other apps that do it like our current implementation (e.g. Spotify). I will bring this up with our UX people to see if we want to change the behavior and ask for your PR.

**Comment by Steef435** [comment]
Alright, thanks for the quick and clear reply!

**Comment by gregor** [comment]
@Steef435  We have discussed this internally and will stick to the current behavior. Thank you very much again for your feedback.
