### ISSUE TITLE
[Electron] Vulnerability on Windows

### ISSUE THREAD

**Issue by fllp** [wireapp/wire-desktop#1237]
There is a recent vulnerability in the protocol handler of Electron:
https://electronjs.org/blog/protocol-handler-fix

I guess you are already aware of it but could you state if Wire is affected on Windows?

**Comment by raphaelrobert** [comment]
Wire doesn't use protocol handlers, so this doesn't affect us.

**Comment by fllp** [comment]
Thank you.
