### ISSUE TITLE
missing app indicator in Ubuntu 17.10

### ISSUE THREAD

**Issue by dgoosens** [wireapp/wire-desktop#1244]
Wire version: 2.17.2813
Operating system: Ubuntu 17.10

**What steps will reproduce the problem?**  
1. launch wire-desktop

**What is the expected result?**  
In Ubuntu 16.04.3 (LTS) Gnome Edition, I've got an app indicator:  
![selection_001](https://user-images.githubusercontent.com/1250047/35518322-88d5d3d2-0511-11e8-89a4-0ced1a72b18e.png)

**What is the actual result?**  
App indicator no longer present in Ubuntu 17.10 which ships with Gnome by default

**Comment by ConorIA** [comment]
See #957 and #590

**Comment by dgoosens** [comment]
thanks @ConorIA 

so that's not something that is to be addressed by Wire...  
Closing

**Comment by ConorIA** [comment]
Seems like it might be coming with #1187
