### ISSUE TITLE
Non-applicable update notice in Linux AppImage

### ISSUE THREAD

**Issue by rawtaz** [wireapp/wire-desktop#1249]
**Wire version:**  wire-3.0.2816-x86_64.AppImage
**Wire for web version:**  I'm not seeing an About dialog anywhere in this app.
**Operating system:**  OpenSUSE Tumbleweed test VM, recently updated
**Which antivirus software do you have installed:**  None.

**What steps will reproduce the problem?**
1. Run the Wire Linux desktop AppImage
2. Spot a notice at the top of the window, saying "A NEW VERSION OF WIRE IS AVAILABLE. WHAT’S NEW, UPDATE NOW".
3. Go to Wire.com -> Download, notice that there is no new version available for download.

**What is the expected result?**
Either that there actually *is* a new version of the Linux client available for download, or that the notice in Wire about a new version does not show for the Linux client when there's no new version available for download.

**What is the actual result?**
See above.

**Please provide any additional information below. Attach a screenshot if
possible.**
So, presumably this situation is due to there being a new version of the Wire Web client, which is embedded in the Wire Linux AppImage, and this triggers the update notice. I think that it would make sense to not display this notice when there's actually no new AppImage or Linux desktop client, as a user running these will most likely not go and start using the Web client just because there's an update there. A notice should of course be displayed when there's actually a newer version of the current client, though.

**Comment by gregor** [comment]
The new version of the web client applies to the Linux AppImage. It is an Electron based container that runs Chromium. It adds a little bit of functionality but essentially loads the webapp. If you restart the app you should see the webapp version on the about screen change. There you also find a link that details the difference between container and webapp. What applies to Windows and macOS also applies to Linux.

https://support.wire.com/hc/en-us/articles/115001919905-How-do-Wire-updates-work-

**Comment by rawtaz** [comment]
@gregor You are missing the point. I understand that the Linux AppImage is an Electron app embedding the web client. But the issue is that the notice about a new version pops up in the AppImage even though there is no new AppImage version available on the download page. Either there should be a new version of the AppImage available for download, or there should not be a notice about it in the first place. Does that make sense?

**Comment by gregor** [comment]
No. If the whe web client is out of date, then the web client inside the AppImage is out of date. We show you that a restart will get you updated code. Thus the update message is valid and you should restart to update. The update message clearly states that you should click it and it will trigger the restart for you. We definitely understand the confusion around this process and are working on general improvements to it but the message is valid and should be shown.

**Comment by rawtaz** [comment]
Well, in that case the problem is of a different type. I restarted my Wire client at least two times, yet got the update notice. That's when I went to the download page to look for a newer AppImage but didn't find one.

At this point in time though, I am not seeing an update notice, so one possibility is that the update finally managed itself. No idea why it wouldn't do that at least the first two times (I don't remember when the notice stopped showing, as I started to ignore it). Perhaps the update process takes a long time or something? Still shouldn't matter, as I usually keep the client running for many hours when I start it.

Anyway, I guess it works as intended then. Would be nice if there was a little progress bar indicating when the client is updating and how far through the process it's gone though, that would remove any confusion.

**Comment by gregor** [comment]
Did you manually restart it? Are you sure you actually restartet it and not only minimized it? Then the next app "start" would only show the existing window. At this time there is no progress. There is nothing we can show. All it does is serve the latest webapp from app.wire.com on each start of the client. So if you want to make sure you actually restarted the app you can check the about screen before and after the restart and make sure that the webapp versions listed there are different.

**Comment by rawtaz** [comment]
I restarted both by clicking "UPDATE NOW" and by manually restarting it (Ctrl+Q). Yes, never minimized it. So that part is weird, that it still kept showing the update notice even though I 100% know I restarted the AppImage.

Anyway, I then compared the version number in the AppImage filename with the one on the download site, and they were the same. This is probably where it went wrong - the AppImage package has its own version number, and the embedded webapp is another one (I presume).

There is no about dialog anywhere as far as I can tell. Where in the app should I go to find it? All I have is the friends list and the preferences view, and there's no "About" anywhere there as of what I can see.

**Comment by gregor** [comment]
The about screen should be accessible from the navigation. Maybe @ffflorian point to it on your environment.

**Comment by ffflorian** [comment]
![About](https://user-images.githubusercontent.com/5497598/35974964-61ed46a2-0cdb-11e8-96cf-0cdd85271808.png)

That's how the menu entry looks like on Debian + Gnome.

**Comment by rawtaz** [comment]
@ffflorian Thanks for the screenshot! This is very interesting - I have no menus whatsoever.

I have the window title row, and the next thing below that is the actual web view content area, meaning the three columns (leftmost is black and has my avatar in it, middle is blurred background and has my alias and my contacts in it, rightmost is the conversation area).

I tried pressing Alt and a bunch of keys in case the menus just happen to me hidden, but none of e.g. Alt+F, Alt+V and Alt+H makes a menu appear.

I can tell you that every other application I use have menu bars and they all work. Am I missing something in Wire? I presume the menus should be visible by default.
