### ISSUE TITLE
Wire Linux Process Name 

### ISSUE THREAD

**Issue by sonicou** [wireapp/wire-desktop#125]
The binary executeable and the processname under Linux use a capital W.
It should be "wire" not "Wire".

**Comment by ConorIA** [comment]
This is not a perfect solution, but if you are using the Debian packages, you can symlink to the `/usr/bin` directory:
```
# ln -s /opt/Wire/Wire /usr/bin/wire
```

**Comment by lipis** [comment]
If the general convention says lowercase we should update our build scripts accordingly..

**Comment by ConorIA** [comment]
Looks like electron-packager defaults to using productName. You can change the executable name using electron-builder by passing the flag `--em.productName=wire`. The only issue is that the "Wire" menu on Linux is also changed to "wire", so we'd have to change that menu title as well. 

I see that there is a "name" option that can be passed to electron-package, but couldn't figure out if it would work with electron-builder. See: https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#name

**Comment by ConorIA** [comment]
I wonder if @develar con provide any insight into this issue. That is, is it possible to change the name of the executable on Linux without changing productName?

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/806 will be fixed for you today.

**Comment by lipis** [comment]
🎆  Much appreciated @develar  :)

**Comment by develar** [comment]
Update to electron-builder `7.21.0` to fix issue.  `name` is used by default.

**Comment by develar** [comment]
BTW, why you still depends on `electron-packager`?

**Comment by lipis** [comment]
So what do I have to change now in order to have process name fixed?

@develar As for the `electron-packager` we were using that for Windows, macOS, MAS and it works smoothly at the moment with the Squirrel and everything.. I tried to do something quick.. but things start breaking fast :D So maybe in the future.. we might need your help there :)  [Gruntfile.coffee](https://github.com/wireapp/wire-desktop/blob/master/Gruntfile.coffee)

**Comment by develar** [comment]
> So what do I have to change now in order to have process name fixed?

Nothing. Just set electron-builder version to `7.21.0`

**Comment by lipis** [comment]
Sweet! #151

**Comment by lipis** [comment]
Here it is... these versions will soon make it to production..

- [wire-2.11.2670-x86_64.AppImage](https://wire-app.wire.com/linux/wire-2.11.2670-x86_64.AppImage)
- [wire-2.11.2670-ia32.AppImage](https://wire-app.wire.com/linux/wire-2.11.2670-ia32.AppImage)
- [wire-2.11.2670-amd64.deb](https://wire-app.wire.com/linux/wire-2.11.2670-amd64.deb)
- [wire-2.11.2670-ia32.deb](https://wire-app.wire.com/linux/wire-2.11.2670-ia32.deb)

**Comment by ConorIA** [comment]
@lipis, just a head's-up: users are going to have to re-login, because the config directory changes from `Wire` to `wire`. This could leave data behind when a user logs out because the old folder will still exist. My solution for the PKGBUILD is: 

```
post_upgrade() {
  if test -e $HOME/.config/Wire ; then
    echo 'Versions of Wire prior to 2.11.2670 stored user files in "$HOME/.config/Wire".'
    echo 'This folder has changed to "$HOME/.config/wire".'
    if test -e $HOME/.config/wire ; then
      echo 'You seem to have both folders on your drive.'
      echo 'You can probably remove "$HOME/.config/Wire".'
    else 
      echo "We'll move the folder now."
      mv $HOME/.config/Wire $HOME/.config/wire
   fi
  fi
}
```

**Comment by lipis** [comment]
Thanks for the headsup.. It will be a bit tricky to start adding those things now in the experimental version of Wire for Linux.. so unfortunately that will happen now :/

**Comment by ConorIA** [comment]
Ooops, nevermind! ... it seems like I misdiagnosed my problem! The config directory is still `$HOME/.config/Wire`. Although all of my old received messages are showing errors. I'm not sure if that is from this change or a recent WebApp update.
