### ISSUE TITLE
Cannot change avatar icon

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#1257]
Version 3.0.2828
Wire for Web Version 2018.02.01.1026
Operating system: Windows 10 x64

What steps will reproduce the problem?
1. click on the wheel icon
2. mouse over the round avatar picture to display the camera icon
3. click on the camera icon

What is the expected result?
- Picture chooser dialog appear

What is the actual result?
- Nothing at all

**Comment by gregor** [comment]
Thanks for the report. We already noticed this bug, which was introduced with last weeks release of the webapp (https://github.com/wireapp/wire-webapp/releases/tag/2018-02-01-10-26).

The fix has been merged into the code base earlier today (https://github.com/wireapp/wire-webapp/pull/2372) and will be part of the next release to the public.

For now please use our mobile clients to change your profile picture. Please excuse the inconvenience.

**Comment by gregor** [comment]
The fix for this is part of https://github.com/wireapp/wire-webapp/releases/tag/2018-02-16-07-54 which was released earlier today.
