### ISSUE TITLE
"Check Spelling While Typing" uses American English instead of the Operating System's Australian English

### ISSUE THREAD

**Issue by balupton** [wireapp/wire-desktop#1273]
Wire version: Version 3.1.2822
Wire for web version: Wire for Web Version 2018.02.01.1026
Operating system: MacOS 10.13.3 (17D47)
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. Enable `Check Spelling While Typing`
2. Type `blah incentivise blah`

What is the expected result?

`incentivise` should not be underlined red, as my operating system is set for Australian English

What is the actual result?

`incentivise` is underlined red

Please provide any additional information below. Attach a screenshot if
possible.

<img width="780" alt="screen shot 2018-02-13 at 8 26 10 am" src="https://user-images.githubusercontent.com/61148/36127275-9ae813a0-1097-11e8-81a7-7bfce4301bc2.png">
<img width="419" alt="screen shot 2018-02-13 at 8 26 02 am" src="https://user-images.githubusercontent.com/61148/36127277-9b1fdcd6-1097-11e8-99c6-7b88048cd682.png">
<img width="518" alt="screen shot 2018-02-13 at 8 29 23 am" src="https://user-images.githubusercontent.com/61148/36127382-0abdffbe-1098-11e8-9c6a-c83c06f849ae.png">

**Comment by balupton** [comment]
Here is the GitHub comment field doing the correct localisation spelling:

<img width="796" alt="screen shot 2018-02-13 at 8 28 08 am" src="https://user-images.githubusercontent.com/61148/36127356-e8500cec-1097-11e8-92ea-b99765339ea5.png">

**Comment by ffflorian** [comment]
Closed due to the removal of the spellchecker in https://github.com/wireapp/wire-desktop/pull/2023.
