### ISSUE TITLE
Deleting conversation (history) in mobile app also removes it on other devices.

### ISSUE THREAD

**Issue by robertnurnberg** [wireapp/wire-desktop#1278]
What steps will reproduce the problem?
1. Within the Wire android app, delete an active conversation with contact A.
2. Start a new conversation with contact A. 
3. On a different device, e.g. Windows PC, open wire and check the conversation with contact A.

What is the expected result?
You should see the history of the conversation with contact A.

What is the actual result?
The history is lost, and the oldest message is the new message to contact A.
In the meantime, contact A can still see the whole conversation history on all their devices.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by Yorgos-V** [comment]
Thanks for writing, really appreciated. 
This behaviour was a product decision. We decided that the option to delete the content of a conversation should be per account and not per device. The reason behind it is that, if a user decides to do some house cleaning, it should be applied on every device this user has. This is why the option resides in the conversation options at the same level with with Archive or Leave. 
Also, deleting the content of a conversation is a personal matter, we do not believe it should affect what the rest of the participants choose to keep. I hope this answers your questions.
Once again, thank you very much for the feedback!

**Comment by robertnurnberg** [comment]
Interesting.

Then you should update your online documentation, as there it seems to be stressed that the conversation is deleted only locally. See for example [here](https://support.wire.com/hc/en-us/articles/204087932-How-can-I-delete-a-conversation-s-history-). Also, the warning before going ahead with deleting the conversation should stress that this will apply to ALL devices.

As an aside: is there any way to free storage space on a mobile by removing (parts) of convervations locally, without affecting the conversation history on other devices?

**Comment by gregor** [comment]
Thanks for your reply. We will review our FAQs and make sure they represent the designed behavior. We will also review  the warning modal copy and might adjust it in the future.

To answer your other question: I am not aware of a way to do that. Devices stay in sync, which is one of the goals we have.

Thanks again for your feedback. I am going to close this issue at this time.
