### ISSUE TITLE
Online Status (@desktop app)

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-desktop#128]
Is it possible to add an online-indicator to the desktop-app? One which shows if the other side is currently online (have a websocket/rtc connection open?)

When users -only- use the Desktop Client, it is used as a classic Instant Messenger.
As such it would be great to have an online-indicator like all the other IM-apps (skype, pidgin, icq,etc..).

I know it doesn't make much sense for wire-android/ios apps, as most of these clients are always online for most people (at least those who use wlan+mobile-data). But for Desktop-only people it really does make some sense!
Maybe, if it is an issue with the mobile-apps, an online indicator only available for users currently using the desktop-version of wire?

Would love some feedback about the idea and whether it is possible of a technological point of view.

**Comment by gregor** [comment]
Technically definitely possible. But we are a messenger focussed on privacy and security. Presence information is sensitive data that many users do not want to share. We have stayed away from this feature for this and other reasons.

**Comment by tokariu** [comment]
I agree, it's definitely sensitive data. But on the other hand it'd be a great feature.. think about other IM's and how they tried to circumvent this privacy problem:
most IM apps having online-status flags/featues also offer an option "show as offline" so other people can't determine the users online-status.
"show as offline" is the current state of Wire, because everybody seems to be offline as long as you haven't a conversation going on right now.
it could also be implemented as opt-in, that only those who people can enable it, who know the risks but still want to use it.

**Comment by tokariu** [comment]
just another thought: 
isn't there already a hidden "online-indicator" implemented with the received status of messages?
One could always write a msg to another user and see whether the msg is only "sent" (=offline) or "received" (=online) - and then delete this msg without the other user having time to read the msg?

If you say you stayed away from this feature due to privacy/secuirty reasons, how do you see it in this context?

**Comment by gregor** [comment]
Definitely a valid idea, and we discussed the benefit of the delivery status for a very long time for exactly this reason. In the end we decided to add it as what you described is not a hidden "online-indicator". The user does not need to open the app for a message to be delivered. Our user base is much bigger on mobile than on desktop. The mobile clients are always running. Thus this is more of a the "user is logged into Wire on at least one device" indicator. We do not share whether the user even touched is phone. We do not share whether the user has opened Wire. We do not share whether the user has had a chance to see you messag. We do not share whether the user read your message.

On the other hand delivery state allows us to create a lot more confidence in the message sending process creating trust that the message has made it to our server and to it's intended recipient. Previously we had a failure based approach, where we would only show anything in the UI is message sending would not go as expected. Now we opted to a much nicer progress approach that gives the user more feedback what we are doing with his message.

**Comment by tokariu** [comment]
Ok alright, for one moment I did not think about people being able to be connected over multiple devices at the same time and some of them being always connected to wire.
Right now it seems to be a good compromise between privacy and convenience when it comes to message status information. And I think it's a lot better than the failure based approch.

However, as I was writing in the initial post, I thought about this feature especially for the Wire-Desktop version, leaving the mobile versions apart for a moment.
I know, as you mentioned, your mobile userbase currently outweighs the desktop wire userbase. But if you think about the Desktop users as a standalone Customer-base, it could really make some sense to have a feature like this.

I guess when you currently think of an average wire user, he uses either only a mobile phone or a mobile phone plus sometimes a web/desktop app.
But I think there could and probably will be a desktop-only userbase too in the future, if the desktop-client is getting the needed features. And that's something where Wire still has some potential to fulfill.

So assuming that there is a userbase only using the desktop version of wire, wouldn't it make sense to offer features all the other Desktop-only Instant Messengers offer too?
Actually, wire for desktop offers already a lot of things other desktop IMs offer too. But an online-status indicator is one of the most elemental things in desktop-IMs and it's currently missing.

Maybe it is possible to implement an online-status indicator for the desktop/web-app only, while leaving always-connected mobile phones apart.
Think of the Facebook browser-webchat: Currently browser logged in friends have a green dot in front of their names while friends currently on the go with a mobile app just have a gray smartphone icon, meaning they're always connected but you don't know if they'll see or read the messages right now.

Of course, due to respect of privacy, there should always be an option to hide the online-status. Either by disabling the feature completely in desktop-app-options or by switching to something like an "show as offline"-status.

All this depends of course on what you want Wire to be. Mainly a mobile-app with just some shallow desktop extension? Or a full featured desktop Instant Messenger with mobile-phone extension. Maybe someday it's possible to have both worlds full-featured?

**Comment by shvchk** [comment]
Yep, status would be nice. Default could be "Invisible" for privacy,  just as it is now. In addition users could set "Online", "Away", "Busy", custom text + icon **if they so choose**.

**Comment by MadEgg** [comment]
I would really like this functionality, in severely limited use cases. I think it can be combined without having a (unwanted) impact on privacy. If you configure online-status notification per device (so that you can for example disable in on mobile but enable it on desktop), and per conversation, you can only share your online presence with just who you want.

If 'being online' is then also not maintained as a contact status, but rather as a online request that's sent as an out-of-band message, no information regarding online presence is kept on the servers.

Such as:

* Sally wants to see if Dave is online, and for this purpose opens her chat with Dave
* Sally's device automatically (if functionality is enabled) sends a message to Dave's account which doesn't really show up but is a 'are-you-online' request.
* Each of Dave's devices receives this request, and each online device considers whether to reply, based on app- and conversation configuration. If the conversation partner (Sally) is allowed to see online status and the feature is enabled on that device, it replies to Sally 'I-am-online'.
* Sally's device then receives either zero replies, indicating that Dave is offline (or doesn't allow Sally to know), or one or more replies, indicating that Dave is online.

If this feature is disabled by default but can be enabled for specific chat-partners, that'd be a great feature for me.

I understand and respect the choice for not implementing online status and/or a 'message read'-status, and have disabled it for the exact same purposes on other messengers, but for some contacts I would find this feature very useful, especially in a way that prevents this information being available on the server.

**Comment by cspitzlay** [comment]
I agree that online status information is sensitive.
I would like to add two use cases though that I would find very useful if supported:

"As long as I am at work I would like my colleagues to be able to see my online status."
"I would like my family members to always be able to see my online status."

That would require
* a user grouping feature
* a privacy setting per group 
* the selective disclosure of status information if the setting allows it.
* Ideally, the setting would also make the devices selectable (or provide an option like "Include mobile devices")

**Comment by JustAskin** [comment]
I came to demand this exact feature! As others already said, for privacy you can add an 'appear offline' option or enable it on a user-by-user basis. It's very annoying to not know who's on/off and it hinders mainstream Wire adoption.

**Comment by Iridias** [comment]
I also want to have this feature! And as mentioned before: privacy is not a valid argument against it, if the users have to explicitly enable the feature. I assume, most users out there don't have any privacy-concerns, if their friends know whether they're online or not - rather the opposite. I want to let my friends know when I'm online.

**Comment by DetlevCM** [comment]
Hello all,

I recently (yesterday, the 8th of Feb 2017) started to try and transition my IM to Wire (having been annoyed by Skype rather severely...)
Of course this starts with close friends and family - and incidentally, out of the two contacts set up (as of writing this), both currently use the desktop client (Windows & Linux). I plan to get a third person onto Wire soon and this person will also be using either the desktop client or the browser.

So status messages are most definitely something I miss - at least it seems stupid to then have to check if a person is online by using another messenger/tool.

So this would be another vote in favour. And as others have indicated, a "show as invisible status" can be added for privacy. Heck, rather than defaulting to "away" as many messengers do, Wire could offer the opportunity to default to "invisible" after a user defined time period.

**Comment by andrassp** [comment]
Hi,

I would like to request this feature as well. I'm looking to get away from Skype, specifically because Skype no longer accurately updates if people are online or offline. I don't feel like wasting time every day trying to call people that might, or might not, be at the computer.

**Comment by andrassp** [comment]
Yeah, I'll use this if it gets that feature. I use Skype for international calls to family, and if I have to call 20+ times a day just to check if they're online I'd rather just stay on Skype tbh.

**Comment by anatoli26** [comment]
I also would like to have an online status and message seen/read clue (like the blue double check in wapp). As others said, privacy is important, but I believe for every single privacy-concerned user there are about 10 of his/her friends/family members who don't even understand why so much buzz about privacy and why should they stop using wapp with you and install some (yet) unknown app...

These 2 features (online status and message seen indicators) could be options, just that. And they could even be off by default, so if the user wants to see the status/message seen of others, he/she should turn these options on. There could be some warning about privacy risks, but IMO all privacy-aware users already know what implications these options would have. And those who don't care or who understand that they won't be negatively impacted by the consequences, shouldn't be limited.

I like the approach of allowing users to make their own decisions vs deciding for them what are their threat vectors, use cases and the best solutions for their situations.

Better yet would be to implement a per-contact permissions like in Telegram (the Last Seen setting, same way would be the Message Read notification), so here would be no privacy concerns as only the trusted peers would be able to see the status.

![t_ps](https://cloud.githubusercontent.com/assets/22968420/23100041/03b0074a-f676-11e6-9ebb-b1376dbab874.png)

**Comment by pteron** [comment]
Have to agree with the majority comments here, I'd definitely like online status and read receipts as options per contact. 

When I try to get people to move from whatsapp, this is the first problem they raise.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. We are however always continuously revisiting this topic and based on the needs of our users we will prioritise the issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by shvchk** [comment]
There is already an issue for discussion there: https://github.com/wireapp/wire/issues/24

**Comment by lfarkas** [comment]
Maybe it'd be useful to treat desktop app differently then the mobile app. since on mobile you always "logged in" or online, but as most people use it for work or as a online communication platform for the desktop app this feature can be treated differently.
