### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#1280]
**Wire-Desktop-App on Debian 9**

- mannings-bug: unencrypted chats are stored in the logs (no option to disable)
- TLS Cipher Suites could be better [1]
- no HTTPS securityfeatures like: **OCSP.Stabling**, **DNSSEC**, **DANE/TLSA** & **HKPS** [1, 2]

[1] https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03116/TLS-Checkliste.html
[2] https://www.hardenize.com/report/app.wire.com/1518461352

Please correct me if I am wrong.

**Comment by raphaelrobert** [comment]
To address your points:

 - Logs: public builds of the desktop app don't have any logs enabled, only debug versions do
 - TLS: we have to maintain compatibility for older Android version, but we are looking into moving to TLSv1.2 exclusively soon
 - OCSP stapling and DNSSEC are unfortunately not supported by AWS, DANE/TLSA is only relevant for emails (i.e. irrelevant for the Wire web app), HPKP (which you probably mean by HKPS) is no longer supported by Chrome

Hope this clarifies a bit.
