### ISSUE TITLE
Infinite loop on startup

### ISSUE THREAD

**Issue by danielroehrig-mm** [wireapp/wire-desktop#1289]
Wire is trapped in an endless loop on startup, going from "Hello Daniel", to "Fetching your connections and conversations" to "Checking for new messages" to a flash of white before starting all over again. I am still connected to my account via the mobile app and somehow the same setup (OS and Wire version) is working at a different computer.

Version 2.13.2741, Ubuntu (Budgie) 17.10, 64 Bit

**Comment by danielroehrig-mm** [comment]
Starting wire from a terminal worked twice. Now it is also stuck in an endless loop but this time it gives me a warning: 
`(node:15178) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by dougjewsbury** [comment]
I have exactly the same issue on Ubuntu 17.04. It seems like a recent development. Wire has been working fine up to two or three days ago.

**Comment by dougjewsbury** [comment]
In my case, the loop isn't infinite. Eventually, the program logs in, but it can take anywhere from 5 to 20 minutes of flashing screen and repeating the same messages before it happens.

**Comment by danielroehrig-mm** [comment]
You are right. This time it took about 6 minutes.

**Comment by mythsunwind** [comment]
Can you try to run wire from the console with `wire-desktop --devtools` and enter `$("webview").openDevTools()` into the web console to get some logs? Make sure you checked "Preserve log" in all console windows.

**Comment by danielroehrig-mm** [comment]
I would love to, but `wire-desktop --devtools` does not open a web console for me.

**Comment by mythsunwind** [comment]
Make sure, the app is closed completely before (through the menu | quit)

**Comment by danielroehrig-mm** [comment]
Done. Where do you want me to send the logs to? It's quite long. 

This happens over and over again:
`/opt/wire-desktop/resources/app/js/preload.js:39Logging into file /home/droehrig/.config/Wire/console.log
Navigated to https://app.wire.com/?hl=en`

**Comment by danielroehrig-mm** [comment]
Just an idea, but I am missing a couple of avatars all of a sudden. Could these be the 404s that I encountered?

**Comment by mythsunwind** [comment]
Can you send one sample URL of the URLs that you get a 404 for?

**Comment by danielroehrig-mm** [comment]
https://prod-nginz-https.wire.com/assets/v3/3-2-de84d712-9409-4b0b-8a7d-4f2…205762.t=a.l=.u=94673fee-72d9-4a17-a28f-f0353c4a0d36.c=8079095820925435811

**Comment by 0xfd000000** [comment]
Hate to be the one "+1"ing here, but I did go to the effort to make a screencap of the inifinite loop so I can't resist commenting:
https://youtu.be/CQ9LCVyaybk
Version is 2.13.2730
To provide another data point, here's one of the URLs that fail for me:
https://prod-nginz-https.wire.com/assets/v3/3-2-88c8a939-f1dd-4196-a2c7-066b6f4e44b1?access_token=u56vKrNwkUArTZgjD-9SGJ9T8aSgud57p-k0T1f3qKECuQRFxOxkUE_aI7eFG6gLJ8eDX-UgoOI-yUAZ2rhGAA==.v=1.k=1.d=1521454463.t=a.l=.u=bf90f95c-067d-43a9-8451-18e4e36cf864.c=5286835830505680649

When launching "wire --devtools" it starts without infinite loop. 

$("webview").openDevTools() does not work for me.

The logfile that is created only contains two lines for me so I guess it's not of any use.

**Comment by 0xfd000000** [comment]
Correction: with --devtools, I do enter the loop from time to time, but it is not infinite.
In the console I can see that the main page is being reloaded over and over:

`Navigated to https://app.wire.com/?hl=en
/usr/lib/wire/resources/app/js/preload.js:39
Logging into file /home/xxxxx/.config/Wire/console.log`

Appears over and over until finally the UI shows up and the 404s fill the console

**Comment by 0xfd000000** [comment]
Update: updated to 3.0.2816, seems to behave now.

**Comment by ffflorian** [comment]
@0xfd000000 since your issue is resolved, I'll close this for now. Feel free to comment if the problem still exists.

**Comment by danielroehrig-mm** [comment]
The problem is not solved for me. Linux, Version 2.13.2741, Web Version 2018.03.12.1141

**Comment by ffflorian** [comment]
Sorry @danielroehrig-mm, I'll reopen.

**Comment by danielroehrig-mm** [comment]
Wait. I'm a little confused. I realized that I was on Version 2.13.2741 while @ffflorian is on version 3.0.2816. I am pretty sure I used to receive updates for wire but this time it seems like this didn't happen. I manually updated to version 3.0.2816 and indeed it seems to work. So maybe the bug is fixed and I need to look at the updating mechanism.

**Comment by danielroehrig-mm** [comment]
So, yeah. I didn't have the ppa enabled so I was stuck at an old version. I am sorry for the confusion.
