### ISSUE TITLE
Wire prevents my screen from going to sleep

### ISSUE THREAD

**Issue by Ham-Radio** [wireapp/wire-desktop#129]
I am on Arch with KDE. I have tested it multiple times, and it seems like Wire is preventing my screen from going to sleep.

**Comment by ConorIA** [comment]
Do you have a plugin like caffeine installed? I use Wire on both Mate and Gnome and have had no problems. Out of curiosity, did you install from the AUR? If so, what package are you using?

**Comment by lipis** [comment]
We are not doing anything special to prevent it.. unless Electron does it.. so if we can figure out the cause we can escalate it to them.

**Comment by herrmannplatz** [comment]
So we had this issue on mac where an audio context was created on app start which prevented the mac from going to sleep. do you had a call?

**Comment by gregor** [comment]
If anyone runs into this problem again on Mac, please run the command `pmset -g assertions` from the console and let us now the output.

**Comment by Ham-Radio** [comment]
I don't have caffeine installed. I restart my computer, allow the screen to go to sleep, then I start Wire and the screen doesn't go to sleep. I did install from the AUR...https://aur.archlinux.org/packages/wire-desktop-bin/

**Comment by Ham-Radio** [comment]
I just updated WIRE and the issue seems to have been resolved in the latest update. Thanks! :)

**Comment by lipis** [comment]
latest `.deb` could be found from the _official_ sources: https://wire.com/download/

**Comment by ConorIA** [comment]
Or use either of my PKGBUILDs (wire-desktop and wire-desktop-git) and build it fresh. :wink:
