### ISSUE TITLE
Scrolling only working one way

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-desktop#130]
For some reason, I can only scroll down in a conversation (view older messages), but I can't scroll back up. In order to see the last message, I need to send a new message, which pulls my view back to the bottom.

**Comment by ConorIA** [comment]
Just installed from the yarn branch, (I wanted to get the PKGBUILD ready) and scrolling works. Must have been something off on my install.

**Comment by lipis** [comment]
Best kind of issues.. The ones that are closing on their own :)
