### ISSUE TITLE
default language after restart

### ISSUE THREAD

**Issue by Supersempfft** [wireapp/wire-desktop#1301]
Hi,
where do I set the language permanently? I´m using wire-3.0.2816-x86_64.AppImage on Linux.
Best
Andy

**Comment by ffflorian** [comment]
Hi @Supersempfft, right now there is a bug regarding this in the Desktop app on Linux, please see https://github.com/wireapp/wire-desktop/issues/1097#issuecomment-372035670. Closing this as duplicate.
