### ISSUE TITLE
wire.com website not accessible from within China

### ISSUE THREAD

**Issue by aquatooth** [wireapp/wire-desktop#1302]
Wire version: Version 3.0.2816
Wire for web version: Wire for Web Version 2018.02.01.1026
Operating system: Ubuntu 14.04 LTS and 16.10 LTS
Which antivirus software do you have installed: none

What steps will reproduce the problem?
1. open wire.com in browser
2.
3.

What is the expected result?
wire.com page loads and is displayed

What is the actual result?
Browser reports timed out

Please provide any additional information below. Attach a screenshot if
possible.
Ping also times out

**Comment by Supersempfft** [comment]
This is China. Other internet connection possible?

**Comment by gregor** [comment]
The website is hosted on AWS servers in Europe. There is no plan to change that. The issue is also unrelated to the desktop app which this repository is for. We obviously cannot change the blocking that is in place in China and have no plans to migrate the website to another service.
