### ISSUE TITLE
Wire not usable from within China 

### ISSUE THREAD

**Issue by aquatooth** [wireapp/wire-desktop#1303]
Wire version: Version 3.0.2816
Wire for web version: Wire for Web Version 2018.02.01.1026
Operating system: Ubuntu 14.04 LTS and 16.10 LTS
Which antivirus software do you have installed: none

What steps will reproduce the problem?
1. Open Wire
2.
3.

What is the expected result?
Opens and logs in, displays wire

What is the actual result?
A message "NO INTERNET. YOU WON"T BE ABLE TO SEND OR RECEIVE MESSAGES"
Is displayed in the Wire bar

Please provide any additional information below. Attach a screenshot if
possible.
I do in fact have internet access

**Comment by aquatooth** [comment]
Upon reboot and restarting Wire, the screen is blue without any text.
Also the "Wire for Web Version" is absent

**Comment by Supersempfft** [comment]
Well, China terminates crypt connetions often.

**Comment by ffflorian** [comment]
See https://github.com/wireapp/wire-desktop/issues/1302#issuecomment-368516524.
