### ISSUE TITLE
Unable to use PPA for updates from within China

### ISSUE THREAD

**Issue by aquatooth** [wireapp/wire-desktop#1304]
Wire version: Version 3.0.2816
Wire for web version: Wire for Web Version 2018.02.01.1026
Operating system: Ubuntu 14.04 LTS and 16.10 LTS
Which antivirus software do you have installed: none

What steps will reproduce the problem?
1. Automatic or manually updating Ubuntu with PPA for wire ticked under software and updates
2.
3.

What is the expected result?
https://wire-app.wire.com_____Packages.xz (cut the long URL) should download updates and install them

What is the actual result?
After a very long wait the Ubuntu update fails with the error message;
"Failed to download repository information"
Please provide any additional information below. Attach a screenshot if
possible.
To disable the wire PPA so that other updates are able to update normally, do this;
DASH>Software and Updates, click on Other Software tab
Look for 'wire-app.wire.com/linux/debian, deselect tick click close then authenticate with your password

**Comment by ffflorian** [comment]
See https://github.com/wireapp/wire-desktop/issues/1302#issuecomment-368516524.

**Comment by Aikatsui** [comment]
@aquatooth there's a snap version now available (might maintain by snapcraft) and it's possible to self-host wire platform
currently wire doesn't seriously care about migrate their hosting service
