### ISSUE TITLE
"npm run build:macos" expects code signing certificate

### ISSUE THREAD

**Issue by daniel-gallagher** [wireapp/wire-desktop#1314]
What steps will reproduce the problem?
1. Follow README instructions
2. Run 'npm run build:macos'

What is the expected result?

Build an internal version of Wire for testing crypto speed improvements on MacOS

What is the actual result?

Build fails with the following error:
`Warning: Command failed: codesign --deep -fs '3rd Party Mac Developer Application: Wire Swiss GmbH (EDF3JCE8BC)' --entitlements 'resources/macos/entitlements/child.plist' 'wrap/dist/Wire-mas-x64/Wire.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework'
error: The specified item could not be found in the keychain.
 Use --force to continue.`

Please provide any additional information below. Attach a screenshot if
possible.

---
I just wanted to give a quick heads up that there might need to be a minor change to package.json in order to successfully build Wire from source on MacOS using the instructions in the README. It seems that the default is to build the prod version, which throws an error when looking for the code signing cert. 

Changing `"build:macos": "grunt macos-prod"` to `"build:macos": "grunt macos"` in package.json seemed to do the trick and kicks off an internal build instead.

**Comment by bennyn** [comment]
Hi @daniel-gallagher, the `grunt macos-prod` script is something that we execute when creating a macOS build for the Mac App Store. It's there for internal use, so you should really run `grunt macos` (as you just did).
