### ISSUE TITLE
Feature request : Allow image paste from clipboard

### ISSUE THREAD

**Issue by relyd** [wireapp/wire-desktop#132]
Pasting image data is currently unavailable (Win client).
Electron clipboard API : 
[Clipboard API](https://github.com/electron/electron/blob/master/docs/api/clipboard.md)

Thanks for considering

**Comment by helenakos** [comment]
Thanks @relyd , this is one of the most wanted features on Wire for Web as well.

**Comment by ConorIA** [comment]
Re: previous comment: https://github.com/wireapp/wire-webapp/issues/236

**Comment by lipis** [comment]
Thanks @ConorIA I'll close it as duplicate of wireapp/wire-webapp#236
