### ISSUE TITLE
Any updates regarding max size for sending files?

### ISSUE THREAD

**Issue by amun1** [wireapp/wire-desktop#1326]
A year and a half ago the original issue [#12](https://github.com/wireapp/wire-desktop/issues/12) was closed while stating "we are looking into increasing the file size limit" but since then nothing has changed.

I'm asking for an update because as a result of this issue I am unable to persuade some of my contacts to switch from skype to Wire.

Apparently they are used to exchanging a bunch of photos by putting them in a zip folder and sending that file via skype because it allows a file size up to 300MB.

While exchanging a bunch of photos via Wire is no problem for the sender, it's really cumbersome for the receiver because the files have to be downloaded and saved one by one.

From what I understand the file size is limited to 25MB in Wire because encrypting/decrypting a file uses an amount of ram that is equal to (or maybe even higher than) the size of the file and trying to encrypt/decrypt larger files would be impossible if the device has an insufficient amount of free ram.

Now I understand that this could be the case for mobile devices but considering the fact that most laptops/desktops have a larger amount of ram than most mobile devices wouldn't it be possible to at least allow sending larger files via wire-desktop and https://app.wire.com?

Or maybe Wire could check the available amount of free ram and if sufficient (taking a safe margin into account) allow for a max size of let's say 300MB when sending files (and for example warn receiver to download file on a different device if the current one has an insufficient amount of free ram)?

**Comment by EvaZg** [comment]
Hi,
thank you for you interest in Wire.
This is an issue we plan to pick up in the near future, but no further details to share just yet. However, as soon as it is available we will make sure to let you know.

**Comment by lunixgeek** [comment]
I too would like to see larger file size transfers when possible as it will help me to move friends off of Skype.  Just thought I would add my .02C to the choir here.  Many thanks for a great product.

**Comment by oscardssmith** [comment]
Why can't you just break all files >`5mb` or so into smaller chunks, encrypt, send, decrypt those chunks and combine client-side? This seems like it shouldn't be that hard.

**Comment by amun1** [comment]
Apparently this is going nowhere, I'll be moving on now.

> Maximum file size for team accounts is now 100MB (25MB for free accounts).

[Source: Wire Release Notes Aug 22 2018](https://medium.com/wire-news/wire-for-web-2018-08-22-68c51bf006ad?source=collection_home---6------2----------------)
