### ISSUE TITLE
"Developer" menu has some issues switching between webapps

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-desktop#1330]
Wire version: 3.0.2816
Wire for web version: 2018.03.07.1459
Operating system: Arch Linux

This ticket is about the "Developer" menu in the internal build, so treat it more like a FYI 🙂

1. Start from scratch by closing Wire, running `rm -rf ~/.config/WireInternal` and starting Wire again.
2. Log in
3. Check the current webapp url:
    - Menu > Developer > Internal is selected     - 👍 
    - Menu > Developer > Toggle DevTools > First > Console > `window.location` > `"https://wire-webapp-staging.wire.com"`   - 👍 
4. Click on Menu > Developer > Production, app reloads
    - Menu > Developer > Production is selected     - 👍 
    - Menu > Developer > Toggle DevTools > First > Console > `window.location` > `"https://wire-webapp-staging.wire.com/..."`   - 👎 👎 👎 
5. Close Wire and open it again.
    - Login screen is shown, history is gone 😞 
    - Menu > Developer > Production is selected     - 👍 
    - Menu > Developer > Toggle DevTools > First > Console > `window.location` > `""https://app.wire.com/login/..."`   - 👍 
6. Switch to Internal again - still see the Login screen 😞 

I don't expect it to be fixed if you say it's by design, but if you actually want this functionality to work - then now you know 🙂 

I noticed this when I discovered https://github.com/wireapp/wire-webapp/issues/2713 earlier today, I wanted to switch to Production while waiting for a bug fix, but no luck.

**Comment by gregor** [comment]
Currently the switch only works if you restart the app after making a change. We never got around to fix internal tool when we introduced the multiple account support.

**Comment by maximbaz** [comment]
Got it - what about history loss between switching, is it known/expected? I checked a few times, seems consistent

**Comment by gregor** [comment]
Yes. It is somewhat hasslesome to use and not recommended for daily use.
