### ISSUE TITLE
Voice Activation

### ISSUE THREAD

**Issue by shumvgolove** [wireapp/wire-desktop#1336]
[This](https://github.com/wireapp/wire-desktop/issues/1146) was considered earlier, but didn't go any further. Can we get activation on voice recognition? I think it's really important feature in modern 	communication software.

**Comment by gregor** [comment]
Not at this time. In the nature of this being a feature request I am again going to close the issue.

**Comment by gregor** [comment]
While looking through the code for some other adjustments I noticed that the feature was not enabled in case you were on the ANSWER side of the SDP connection.

This is fixed with https://github.com/wireapp/wire-webapp/pull/3598. Experience should improve with the next release.
