### ISSUE TITLE
Missed messages

### ISSUE THREAD

**Issue by Da0012** [wireapp/wire-desktop#1340]
On one device I can't to see messages sent from my other device

Wire version: 3.0.2816 desktop linux, android 3.8.412
Wire for web version: <Check the About dialog>
Operating system: Ubuntu 17.10,android 7.1.2

What steps will reproduce the problem?
1.Write any message on smart-phone or desktop
2.View missed messages

What is the expected result?
Be able to view all messages regardless of the device from which they were sent

What is the actual result?
On one device I don't see messages sent from my other device

**Comment by gregor** [comment]
Are all of your messages missing or just a specific type of message? The cross device sync for your own messages generally works so it would be interesting to figure out why it does not for you.

**Comment by Da0012** [comment]
All messages, i have two Linux desktop and one phone,and the same happens regardless of the source device.I have restarted sessions.

**Comment by gregor** [comment]
Timed messages are no synched to your other devices. This is by design.

**Comment by gregor** [comment]
They only stay in squiggly text on the sending device. Your other devices never receive them.
