### ISSUE TITLE
[Kubuntu] No smileys selectable in chat window

### ISSUE THREAD

**Issue by flipreverse** [wireapp/wire-desktop#1357]
Wire version: 3.0.2816
Wire for web version: 2018.03.12.1141
Operating system: Ubuntu 17.10 with KDE
Which antivirus software do you have installed: None.
What steps will reproduce the problem?
1. Open any conversation
2. Try to add a smiley

What is the expected result?
I expect a clickable symbol which shows smileys to choose from.

What is the actual result?
No smiley selection as shown in the red rectangle.
![wire-no-smiley](https://user-images.githubusercontent.com/1066130/37864530-b76dbd70-2f70-11e8-88af-3a9b1794fa00.png)

**Comment by mythsunwind** [comment]
We have an open issue for this feature request: https://github.com/wireapp/wire-desktop/issues/745

There is emoji-auto-complete feature when you type a colon and letters (or example ":cat") you will see an emoji selected.
