### ISSUE TITLE
[Ubuntu] Web Camera does not work with v4l2convert.so or v4l1compat.so preload

### ISSUE THREAD

**Issue by brokoli-mate** [wireapp/wire-desktop#1358]
Wire version: 3.0.2816
Wire for web version: 2018.03.12.1141
Operating system: Ubuntu 17.10 x86_64
Which antivirus software do you have installed:no antivirus

What steps will reproduce the problem?
1. Run in terminal:
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l1compat.so wire-desktop`
or
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l2convert.so wire-desktop`
2. Go to Preferences -> Audio/Video

What is the expected result?
Webcam works without  upside down image on ASUS laptop

What is the actual result?
Black image instead, webcam does not work.

Additional information:
I need to run it this way because of the issue with ASUS webcams with upside/down image.
This works well with skype and chromium and should work with any other app, that uses webcam.
Possible workaround:
Run **chromium** with **v4l2convert.so** or **v4l1compat.so** **preloaded** and use [web interface](https://app.wire.com/)

**Comment by gregor** [comment]
We can't give support for individual device issues with the unsupported Linux versions. We do not have any device specific hacks in place. Either it works with the Chrome browser or not.
