### ISSUE TITLE
Login take ages........

### ISSUE THREAD

**Issue by vincegre** [wireapp/wire-desktop#1365]
Wire version: 3.0.2816 (problem present since a long time !!)
Operating system: Same on Ubuntu 16.04 and 17.10
Which antivirus software do you have installed: N/A

What steps will reproduce the problem?
1. Start Wire app and then it take ages to open, stalling on Deccrypting messages
2. Most of time you have to restart app till it wants to start correctly but most of time get stuck on that boring message

**Comment by ffflorian** [comment]
Hi @vincegre, thanks for flagging. We although have a ticket here already: https://github.com/wireapp/wire-desktop/issues/1105.

Closing as duplicate.

**Comment by vincegre** [comment]
Thanks @ffflorian but looking at original ticket looks like it'll be one more of all these bugs making Wire so boring to use day after day and without hopes of improvement, only working worse and worse and no fix at all :(
