### ISSUE TITLE
Force Login on Startup before decrypt my Messages!

### ISSUE THREAD

**Issue by Delikt** [wireapp/wire-desktop#1376]
Wire version: undefined on my Desktop (self compiled), on my Notebook 3.0.2816 from the .deb
Operating system: Linux Mint 18.3 - Kernel: 4.13.0-37-generic
Which antivirus software do you have installed: anti what? :)

What steps will reproduce the problem?
1. Start App ->
2. see automaticly decryption and wonder..

What is the expected result?
If i open the application, i should be forced to Login or even enter a Passphrase before the App start the decryption!!

What is the actual result?
Login without verification

-----> The App should force me to enter a Passphrase before decrypt my messages and Log me in!

Sure i can always Logout manually before i close the App, but i need to think about it every time... this mechanism isn’t secure in the current state!

**Comment by ffflorian** [comment]
Hi @Delikt, thanks for the suggestion, please see https://github.com/wireapp/wire-desktop/issues/941#issuecomment-330468980.

Closing this as duplicate.
