### ISSUE TITLE
After wake up of my laptop I got exception

### ISSUE THREAD

**Issue by varosi** [wireapp/wire-desktop#1378]
Wire version: 3.0.2828
Wire for web version: 2018.03.12.1141
Operating system: Windows 10 Home x64
Which antivirus software do you have installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?
1. Run Wire Desktop app on a laptop
2. Sleep your laptop
3. Wake it up (possibly on different place with different WiFi)

What is the expected result?
To continue to work well.

What is the actual result?
![image](https://user-images.githubusercontent.com/6051718/38174931-6a858aa6-35dd-11e8-9b17-850facc5816e.png)

**Comment by ffflorian** [comment]
Hi @varosi, thanks for reporting but we already have a ticket for this here: https://github.com/wireapp/wire-desktop/issues/968.

Closing this as duplicate.
