### ISSUE TITLE
Uncaught Exception - Javascript error occured - AppImage

### ISSUE THREAD

**Issue by pgDS97Fq** [wireapp/wire-desktop#1381]
Wire version: 3.0.2816
Wire for web version: 2018.03.12.1141
Version installed: AppImage
Operating system: GNU/Linux Fedora 27
Which antivirus software do you have installed: N/A

What steps will reproduce the problem?
Whilst I can't be specific, it seems to occur without discernible pattern.
I've had this issue for a long time. 
It seems to be when Wire is in the background and a new message is received.
I will either see a black screen instead of the wire app or the error appears multiple times. To fix this I close the app completely and reopen.
 See Screenshot below for detailed error:

![error](https://user-images.githubusercontent.com/38013134/38206660-8c061a0a-36ab-11e8-9eb2-30db011b98a8.png)

**Comment by ffflorian** [comment]
Hi @pgDS97Fq, thanks for reporting but we already have a ticket for this here: https://github.com/wireapp/wire-desktop/issues/968.

Closing this as duplicate.
