### ISSUE TITLE
Add Spell Check

### ISSUE THREAD

**Issue by cwmke** [wireapp/wire-desktop#139]
I'm not sure if I am missing something or not but spell-check would be great to have. Is there a specific dependency for spell checking on Linux?

**Comment by olumby** [comment]
I don't see any spell checking on MacOS either. Perhaps [this](https://github.com/hokein/electron-sample-apps/tree/master/spell-check) could be of some use, I could look into it later.

**Comment by lipis** [comment]
I updated the title to remove the Linux from it as we don't support it in any platform.. We looked into it back in the day but had bunch of issues with early versions of Electron.. maybe now things are better! :)

**Comment by olumby** [comment]
I played around a little with [node-spellchecker](https://github.com/atom/node-spellchecker) just now and have added support for spell checking easily (only tested on MacOS).

I haven't yet tried adding it to the right-click menu though, so far it is just the red line. I will take another look shortly.

https://github.com/olumby/wire-desktop/commit/fa005c97f42ce31f37f735eb56c18345036491ef

**Comment by lipis** [comment]
@olumby That looks promising.. I think I saw somewhere that spellchecker comes to Electron natively.. but maybe I also dreamt about it.

**Comment by mcg** [comment]
https://github.com/electron/electron/pull/942 perhaps?

**Comment by olumby** [comment]
@mcg I was just reading that. 

I can look into adding it later unless anybody else wants to sooner.

**Comment by lipis** [comment]
No much rush from our side.. as it wasn't in our current timeline :) As I haven't checked into that subject lately.. obviously if we can get away without adding new dependency would be awesome!

**Comment by lipis** [comment]
Will close this in favor of #207 :)
