### ISSUE TITLE
Wire Helper idle cpu load on OS X

### ISSUE THREAD

**Issue by jensliebau** [wireapp/wire-desktop#14]
Hi,

when i run the desktop Wire.app on OS X (10.11.6) it starts a "Wire Helper". This is consuming about 15% CPU even if Wire is idle. That's definitely to much for an idle application.

**Comment by lipis** [comment]
Unfortunately we are aware of that issue, but luckily we are not the only ones with the [same problem](https://github.com/atom/atom/issues/3426). We are following this issue closely with Electron and Chromium, so we will report back here once we have something new.

Thanks for reporting it @jensliebau.

**Comment by bennyn** [comment]
@jensliebau Thanks for reporting! Can you please raise your voice also on https://github.com/atom/atom/issues/3426? 

As community we are stronger. Let's team up. :v:

**Comment by sirnacnud** [comment]
Is this issue dead in the water since Atom closed it? What do the helper processes actually do?
