### ISSUE TITLE
Multiple SIGSEGVs when sending youtube links and looking after the device list

### ISSUE THREAD

**Issue by Bandie** [wireapp/wire-desktop#1415]
Wire version: Version 3.0.0-f31a420
Wire for web version: Wire for Web Version 2018.04.12.1337
Operating system: Arch Linux
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. Get a youtube link
2. Post it into a conversation
3. --

What is the expected result?
- Youtube link will be sent correctly

What is the actual result?
- Segmentation fault on every start up if the conversation is still selected

Removing `~/.config/Wire` to restart everything won't help. I tried to list the fingerprints and it SIGSEGVs again.

**Comment by gregor** [comment]
We do not support self build versions from our master branch. Please stick with the publicly release builds from the commits we tagged as release.

**Comment by Bandie** [comment]
@gregor FYI: 
This is a bug report. Not a question for support.
