### ISSUE TITLE
App detects Linux as new device after update

### ISSUE THREAD

**Issue by felixwiemuth** [wireapp/wire-desktop#1423]
Wire version: Version 3.0.0-undefined
Wire for Web version: 2018.04.24.1458
Operating system: Arch Linux up-to-date

What steps will reproduce the problem?
(not sure) Update from 3.0.2816-1 (Arch package number) to current 2018.04.24.1458 via App (is it possible the app does that automatically? I can't remember clicking update, but there was a popup).

What is the expected result?
App stays logged in as usual on next start.

What is the actual result?
App asks to login, after login there is the message that the device is a new one and therefore history is not shown (and it is not shown).

It is interesting that the device is named "Wire Linux" while there is another device in the list named "Wire for Linux" which is probably the name of the same device before upgrade.

**Comment by gregor** [comment]
We advise against building any builds from master on Linux for your daily use. Please stick to the publicly released builds and commits tagged as release for Linux.

**Comment by felixwiemuth** [comment]
Well, the latest Linux release is [3.0.2816](https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.0.2816) and this is what the ArchLinux package with version 3.0.2816-1 installs. I just checked my installation log and this is the version currently installed and there was no upgrade since 2017-10-19. So the app must have updated automatically to the mentioned build which you say is not a realease. Is this possible?

**Comment by gregor** [comment]
Not really. Any build with undefined in the version string is a self build one. 3.x.x is a wrapper build number. 2018.xx.xx.xxxx is the build number of the webapp we are serving you. This will update whenever you restart the wrapper. If your 3.x number changed than it was through a package manager or a manual action.

**Comment by felixwiemuth** [comment]
Then I have no idea how this happened. I can however remember seeing the "There is a new version of Wire available" pop up being shown. And then there must have happened an upgrade, maybe I clicked "update" or similar in the app.
