### ISSUE TITLE
Any GTk3 or Qt version in the works?

### ISSUE THREAD

**Issue by Strit** [wireapp/wire-desktop#144]
Just started using Wire on my phone and found it for the Linux desktop.

A bit disappointed to see it's using GTK2, which is old and behind on features.

Obvious and probably easiest port would be to GTK3. But if you go to Qt it could work on Windows as well.

So my question is as the title says: Any of these being thought of?

**Comment by ConorIA** [comment]
The desktop app is based on Electron. It seems that GTK3 is recently supported (https://github.com/electron/electron/issues/2927). The app already works on Windows!

**Comment by lipis** [comment]
I think @Strit meant Windows mobile.. :) As for Qt there are no current plans to port it there, but maybe in the future we'll do something about it..

**Comment by Strit** [comment]
[quote=ConorIA]
The app already works on Windows!
[/quote]
What I meant is, that it could use QT on the Windows platform too, instead of some .net framework, or whatever it's using now.

[quote=lipis]
I think @Strit meant Windows mobile.. :)
[/quote]
Actually I was talking about the Windows desktop, but my point wasn't clear I guess.

I guess this question is a no then.
