### ISSUE TITLE
Not working for Ubuntu 18.04(after build)

### ISSUE THREAD

**Issue by yomiso** [wireapp/wire-desktop#1452]
Following installation steps:
```bash
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install nodejs
curl -sf -L https://static.rust-lang.org/rustup.sh | sh
sudo apt install libgconf2-4
git clone https://github.com/wireapp/wire-desktop.git
cd wire-desktop && npm install
npm start
```

It successfully installed. But gives some weird error like some JS files cannot be loaded when started and the interface is non-functional.

**Comment by ffflorian** [comment]
Hi @yomiso,

thanks for reporting. Can you please provide a log of the errors? Because I can't reproduce this.

By the way, Rust is no longer needed.

**Comment by gregor** [comment]
Closing as we did not get additional info.
