### ISSUE TITLE
Personal Account

### ISSUE THREAD

**Issue by trukurt** [wireapp/wire-desktop#1471]
To Whom It May Concern,

I believe I've accidentally created a team account in Wire, and now I'm locked out because I didn't pay to extend my service. I just want to change my account to a personal one, and rejoin my friends chat group. 

Currently I can't log in, or create a new account because my email address is already in use. 

How can I change my account type/delete my account and start again?

Kind regards,

Kurt

**Comment by kristin-wire** [comment]
Hi Kurt,

Sorry to hear about the confusion, but we can help you get it sorted out. Please open a ticket with us at support, and let us know the email you registered your team under. We can then unsuspend the account, and you can go in to teams.wire.com, delete the team, then create a new personal account under app.wire.com. Here's how to reach us:https://support.wire.com/hc/en-us/requests/new

**Comment by gregor** [comment]
As CS has taken over I am going to close this issue.
