### ISSUE TITLE
Linux desktop - stable package option?

### ISSUE THREAD

**Issue by janice2a** [wireapp/wire-desktop#1488]
The Electron package has a dependency on a higher version of Node.js than the Ubuntu 16.04 LTS build, and requires some work at the command line to install/run.
These dependencies present a challenge for many casual users of the Linux desktop.
Is there the possibility of an AppImage/Snap/Flatpack package for a stable instance which such casual users could utilize, whilst those interested in assisting with the development of the Electron approach could continue to work with this code on Github?

**Comment by gregor** [comment]
We provide stable packages for the released versions. Building code from master on this repo from any commits other than the ones marked as release for Linux is highly discouraged.
