### ISSUE TITLE
Support for Arch-based GNU/Linux distributions

### ISSUE THREAD

**Issue by ondrjs** [wireapp/wire-desktop#1513]
Hello,
are there any future plans for supporting Arch-based distributions packages (or - better - repositories) ,such as ArchLinux, Manjaro..?
I guess a lot of users of rolling Arch-based distros would really appreciated it.
Thanks for answer,
Regards,
ondrjs

**Comment by ffflorian** [comment]
Hi @ondrjs,
there is already [a package on AUR](https://aur.archlinux.org/packages/wire-desktop/) which is actively maintained by @ConorIA and @maximbaz.

**Comment by ondrjs** [comment]
Hey @ffflorian , many thanks! :)

**Comment by ffflorian** [comment]
No problem. I'll close this as it is solved.
