### ISSUE TITLE
Security issue 

### ISSUE THREAD

**Issue by aysufhne** [wireapp/wire-desktop#1526]
Hello everyone, 
Wire main statement says "The most secure collaboration platform", but I just noticed that you guys using this js nodes:

- fbjs 
- googleapis 
- google-auth-library 
- google-p12-pem

Yes, they are opensource under MIT license and stuff, nothing worry about...
But how about this scenario: group chat with 10 person, everything secure and OK, but someone suddenly throw Youtube video in this particular chat, where 10 persons immediately get images from google servers(and ofc google gets metadata), and wouldn't be so obvious for google or fb, that those 10 downloads are somehow connected? I mean, if video have 1k views for all time, and suddenly 10 people download preview for this video, mean that they are connected somehow, if we assume that google have many services like entire web, google could automatically draw lines between those people in chat, and suggest that they are. Am I wrong? At least would be great to have some option to turn off that APIs.

**Comment by kristin-wire** [comment]
Thanks for the suggestion, we added it to our list of future improvements.
