### ISSUE TITLE
Cannot Install on Zorin OS Lite

### ISSUE THREAD

**Issue by codeliger** [wireapp/wire-desktop#1527]
Distributor ID:	Zorin
Description:	Zorin OS 12.3
Release:	12
Codename:	xenial

`npm install`

> husky@0.14.3 install /home/codeliger/Downloads/wire-desktop/node_modules/husky
> node ./bin/install.js

sh: 1: node: not found
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-mac:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-mac@1.0.1
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.1.1
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! Linux 4.13.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! husky@0.14.3 install: `node ./bin/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the husky@0.14.3 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs husky
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/codeliger/Downloads/wire-desktop/npm-debug.log

**Comment by ffflorian** [comment]
Hi @codeliger,

it seems like your Node.js installation is broken - please try reinstalling Node.js before building.

Closing this since it's not an issue of Wire Desktop.
