### ISSUE TITLE
Macos app crashed on update

### ISSUE THREAD

**Issue by vlladdrakk** [wireapp/wire-desktop#1549]
Wire version: 3.1.2822 Wire for web version: 2018.06.19.0804 Operating system: Macos High Sierra 10.13.4 Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Click on update now button in update alert message.

What is the expected result?
I expected the app to either update in place, or install the update and restart.

What is the actual result?
The application crashed and Macos displayed a crash log for me.

Additional Information
[Here](https://paste.ubuntu.com/p/HHxWGW6txc/) is the crash log that Macos reported. Hope it helps.

**Comment by gregor** [comment]
@vlladdrakk Thanks. The issue is known. Unfortunately this is caused by an issue in electron. All that clicking the update now button does is restart the app in order to load the newest webapp version from our servers.

**Comment by gregor** [comment]
We have mitigated the situation with the release 3.3.2862 we pushed today. The reload is now a soft reload of the web contents while the app remains running. Thus it will no longer crash.

**Comment by vlladdrakk** [comment]
I just updated and it works perfectly now, thanks! :)
