### ISSUE TITLE
close button don't work after latest update

### ISSUE THREAD

**Issue by beew** [wireapp/wire-desktop#1555]
Wire version: 3.2.2840

Wire for web version: 2018.06.19.0804

Operating system: Ubuntu 16.04.4 64 bit with default unity desktop

What steps will reproduce the problem?
open wire
click close button 
nothing happen.
if click close then click minimize then window would close and leave only the tray icon as expected.

Now if click open in tray icon, wire doesn't open, but the toolbar appears. click maximize button on toolbar then window  opens.

expected behaviour (before update):
If window is open, click close button should close the window and leave only the tray icon.

Now click "open" in tray icon window should open

wire-desktop was installed and updated through the .deb repository.

**Comment by ffflorian** [comment]
@beew this should be fixed by now, can you confirm?

**Comment by beew** [comment]
@ffflorian Yes it works now.

**Comment by ffflorian** [comment]
Good to hear!
