### ISSUE TITLE
Crashes on macOS Mojave

### ISSUE THREAD

**Issue by NetOperatorWibby** [wireapp/wire-desktop#1558]
**Wire version:** The latest version (unable to check before app crashes)
**Operating system:** macOS 10.14

### What steps will reproduce the problem?
1. Install macOS Mojave
2. Install Wire
3. Open Wire

### What is the expected result?
Wire opens and loads messages.

### What is the actual result?
Wire hangs.

**Comment by KenanSulayman** [comment]
https://github.com/electron/electron/issues/13564

**Comment by NetOperatorWibby** [comment]
I forgot to add that [this comment](https://github.com/electron/electron/issues/13564#issuecomment-406824905) solved the issue for me!
