### ISSUE TITLE
Screen sharing option broken on linux

### ISSUE THREAD

**Issue by kotryyte** [wireapp/wire-desktop#1563]
Wire version: 3.2.2840
Wire for web version: 2018.06.19.0804
Operating system: Linux Mint 18.2 'Sonya' "Mate 64-bit"

What steps will reproduce the problem?
1.  Calling for other person
2.  Trying to share a screen

What is the expected result?
Option to select which screen I'm about to share if I have multiple.

What is the actual result?
No option to select shareable screen - both are shown as if non of them would be selected in an enormously terrible unreadable quality.

Once sharing the screen i receive such window with no option to select which screen to share. If I'm  clicking anywhere on any of these screens they're zooming in and out a bit, but neither of them are selected. 

![image](https://user-images.githubusercontent.com/17424619/41835390-0f86bfb0-7860-11e8-9ee5-634d4ba23b81.png)

**Comment by gregor** [comment]
Thank you very much for your report. We rely on the electron exposed Chromium API to share the desktop content. If it returns multiple screens, we will ask you, which one you want to share. There seems to be a lot of incompatibility with this on Linux. If the browser does not recognize the individual screens and informs us about a big screen consisting of all screen combined, we fail. I suspect this is related to the combination of Linux distribution and graphics driver you are using. We are out of luck in this case.

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/wire-webapp/pull/8848
