### ISSUE TITLE
[feature request] sort/reorder accounts in client

### ISSUE THREAD

**Issue by x2k13** [wireapp/wire-desktop#1568]
Please add an option to sort/reorder existing accounts in the client overview, preferably with drag 'n drop. 
Thank you.

**Comment by gregor** [comment]
Thanks for your feature request. This is an interesting idea. We will keep it in mind for future improvements to the product. With the nature of this issue being a feature request, I am going ahead with closing this as we solely keep this for bugs.

**Comment by x2k13** [comment]
Thanks for considering this. 🙂
