### ISSUE TITLE
Scrolling in OS X App, Smileys displayed wrong

### ISSUE THREAD

**Issue by Taddaeus** [wireapp/wire-desktop#157]
Hello,
I just recognized, that scrolling  with mouse wheel in the conversation sometimes failed. And sometimes are certain emojis only displayed as poor black and white symbols.
OS: 10.11.6

**Comment by ConorIA** [comment]
What version are you using? I had an issue on Linux where I could scroll backwards through history, but I could't get back down to the last message. This was resolved in a recent build. 

I think the 'poor black and white' symbols are from a new emoji api that seems to have made its way into the app. I quite like them.

**Comment by Taddaeus** [comment]
Hi,

exactly the same here! I`m using the Mac Appstore version 2.10.2652.
The smiley-issue must be on Wire… I`ve made a screenshot. 


If I copy it in Wire and paste it here, it`s this one:

☺️

I don`t know, when exactly it happens, but one time, I wasn`t able to send a message in the way I wanted – the emoji appeared with every klick as the strange one above.

If I respectfully can make a suggestion: It would be easier to use emojis if there would be an icon with popping up smileys… and if one could choose different options for using the return-key (send or return).


Best regards!

**Comment by Nuruddinjr** [comment]
I also confirm Scrolling is an issue especially when scrolling down, it doesn't work at all
