### ISSUE TITLE
Latest releases source code version number inconsistent

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-desktop#1576]
The latest release 3.2.2840 has source code using 3.0.2840. This means manual intervention in PKGBUILDs to use https://github.com/wireapp/wire-desktop/archive/release/3.0.2840.tar.gz instead of https://github.com/wireapp/wire-desktop/archive/release/3.2.2840.tar.gz. A small inconvenience, but something that should be fixed for consistency.

**Comment by gregor** [comment]
I fixed the release takes here on GitHub. Did you see the wrong number elsewhere?

**Comment by ConorIA** [comment]
Just on GitHub. Thanks, @gregor!
