### ISSUE TITLE
Audio drops when both parties start talking at the same time (Mac desktop app)

### ISSUE THREAD

**Issue by koorosh1224** [wireapp/wire-desktop#158]
Using two Mac OS (10.9.5), when we start talking at the same time, the application drops the audio and we can not hear each other. It is very annoying and disruptive that makes the conversation impossible. The build version is 2.10.2652. This problem does not appear when we both use the browser-based version of the app (https://app.wire.com). We tried also the scenario in which one party uses the Mac OS app and the other uses the web-based app. The problem was still present but it was significantly less disruptive.

**Comment by gregor** [comment]
This is the underlying Chrome browser trying to optimize call quality if you are not using a headset. Nothing we can possibly control. Please use a headset. You will see similar issues with other webRTC based call applications in Chrome. Thereby closing this.
