### ISSUE TITLE
page-up page-down buttons broken on linux desktop

### ISSUE THREAD

**Issue by libBletchley** [wireapp/wire-desktop#1583]
Wire version: 3.2.2840 Wire for web version: 2018.06.19.0804 Operating system: Debian Stretch Which antivirus software do you have installed: none

What steps will reproduce the problem?

Open a page with long history, and press the "Page Up" button.

What is the expected result?

The page should scroll up by one screenfull.

What is the actual result?

Nothing happens.

Not sure if this a bug report or a feature request, but in any case it would be useful to have this work.

**Comment by gregor** [comment]
This is a feature request as the page up/down is not supported. We have heard this a few times. We currently do not have the resources to implement it though. Could be a nice little contribution though. With the nature of this being a feature request I am going ahead to close the issue though as we solely keep this for bugs.
