### ISSUE TITLE
The demonstration screen Wire

### ISSUE THREAD

**Issue by luk4196** [wireapp/wire-desktop#159]
Please specify, are there any plans to implement screen sharing, it would be very great, many are waiting from you this functionality.

**Comment by ConorIA** [comment]
Screen sharing exists in the app

**Comment by lipis** [comment]
what browser are you using?

**Comment by lipis** [comment]
but the other hand this is desktop.. so it should beer there..

**Comment by luk4196** [comment]
Sorry to bother you, I installed the desktop version of Ubuntu 16.04.1, first time working with your application, saw the demos when we first met.

Thank you, already all found, once again I apologize.

**Comment by lipis** [comment]
We are glad you found it.. enjoy.. :)
