### ISSUE TITLE
Wire app doesn't start anymore

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-desktop#1611]
I just recently installed Arch Linux `4.14.55-1-lts`. I downloaded the ([desktop](https://wire-app.wire.com/linux/wire-3.2.2840-x86_64.AppImage)) AppImage `3.2.2840-x86_64` Wire app, set the executable flag, and try to run it...but nothing happens. I checked the `journatctl` logs and I see this:

```shell
Jul 15 19:04:26 uplink dbus-daemon[384]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jul 15 19:04:26 uplink systemd[1]: Started Hostname Service.
Jul 15 19:04:31 uplink gnome-shell[739]: setup_framebuffers: assertion 'width > 0' failed
Jul 15 19:04:33 uplink org.gnome.Nautilus[706]: /tmp/.mount_B0L68p/usr/bin/wire-desktop: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

Looks like there is some dependency missing. Shouldn't that be shipped along within the AppImage itself? The Flatpaks doesn't have these issues since the required "environment" is installed prior to the application.

**PS:** I have no anti-virus installed. As a workaround, I'm using the Web version – but eventually that doesn't affect it.

---

What steps will reproduce the problem?

1. Install any Linux distro that doesn't contain that dependency
2. Run it...enjoy the void since it doesn't even tell you, visually, what's going on ;)

**Q.** What is the expected result?
**A.** Wire dekstop app to be executed and opened successfully – or at least some dialog with an error message, etc.

**Q.** What is the actual result?
**A.** Literally nothing.

**Comment by ffflorian** [comment]
Hi @x80486,
which desktop environment are you using in your Arch Linux installation?
