### ISSUE TITLE
Microphone issue (USB with headset)

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#1616]
Wire version: 3.2.0-undefined Wire for web version: 2018.07.16.1405 Operating system: Solus 3.999 

Problem:
It would seem that Wire does not recognize the microphone that is attached to my headset. It's a one cable (one usb for both Sound and mirophone). 

**Note: In previous version this worked**

![Image](http://oi63.tinypic.com/675n2d.jpg)

**Comment by chdh** [comment]
I have the same problem with the Wire Desktop Electron app (version 3.2.2860) under Windows 7.

**Comment by gregor** [comment]
Thank you very much for your report. In one of the previous version of the underlying webapp we introduced a regression that would cause the preferences page to no longer work as inteded if you did not have a camera attached to your computer. We fixed this in our code base https://github.com/wireapp/wire-webapp/pull/4179 and pushed out a new version of the webapp this morning. If you quit and restart the app. you can select your microphone again.
