### ISSUE TITLE
processor use bad again on latest version

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#1617]
Wire version: 2.15.2750 
Operating system: macOS 10.12.6
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  launch wire
2.  use 1 hour timers
3.  talk for a while with a few people

What is the expected result?

Not having a CPU core pegged near 100%.

What is the actual result?

Pegs a core at near 100%.

Please provide any additional information below. Attach a screenshot if possible.

<img width="221" alt="screen shot 2018-07-18 at 12 32 58" src="https://user-images.githubusercontent.com/5317653/42857981-4cbf9fb2-8a87-11e8-9899-ef3c56e5cd1d.png">

This... basically should never happen. Chatting is not something that should take up over 90% of a core on a 2017 MacBook Pro. 

CPU issues have been with this app forever and the prior release was the first release that seemed to run without hammering the processor. I'm on a train for four hours, now I can't run Wire to talk to my contacts because doing so has already drained 50% of my Macbook's battery after about 90 minutes of use.

You really have to have this in mind with this application that all of your features are useless if you are going to shred a laptop battery. Because if the app is not running, no features can be accessed at all. Running efficiently is the #1 feature in a mobile world.

Please don't let these versions out of your lab if they are going to do this. My laptop is doing pretty much nothing else than trying to run Wire, and Wire is doing nothing else than receiving a handful of messages from 2 people and my own typing. It shouldn't run like it's trying to crack quantum encryption. It's a messaging app.

**Comment by gregor** [comment]
@dbquarrel Please update to a more recent version of Wire. The latest release version for macOS is at 3.12822, which can be updated via the store.

**Comment by gregor** [comment]
There is no safe downgrade path as electron relies on an instance of Chrome. The IndexedDB implementation has changed quite a bit over time and is not backwards compatible. You can do a history backup though and install one of the versions available at https://github.com/wireapp/wire-desktop/wiki/Builds. We do not recommend that though. Compatibility of newer webapp versions with older wrappers is not tested and might brake at any time.

**Comment by dbquarrel** [comment]
I just went through and deleted content on all active conversations, quit and restarted the app. So no messages, but some older conversations here with no content. This brought processor use down to 65%. 

After this I went through and deleted every conversation, even the empty ones, so I have nothing. Now processor use is down to 6%. So you have some kind of a problem for sure with conversations, even empty ones, occupying processor, spinning trying to check something or process something that is not there.

So at least this is a workaround to recommend when someone is pegging a processor to 100%, to wipe all conversations. 

Also a suggestion is a "delete all for both of us" command, if it's not there in the newer versions. Would help cleaning up in a situation like this.

<img width="223" alt="screen shot 2018-07-19 at 01 33 38" src="https://user-images.githubusercontent.com/5317653/42895188-14959f5c-8af4-11e8-8e3a-6812e8979f1b.png">

**Comment by dbquarrel** [comment]
A couple of days of conversations later and it's back up to 130% again. 

Lots of new bugs too so going to open some new threads.
<img width="222" alt="screen shot 2018-07-20 at 02 18 35" src="https://user-images.githubusercontent.com/5317653/42959353-646ffae8-8bc3-11e8-9a3e-95b025c6432d.png">

**Comment by dbquarrel** [comment]
I opened my Macbook Pro this morning to read messages from the team about how everything is working correctly and as by design. I wrote back to those. I've had the laptop open for about 30 minutes. My battery went down from 100% to 77% in this time and the laptop is super hot to the touch. 

Wonder what it could be.

<img width="224" alt="screen shot 2018-07-23 at 09 59 00" src="https://user-images.githubusercontent.com/5317653/43052300-5269920c-8e5f-11e8-87dc-9ec2c673e691.png">

"The battery draining feature is working as designed and we have no intention of revisiting the feature" - Thread closed

**Comment by dbquarrel** [comment]
I would like to leave a suggestion somewhere about regression testing being added to your project, and/or specifically testing each version for this kind of processor use. This is now forcing me to shut wire down and "log in" periodically to see if there are messages, and shut it down again to keep my machine alive. 

Basically it's like POP mail now for me. Log in, download messages, send responses and quit before my computer explodes into a fountain of lithium.

**Comment by kirusyaga** [comment]
Same situation on Windows. Process with opened window use 35-60% of CPU, in background CPU usage is 10-20%.

**Comment by gregor** [comment]
We have decreased the load created by ephemeral messages in https://github.com/wireapp/wire-webapp/pull/4149 which will be part of the next public webapp release. Please check back then,

**Comment by gregor** [comment]
The fix was pushed to production this morning. Please restart your desktop app and ensure that you are running webapp version 2018.08.06.0803. Timed messages should not longer cause the load to spike.
