### ISSUE TITLE
can't delete contacts

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#1621]
Wire version: 3.1.2822
Wire for web version: 2018.07.16.1405

Operating system: macOS sierra

What steps will reproduce the problem?

1. try to delete a contact

What is the expected result?

Be able to delete a contact.

What is the actual result?

You can't delete a contact.

Please provide any additional information below. Attach a screenshot if possible.

This has been in a while and I complained about it before. This makes no sense to be able to add contacts and the not be able to delete them. You have only the option to block them. Blocking them keeps them hanging around. You may not want to block them. You may only want to delete them. Blocking and deleting are not synonyms. 

There are times in life that you accumulate contacts and then you find out you are not talking at length anymore with them. So you want them off your contact list. They may not want YOU off their contact list and you may want to preserve the option for that person to message you again.

Blocking them deprives them of that option.

That's why they are not synonyms and should not be treated as such.

Let's think about the telephone now. 

Say, you call my phone by accident and you get a wrong number. If the phone added you automatically to my contacts, I'd tell the caller "sorry, wrong number" and then delete them from my contact list. But now say this person ends up having a legitimate reason for contacting me: we got in a car accident, my son is dating their daughter, we are on the same softball team, whatever, now, since I didn't put them on block, I can still accept a future call from them. 

If my option though is only permanent contact OR block, then, that can never happen until I find their contact and unblock them.

Of course every other messenger in the world implements it just like this. Add a contact, delete a contact, block a contact. For this exact reason. Adding them allows you to quickly message. Deleting means YOU no longer want to message THEM. Blocking means YOU don't want THEM to message YOU.

This is one of the very many logical ergonomic issues you have in this app. It is not congruent with either normal human behavior or else the messaging ecosystem. 

Email is another example, where I may want to trim people who emailed one once 3 years ago from my contacts list, but I don't want that person blocked. I am just not going to initiate contact again. Perhaps they were a lawyer at a law firm I engaged one time and I don't need to talk to them again. But if an issue opens up on that case and they need to contact me, I want them to be able to do this.

Wire, this paradigm does not exist.

You should adopt it as it is useful, natural, and puts you in harmony with everything else.

**Comment by gregor** [comment]
Thanks for the feature request. It was a conscious decision at the time to not add a contact deletion feature but a blocking. We currently do not plan to revisit the user management. This is also not of concern for the desktop app as it is part of the Wire protocol and behavior shared between client. We are aware of your feature request. As such I am going to close it. As always and as outlined in our issue template.

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11198 https://github.com/wireapp/wire/issues/206
