### ISSUE TITLE
wire upgrade notification not in sync with app store

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#1622]
I don't know the versions since this happened the last time I upgraded to current (3.1.2822)

What steps will reproduce the problem?

1.  wait for wire to update
2.  get the blue title bar that wire has a new update available
3.  click it and update wire

What is the expected result?

That you will be on the most recent version.

What is the actual result?

You are not on the most recent version. What you are on, I am ont sure.

Please provide any additional information below. Attach a screenshot if possible.

When I posted to the boards giving a bug report, I kept my wire updated in this way, and was told, to update to the most recent version of wire. Even though I already told wire to update and it did and no longer notified me.

This means that the window title bar notification does not bring you to the same version as the app store, and if it can't get you onto the latest version, then it is leading the user to the wrong conclusion that they are up to date.

As such this alert needs to be removed, or else made to function correctly, or else redirect the user to the app store which seems to work.

**Comment by gregor** [comment]
Our updating process is detailed in depth at https://support.wire.com/hc/en-us/articles/115001919905-How-do-Wire-updates-work-. We are aware of the complexity of it. We will look into improving it in the future. But there is nothin that "needs" to be done. Thank you for your concern. The banner does exactly what it is supposed to do. Update the webapp component. macOS users currently have to rely on the AppStore to be notified about available updates.
