### ISSUE TITLE
Sending messages with URLs to large Zip files crash Wire

### ISSUE THREAD

**Issue by daniel-lerch** [wireapp/wire-desktop#1642]
Wire version: 3.2.2860
Wire for web version: 2018.07.26.0854
Operating system: Windows 10 April Update (Build 17134.165)
Which antivirus software do you have installed: Windows Defender

What steps will reproduce the problem?

1.  Open any conversation in Wire
2.  Send a message containing a URL to a large Zip-File (tested with 670 MB)
3.  Send this message and wait for a few seconds

What is the expected result?

Wire will try to create a preview of this link. If it was clever, it would cancel the request just after receiving the header with `Content-Type: application/zip`. If not it will download the file, try to open it and fail because it is no html file. After the request the link will look the same and no preview will be shown.

What is the actual result?

Wire downloads the whole file and does not cancel after receiving the header. This can easily be confirmed by the Task-Manager when using an URL to a large file. While downloading the UI has less than 1 frame per second and reacts to user input, such as a chat message after many seconds. When the download finishes, the Wire screen turns black. Then you to select _Quit Wire_ and open it again.

Please provide any additional information below. Attach a screenshot if possible.

![](https://i.imgur.com/njkqqIV.png)

This screenshot was made a few seconds after sending the message when the download of the file was finished.

This bug only occurs when sending messages with URLs to large files, not when receiving those messages.

**Comment by gregor** [comment]
The latest desktop apps that we released today for all platforms addresses this issue. It was fixed in #1645 and #1671. The link preview creation will only check the head of html pages and never download more large files (or html pages for that matter).
