### ISSUE TITLE
How to get latest version of wire ?

### ISSUE THREAD

**Issue by DragonzMaster** [wireapp/wire-desktop#166]
I've downloaded Wire from the site (wire.com) and it is version 2.10.2652 but the latest one is 2.11.2671 so how to get the latest build of wire ?? Is there any chance to get the installer for it ??

**Comment by shvchk** [comment]
You can wait until new version is published in the wire.com download section, or build it yourself: https://github.com/wireapp/wire-desktop#wire-desktop

**Comment by DragonzMaster** [comment]
Thanks for replay,
But in "About Wire" it says 2.11.2652 so I don't think it is updated and still using the version back to August.
Also the "nupkg" is 2.11.2652.

**Comment by lipis** [comment]
Coming soon!!

**Comment by lipis** [comment]
What @shvchk  meant was that there are two parts in the Wire for Desktop.. the webapp inside has faster cycles and bunch of updates are appearing seamlessly.. but the shell (wrapper) has less frequent cycles, plus there are not huge updates usually there.. either case the wait is almost over! 

We will publish the new version today..

**Comment by shvchk** [comment]
2.11.2652 is the version of the wrapper (wire-desktop), this wrapper just requests regular web version from [app.wire.com](https://app.wire.com) and shows it to you, and this core app is always updated. Wrapper provides additional features for Wire to feel native to your system compared to browser tab (separate window, autostart, notifications, language selection, etc), so only these additional features are outdated, not the main Wire app.

**Comment by lipis** [comment]
<img width="396" alt="screen shot 2016-11-09 at 12 48 50" src="https://cloud.githubusercontent.com/assets/125676/20137474/ee36b346-a67a-11e6-95e1-d11a44794e6e.png">

**Comment by lipis** [comment]
The 2.11.2673 is released! Download from https://wire.com/download/ or restart your app to not wait too long for the auto update :)

**Comment by DragonzMaster** [comment]
Thanks, it is updated now.
@lipis But I've noticed that after downloading new "nupkg" the old one is deleted but the folder which contain the old version is still exist, so I can guess that updater don't delete old version and should do that.

**Comment by lipis** [comment]
I think the updater keeps the last two versions and this is something that we don't really control as we are depending on https://github.com/Squirrel/Squirrel.Windows
