### ISSUE TITLE
Indication in Wire

### ISSUE THREAD

**Issue by DimitriyPS** [wireapp/wire-desktop#1662]
Good day!

I hope I am writing this appeal where necessary. This is not an error message. This is a request for additional features.

I started using Wire instead of another messenger. I use not only video calls but also text correspondence. In principle, all is well, but lacks a few functions:

1. Indication of the subscriber online/offline;
2. Indication when the caller dials me a message;
3. Full smiles / stickers, ability to install / create your own stickers.

If this is possible and does not conflict with the Wire security policy, please consider adding this functionality to Wire.

P.S.: If I wrote this in the wrong place, I apologize.

**Comment by Strit** [comment]
Pretty sure no. 1 got turned down multiple times for privacy reasons.
No. 2 exists on mobile, but is (according to the devs) hard to implement on desktop.
No. 3: I don't like stickers, so if those got added, I should have the option to not have them shown in my messages at all. Smileys are stretching it as is.

**Comment by bennyn** [comment]
Hi @Strit, for feature requests please refer to: https://github.com/wireapp/wire/issues

**Comment by Strit** [comment]
@bennyn Hm. But I didn't create this request. The OP did...
But oh well...
