### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Alzimzim** [wireapp/wire-desktop#1672]
Wire version: 3.2.2840
system: OS Linux
yarn 1.9.4

yarn install
./node_modules/grunt/bin/grunt --arch=x64 --target=tar.xz linux-other

```
[4/4] Building fresh packages...
success Saved lockfile.
Done in 81.22s.
+ ./node_modules/grunt/bin/grunt --arch=x64 --target=tar.xz linux-other
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
Warning: Task "linux-other" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by ffflorian** [comment]
The task is called `linux:other`.

**Comment by Alzimzim** [comment]
+ ./node_modules/grunt/bin/grunt --arch=x64 --target=tar.xz linux:other
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
Warning: Task "linux:other" not found. Use --force to continue.

**Comment by ffflorian** [comment]
Which Node.js version are you using?
