### ISSUE TITLE
Closing wire during call, does not close it

### ISSUE THREAD

**Issue by sonicou** [wireapp/wire-desktop#168]
When wire is closed during an audio conversation and then restarted again later, the call is still there, even if nobody else is available for the call.

This is kind of confusing.

When wire is closed during a call, it should also trigger the close call function. 

Experienced with the windows-desktop client

**Comment by gregor** [comment]
Currently for 1:1 calls the call state is held on the backend. If you close Wire, the browser does not receive any unbeforeunload event. We thus do not leave the call on the backend. As we are moving away from our current call implementation, this will soon no longer be an issue for 1:1 calls. We will have to revisit group calls down the road. Thereby closing this for now as we will not fix it for the current implemenation.
