### ISSUE TITLE
Wire remains in Systemmonitor after closing

### ISSUE THREAD

**Issue by glomeg132** [wireapp/wire-desktop#1682]
![bildschirmfoto vom 2018-08-20 20-35-25](https://user-images.githubusercontent.com/42551964/44359613-aab92c00-a4b8-11e8-8bc3-cc630435f5d1.png)
After closing Wire in Pop!OS it stays active inside Systemmonitor. It shows 6 processes.

Wire version: 3.2.2840
Operating system: Pop! OS 18.04 Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Open Wire
2.  Close Wire without any action

**Comment by ffflorian** [comment]
This should be fixed by now. Feel free to comment if this is still an issue and I'll reopen.
