### ISSUE TITLE
Allow local renaming of contacts and add option to add biographical remarks

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1689]
It seems that there is currently no (or at least no easy) way to rename a contact in my contact list locally. There is also no possibility to make biographical or otherwise important remarks to individual contacts in the contact list.

**Comment by ffflorian** [comment]
Closing this as duplicate of https://github.com/wireapp/wire/issues/104. As @kristin-wire said, this request has been logged on our internal database for feature requests.
