### ISSUE TITLE
Failure by Wire Desktop build on Linux

### ISSUE THREAD

**Issue by 1div0** [wireapp/wire-desktop#172]
€ grunt linux-prod --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /usr/src/wireapp/wire-desktop/node_modules/grunt-contrib-clean/package.json...OK
Parsing /usr/src/wireapp/wire-desktop/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-electron-installer" local Npm module tasks.
Reading /usr/src/wireapp/wire-desktop/node_modules/grunt-electron-installer/package.json...OK
Parsing /usr/src/wireapp/wire-desktop/node_modules/grunt-electron-installer/package.json...OK
Loading "index.js" tasks...OK
+ create-windows-installer

Registering "grunt-git" local Npm module tasks.
Reading /usr/src/wireapp/wire-desktop/node_modules/grunt-git/package.json...OK
Parsing /usr/src/wireapp/wire-desktop/node_modules/grunt-git/package.json...OK
Loading "git.js" tasks...OK
+ gitadd, gitarchive, gitcheckout, gitclean, gitclone, gitcommit, gitdiff, gitfetch, gitlog, gitmerge, gitpull, gitpush, gitrebase, gitreset, gitrevParse, gitrm, gitstash, gittag

Registering "grunt-github-changes" local Npm module tasks.
Reading /usr/src/wireapp/wire-desktop/node_modules/grunt-github-changes/package.json...OK
Parsing /usr/src/wireapp/wire-desktop/node_modules/grunt-github-changes/package.json...OK
Loading "github_changes.js" tasks...OK
+ githubChanges

Registering "grunt-shell" local Npm module tasks.
Reading /usr/src/wireapp/wire-desktop/node_modules/grunt-shell/package.json...OK
Parsing /usr/src/wireapp/wire-desktop/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell
Reading package.json...OK
Parsing package.json...OK
Reading info.json...OK
Parsing info.json...OK
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ build-inc, electron, linux, linux-prod, macos, macos-prod, productbuild, release, release-internal, release-prod, update-keys, win, win-prod

Running tasks: linux-prod

Running "linux-prod" task

Running "clean:linux" (clean) task
Verifying property clean.linux exists in config...OK
Files: [no src] -> linux
Options: force=false, no-write=false
>> 0 paths cleaned.

Running "update-keys" task
Options: config="electron/js/config.js"
Reading electron/js/config.js...OK
Writing electron/js/config.js...OK

Running "release-prod" task
Reading electron/package.json...OK
Parsing electron/package.json...OK
Writing electron/package.json...OK
Releases URL points to https://wire-app.wire.com/win/prod/ OK

Running "shell" task

Running "shell:linux64" (shell) task
Verifying property shell.linux64 exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal, execOptions={"env":null}
Command: yarn run linux64
**Error: Could not find or load main class run
Warning: Command failed: /bin/sh -c yarn run linux64
Error: Could not find or load main class run**
 Use --force to continue.

Aborted due to warnings.

€ cat /etc/fedora-release 
Fedora release 24 (Twenty Four)

Are there some additional packages necessary? Am I doing something wrong? It used to be working previously. Thanks.

**Comment by ConorIA** [comment]
Looks like you are missing yarn. Install from your distro or `npm install -g yarn`.

**Comment by lipis** [comment]
Updated instructions #173
