### ISSUE TITLE
Tiny tray icon ubuntu

### ISSUE THREAD

**Issue by brokoli-mate** [wireapp/wire-desktop#1747]
Wire version: 3.3.2872 Wire for web version: 2018.09.07.1418 Operating system: Ubuntu-MATE 18.04 

What steps will reproduce the problem?

1.  Open wire
2.  Look on the mate-panel
3.  See tiny icon (10px maybe)

What is the expected result?
Icon sized to the size of the panel, like in previous version of wire-desktop
What is the actual result?
Super tiny icon
Please provide any additional information below. Attach a screenshot if possible.
It happened after last update. Before everything was fine. This is wire from ppa repository, not snap one.
Can't upload screenshot: can't process that file

**Comment by XRevan86** [comment]
https://github.com/electron/electron/issues/12791

**Comment by ffflorian** [comment]
@brokoli-mate thanks for flagging. As @XRevan86 already mentioned, this is an Electron issue. Therefore closing this for now.
