### ISSUE TITLE
ERROR: There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by ChrisFernandez** [wireapp/wire-desktop#175]
when following github README, I clone the repo
but when I run yarn I get:
ERROR: There are no scenarios; must have at least one.
this is Ubuntu 16.10

**Comment by ConorIA** [comment]
That is odd.  Did you `cd wire-desktop`? Can you post your terminal output?

**Comment by lipis** [comment]
Also, what is your `node` and `yarn` versions?

**Comment by ChrisFernandez** [comment]
yes of course..
```
cfernandez-Oryx-Pro:~/wire-desktop$
cfernandez@cfernandez-Oryx-Pro:~/wire-desktop$ nodejs --version
v4.2.6
cfernandez@cfernandez-Oryx-Pro:~/wire-desktop$ yarn --version
0.26
cfernandez@cfernandez-Oryx-Pro:~/wire-desktop$ yarn
ERROR: There are no scenarios; must have at least one.
```

**Comment by ConorIA** [comment]
My guess is that yarn is too old. 
```
[conor@Sushi ~]$ node --version
v7.0.0
[conor@Sushi ~]$ yarn --version
0.16.1
```

Did you install yarn from apt-get or through `npm install -g yarn`?

**Comment by lipis** [comment]
@ChrisFernandez Yes it looks like your `yarn` is something totally different from what we expect :) Also please update your node to 6+

**Comment by ConorIA** [comment]
Ha! I was just going to say, you are running whatever this yarn is: http://code.liw.fi/cmdtest/yarn.1.txt

**Comment by ChrisFernandez** [comment]
ahhhh hmm crap!! I knew I should had stick with Arch :)  will uninstall at work tomorrow that package cmdtest and try again. Thanks

**Comment by ChrisFernandez** [comment]
@ConorIA and @lipis yap that did the trick now is working (yarn)  thanks! <3

**Comment by maretekent** [comment]
First install 
npm sudo apt-get install npm
then
npm install -g yarn

**Comment by sylnsr** [comment]
Also .. don't install yarn in one terminal and try to use it in another

**Comment by anisht42** [comment]
@sylnsr  The above trick was so good.

**Comment by Bhrugu14** [comment]
in my case 
`sudo npm remove --global yarn`
and installing back with same
`sudo npm remove --global yarn`
worked
