### ISSUE TITLE
Account switcher uses way too much space

### ISSUE THREAD

**Issue by fbruetting** [wireapp/wire-desktop#1767]
- Wire version: v2.15.2751
- Wire for web version: 2018.09.28.1146
- Operating system: Fedora 29 Silverblue beta
- Which antivirus software do you have installed: RLY? 🤣🤣🤣🤣

Currently, that account switcher uses relatively much space on the left side needlessly. I assume 99,9 % of users don’t have more than one account, so they never ever use that feature. This gets annoying, if you tile the application on one half of a 15" screen (I for example have both Wire and WhatsApp tiled on both halves of my screen), then the content field gets quite shrinked in width. In case of 13" laptops – which are more common nowadays – this leads to Wire needing a full screen for the content to be readable in a good manor.

I suggest placing this vertical pane as a horizontal pane above the contact list, with hiding that pane completely if only one account is used.

![bildschirmfoto von 2018-09-29 18-44-44](https://user-images.githubusercontent.com/10520767/46248438-92bebb80-c419-11e8-8a74-e8d8fb3fa8fd.png)

Also those icons on the right side of the device list disappear. OK, that’s just partly due to that issue, yet this also is an example of negative usability impact:

![bildschirmfoto von 2018-09-29 19-00-05](https://user-images.githubusercontent.com/10520767/46248511-5f306100-c41a-11e8-83ae-4b5f35429665.png)

**Comment by ffflorian** [comment]
Hi @fbruetting, thanks for your suggestions. We will forward your feedback to the design team.
