### ISSUE TITLE
Invalid generated "Version" key in Desktop Entry

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-desktop#1768]
#### What steps will reproduce the problem?

1. Unpack any of the generated `.deb` file(s) – `ar x wire_*.deb`
2. Untar `data.tar.xz` – `tar xf data.tar.xz`
3. Open up the file `wire-desktop.desktop` – and look at the `Version` key

#### What is the expected result?

To have a valid `Version` value according to the Desktop Entry [specification](https://specifications.freedesktop.org/desktop-entry-spec/1.1/).

#### What is the actual result?

Wire's version instead :wink:

#### Please provide any additional information below. Attach a screenshot if possible.

![screenshot from 2018-09-29 20-45-48](https://user-images.githubusercontent.com/34633617/46251708-b5a49c00-c428-11e8-8f6b-1037a7b103e8.png)

I see that you start with the correct version on the [Gruntfile.js](https://github.com/wireapp/wire-desktop/blob/master/Gruntfile.js), but somehow that's getting changed down the line :boom:

**Comment by ffflorian** [comment]
Hi @x80486, are you using the released wire-desktop version or are you building from this repo? Because this should have been fixed in https://github.com/wireapp/wire-desktop/commit/bd4b185d06b272e5ab81b4af5976d2a6e0161543 but it's not released yet.

**Comment by x80486** [comment]
I'm using the released version `3.3.2872` – from September 17th.

**Comment by ffflorian** [comment]
@x80486 This will be fixed in the next version.
