### ISSUE TITLE
Wire refuses to start minimized

### ISSUE THREAD

**Issue by inviktus** [wireapp/wire-desktop#1774]
Due to the lack of an option within Wire to start minimized, I've tried using windows shortcut options to have Wire run minimized yet it seems unwilling to cooperate with windows.

I have tried to run it with the argument -minimized to no effect.
Other programs will fall in line when using this windows shortcut option, so it would not seem to be a windows specific issue. Chrome is another program which refuses to take orders from windows.

**Comment by ffflorian** [comment]
This should be fixed by now. Feel free to comment if this is still an issue and I'll reopen.

**Comment by JacekLeszczynski** [comment]
the problem persists.
