### ISSUE TITLE
Installation of Wire 3.3.2862 fron .pkg fails because of untrusted certificate

### ISSUE THREAD

**Issue by sstucki** [wireapp/wire-desktop#1775]
Wire version: 3.3.2862 
Wire for web version: 2018.09.28.1146
Operating system: macOS Sierra

**What steps will reproduce the problem?**

1.  download [the installer package for release 3.3.2862](https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.3.2862)
2.  run `$ sudo installer -pkg wire-3.3.2862.pkg -target /`

**What is the expected result?**

Successful installation, i.e.
```
installer: Package name is Wire
installer: Installing at base path /
installer: The install was successful.
```

**What is the actual result?**

```
$ sudo installer -pkg wire-3.3.2862.pkg -target /
installer: Package name is Wire
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
```

**Please provide any additional information below. Attach a screenshot if possible.**

I can use `-allowUntrusted` as a workaround, but I'd rather not.

Also, this breaks the Homebrew cask for wire: https://github.com/Homebrew/homebrew-cask/issues/52675

Previously, I was able to install wire via `brew cask install wire` without any problems, now it fails with the aforementioned error. I was told that there's a risk that the Homebrew cask will be removed if this issue is not fixed (see [this comment](https://github.com/Homebrew/homebrew-cask/issues/52675#issuecomment-426106907) in the Homebrew issue tracker).

**Comment by mercieralex** [comment]
Bumping because I have the same problem. `-allowUntrusted` is a workaround but it defeat the whole purpose of having signed certificate.

Also using `brew` to install Wire!

**Comment by mythsunwind** [comment]
Unfortunately the certificate we used expired. This is not a problem when you install through the macOS appstore but becomes an issue when you use the pkg file directly. We do not recommend to install Wire on macOS through the pkg file, because the appstore has an automatic update mechanism, while with the pkg you need to check for updates manually. But we are also working on a new release that is signed with an updated certificate. Thanks for flagging the issue!

**Comment by sstucki** [comment]
@mythsunwind, thank you for the update.

> We do not recommend to install Wire on macOS through the pkg file, ...

I understand your recommendation to install Wire via the appstore rather than the pkg file, so let me clarify: I'm not primarily interested in using the pkg file directly. I'm using the [Homebrew](https://brew.sh/) package manager, which in turn relies on the pkg file to install Wire. Thanks to Homebrew, I do not need to check for updates manually -- in fact, I encountered this issue when Homebrew tried to upgrade the Wire package automatically, and failed. I suspect that installing Wire via Homebrew is a common (and IMO reasonable) use case for the pkg file.

**Comment by ffflorian** [comment]
Closing because the certificate was renewed long ago. Feel free to comment if this is still an issue for you.
