### ISSUE TITLE
Mixpanel status

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1787]
What's the definite status regarding sending data to mixpanel? Is it opt-in or opt-out for users on all platforms (wire-desktop, android, etc.) or completely removed? And in case it's still part of your development philosophy, why is this when other privacy-oriented messengers can do entirely without it? Where can an end user find the option to opt-in or opt-out of it in the actual app?

https://wire-docs.wire.com/download/Wire+Privacy+Whitepaper.pdf

Under point 6: what kind of server side logs are these?

**Comment by lucilacaranza** [comment]
Hello,

Anonymous usage data and crash logs are opt-in. If users opted in, they can always opt out in the settings of the app (see [FAQ)](https://support.wire.com/hc/en-us/articles/115000593925-How-can-I-opt-out-from-sending-anonymous-usage-statistics-and-crash-logs-).

Regarding server-side logs: those are application logs used to debug and monitor the services. For an in-depth look, take a look at https://github.com/wireapp/wire-server"

**Comment by baimafeima** [comment]
Hello, 

Could you add and specify what kind of server logs these are, why these are kept and for what period of time under point 6 in the `Privacy Whitepaper`? 

I'm also still interested why any kind of **user metadata tracking** (more nicely worded as "anonymous usage data and crash logs") is part of your development philosophy when other privacy-oriented messengers such as `Signal`, `Tox` or `Briar` can do entirely without it? Isn't there a way to rely more heavily on user feedback than on aggregated information send to a third party in the US which is known for its privacy violations?

**Comment by ffflorian** [comment]
Hi @baimafeima, we removed the usage of Mixpanel by now. Have a good day!
