### ISSUE TITLE
Desktop App Freezes when a message is received

### ISSUE THREAD

**Issue by croark** [wireapp/wire-desktop#179]
Everytime a message is received on the desktop app, the entire app will freeze. This is on a Windows 10 box. I have uninstalled and reinstalled several times with no improvement.

**Comment by herrmannplatz** [comment]
Can you provide some more information, e.g. which Windows Version.

**Comment by croark** [comment]
Wire version 2.11.2673 on Win 10 Pro 64bit.

**Comment by githtz** [comment]
I've got a similar problem under Windows 10 Pro x64 v. 1607 (Build 14393.447) with Wire v. 2.11.2673. 
Application GUI freezes and does not accept any input. When the freeze happens while on a call the call is continued but cannot be ended; incoming video is stuck, too.
Tried running Wire in compatibility mode which improved the issue but did not solve it. I'm not absolutely sure at what conditions the issue occurs. Sometimes it happens on incoming messages and calls, sometimes when pressing a certain button or marking text in the chat window.

**Comment by resoau** [comment]
Similar problem for me. Application freezes when receiving a message from a contact, won't allow any input at all and trying to quit from the system tray does not work. Need to force quit from task manager.

Windows 10 Version: 1607 (OS Build: 14393.576)
Wire App (Desktop): v 2.11.2673

I've checked the Wire folder in %appdata% for any crash logs but was unable to locate any. Let me know if I can provide more details.

**Comment by ConorIA** [comment]
I think you can start Wire from the command prompt with the `--enable-logging` flag to get better debug info.

**Comment by Sopsys** [comment]
Same problem here. Sent quite a few emails to support about this already before noticing the GitHub issue tracker here. Freezes like every ten minutes. Only remedy seems to be killing from task manager and restarting.

I can close the main windows after a freeze, but when trying to "Show Wire" from the tray, I get this:
![untitled](https://cloud.githubusercontent.com/assets/721951/21428133/cbb6f9ac-c858-11e6-9d3a-1c50319aef4d.png)

For some reason the freezing seems to be related to notifications. But it might be that just something's happening when a notification comes.

Not sure if related at all, but when ran from CMD with --enable-logging, i get multiples of these warnings/errors:
[3200:1222/150803:WARNING:webmediaplayer_impl.cc(341)] Using MultibufferDataSource
[3200:1222/150803:ERROR:ffmpeg_demuxer.cc(1510)] media::FFmpegDemuxer::OnReadFrameDone result=-541478725 IsMaxMemoryUsageReached=0

Tried to search for any log files besides thoses, but couldn't find any. Where should they be?

**Comment by Sopsys** [comment]
The freezing is definitely related to notifications. Disabled them from the settings and haven't had a single freeze after that. Seems to have fixed the issue for me, but working notifications would be nice of course.

**Comment by Sopsys** [comment]
The freezing is definitely related to notifications. Disabled them from the settings and haven't had a single freeze after that. When having the notifications enabled, the program always froze like after every second or third received notification.

So this seems to have fixed the issue for me, but working notifications would be nice of course.

OS is Windows 10 Enterprise 2016 LTSB N with Media Pack installed.
![untitled](https://cloud.githubusercontent.com/assets/721951/21430663/5ec3d46c-c864-11e6-898d-118a98e5ec81.png)

**Comment by Alexander39t51** [comment]
Thanks all for the disabling notifications fix.  Not ideal, but if it doesn't freeze, I'll call it a win for now.

**Comment by janost** [comment]
The same problem seems to be happening on one of my machines running Windows 10 enterprise x64.

**Comment by alien2003** [comment]
The same happens on my friend's Windows 10

**Comment by 0xfd000000** [comment]
Why has this been closed? The issue still remains.

Version: 3.2.2840
OS: Linux (Arch)
Window Manager: i3

uname -a:
Linux walpurga 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
Intel i915 graphics on an Intel i5-3360M, Thinkpad x230
