### ISSUE TITLE
Show preview of links 

### ISSUE THREAD

**Issue by sonicou** [wireapp/wire-desktop#180]
In many messengers posting a link to a picture or website will create a preview or the site respectively show the picture directly without the need to click on it. 
Wire currently does not show any preview but requires to open the link to see an e.g. image 

It would be nice to have a feature for pictures and maybe links in general simular to the preview of youtube videos that already exists in wire.

**Comment by Strit** [comment]
I'm for this. Also, maybe a consistant markdown support across the platforms. Right now the desktop version has better markdown support than the android version (which has almost none).

**Comment by lipis** [comment]
You can now paste an image from clipboard instead of pasting the URL to it..

**Comment by helenakos** [comment]
Nice workaround suggested by @lipis <img width="1063" alt="screen shot 2017-04-04 at 16 04 12" src="https://cloud.githubusercontent.com/assets/5180637/24660661/61f18872-1950-11e7-927e-e883a01c5c45.png">

We don't have plans to include this in the next few months so I will close the issue.
