### ISSUE TITLE
Do not show exact device name 

### ISSUE THREAD

**Issue by sonicou** [wireapp/wire-desktop#181]
When I added a buddy in wire, I could see his exact phone model in the device list.
Other apps like conversation only show the device type by default.

Using the device name as a public identificator can be considered an unwanted leak of private information and possibly provide valuable information for adversaries, especially if devicenames are changed individually.

Wire should by default use generaic device names like "Phone" or "Phone-ABCD..." where ABCD is the beginnign of the key id.

**Comment by helenakos** [comment]
@sonicou Not sure I understand your issue, we list "PHONE" or "DESKTOP" in list of devices.

**Comment by ConorIA** [comment]
In my own device list, I see "OnePlus A0001" for my phone, but in the device list of any contact, I just see "phone" and "desktop" for my contacts, as @helenakos stated.

**Comment by sonicou** [comment]
My mistake, the exact device name is only listed for my own devices.
