### ISSUE TITLE
Provide an option to toggle the developer tools 

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-desktop#1819]
It would be (extremely) nice if you can provide (or activate since that's available out of the box for Electron applications) a menu entry for the **Developer Tools** – similar to what Bitwarden provides.

I'm aware you have an `npm` task (named `start`) that have that option predefined, but what I'm referring to is to have the possibility to toggle it, regardless of how/when the application is started.

**Comment by ffflorian** [comment]
Hi @x80486, we have this option in the internal version. You can build it with `grunt linux`.

**Comment by x80486** [comment]
What I'm trying to say is that it would be great if you have that option in the application itself, regardless of the way it was built...like a normal menu option, as many other Electron-based application have.

I understand it's not useful for most of the users though.

**Comment by ffflorian** [comment]
> I understand it's not useful for most of the users though.

True :wink: 

Another idea: You could start the app with `wire-desktop --devtools`. Does that help?

**Comment by ffflorian** [comment]
Alright :slightly_smiling_face:
Feel freet to comment if you have more questions regarding this topic.
