### ISSUE TITLE
left clicking system tray icon on GNU/Linux does nothing

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-desktop#183]
To reopen Wire when it is minimized to the system tray, I have to right click on it and select "Open Wire" from the menu. Left clicking on the system tray icon does nothing. When the Wire window is not open, it does not open the Wire window. When the Wire window is open, it does not bring the window to the foreground. This is using KDE Plasma 5.27.0 on Fedora 24.

**Comment by darkbluelight** [comment]
FYI: On my Debian Stretch with 4.6.0.1-amd64 kernel and Cinnamon 3.0.7 Desktop the left click is working, i.e. it brings the app to the foreground. But if it is in foreground left clicking the tray icon again doesn't minimize it as I would expect it. I then have to close the window by clicking the "x".
BTW: The right click works as well, it shows "Open Wire" and "Quit".

**Comment by ConorIA** [comment]
@darkbluelight, this is normal. The tray icon isn't a toggle. 

@Be-ing, are you using the AppImage or did you build from source? Is it only Wire that is giving your problems? Have you used another electron-based app?

**Comment by MaCroX95** [comment]
I think this issue is not Wire-based it is rather electron-based because it accounts for Discord as well. I'm not really sure who needs to fix this issue electron devs or Plasma devs but I guess that it's Plasma devs since for some tray icons that are not electron-based left click isn't working as well and it does on GTK desktops like CInnamon.

**Comment by hlwsmith** [comment]
I have a recent (2.11.2687) build on Debian 8 (Jessie) with the Mate desktop and left clicking will open an Electron app, including Wire-desktop, if it's closed but wont close it (or do anything at all) if it is already open. It is like that with all (4 or more) electron apps I have tried. Other apps in the system tray behave as expected. I believe it is a electron issue.

**Comment by ffflorian** [comment]
@darkbluelight 
> FYI: On my Debian Stretch with 4.6.0.1-amd64 kernel and Cinnamon 3.0.7 Desktop the left click is working, i.e. it brings the app to the foreground

Same on Debian 8/9 with Gnome 3.

@Be-ing Can we close this issue since it is related to Electron and not Wire Desktop?

**Comment by Be-ing** [comment]
Yeah, go ahead and close this.
