### ISSUE TITLE
Show progress when uploading an image

### ISSUE THREAD

**Issue by MartinDelille** [wireapp/wire-desktop#1844]
When uploading an image, there is no indication that the upload is in progress. When we are in a low connection mode, it looks like the upload fails and we are tempted to upload it again.

I upload via drag and drop for your information.

**Comment by bennyn** [comment]
Thanks @MartinDelille for your suggestion. It's on our roadmap! 👍

**Comment by MartinDelille** [comment]
Ok just a workflow question: why don't you keep the issue open for tracking? or provide a link to an existing issue? It's always pleasant as a user to follow the development of a feature! 😉
