### ISSUE TITLE
wire-desktop proxies involuntarily through port 9050

### ISSUE THREAD

**Issue by libBletchley** [wireapp/wire-desktop#1846]
Wire version: Version 3.3.2872 Wire for web version:  Wire for Web Version 2018.10.23.1205 Operating system: debian stretch

What steps will reproduce the problem?

voice chat with someone

What is the expected result?

i should hear them, and they should hear me, continuously.

What is the actual result?

works for ~5-10 seconds, then 1 min of silence, off and on.

Please provide any additional information below. Attach a screenshot if possible.

I ran netstat, and could see that wire-desktop is proxying through port 9050 (that's tor).  I did not ask for that.  This is in `$HOME/.config/autostart/wire.desktop`

```
[Desktop Entry]
Name=Wire
Comment=Wire is a secure video/chat tool
Exec=/usr/bin/wire-desktop --startup
Icon=wire-desktop
StartupNotify=true
Terminal=false
Type=Application
Categories=Network;Telephony;
```
Notice that there is no proxy switch (no `--proxy-server="socks5://localhost:9050"`).  In the GUI setup, there is no field for a proxy.  So there is no reason wire-desktop should be proxying.

**Comment by ffflorian** [comment]
Hi @libBletchley,
thanks for reporting. Can you please provide the relevant `netstat` output for wire-desktop? I unfortunately can't reproduce this issue on my debian installation.

**Comment by libBletchley** [comment]
Sorry, I said `netstat` but I mean `lsof`.  This is what I executed:

```
lsof -i | sed -ne '/(LISTEN)$/d;s/(ESTABLISHED)/(ESTAB)/;s/:\([^:]*\)$/ \1/;/(/p' |
  tr -s ' ' | cut -d ' ' -f1-3,7-99  | column -t
```
The output shows wire-desktop is using the Tor port:
```
wire-desk  2470   user  0t0  TCP  localhost:55842->localhost  9050  (ESTAB)
```

**Comment by ffflorian** [comment]
@libBletchley thank you for your detailed answer. Are you running wire-desktop and `lsof` while using Tor? Because without running Tor I still can't reproduce this issue.

**Comment by libBletchley** [comment]
Yes I'm running Tor.  This is why my conversation was poor quality.  The `wire-desktop` app apparently discovers Tor running and uses it autonomously without the user asking.  In order to have a functional voice chat, I must exit `wire-desktop` and re-run it with `--proxy-server=''` to force it to not use Tor.

Also, very annoying that there is no `man` page for `wire-desktop`, which should document the `--proxy-server` option and mention any environment variables that are used (such as `HTTP_PROXY` for example).

**Comment by ffflorian** [comment]
@libBletchley 

> In order to have a functional voice chat, I must exit `wire-desktop` and re-run it with `--proxy-server=''` to force it to not use Tor.

Thanks for reporting. I will add a note for using Wire with Tor to our [Wiki Page](https://github.com/wireapp/wire-desktop/wiki). Since we don't specify any proxy settings in wire-desktop, this is more of an Electron issue. Please [open an Issue](https://github.com/electron/electron/issues/new/choose) there.
Thanks :slightly_smiling_face: 

> Also, very annoying that there is no man page for wire-desktop

Please note that Wire Desktop for Linux is still experimental (as stated on the [Download Page](https://wire.com/en/download/)) and currently we don't have the time to maintain a complete man page.

**Comment by libBletchley** [comment]
So it turns out that Electron does in fact discover Tor and use it automatically.  While it's a good thing to default in favor of security, it's a bad idea for `wire-desktop` to do this so silently with no documented or obvious indicator that it has happened.  I only knew Tor was being used because I used `lsof`.  Many users likely get poor voice quality and have no idea why.  So this is what needs to happen:
* `wire-desktop` should show an onion icon or something to make it loud and clear that Tor is being used, so when voice quality is bad the user can see why.
* `wire-desktop` needs a documented man page
* `wire-desktop` needs a config option to disable the use of Tor for voice chat.  In fact, why isn't UDP used for voice and video?  UDP naturally bypasses Tor.  The user should have a mutually exclusive radio button in the preferences giving these choices: 1) Use UDP for voice and video (thus not Tor) or 2) Use TCP for voice and video (and use Tor if available).
