### ISSUE TITLE
Just Lost All My Message History –Wire Saving Data Into Another App's Sandbox?

### ISSUE THREAD

**Issue by madranet** [wireapp/wire-desktop#1851]
Wire Version OSX Desktop 3,3x
OSX Version 10,11,16

I've just been doing a bit of spring cleaning out on my Macbook Air of various junk left over from apps I no longer use; old prefs, app support files etc.

After doing so, I opened up Wire Desktop to find that all my messages were gone and Wire was asking me to login and setup as a new device. I was pretty certain I'd not deleted anything to do with Wire, but decided to double-check.

As you don't provide any info as to where Wire stores its various files, I fired up [FSEventer](https://www.macupdate.com/app/mac/19141/fseventer) and clicked round a bit in the Wire app. This is what I saw in FSEventer. Rather than saving its support files to `~/Library/Application Support/Wire/*` the Wire desktop app is saving them to `~/Library/Containers/com.wearezeta.zclient.mac/Data/Library/Application Support/Wire/*`:

![wire](https://user-images.githubusercontent.com/669658/47853802-cd7c9080-ddd7-11e8-8c7c-b8db22fbd9f2.png)

Which can be confirmed in the Finder [There is no `Wire` directory in `~/Library/Application Support` only the one in the `wearezeta.com` Container]:

![2018-11-01_13-33-56](https://user-images.githubusercontent.com/669658/47854890-ec305680-ddda-11e8-8a61-707300005883.png)

![2018-11-01_13-31-21](https://user-images.githubusercontent.com/669658/47854830-b4c1aa00-ddda-11e8-9c86-6ac7fc0fa818.png)

Now my understanding of Containers in OSX is that they are to provide a sandbox whereby a sandboxed app can store files in an isolated environment which mirrors the Finder's layout for support files. So, in this case, Wire is saving its `~/Library/Application Support` folder inside the sandboxed container of another app belonging to [wearezeta.com](http://wearezeta.com/) which, incidentally, appears to be a Spanish site selling T-shirts:

![2018-11-01_13-16-07](https://user-images.githubusercontent.com/669658/47853964-5b587b80-ddd8-11e8-9b21-1d2fe1cf61a2.png)

Obviously, this `wearezeta.com` Container directory is one that I have removed while doing my spring cleaning as it was not related to anything I have on my laptop and I naturally assumed it was junk. So, it now looks like i've lost my entire message history in Wire as it was [for some unfathomable reason] saved into this Container belonging to a Spanish Tshirt vendor. Am I going insane here, or is Wire's OSX app? 

Why is Wire apparently saving it's `Application Support` files into the sandbox belonging to another app and how is this even possible? Isn't the whole point of Containers and sandboxed apps in OSX supposed to prevent exactly this kind of thing; ie. keep apps' data isolated from each other?

Ref: https://apple.stackexchange.com/questions/290310/whats-the-purpose-of-library-containers/290312

**Comment by madranet** [comment]
Just to confirm: I've opened a copy of Wire on Desktop on my other computer and it's also writing its support files to `~/Library/Containers/com.wearezeta.zclient.mac/Data/Library/Application Support/Wire/*` which suggests this is by design, rather than accident.

So, the question remains; why is Wire using an OSX Container seemingly belonging to a completely unrelated 3rd party domain to save its support files. Surely this is not the thing you Earthlings call "Security Through Obscurity"?

**Comment by ffflorian** [comment]
@madranet this is indeed "by design", but not security through obscurity. We are using `com.wearezeta` for historical reasons (the app bundle ID can't be changed afterwards). Note that an app bundle ID **should** match the publisher's domain name, but doesn't **need** to.

See https://help.apple.com/xcode/mac/current/#/dev91fe7130a.

**Comment by madranet** [comment]
Wow! –that's pretty amazing [and I don't mean in a good way].  

I don't know what's more surprising; the fact that Apple has designed a system which supposedly increases app security and integrity but which actually can actually result in applications saving their data in secure containers which belong to domains they no longer control... or the fact that the people behind Wire don't think it worth mentioning somewhere in your support documentation that our entire message history is being saved [whether for historical reasons or not] inside a directory structure ostensibly belonging to a Spanish T-shirt vendor.  

Did it really never occur to anyone at Wire that this situation was just asking for accidental data loss?  I've also got no way of even part-restoring from my monthly backups as [for the same obvious reasons] that particular OSX Container wasn't included in my backups.

So, forehead slapping aside: is there no way at all now I can retrieve my message history  cross-platform? I have all my message history intact on my Android tablet and my Android phone.  It seems crazy that all the info is there but I can't somehow migrate and restore it onto my desktop machine, especially now that a Backup/Restore function has been added. Again, is this by accident or design –ie. the fact that a backup can only be used to restore onto a device of the same type?

**Comment by bennyn** [comment]
@madranet Message backup across platforms is on our roadmap but won't be there anytime soon because it's not trivial to sync databases of different platforms.

You can do a backup on desktop at any time:
https://support.wire.com/hc/en-us/articles/360000824805-How-can-I-backup-my-conversation-history-

We advise you to make periodically backups of your Wire conversations. You can also create a conversation with yourself and share the backup as a file, so that you have a safe place to store your backup.

**Comment by ArchiveBase** [comment]
@madranet I see wearezeta.com no longer sell T-shirts :/
