### ISSUE TITLE
color setting syncing broken

### ISSUE THREAD

**Issue by zeebok** [wireapp/wire-desktop#186]
I am not sure which recent update it started with, a fairly recent one though, where now the color selection doesn't match between devices. More specifically between desktop of any platform and Android, so perhaps it's a bug within the android version, but I am not entirely sure. The issue is when I set my color setting on the desktop app, my android device syncs itself to the next color on the list.

An example is I pick the default blue on desktop, and android syncs but is set to green. Or if I pick purple on desktop, android changes to blue. If I change the setting on android, it still syncs in the same manner.

**Comment by gregor** [comment]
@zeebok Thanks for letting us know. This is a known issue with the current Android build that occured after we removed the yellow accent color due to readability issues on the white theme. The Android team is awre of the issue.
