### ISSUE TITLE
Provide IP , Port Manual configurations

### ISSUE THREAD

**Issue by TNTBOMBOM** [wireapp/wire-desktop#1860]
- Wire version?

 Version 3.3.2872

- Operating system?

Debian stretch 9 

- Which antivirus software do you have installed?

GNU/Linux users dont need it. 

- What steps will reproduce the problem?

Invalid

- What is the expected result?

to route Wire connection to specific IP/Port

- What is the actual result?

Wire doesnt seem to have this feature

**Comment by ffflorian** [comment]
Hi @TNTBOMBOM, you can use the `--proxy-server` flag. See https://support.wire.com/hc/en-us/articles/115005697189-How-I-can-connect-through-a-proxy-server-on-desktop-.

**Comment by TNTBOMBOM** [comment]
@ffflorian not really a secure/good method comparing if i force by default the Wire app to run through the specified IP/Port within the app itself. 

i dont see any graphical implementation in the app itself. 

which is very great to have it.

**Comment by ffflorian** [comment]
Thanks for the suggestion, we'll note it down. Feel free to comment if you have further questions.
