### ISSUE TITLE
No Audio Alerts

### ISSUE THREAD

**Issue by johnstonesnow** [wireapp/wire-desktop#1861]
Wire V3.3.2862 - When incoming messages received when window not in focus (or when it is too for that matter) there are no audio alerts. I checked settings and it's set to alert for all events. I cranked volume up full (on both Windows 7 machine and iMac running OSX Sierra) and I heard a barely audible 'tink' sound. This is unusable, any chance of providing decent alerts similar to Skype and all other messaging apps?
Thanks

**Comment by ffflorian** [comment]
@johnstonesnow Hi, for now we don't have any plans for changing the notification sound. But I'll forward your request to the design team.

**Comment by johnstonesnow** [comment]
I understand, but am frankly bewildered by this. It prevents the software being usable! You have said many other people have asked, is the software dying a slow death? That’s the only reason I can think of why such a badly needed (and easy) fix wouldn’t be a priority. Or maybe you’re selling and it’s not needed to secure the sale. Who knows, but what a shame, it’s a great piece of software made totally unusable by a lack of a PING?!

**Comment by bennyn** [comment]
@johnstonesnow I don't think that our app is totally unusable because it lacks a ping sound. Software is also not a living being, so it cannot die a slow death.

Can you please elaborate what you mean with _decent alerts_? In the issue title you write about "no audio alerts" but then you write that there is a barely audible tink. So do you hear a ping sound or do you hear no sound at all? Should we just make it a little louder or do you want to hear a completely different sound?

**Comment by johnstonesnow** [comment]
Danke sehr. However I don't need an education in my own language. Perhaps not being a native English speaker, you have never heard the phrase "I was driving along when my engine suddenly died", or "my computer got the blue screen of.... DEATH". It's called a metaphor, in case you didn't know, which I have a feeling you did as I am sure you speak excellent English like most Germans I know.

"I don't think that our app is totally unusable because it lacks a ping sound." - I didn't post because of what you think, I posted because of what I think, odd as that may sound. I might add that all of the people I know who use desktop messaging software agree that without an audible alert (i.e. something the ear can hear), it is unusable. That doesn't mean someone else couldn't use it, and you're right, it doesn't render it "totally unusable". It 'could' be used. But in my opinion (and I believe in most people's opinion), it makes it unusable WHEN there are other programs out there which do let you know of an incoming message without the need to stare at the message board constantly for a visual indication. Most people install more than just one program on a computer, some even use several at the same time ;-). Literally speaking you are correct though. Just as it would be correct to say a phone which doesn't make a noise when someone calls, is not "totally unusable". You probably wouldn't 'want' to use one though. :)

Yes you are correct. The title I chose was technically incorrect where it says "NO" audio alerts, as I think there IS something you could describe as an audio alert. (We could debate that if it's virtually impossible to hear, is it still an alert?!) The problem is the only way I can hear it is (and I am being honest here) is if I turn off the fan on my desk, pause any music playing, tell the kids and dog to stand totally still, turn my system volume to full blast, and move my ear to within 6 inches of my computer. THEN I can hear a very VERY feint "tink" sound. That's the truth. I am on an iMac, but friends who I was testing it with (before they uninstalled after your support said there were no intentions to address this issue) have tried it on various Windows installations and all have the same issue, inaudible alerts for incoming messages. It's therefore 'unfit for purpose' (a phrase more to your liking?) for our needs, and indeed for anyone who wants an audible notification of a message being received. It's such a shame because everyone loved it, and we have tried LOADS of other programs which have other issues too, leading us to try out Wire. The GUI is lovely, the functionality is perfect for our needs, but if we don't know when we have a message coming in, it just can't be used. 

"Should we just make it a little louder or do you want to hear a completely different sound?" - I am not sure if this is a rhetorical question or not. I was told by someone at Wire that you have no intentions to fix this issue, AND I was told that you have had the same request from plenty of other people before me. But I am going to be positive and assume you are not being facetious....

A little louder or a different sound? Neither. A LOT louder would suffice. We don't care what the sound is particularly, a choice might be nice for some people but all we want is A notification which we can hear. So a volume boost is all that's needed for us to start using it and spreading it to other group members and beyond. Going by the fact that plenty of other users have complained about this before, I don't think this would be a wasted fix, it would (I believe) bring LOTS of people over to Wire from Skype and other horrible but fully usable programs. I will leave that decision to your good self though, and just hope that someone at Wire does see the merit in making alerts properly audible in average conditions.

**Comment by bennyn** [comment]
> The GUI is lovely, the functionality is perfect for our needs, but if we don't know when we have a message coming in, it just can't be used.

Let's take it from here: We both like the functionality of Wire and strive to make it even better. Sounds that are hard to hear are an obstacle in this case and I am with you when it comes to making them noticeable. 

To work on it we need to know exactly which sounds are hard to hear. All our sounds are available here:
- https://github.com/wireapp/wire-audio-files/tree/v1.1.1/webapp

I did an analysis with [MP3Gain](http://mp3gain.sourceforge.net/) and got the following result:

![image](https://user-images.githubusercontent.com/469989/48409137-5c27d080-e73b-11e8-98fc-b325cdd9d5b8.png)

Based on the analysis, these 6 sounds are quieter than others:
1. `new_message.mp3`
1. `first_message.mp3`
1. `ringing_from_me.mp3`
1. `nw_interruption.mp3`
1. `camera.mp3`
1. `alert.mp3`

Does this analysis also match your impression?

**Comment by johnstonesnow** [comment]
I haven't tested many of them, once the incoming/first text message issue arose, it became unusable for us at that point so most uninstalled it. I still have it, will ask a friend to install it again and can do some testing of all sounds. The only way I can describe it right now is that the volume LEVEL is incredibly low. So for example, if i turn my machine volume up as loud as possible, if a skype message comes in, an email, a whats app message, a poker hand action alert  (:-D), a calendar alert, or ANY other alert, it's loud enough to hurt my ears! But at the same time if a Wire message comes in, I MIGHT notice the feintest sound, like a penny dropping on the floor 20 yards away. I can test and update you if required, but not sure if it is. please let me know
