### ISSUE TITLE
It needs scale and resize better

### ISSUE THREAD

**Issue by survivor303** [wireapp/wire-desktop#1878]
Problem is that when user trying to resize the whole application window, it has limits that how small resize can happen. And even with the limits, it can be resize smaller than the internal UI can scale, like ping button disappears...

On current versions of the electron app, users cannot move or change the contacts/conversation area sizes which is the problem. If we can adjust that size, we dosnt have this problem.

This scalling is problem especially for users who use vertical monitors, the scaling limits are larger than the resolution and current electron settings not maximize the app correctly to those screens because it cannot scale the content.

**Comment by bennyn** [comment]
@survivor303, thank you for taking the time to explain the issue. 

The approach that we use to handle resizes of our app is a compromise of many different variants that we looked at in the past. We are not super happy with it either and are looking at a way to have a unified design language for mobile and desktop but it is extremely _expensive_ both in terms of design and development. 

All the concerns regarding window size and content visibility that you have brought up in this issue will be taken into account but we don't have the resources to fix them anytime soon.

If you're a programmer yourself, you're welcome to open a pull request and we can take it from there.
