### ISSUE TITLE
Window out of screen, when second monitor is disconnected

### ISSUE THREAD

**Issue by jaypikay** [wireapp/wire-desktop#189]
When the program is closed and the extended desktop is disabled, the next time the wire window is opened it will shown off screen and unreachable to move via mouse drag'n'drop.

Workaround: activate window in task bar, press ALT + SPACE, press M, press ARROW-Keys until window becomes visible, or move mouse. The window will stick to the mouse cursor after first ARROW-Key press.

**Comment by gregor** [comment]
@jaypikay Thanks you very much for the report. This is indeed very annoying and has bothered me personally. I hope we can fix it soon. Not that many of our users are on dual monitor setups though.

**Comment by gregor** [comment]
This was fixed back in December by PR #253. Unfortunately we have not had a public release yet but it will be in the next one. Please reopen if you run into the issue again after that.
