### ISSUE TITLE
(Design / UX) Make avatar & background separately

### ISSUE THREAD

**Issue by TheAresjej** [wireapp/wire-desktop#19]
Make avatar & background separately - THX :D

**Comment by bennyn** [comment]
@TheAresjej Can you please be more explicit on this one?

**Comment by ConorIA** [comment]
Not OP, but I imagine they are asking for options for background image and display picture. As it is now, my display picture is also the chat window background. Makes me feel like a narcissist.  😂

**Comment by helenakos** [comment]
Hey @TheAresjej and @ConorIA. We've had a few folks asking for this so we will take it into consideration in the upcoming planning. Thanks!

**Comment by pprucia** [comment]
What is the current status of this feature request? Do you have any time frame for that? It's weird looking at myself while talking with someone else.

**Comment by helenakos** [comment]
@pprucia We don't have a committed date right now.
