### ISSUE TITLE
Random crashes related to tray badge

### ISSUE THREAD

**Issue by eNNercY1337** [wireapp/wire-desktop#192]
since the past days i experience strange errors thrown my the windows wire client and they appear mostly when i want to scroll through the chat or simply recieve/sending a message.

basically looks like this then and only gets resolved with closing wire and restarting it.

![vzij](https://cloud.githubusercontent.com/assets/7194960/20403038/807482bc-acff-11e6-978b-bded4707b1fb.png)

![zoe9](https://cloud.githubusercontent.com/assets/7194960/20403107/c295ca2a-acff-11e6-8076-603724d63489.png)

![j15a](https://cloud.githubusercontent.com/assets/7194960/20403108/c4398f6a-acff-11e6-97bd-8432a6bfc3d3.png)

**Comment by aquatooth** [comment]
Ubuntu 64bit errors in a very similar way.
Wire is running minimised, the notification 'W icon' is showing
On Taskbar [left side] upon left click, it seems Wire attempts to start again, the icon flashing, then the following error and information;

![javascript-error](https://cloud.githubusercontent.com/assets/26221740/23610076/2522b91c-02ac-11e7-973a-11f050c2f7ca.png)
![ubuntu-version](https://cloud.githubusercontent.com/assets/26221740/23610089/2daba8e6-02ac-11e7-8f2c-804693f68d91.png)
![wire-version](https://cloud.githubusercontent.com/assets/26221740/23610096/337e674a-02ac-11e7-867a-42159dda77f8.png)


In my case, Wire does still run only generating the error and can still be accessed from the notification area.

I do hope this can be worked on to resolve.

**Comment by lipis** [comment]
Can you try with [`2.12.2729`](https://wire.com/en/download/)?

**Comment by aquatooth** [comment]
will do so and report back here. thank you for your response and keep up your good work.

**Comment by aquatooth** [comment]
nice, it seems to be rectified. I will update all the installations and report back if the issue occurs again

**Comment by lipis** [comment]
I'll close it for now then.. thank you
