### ISSUE TITLE
tray icon not responsive after last wire-desktop update

### ISSUE THREAD

**Issue by talbym** [wireapp/wire-desktop#1931]
The tray icon in KDE PLASMA is nor more responsive after the last update of wire-desktop.
Before it showed a menu after a right mouse click, which then offered options like "open" and "quit". Now the tray icon simply does not react anymore to any mouse activity.
I know that the lost mouse action response is unlikely to be related to the design of the icon image, but in order to be complete, please let me mention that the icon since this last update also looks deformed, no more circular round, but looking elliptic like if it would be compressed from the left and right. I checked if the sensitive area to which I might have to click into the icon could be limited now to a certain area of the icon only, but I found that nowhere in the icon a click shows a response.

My last update was: wire-desktop:amd64 (3.3.2872-2872, 3.4.2879-2879)
Wire-Desktop is now version "3.4.2879 /  2018.11.15.1314"
installed (updated) from your repository:
http://wire-app.wire.com/linux/debian stable/main amd64 Packages

My software versions in use:
Linux, DEBIAN 9 (stable, "stretch", 64 bit)
all updates are installed as availabel for the "stable" Debian
KDE PLASMA: 5.8.6
KDE Framework: 5.28.0
QT Version: 5.7.1
Kernel Version: 4.12.0-14-1-liquorix-amd64

There was no problem like this with the former wire-desktop version.

**Comment by ffflorian** [comment]
Hi @talbym, thanks for the report. Unfortunately it is hard to maintain a normal icon behavior throughout all desktop managers. Could you please provide a screenshot of the icon in a normal state and in an unread state? Thanks!

**Comment by talbym** [comment]
![screenshot_20181128_201701](https://user-images.githubusercontent.com/10980062/49177084-9ce33480-f34c-11e8-83e5-33adb14174c3.png)
![screenshot_20181128_202806](https://user-images.githubusercontent.com/10980062/49177088-9d7bcb00-f34c-11e8-8f40-4524a4194607.png)

**Comment by ffflorian** [comment]
@talbym Thanks, we will fix the icon in the next release.

**Comment by ffflorian** [comment]
Hi @talbym,
we just released version [3.5.2881](https://github.com/wireapp/wire-desktop/releases/tag/linux%2F3.5.2881) for Linux. The icon should be fixed and it should be responsive again :wink:

**Comment by talbym** [comment]
Hello Florian,
the icon design is corrected, yes. But it is not interactive again, at least not on my Debian 9 with KDE Plasma 5.8.6, KDE Famework 5.28.0 and Qt Version 5.7.1 . I by now did not find out if this is a problem due to Debian 9 (stable) not having the newest KDE software versions, or if it is the icon which does not work. At leaste before, the cion worked.
Best greetings from Spain, Marco.

On 08.03.19 13:16, Florian Keller wrote:

Closed #1931<https://github.com/wireapp/wire-desktop/issues/1931>.
