### ISSUE TITLE
Announced 3.4 releases are missing on Github

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-desktop#1932]
There are announcements on Medium about new releases [Windows 3.4.2885](https://medium.com/wire-news/windows-3-4-2885-90ca69a53416) and [Linux 3.4.2879](https://medium.com/wire-news/linux-3-4-2879-d10b4304b550), but there are no such releases/tags on Github.

Initially reported by someone on AUR 🙂

**Comment by ffflorian** [comment]
It's live now: https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.4.2879
Sorry for the delay.
