### ISSUE TITLE
Strange rendering in Windows 7

### ISSUE THREAD

**Issue by w7zz** [wireapp/wire-desktop#1937]
Wire version: 3.4.2885 - 2018.11.15.1314 
Operating system: Win 7 Ultimate SP1
 Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Open Wire
2.  That's it, the issue persists even when starting over with a fresh download/clearing appdata/clearing everything

What is the expected result?
Non-blurry screen

What is the actual result?
Very blurry screen. It affects the entire inside of the window as well as the system tray icon
![wire](https://user-images.githubusercontent.com/45375150/49049900-1982ef80-f235-11e8-95e2-a5256ce2f7c3.png)

**Comment by w7zz** [comment]
1600*1200

**Comment by w7zz** [comment]
Monitor is a CRT with a maximum resolution of 2048 x 1536
Have been using wire-desktop for about 5 or 6 months now, and this issue has only appeared since the last update

**Comment by ffflorian** [comment]
> Monitor is a CRT with a maximum resolution of 2048 x 1536

Try disabling automatic scaling for apps in the Nvidia and disable FXAA for wire-desktop.

Do you use an external monitor?

**Comment by lipis** [comment]
> Do you use an external monitor?

[Yes!](https://www.google.com/search?q=crt+monitor&hl=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjt9I2PmvfeAhUIy4UKHfcCDvYQ_AUIDigB&biw=1366&bih=767)

**Comment by w7zz** [comment]
> Try disabling automatic scaling for apps in the Nvidia and disable FXAA for wire-desktop.

Adding wire-desktop to the list of programs and disabling FXAA was indeed the solution

Thank you
