### ISSUE TITLE
RTL is not supported

### ISSUE THREAD

**Issue by mohammadrafigh** [wireapp/wire-desktop#194]
it's really good to see wire is supporting RTL messages in all platforms... currently on desktop (Linux) RTL is not supported and I think it wouldn't take too much time to implement it. I cannot promise but if I have a free time I can do that. although hope to see this feature soon.

**Comment by mohammadrafigh** [comment]
@lipis sent a pull request in the wire-webapp repo for this.

**Comment by lipis** [comment]
Closing in favor of https://github.com/wireapp/wire-webapp/issues/475
