### ISSUE TITLE
Provide PGP signature for sources tarball as part of a release

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-desktop#1944]
I've learned a lot about how package managers work on Linux and what are the usual ways of verifying authenticity of downloaded source code when compiling a package. I'd like to share what I know and ask for your help on improving the distribution, consider this a follow-up to #542. cc @raphaelrobert 

1. Please upload [your PGP key](https://wire-app.wire.com/linux/releases.key) to a key server such as http://keys.gnupg.net/.

    Package managers like `pacman` are integrated with `gpg`, which in turn knows how to automatically fetch keys from a key server. Package maintainers will only have to specify your PGP key ID, and package manager will do the rest: fetch your key from a key server and use it to validate the downloaded sources.

    There are many keyservers, but you only have to upload your key to one of them, they are periodically synchronizing between themselves.

1. Please provide a `.sig` file for the sources tarball as part of a release.

    When you create a release, Github automatically attaches a source tarball `3.4.2879.tar.gz`:

    ![image](https://user-images.githubusercontent.com/1177900/49120574-7ae6a500-f2ad-11e8-9064-b8c9b5a8c76f.png)

    This is the sources archive that package maintainers will use. When a `.sig` file is present (`3.4.2879.tar.gz.sig` in this example), package managers like `pacman` that are integrated with `gpg` will automatically use it to verify the signature of the downloaded sources. It's pretty neat as allows to avoid having to trust package maintainer that they used valid sources when packaging the app.

    Here's how you would create a signature:

    ```
    # First generate the tarball that Github will generate when creating the release
    # This is guaranteed to generate bit-by-bit identical archive
    git archive -o 3.4.2879.tar.gz --format tar.gz --prefix=wire-desktop-release-3.4.2879/ release/3.4.2879

    # Now generate a PGP signature for this file, this creates `3.4.2879.tar.gz.sig` that you need to upload as part of a release
    gpg --detach-sign --yes --local-user D599C1AA126762B1 3.4.2879.tar.gz

    # Finally remove the tarball
    rm 3.4.2879.tar.gz
    ```

------

cc @ConorIA, after this is implemented we could apply the patch below and pacman will do the rest for us.

```patch
--- PKGBUILD    2018-11-28 01:35:16.940349157 +0100
+++ PKGBUILD-new        2018-11-28 01:36:36.186535102 +0100
@@ -16,9 +16,12 @@
             'ttf-emojione: for colorful emoji made by EmojiOne')
 provides=('wire-desktop')
 source=("${pkgver}.tar.gz::https://github.com/wireapp/wire-desktop/archive/release/"$pkgver".tar.gz"
+        "${pkgver}.tar.gz.sig::https://github.com/wireapp/wire-desktop/archive/release/"$pkgver".tar.gz.sig"
         "${pkgname}.desktop")
-sha256sums=('7f66588be58b3854609729e9531ba5693e13e090d8ec037bca73f013ea7dd4e9'
+sha256sums=('SKIP'
+            'SKIP'
             'cc9056cecff2aa49a9ce9c8376d57ec8c7c2cb8174f7966b5cdccbeb2e3751ea')
+validpgpkeys=('ABBA007D6E14E2DB5B283C45D599C1AA126762B1')
 
 build() {
   cd "${srcdir}/${pkgname}-release-${pkgver}"
```

----

#road-to-official-repos

**Comment by ConorIA** [comment]
Hi @maximbaz, great idea. I feel like the idea of signed releases has been floated before. But I might be mis-remembering. It is definitely a good step to make downloads more secure and should be trivial to implement for both upstream and downstream.

**Comment by ffflorian** [comment]
//cc @mythsunwind

**Comment by ffflorian** [comment]
@maximbaz
Thank you for the detailed explanation and the code examples :slightly_smiling_face: 

I also think this is a good idea - I uploaded the PGP public key to GnuPG's key server and will create a PR for uploading the signature file.

**Comment by ffflorian** [comment]
> Hope to see a new release soon so we can test this :stuck_out_tongue: 

Me too :wink:

**Comment by ConorIA** [comment]
Hi all, 

I see that there is a .sig file for the latest Linux release. However, I am getting a signature verification failure. Am I correct in my thinking that the latest source tarball is just the GitHub generated one with no signature?

**Comment by maximbaz** [comment]
I confirm, @ffflorian it seems you missed the `--detach-sign` flag in your command, could you please have a look?

**Comment by ConorIA** [comment]
Am I doing something wrong here?

```
>>> gpg --verify 3.6.2885.tar.gz.sig 3.6.2885.tar.gz                                                                                                     
gpg: Signature made Thu 14 Feb 2019 10:16:40 AM EST
gpg:                using RSA key ABBA007D6E14E2DB5B283C45D599C1AA126762B1
gpg: BAD signature from "Wire Releases Signing Key <releases@wire.com>" [unknown]
```

**Comment by maximbaz** [comment]
We've chatted with Florian, the command that generates archive to sign needs to be updated, he promised to reupload a new signature tomorrow 😉

**Comment by ConorIA** [comment]
`pkgrel=3` tomorrow, then!
