### ISSUE TITLE
Window out of screen on small Devices

### ISSUE THREAD

**Issue by WDGroll** [wireapp/wire-desktop#196]
On my Netbook (Xubuntu 14.04 LTS with a 1024x600 screen resolution) it's (almost) impossible to reach the input line as it is below the lower screen border. 
Resizing does not work. It's only possible to alter the width, but not the height. Even in fullscreen-mode the input line is below th screens lower border.

There is however a trick to obtain a window fitting to this tiny screen: Closing the Wire-window with the 'X'-button in the title bar. The Wire-icon in the task-bar persists. Clicking it will open a Wire-window fitting into the screen, exposing the sadly missed input line. 
But caution: Maximizing or minimizing will mess up this window again, pushing the input line down and out of reach again.
Seems to me as the Wire window has a programmed minimal height which is larger than my netbooks vertical screen resolution.

**Comment by ConorIA** [comment]
Are you using the latest version? The devs reduced the minimum height in commit 65d846e727592b992d111814047cefb34a0095ff. But it might need to get bumped down again. It is currently set to 576. What is your screen resolution?

**Comment by WDGroll** [comment]
I'm using the latest .deb package from wire.com, which is 2.11.2670, somewhat older than the latest git-release.
The netbook's (Acer One) screen resolution is only 1024*600.

**Comment by ConorIA** [comment]
In that case, the issue is fixed, but you haven't received the update yet! Pinging @lipis, maybe time for an updated .deb?

**Comment by ConorIA** [comment]
In the meantime, feel free to test these. Fresh builds form the latest source. [x64](https://cloud.conr.ca/s/qUHw0USCGB1igno/download) and [ia32](https://cloud.conr.ca/s/yJv1GKWP9I1DfJo/download).

**Comment by DragonzMaster** [comment]
Is there a link to fresh builds from latest source for windows too ?? @ConorIA

**Comment by ConorIA** [comment]
@DragonsMaster, not from me! Sorry.

**Comment by WDGroll** [comment]
Thank you, I've tried out the new release (2.11.2675) from your link. 
Fullscreen is ok now, the desktop app can be used normally:
![fullscreen](https://cloud.githubusercontent.com/assets/23437854/20464889/85ea7ff4-af51-11e6-801e-4e16c8daac5a.png)
But in windowed mode, still a few lines get lost beyond the bottom of the screen.
Maximized window:
![maximized](https://cloud.githubusercontent.com/assets/23437854/20464890/85ef9a20-af51-11e6-9b84-f2bc24bdd33b.png)
Normal window:
![windowed](https://cloud.githubusercontent.com/assets/23437854/20464891/85f58412-af51-11e6-9526-ac8fea18bad5.png)

**Comment by lipis** [comment]
Interesting.. we'll see what we can do :)

**Comment by lipis** [comment]
Will be coming soon once we'll release a new webapp as well.
