### ISSUE TITLE
Wire cannot launch

### ISSUE THREAD

**Issue by xtotdam** [wireapp/wire-desktop#1961]
Wire version: 3.4.2885 2018.11.30.1103 
Operating system: Win7 SP 1
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1. Wire crashes several times
2. Reboot
3. Still crashes
4. Make a backup 
4. Remove Wire to install it anew 
5. Delete all these folders Wire creates in `%appdata%\roaming`
6. Reboot
7. Install Wire from new exe, downloaded from https://wire.com/en/download/

What is the expected result?

Wire works

What is the actual result?

It doesn't work. All I get is
![2018-11-30 22 49 29](https://user-images.githubusercontent.com/5108025/49311466-4b74aa00-f4f2-11e8-80dc-d5971867afc7.png)
Interesting thing is that menu on top of the window (Wire, Conversation etc) works. I can see Wire version, can quit and so on.

Please provide any additional information below. Attach a screenshot if possible.

An important information may be the fact that I am located in Russia and our government is a bit *ahem* overprotective (see https://usher2.club/en/).
Wire is a bit too slow on my PC (no VPN) and OK on my phone (VPN installed)

**Comment by xtotdam** [comment]
Update: I have installed system-wide VPN (NordVPN), nothing seems to change.

**Comment by xtotdam** [comment]
One kind sir has contacted me with a solution:

> I arrived at the logical hypothesis that some code was added to the Windows app later in the releases that kinda broke it! so I tried a couple of versions back and found that the one that worked best and consistently was the version **3.2.2860** since **3.3.2860** just kept requiring me to login after every single time I started the app!
> So my solution is as follows:
> 1. Uninstall Wire from (Control Panel\Programs\Programs and Features)
> 2. Make sure to delete its leftovers found in two locations:
>   * `C:\Users\*User*\AppData\Local`
>   * `C:\Users\*User*\AppData\Roaming`
> 3. Install the old file found on the github 
> https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.2.2860
>
> and voila! its working again!
> please feel free to post this on the github issue you were already kind enough to post in the hope that the Wire team will find out exactly what is causing this issue so we don't endanger ourselves by using outdated versions!

**Comment by xtotdam** [comment]
Maybe this helps?
[CrashDumps.zip](https://github.com/wireapp/wire-desktop/files/2650737/CrashDumps.zip)

**Comment by ffrt32** [comment]
I can confirm this issue with Wire 3.4.2885 on Windows 7 SP1

This also has no relation to russian censorship as it is the same issue in Germany

**Comment by xtotdam** [comment]
The new beta https://github.com/wireapp/wire-desktop/tree/release/3.4.2890 seems to fix my problem

**Comment by Aranad** [comment]
Dammit, I tried copying my Wire config dir over to my wife's conputer which worked, but then I tried to create a new account for her and now both computers are in the same state! Now I can't use wire any more :-(

**Comment by ffflorian** [comment]
Hi @xtotdam, can you please update to version 3.5 and see if the app starts again?

**Comment by Aranad** [comment]
Note that I was able to resolve this by:
- copying across a working config dir from another computer
- starting the program (gets same result but has a sidebar with user avatar)
- delete user account from sidebar avatar
- click + in sidebar for new account
- sign in works
For some reason the new account shows as a new device ID

**Comment by xtotdam** [comment]
Hi @ffflorian 
Version 3.5.2899 seems to works fine

**Comment by ffflorian** [comment]
@xtotdam
Great! Closing this then.
