### ISSUE TITLE
"Unexpected error" when trying to log in with macOS client

### ISSUE THREAD

**Issue by teller** [wireapp/wire-desktop#1963]
**Wire version:** 3.4.2883 
**Wire for web version:** 2018.11.30.1103 
**Operating system:** macOS 10.13.6 (17G3025)
**Which antivirus software do you have installed:** None

**What steps will reproduce the problem?**

1.  Launch Wire
2.  Enter username or email associated with the account
3.  Enter password
4. Click "Log in"

**What is the expected result?**

Wire logs in, displays conversation list, syncs chats.

**What is the actual result?**

Wire displays "unexpected error" error message.

Same result when trying to log in with username or email address. Password is correct and account is active as I can log in with the same via Chrome at app.wire.com and with iOS client.
![screen shot 2018-11-30 at 22 38 58](https://user-images.githubusercontent.com/411583/49316334-e53b5780-f4f0-11e8-990c-7f013448de41.png)

**Comment by ffflorian** [comment]
This should be fixed by now. Feel free to comment if this is still an issue and I'll reopen.

**Comment by AfricaSaga** [comment]
Same here, installed using flatpak on centos
I get an "unexpected error" 9 times out of ten, and sometimes it just works...
