### ISSUE TITLE
Unable to log in with phone number on macOS client

### ISSUE THREAD

**Issue by teller** [wireapp/wire-desktop#1964]
**Wire version:** 3.4.2883
**Wire for web version:** 2018.11.30.1103
**Operating system:** macOS 10.13.6 (17G3025)
**Which antivirus software do you have installed:** None

What steps will reproduce the problem?

1. Open Wire app
2. Click "Log in with phone number"
3. Enter phone number
4. Enter password
5. Click "Log in"

**What is the expected result?**

Wire logs me in, displays conversation list, syncs chats.

**What is the actual result?**

After clicking "Log in" the button turns grey and "nothing else happens", the app is stuck on the screen (screenshot added).

I have verified that I'm trying to log in with the correct number, that the number is associated with my Wire account and that the password is correct (I can log in with it via Chrome at app.wire.com).

Same account as reported at https://github.com/wireapp/wire-desktop/issues/1963

![screen shot 2018-11-30 at 22 43 25](https://user-images.githubusercontent.com/411583/49316641-d7d29d00-f4f1-11e8-8fe3-0c5a01525d5d.png)

**Comment by teller** [comment]
I've moved to a new computer since and logging in with the same account works fine now. So issue possibly tied to a specific device.

**Comment by nynhex** [comment]
i had this same issue, i uninstalled the package and cleaned out artifacts + reinstalled problem solved.

**Comment by ffflorian** [comment]
This should be fixed by now. Feel free to comment if this is still an issue and I'll reopen.
