### ISSUE TITLE
Flag comments as "(edited)" when they get edited.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#1974]
Sample (from Slack)
![image](https://user-images.githubusercontent.com/388716/49504986-c9191c80-f848-11e8-9537-169901882127.png)

**Comment by ffflorian** [comment]
Edited messages have a small pen icon next to the username of the user who sent it.

![screenshot from 2018-12-05 12-15-59](https://user-images.githubusercontent.com/5497598/49510111-8fb3d180-f887-11e8-9d85-e6dc7eb3d4ab.png)
