### ISSUE TITLE
Better usability of Emoji and "Add file" icons

### ISSUE THREAD

**Issue by shful** [wireapp/wire-desktop#198]
.. in the Mac Desktop Client 2.10.2652.

Beside the "TYPE A MESSAGE" field there are four icons, e.g. to add files. Whats the problem ?

1. There is no "add Emoji" icon. We use Emojis in most messages, but Emojis take a long and un-intuitive way over the menu.
2. The other four Icons disappear when typing.

Trying to switch from Skype to Wire, this usability seems a real issue to me. Eventually, the GUI is too radically clean.

**Comment by DragonzMaster** [comment]
For emoji, You can vote at this issue #161 by adding thumb-up reaction.

**Comment by gregor** [comment]
Thank you for your report. This feedback had been forwarded and taken into consideration internally. Currently we have no immediate plans to change the current implementation regarding the visibility of the conversation action icons.
