### ISSUE TITLE
Notifications not showing if Wire is minimised.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#20]
Our client's that try to use Wire keep missing messages and getting REALLY annoyed.

I think it should always show a notification, else you cannot rely on it.

All of them use the latest version of Wire and Windows 7/10.

**Comment by tmikaeld** [comment]
And if you minimise, it get placed in the tray-bar instead of the task-bar, so no way to even see the indication of new messages.

**Comment by 3n-mb** [comment]
@tmikaeld cool it down. Tone of phrases like, quoting you, " ... getting REALLY annoyed" is a bit too much on a product you get for free from these folks.
When you have a paid support from Wire (may be you should ask for it today), then vent extra steam in a private conversation. Otherwise, such high temperature in mere comments discourages developers from contributing anything.

**Comment by tmikaeld** [comment]
It's a normal reaction when you use an app daily and basic functionality don't work as expected. I don't see how anyone can possibly be offended by someone being annoyed.

**Comment by ConorIA** [comment]
A big part of the GPL is the warranty disclaimer. The software is provided as is. Wire owes us users nothing. 

While I'm not entirely sure what your use case is, I think it is great that you encourage the use of Wire with your clients. From what I can tell it is the most private messenger around that offers functionality on so many platforms.  Even so, this app popped up on GitHub just a couple weeks ago, and is still under heavy development. You and your clients are early adopters! , You're doing everything right by reporting the errors, but give the devs time to fix things and don't take any functionality (even what you'd expect to be basic) for granted until the app matures.

**Comment by tmikaeld** [comment]
@ConorIA I'm not assuming anything, i think you are both reading in too much at clients just being annoyed. But I do find it appalling that 3n-mb assume that we should pay to get bugs fixed. We don't expect anything from Wire and will continue to report bugs, issues and suggest features - for **free**.

**Comment by 3n-mb** [comment]
@tmikaeld mean that just being civil is a low bar. Better be civil and soft. Like, civil, soft pressure.
It just reminded me of moxie's comments about his experience. And, for it not to be repeated, we should raise the bar to being civil, and soft. And it works both ways, as pissed off dev can leave a subtle backdoor.

**Comment by tmikaeld** [comment]
@3n-mb You are right of course, being civil should always be the gold standard. But consider what happened, the client missed an important message for an entire day because the app didn't notify him at all. Being annoyed is quite a mild reaction when such a thing happens.

**Comment by bennyn** [comment]
@lipis Is this reproducible for you?

**Comment by lipis** [comment]
![screen shot 2016-09-08 at 14 06 00](https://cloud.githubusercontent.com/assets/125676/18348760/94cc73be-75cd-11e6-8cf2-bfa8c80d44c5.png)

Works here :/

**Comment by tmikaeld** [comment]
It shows in the tray bar but not on the task bar, you can see it in your screenshot.

![screenshot_2016-09-08_02-09-16_pm](https://cloud.githubusercontent.com/assets/907195/18348846/1004727a-75ce-11e6-8ffd-b58af63d53fa.png)

**Comment by lipis** [comment]
to show the notification badge in the icon in the taskbar?

**Comment by tmikaeld** [comment]
Yes

**Comment by tmikaeld** [comment]
Many clients have disabled Windows default notifications, they find it too intrusive.

So by having the notification badge in the task bar, it's always visible.

**Comment by lipis** [comment]
Well.. this is by design.. it's [not supported on Windows](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetbadgecountcount-linux-macos)

Updating the icon will be a hack :/

**Comment by tmikaeld** [comment]
But you can blink the icon to show changes/get attention of the user, like Skype does - right?

**Comment by lipis** [comment]
https://github.com/electron/electron/blob/master/docs/api/app.md#appdockbouncetype-macos only macOS feature.. :/

So I will close that issue, but we are following up the Electron's update very closely.. so in case it will be supported we'll include right away :)
