### ISSUE TITLE
No indication that a message failed to send

### ISSUE THREAD

**Issue by mlacorte** [wireapp/wire-desktop#200]
The message remains gray as if it were trying to send, even after the app gives up on trying to send it.

**Comment by gregor** [comment]
@mlacorte Thanks for your report - and feature request. We will continue to track this internally and close the public issue as an act of housekeeping as we mainly want to use the public issues to track bugs in the product.

While we now that failed to send state and retry option would be very nice to have, we have no immediate plans to implement this. It is on our to do list and will get prioritized looking at the big picture accordingly though.
