### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by GabMar** [wireapp/wire-desktop#202]
I'm using Wire Desktop in Arch Linux 4.8.10-1.
When I take a screenshot and I save it in the clipboard, it's not possible to send it via "paste" option in Wire.
Could it be possible to link system clipboard with the Wire Desktop application?

Thanks

**Comment by lipis** [comment]
Please upvote to raise your voice in this issue: https://github.com/wireapp/wire-webapp/issues/236
