### ISSUE TITLE
Not all executables are digitally signed

### ISSUE THREAD

**Issue by mrjcap** [wireapp/wire-desktop#2031]
Wire version: 3.5.2899 
Wire for web version: 2018.12.04.1424 
Operating system: Windows 10 / Build 1809

What steps will reproduce the problem?

1.  download [sigcheck](https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck)
2.  Go to C:\Users\username\AppData\Local\wire folder
3.  run sigcheck -r -e -h

What is the expected result?
No output.

What is the actual result?

C:\Users\username\AppData\Local\wire>sigcheck -r -e -h

C:\Users\username\AppData\Local\wire\Update.exe:
        Verified:       Unsigned
        Link date:      03:31 ?? 17/1/2018
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    32-bit
        MD5:    B4DA190FFD7A5049EC8FE2A33B1CC828
        SHA1:   1D59C6616590669CA91D788CFD7468DB5F60A1E0
        PESHA1: 8FD65DF1901E6CEF10F94DA0A64CC756891C95DC
        PE256:  4AA8D199E134D9B840DCF3DF0C038CE28F501CD4AE3B41C090156DFBF30B4AE4
        SHA256: AD8AC00068E49EE85618692700B582E9AB1BDFC6C5FDD6B0BF6D68C40109E801
        IMP:    F34D5F2D4577ED6D9CEEC516C1F5A744
C:\Users\username\AppData\Local\wire\Wire.exe:
        Verified:       Unsigned
        Link date:      03:30 ?? 17/1/2018
        Publisher:      n/a
        Company:        Wire
        Description:    Wire
        Product:        Wire
        Prod version:   3.5
        File version:   2899
        MachineType:    32-bit
        MD5:    72532A40761C0D9AD070E21B0D36FC3C
        SHA1:   B1CC2CC811402D89C6421076ECCAAF01D4C38119
        PESHA1: 888EDA93376DCB412B7351D14579A2FCEA3E68AC
        PE256:  A63445EA17D3B1C45BFA81BE31C33ACD2BE24B32F06F7E09B163FF3AD09616C0
        SHA256: 0082491D977A051074F775E10C6A2D3F52223A129A4191F2237B4CE98C95CA53
        IMP:    6B4AA3D8577B072415ADD0E71C03EEF4

As you can see Wire.exe and Update.exe are unsigned.

![capture](https://user-images.githubusercontent.com/3140504/50385807-6a76ee00-06e4-11e9-872b-13279659cee1.JPG)

**Comment by ffflorian** [comment]
Hi @mrjcap, in the next release of Wire Desktop all executables should be signed :slightly_smiling_face:
