### ISSUE TITLE
Linux Indicator-plugin icon is missing

### ISSUE THREAD

**Issue by marek141017** [wireapp/wire-desktop#2042]
Wire version: 3.5.2881
Wire for web version: 2018.12.04.1424 
Operating system: Ubuntu 16.04.5 LTS
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  execute: dbus-monitor
2.  run wire-desktop
3.  in the dbus log one can see the following:

`array [
      dict entry(
         string "Id"
         variant             string "Wire1"
      )
      dict entry(
         string "Category"
         variant             string "ApplicationStatus"
      )
      dict entry(
         string "Status"
         variant             string "Active"
      )
      dict entry(
         string "IconName"
         variant             string "Wire1_3"
      )
      dict entry(
         string "IconAccessibleDesc"
         variant             string ""
      )
      dict entry(
         string "AttentionIconName"
         variant             string ""
      )
      dict entry(
         string "AttentionAccessibleDesc"
         variant             string ""
      )
      dict entry(
         string "Title"
         variant             string "wire-desktop"
      )
      dict entry(
         string "IconThemePath"
         variant             string "/tmp/.org.chromium.Chromium.VCsbhA"
      )
      dict entry(
         string "Menu"
         variant             object path "/org/ayatana/NotificationItem/Wire1/Menu"
      )
      dict entry(
         string "XAyatanaLabel"
         variant             string ""
      )
      dict entry(
         string "XAyatanaLabelGuide"
         variant             string ""
      )
      dict entry(
         string "XAyatanaOrderingIndex"
         variant             uint32 0
      )
   ]
`

As you can see the application sends to indicator-plugin via dbus IconName details, which is = 
`dict entry(
         string "IconName"
         variant  string "Wire1_3"
      )
`
and Path:
`
dict entry(
         string "IconThemePath"
         variant             string "/tmp/.org.chromium.Chromium.VCsbhA"
      )
`

Okay, need to change issue again

Application sends another icon and in this time it matches path and image name, but there not "png"

I think the problem is, that the image needs to have full path and extension.
Right now it is just "Wire1_3", but filename is Wire1_3.png

What is the expected result?
Application needs to provide file name with path and extension
/tmp/.org.chromium.Chromium.0F73yY/Wire1_3.png

Please provide any additional information below. Attach a screenshot if possible.

![screenshot_2018-12-27_23-01-28](https://user-images.githubusercontent.com/32798889/50492917-738cf580-0a2b-11e9-9394-b99b588b746b.png)

**Comment by ffflorian** [comment]
@marek141017 Is this still an issue for you in the current version of Wire Desktop?

**Comment by marek141017** [comment]
Sorry for very delay
I was waiting for new version
Yes - I still see the issue. But as long as I see the same issue for skype also, I began to suspect that applications was not designed to use xfce4-indicator-plugin at all and it is xfce4-indicator-plugin, that is trying to show what is in sys-tray, but does it wrong way

So, i do not think you need to do anything about it.
Thank you.
