### ISSUE TITLE
emoticons text shortcuts

### ISSUE THREAD

**Issue by kb8000** [wireapp/wire-desktop#2067]
is there a list for all supported emoticons and their text shortcuts?

The only way is to know the text shortcuts and type them manually but there is no full list for reference that I can find.

**Comment by tokariu** [comment]
not that I would know of. 
many people including me asked already for a emoticon-popup-window similar to skype where all available emoticons are shown and then can be selected for insertion. however, everytime it was neglected saying "won't fix".

**Comment by kb8000** [comment]
> not that I would know of.
> many people including me asked already for a emoticon-popup-window similar to skype where all available emoticons are shown and then can be selected for insertion. however, everytime it was neglected saying "won't fix", stating we should use the virtual keyboard of windows 10 and using the emoticon tab there or something like that. This completely ignores the people using Windows 7 who don't have this option.

I am not asking for any fix, just a list of text shortcuts corresponding to emoticons to type them manually. I couldn't find one and I dont know if one exists.

**Comment by ffflorian** [comment]
Hi @kb8000,
here you can find the shortcuts: [EmojiInputViewModel.js#L40](https://github.com/wireapp/wire-webapp/blob/staging/app/script/view_model/content/EmojiInputViewModel.js#L40).

**Comment by kb8000** [comment]
@ffflorian this list does not include all emoticons. for example :package and all the :something ones. where can I find them?

**Comment by kb8000** [comment]
@typfel @vytis @ffflorian anyone please?
