### ISSUE TITLE
Do you plan to support the snap-package for the application in order not to be tied to distribution libraries?

### ISSUE THREAD

**Issue by BlinCT** [wireapp/wire-desktop#2071]
It would be nice if the application began to distribute in the snap package. Simplify access and support in many distributions.

**Comment by ffflorian** [comment]
Hi @BlinCT,
we do not intend to support additional Linux distribution methods and packages at this time.

(duplicate of https://github.com/wireapp/wire-desktop/issues/1168)

**Comment by bitinerant** [comment]
A snap package is available. Install via:
```
sudo snap install wire
snap connect wire:camera core:camera
```
