### ISSUE TITLE
Disapearing notification on tray on autostart

### ISSUE THREAD

**Issue by tmczar** [wireapp/wire-desktop#2089]
Wire version: 3.5.2881 Wire for web version: 2019.01.08.1320 Operating system: Linux Kubuntu 18.04 Which antivirus software do you have installed: None

I have Wire on autostart (minimized). If i got message on exactly one conversation, while computer was turn off, wire gets it, but new message indicator lasts only about second, and it disappears.
I noticed, that this behavior is exactly the same, if i start wire by hand, but then wire window opens, and shows conversation where i got the message - so i know that there is something new.

What steps will reproduce the problem?

1.  Log out of your computer with wire on autostart.
2.  Have somebody send you message on one conversation
3.  Log in.

What is the expected result?
Wire icon on tray should have this red dot, that indicates, that i've got new message.

What is the actual result?
Red dot disappears after about short moment and wire acts like i've already saw this message.

**Comment by ffflorian** [comment]
@tmczar this was fixed in https://github.com/wireapp/wire-webapp/pull/5121
