### ISSUE TITLE
Link Preview doesn't honors page encoding

### ISSUE THREAD

**Issue by Snawoot** [wireapp/wire-desktop#2097]
Wire version: 3.5.2881
Operating system: Debian 9
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Send a link pointing to non-unicode page (like this one: https://www.opennet.ru/opennews/art.shtml?num=49969)

What is the expected result?

Normal preview of page caption

What is the actual result?

Preview without respect of non-unicode page encoding. Text looks like bunch of question marks.

Please provide any additional information below. Attach a screenshot if possible.

Preview looks like this:
![Screenshot](https://gist.githubusercontent.com/Snawoot/8e21d3404f1708ba05232dc984bc943b/raw/7b0ddb05c3d9423c1e249c660faa4e90da6d3676/2019-01-17-115605_464x104_scrot.png)

**Comment by pitachx** [comment]
+1

**Comment by thisnickwasfree** [comment]
Can confirm this. Any link from opennet.ru, pikabu.ru has wrong encoding in wire's preview.
