### ISSUE TITLE
wire-desktop 3.5.2881 cannot find microphone

### ISSUE THREAD

**Issue by isj4** [wireapp/wire-desktop#2099]
Wire version: 3.5.2881
Operating system: Linux x86_64, OpenSUSE 15.0, KDE desktop.
No antivirus installed.

After updating to version 3.5.2881 wire-desktop can no longer find my microphone.
The previous version (which _may_ have been 3.0.2816) had no problems.

wire-desktop finds the speaker (headset) fine and I can hear the ring tone (but I cannot answer the call because wire cannot find a microphone).

Wire-web (firefox) can find the microphone. Skype has no problem either.

The only slightly unusual thing about the setup I can think of is that the motherboard has 2 soundcards embedded, and one of them is disabled. But wire can use the speaker/headset output fine.

You obviously need more info on bug but I'm not sure what that could be. Output from 'lspci' and 'gst-device-monitor-1.0' below. Please tell me which other information could be useful.

---snip---
# lspci 
00:00.0 Host bridge: Intel Corporation 4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 9 Series Chipset Family USB xHCI Controller
00:16.0 Communication controller: Intel Corporation 9 Series Chipset Family ME Interface #1
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection (2) I218-V
00:1a.0 USB controller: Intel Corporation 9 Series Chipset Family USB EHCI Controller #2
00:1b.0 Audio device: Intel Corporation 9 Series Chipset Family HD Audio Controller
00:1c.0 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 1 (rev d0)
00:1c.3 PCI bridge: Intel Corporation 82801 PCI Bridge (rev d0)
00:1c.4 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 5 (rev d0)
00:1d.0 USB controller: Intel Corporation 9 Series Chipset Family USB EHCI Controller #1
00:1f.0 ISA bridge: Intel Corporation 9 Series Chipset Family Z97 LPC Controller
00:1f.2 SATA controller: Intel Corporation 9 Series Chipset Family SATA Controller [AHCI Mode]
00:1f.3 SMBus: Intel Corporation 9 Series Chipset Family SMBus Controller
03:00.0 PCI bridge: ASMedia Technology Inc. ASM1083/1085 PCIe to PCI Bridge (rev 04)
05:00.0 Ethernet controller: Intel Corporation 82572EI Gigabit Ethernet Controller (Copper) (rev 06)
---snip---

---snip---
# gst-device-monitor-1.0 
Probing devices...

Device found:

        name  : Monitor of Built-in Audio Analog Stereo
        class : Audio/Source
        caps  : audio/x-raw, format=(string){ S16LE, S16BE, F32LE, F32BE, S32LE, S32BE, S24LE, S24BE, S24_32LE, S24_32BE, U8 }, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
                audio/x-alaw, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
                audio/x-mulaw, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
        properties:
                device.description = "Monitor\ of\ Built-in\ Audio\ Analog\ Stereo"
                device.class = monitor
                alsa.card = 1
                alsa.card_name = "HDA\ Intel\ PCH"
                alsa.long_card_name = "HDA\ Intel\ PCH\ at\ 0xf7d30000\ irq\ 31"
                alsa.driver_name = snd_hda_intel
                device.bus_path = pci-0000:00:1b.0
                sysfs.path = /devices/pci0000:00/0000:00:1b.0/sound/card1
                device.bus = pci
                device.vendor.id = 8086
                device.vendor.name = "Intel\ Corporation"
                device.product.id = 8ca0
                device.product.name = "9\ Series\ Chipset\ Family\ HD\ Audio\ Controller"
                device.form_factor = internal
                device.string = 1
                module-udev-detect.discovered = 1
                device.icon_name = audio-card-pci
        gst-launch-1.0 pulsesrc device=alsa_output.pci-0000_00_1b.0.analog-stereo.monitor ! ...

Device found:

        name  : Built-in Audio Analog Stereo
        class : Audio/Source
        caps  : audio/x-raw, format=(string){ S16LE, S16BE, F32LE, F32BE, S32LE, S32BE, S24LE, S24BE, S24_32LE, S24_32BE, U8 }, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
                audio/x-alaw, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
                audio/x-mulaw, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
        properties:
                alsa.resolution_bits = 16
                device.api = alsa
                device.class = sound
                alsa.class = generic
                alsa.subclass = generic-mix
                alsa.name = "ALC887-VD\ Analog"
                alsa.id = "ALC887-VD\ Analog"
                alsa.subdevice = 0
                alsa.subdevice_name = "subdevice\ \#0"
                alsa.device = 0
                alsa.card = 1
                alsa.card_name = "HDA\ Intel\ PCH"
                alsa.long_card_name = "HDA\ Intel\ PCH\ at\ 0xf7d30000\ irq\ 31"
                alsa.driver_name = snd_hda_intel
                device.bus_path = pci-0000:00:1b.0
                sysfs.path = /devices/pci0000:00/0000:00:1b.0/sound/card1
                device.bus = pci
                device.vendor.id = 8086
                device.vendor.name = "Intel\ Corporation"
                device.product.id = 8ca0
                device.product.name = "9\ Series\ Chipset\ Family\ HD\ Audio\ Controller"
                device.form_factor = internal
                device.string = front:1
                device.buffering.buffer_size = 352800
                device.buffering.fragment_size = 176400
                device.access_mode = mmap+timer
                device.profile.name = analog-stereo
                device.profile.description = "Analog\ Stereo"
                device.description = "Built-in\ Audio\ Analog\ Stereo"
                alsa.mixer_name = "Realtek\ ALC887-VD"
                alsa.components = "HDA:10ec0887\,10438630\,00100302"
                module-udev-detect.discovered = 1
                device.icon_name = audio-card-pci
        gst-launch-1.0 pulsesrc device=alsa_input.pci-0000_00_1b.0.analog-stereo ! ...

Device found:

        name  : Built-in Audio Analog Stereo
        class : Audio/Sink
        caps  : audio/x-raw, format=(string){ S16LE, S16BE, F32LE, F32BE, S32LE, S32BE, S24LE, S24BE, S24_32LE, S24_32BE, U8 }, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
                audio/x-alaw, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
                audio/x-mulaw, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 32 ];
        properties:
                alsa.resolution_bits = 16
                device.api = alsa
                device.class = sound
                alsa.class = generic
                alsa.subclass = generic-mix
                alsa.name = "ALC887-VD\ Analog"
                alsa.id = "ALC887-VD\ Analog"
                alsa.subdevice = 0
                alsa.subdevice_name = "subdevice\ \#0"
                alsa.device = 0
                alsa.card = 1
                alsa.card_name = "HDA\ Intel\ PCH"
                alsa.long_card_name = "HDA\ Intel\ PCH\ at\ 0xf7d30000\ irq\ 31"
                alsa.driver_name = snd_hda_intel
                device.bus_path = pci-0000:00:1b.0
                sysfs.path = /devices/pci0000:00/0000:00:1b.0/sound/card1
                device.bus = pci
                device.vendor.id = 8086
                device.vendor.name = "Intel\ Corporation"
                device.product.id = 8ca0
                device.product.name = "9\ Series\ Chipset\ Family\ HD\ Audio\ Controller"
                device.form_factor = internal
                device.string = front:1
                device.buffering.buffer_size = 352800
                device.buffering.fragment_size = 176400
                device.access_mode = mmap+timer
                device.profile.name = analog-stereo
                device.profile.description = "Analog\ Stereo"
                device.description = "Built-in\ Audio\ Analog\ Stereo"
                alsa.mixer_name = "Realtek\ ALC887-VD"
                alsa.components = "HDA:10ec0887\,10438630\,00100302"
                module-udev-detect.discovered = 1
                device.icon_name = audio-card-pci
        gst-launch-1.0 ... ! pulsesink device=alsa_output.pci-0000_00_1b.0.analog-stereo

---snip---

**Comment by ffflorian** [comment]
Hi, does the [WebApp](https://app.wire.com) in Chrome see the microphone?

**Comment by isj4** [comment]
No, wire-web on google-chrome only sees the speaker/headset. No microphone.

**Comment by ffflorian** [comment]
Then it's a problem in your system. Can other websites see your microphone?

**Comment by isj4** [comment]
wire-web in mozilla firefox can find the microphone.
www.onlinemictest.com in mozilla firefox can find the microphone

wire-web in google-chrome cannot find the microphone.
www.onlinemictest.com in google-chrome cannot find the microphone

skype-desktop can find the microphone

audio playback (eg youtube) works in google-chrome, so it is finding the correct sound card.

It seems to me that something must have changed in chrome/chromium recently which affects both the chrome browser and electron apps.

**Comment by ffflorian** [comment]
> It seems to me that something must have changed in chrome/chromium recently which affects both the chrome browser and electron apps.

Definitely. Since Wire Desktop is based on Electron, there is not much we can do for you, sorry. I hope you can find a solution for your system.

**Comment by nynhex** [comment]
I've verified in multiple distros this is not an issue.  Can we close? cc: @ffflorian

**Comment by isj4** [comment]
The issue hasn't magically disappeared. Wire-desktop and google-chome still can't find my microphone.
It appears the underlying problem is in chrome (and therefore affects all electron apps). If you have any suggestions of how to narrow down the problem then please tell me.

**Comment by Kyoshiro-san** [comment]
I have the same issue with the title's version and with latest version 3.6.2885 as well.

Everything works fine with Firefox but Chromium and Wire Desktop fail to access my webcam / microphone. When I try an audio or video call, it complains about :
> Wire doesn’t have access to the camera. Read [this support article](https://support.wire.com/hc/en-us/articles/202935412) to find out how to fix it. 

In wire-desktop, when I check the audio / video parameters :
* with 3.5.2881, the webcam activity indicator led shortly blinks then it fails with no access error.
* with 3.6.2885, the webcam led stays on and the capture is black.
Also, the header says : 
> You cannot call because your computer does not have a microphone.

I'm  running up to date Ubuntu 18.04.2 LTS with KDE environment.
I'm open to suggestions as well !

Thank you so much.

**Comment by Kyoshiro-san** [comment]
A complement of information, when I test on https://test.webrtc.org/, even after authorizing access to camera and microphone, I get : 

> Audio capture
> [ FAILED ] Failed to get access to local media due to error: NotReadableError

**Comment by neolovich** [comment]
I tested my machine too on the website: https://test.webrtc.org/

Brave Browser (Version 0.63.48 Chromium: 74.0.3729.108) doesnt see webcam or microphone and no "error message" or something like that. With Opera (Version: 60.0.3255.70) i got the following message (while Wire Desktop App opened):

> Failed to access your computer's camera and microphone (NotReadableError: Could not start video source).

When i close the Wire Desktop App Opera can pass the check without a problem. Except the microphone.
Same for firefox (Version: 66.0.2).
The desktop app cant get access to the camera or the microphone. The WebApp get access to the camera but not the microphone.
So for the WebApp it seems to me like a problem between firefox and Linux Mint 19 on my machine.

**Comment by ffflorian** [comment]
I am closing this since the underlying problem is Chrome and not Wire.
