### ISSUE TITLE
AppImage upgrade path for wire results in "new device" and lost message history

### ISSUE THREAD

**Issue by fermulator** [wireapp/wire-desktop#2114]
Wire version: `wire-3.5.2881-x86_64.AppImage`
Operating system: `Linux Mint 18.3 Sylvia`

What steps will reproduce the problem?

Was running wire 2.15 for a LONG time on my notebook.  Seems like the AppImage would update itself OK using the built-in functionality.

But at some point, I ran into BLANK WIRE issues (similar to #2055).. so I downloaded latest AppImage and re-ran it.

Now when I opened it, its an ENTIRELY NEW wire-installation (of course...ugh). And no message history exists.

```
:~/bin$ ll
total 180732
drwxrwxr-x  2 fermulator fermulator      4096 Jan  8 09:32 ./
drwx------ 75 fermulator fermulator     20480 Jan 21 21:26 ../
-rwx--x--x  1 fermulator fermulator 103415808 Aug 13  2017 wire-2.15.2751-x86_64.AppImage*
-rwxrwxr-x  1 fermulator fermulator  81597123 Jan  8 09:32 wire-3.5.2881-x86_64.AppImage*
```

What is the expected result?

https://wire.com/en/download/

what is the PROPER upgrade path/fix for AppImage? docs?

What is the actual result?

AppImage re-installation path

**Comment by fermulator** [comment]
_wtf_, I did not even perform an upgrade, and suddenly after a close + re-open, my entire history was lost again due to "new device" - SUPER FRUSTRATING I don't even feel like debugging this ...

**Comment by ffflorian** [comment]
Hi @fermulator, it's possible that you were running out of disk space. Chrome will delete the content of IndexedDB if it detects low disk space.

**Comment by ffflorian** [comment]
@fermulator sorry for the late response - as we are now [registering a persistent storage](https://github.com/wireapp/wire-web-packages/pull/2224) in the app the database should not be deleted if Chrome detects low disk space. Sorry for the inconvenience it caused you! I will close this for now.
