### ISSUE TITLE
High CPU usage again (OSX)

### ISSUE THREAD

**Issue by dimitrik-fr** [wireapp/wire-desktop#2127]
Hello,

since the last update, Wire is constantly using 10% CPU all the time (while running in background without any interface activity).. Restarting or even archiving all conversations in Wire did not help..

NOTE : even Skype (which is a well known CPU "eater") using only 1% CPU in the same conditions (and today both are built on Electron, right ?)

Wire version: 3.5.2910 
Wire for web version: 2019.01.17.1508 
Operating system: MacOS 
Which antivirus software do you have installed: none

Please, fix it asap, as right now Wire becomes the #1 battery drainer..

Rgds,
-Dimitri

**Comment by dimitrik-fr** [comment]
Probably yes -- can confirm it's writing to disk all the time for no reasons.

**Comment by dimitrik-fr** [comment]
Wire upgraded itself to web version 2019.01.28.1508 and seems like the issue I've observed is gone ! (no more high CPU activity nor constant writes to disk) -- do you see similar improvements on other platforms as well ?

**Comment by nynhex** [comment]
Can confirm on both High Sierra and latest Mojave builds this is fixed:

![image](https://user-images.githubusercontent.com/13086902/52429154-1a53bf80-2ac9-11e9-8c01-54573e2d8341.png)


`close?`

**Comment by dimitrik-fr** [comment]
yes, issue is closed. thanks for great work !

**Comment by muesli** [comment]
Which commit has this been fixed with? Mine still uses between 15% and 20% doing nothing.
