### ISSUE TITLE
record audio / video calls

### ISSUE THREAD

**Issue by kolAflash** [wireapp/wire-desktop#213]
As simply as it sounds:
It would be a great feature to have a record feature for audio/video calls.

**Comment by lipis** [comment]
I think it's more of a legal challenge than technical.. as in many countries, this is very illegal to do so without informing all the parties on the call that they are being recorded, before actually doing so. 
But most importantly as privacy is our top priority, I strongly believe that this might scare a bunch of users that their conversation can be recorded (even if it's just happening client side).

**Comment by TomSea** [comment]
Well I requested this feature back in March - request (10827), and I know the folks I work with would leave Skype / Pamela for Wire if this solution were available. This could certainly be implemented as an opt-in to have yourself recorded from the client side, while notifying each call participant of the recording status. It shouldn't scare users as long as your code is verifiable and audited, as we're already trusting the wire app with the encryption. I strongly believe this feature should be implemented to give users a choice. What's to stop one person on a group call using a usb conference speaker from recording everything? At least with the option built in everyone could be notified of the recording and opt out if they are going to say something they don't want recorded. Not having this option makes wire a tough sell to those that need this flexibility.

**Comment by Bugsbane** [comment]
I'm a privacy geek myself, but I'd still like an option to record calls. Just make it confirm with others on the call.

For example, one person hits the record button. They're told by an on-screen message: "Waiting for permission to record from other caller(s)". Anyone else on the call would see a message "$NAME is requesting to record this call. [Agree] [Disagree]". Recording would only start when everyone had clicked "Accept".

I really don't see anyone having a problem with recording legally or from a privacy perspective when it's all done transparently and with consent of all involved.

**Comment by ConorIA** [comment]
I really like @Bugsbane's suggestion. With their solution, Wire still ensure's a user's right to Privacy, and gives every participant control over call recording.

**Comment by helenakos** [comment]
Thanks for the request. Although it's a very useful use case we don't have plans to implement this at the moment. Therefore closing the issue.
