### ISSUE TITLE
Running out of disk space makes local message history unrecoverable

### ISSUE THREAD

**Issue by marmarek** [wireapp/wire-desktop#2131]
Wire version: 3.5.2881 (AppImage)
Operating system: Linux (Fedora 29)

##### What steps will reproduce the problem?

1. Start Wire
2. Run out of disk space
3. Observe no new messages are received
4. Close Wire
5. Open Wire again

##### What is the expected result?

Some error message about out of disk space (possibly closing app, if that's necessary)
After freeing some space on the disk, Wire should behave normally.

##### What is the actual result?

After opening Wire again, it behave like there was no logged in account ever. It asks for username and password and when provided with one, it behaves as it was new device. Messages history is lost.

##### Please provide any additional information below. Attach a screenshot if possible.

`~/.config/Wire` still contains a lot of files, but I have no idea which are related. Checked files in `logs`, but there are no relevant messages.

**Comment by marmarek** [comment]
>  And if you're running out of disk space the expected behavior should be for applications to have possible issues.

That's true. While "application crash" would be not the best but acceptable behavior, loosing the whole messages history is very painful, at least. Especially when backup format is not compatible cross-platforms (reading message archive by manual inspection of sqlite database dump from android, is the most convenient way...).

> Also, if by chance you cleared out diskspace in your `$HOME` path, likely you deleted wire-related files.

I'm sure I didn't done that.

**Comment by nynhex** [comment]
@marmarek Gotcha, and makes sense.  problem is if your disk fills it's likely to corrupt files/db/backed up persistence.  It happens in other programs as well.  I'm honestly not sure this one will get a lot of attention, but i I have some time I can try to PR it

**Comment by bennyn** [comment]
@marmarek Problem here is that we rely on [IndexedDB](https://developer.mozilla.org/docs/IndexedDB) for persistent storage and IndexedDB deletes itself when the system has too little disk space: 

>  IndexedDB without StorageManager is just a “best-effort” database that can be erased in situations of low disk space on a device.

Source: https://dexie.org/docs/StorageManager
