### ISSUE TITLE
App opens to a white screen

### ISSUE THREAD

**Issue by andyglover** [wireapp/wire-desktop#2140]
Operating system: Windows 10

This started after updating to the latest version. I just get a white screen. I tried unistalling and deleting all trace files, updating java, restarting and going back to version 3.4.2885 and issue still persists. Any idea how to rectify this? 

![wire_2019-01-29_18-36-35](https://user-images.githubusercontent.com/13704069/51954386-db50aa80-23f4-11e9-8dd0-b3e00a4583e1.png)

**Comment by macexpertsusa** [comment]
same issue win 8.1

**Comment by ddobrev** [comment]
Two of my friends got this too, one of them quit Wire over it. It's because of the settings. The friend that quit moved his settings away and Wire was able to load but since he thus lost his history, he decided not to use it any longer.

**Comment by andyglover** [comment]
> Two of my friends got this too, one of them quit Wire over it. It's because of the settings. The friend that quit moved his settings away and Wire was able to load but since he thus lost his history, he decided not to use it any longer.

Yeah. I may just drop it and use something else. It was a nice little program while it lasted.

**Comment by nynhex** [comment]
@andyglover what build are you on?  Is this isolate to windows?  Have you tried a downgrade from a previous build release to validate?

**Comment by hap124** [comment]
I get this on webapp on Firefox and on Desktop app. I cannot log in to Wire at all on computers. Only iOS and Android mobile devices.

**Comment by andyglover** [comment]
> @andyglover what build are you on? Is this isolate to windows? Have you tried a downgrade from a previous build release to validate?

i downgraded to 3.4.2885 and issue persisted. i'm on 3.5.2899 now and issue seems to have resolved itself. just opened up the program for the first time in a week and it works. that was weird.

**Comment by dlfsdev** [comment]
I had this on Win10 too. After wasting a lot of time trying and failing to get Wire to do anything at all (couldn't even log out), I eventually I just got up and walked away from the computer. After a few minutes, a loading bar appeared out of the blue (white) for no obvious reason and then everything went back to normal.
