### ISSUE TITLE
Feature :  Nuke all his own messages in conversation

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#215]
Wire does have a great feature: sending remote delete order to remove from recipients a message. (everyone knows that it's a countermesure not designed against malicious recipient). But it is for one message at once.

It would be interesting, when deleting an entire conversation, to ask if the user want also to have all his own messages removed from recipients too.

**Comment by panigrc** [comment]
Yeah I would love to see it too! Delete all the messages inside a conversation but without leaving or deleting it.

**Comment by helenakos** [comment]
@IpsmLorem Currently you can use "Delete for Everyone" to delete a specific message for other recipients. We don't have plans to implement deleting all of the message for other recipients. Closing this issue.
