### ISSUE TITLE
Search in chats

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#218]
How about a full-text search function in chats?

It would also be nice to have on overview of all media and files stored inside a chat.

**Comment by lipis** [comment]
As you might know already, since we can't do that server side due to e2ee, this functionality will have to be implemented on each client independently. But it's something that many users ask and we hear you.

**Comment by herrpoerner** [comment]
Good. WhatsApp can do this, too.

**Comment by lipis** [comment]
We are [aware](https://wire.com/privacy/) of that.. and I didn't say we are not going to do that :)

**Comment by gregor** [comment]
We just launched a collection feature, which lets you view all the media and files within a conversation. As search in conversations is trackend in #76 I am closing this one.

**Comment by herrmannplatz** [comment]
on it

**Comment by lipis** [comment]
Rolled out 💃 🎆
