### ISSUE TITLE
Overview of liked messages

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#219]
As the title says: If Wire has a Like function, it would be nice to have an overview of all liked messages.

**Comment by anatoli26** [comment]
Indeed, I just wondered where to see all the liked messages...

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by anatoli26** [comment]
What could be (easily?) done is to put all the liked messages in a separate group in the search window, like images, videos and the like. Otherwise the like option should probably be removed (at least I don't see it any use without being able to see later all liked messages).
