### ISSUE TITLE
No (native) tray icon

### ISSUE THREAD

**Issue by fenrig** [wireapp/wire-desktop#22]
Would it be possible to add a tray icon to the app ? Something we can (optionally) close to... ?

**Comment by ConorIA** [comment]
The tray icon was limited to Windows only in commit 7e11fc40. You could try reverting it. I'll test on my install.

**Comment by ConorIA** [comment]
Alright, I manged to come up with something in #23. I think you mentioned that you run Arch, right? I will update my PKGBUILD so that the AUR build gets the tray icon, but I'd really like to move the source back to the official repo, so I hope this gets merged and the devs can push another point release so I can go back to basing on the official code.

**Comment by lipis** [comment]
@fenrig if it works OK on Linux we could enable it there as well but we need your help to test it out :)

**Comment by ConorIA** [comment]
@lipis I'm happy to test too. The only two tray menu items on Linux are "Open WireInternal" and "Quit". No way to minimize to tray yet. But at least there is an icon that will show a badge when there is a message waiting.

**Comment by fenrig** [comment]
yeah I'm ready to test it, indeed I run arch

**Comment by ConorIA** [comment]
Fenrig, while we wait for Arch to fix the `nodejs` version issue, see if this package will install with `pacman -U` http://cubert.conr.ca:8001/f/c95b3b631b/?dl=1

**Comment by fenrig** [comment]
Okay on gnome it works fine, still awaiting the close to tray option. But its really shaping up to be a great desktop app :D

**Comment by fenrig** [comment]
Oh and afterward it would be great if we could pass a flag to start the app in the tray :)

**Comment by ConorIA** [comment]
There is some code over on StackExchange ([source](https://stackoverflow.com/questions/37828758/electron-js-how-to-minimize-close-window-to-system-tray-and-restore-window-back)) that might help. But I'm not sure where to add things like this, so I'll leave it to the professionals for now. :wink:

**Comment by lipis** [comment]
Fixed in #23 :)

**Comment by lipis** [comment]
@ConorIA Do I have to do anything special on Ubuntu to see the Tray Icon? I just installed a new VM and it doesn't appear.. maybe some sort of settings or something?

**Comment by lipis** [comment]
Found it :) https://github.com/electron/electron/issues/1347#issuecomment-123140402

```
sudo apt-get install libappindicator1
```

**Comment by ConorIA** [comment]
Linux is funny with electron tray icons. I find the icon doesn't appear the first time I start Wire, but if I quit and open it again, it does work. Same thing with Rambox and other apps.
