### ISSUE TITLE
Bulk deleting of messages

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#220]
Marking multiple messages to delete them. How about by long-pressing messages? Liking messages could be implemented by double-tapping a message.

**Comment by lipis** [comment]
That would be great for sure.. But if you are about tapping stuff you might want to post something in [iOS](https://github.com/wireapp/wire-ios) or [Android](https://github.com/wireapp/wire-android).

**Comment by Post-Scriptum06** [comment]
Yes or just a button "select/select all" in the top bar next to audio/video conversation (same thing in the media folder)

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
