### ISSUE TITLE
Better optical distinction of 1:1 and group chats in conversation overview

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#222]
When having a lot of conversations, it's hard to find a specific one in the conversations overview. A clear distinction between 1:1 and group chats would help.

**Comment by Post-Scriptum06** [comment]
Hello,
Yes, it would be nice to be able to display, maybe in 3 different tabs :

- "Friends" contact list add
- conversation
- group conversation

Th other advantage would be that when we empty our voncersations, we could find our friends directly in the lost of our frinds add, without have to re*search it.

**Comment by helenakos** [comment]
A different layout of conversation list is coming out soon. Stay tuned and if you have interest joining our beta group add @helena on wire.
