### ISSUE TITLE
No more i386 releases for .deb files?

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-desktop#2223]
Just a recap, I'm the folk maintaining the Wire Flatpak for the time being.

I just noticed there was a new release for the wrapper, but in there is no **Wire-3.6.2885-i386.deb** in there. Was that intended and you are not going maintain anymore i386 builds? I see there is one for the AppImage :smirk:

I didn't know where else to report this...so it's not really an "issue", more like a question :sunglasses:

---

I need these three files to make the Flatpak:

- `wire_X.Y.ABCD_amd64.deb`
- `wire_X.Y.ABCD_i386.deb`
- `X.Y.ABCD.tar.gz`

**Comment by ffflorian** [comment]
Our build system had a little hiccup while releasing, the missing files will be uploaded today.

**Comment by ffflorian** [comment]
@x80486 The missing .deb file was just uploaded. Have a great day! :sun_with_face:

**Comment by x80486** [comment]
Hey @ffflorian, I think the build system had another of those hiccups...I don't see the i386 `.deb` for release `3.7.2891`.

**Comment by ffflorian** [comment]
Hi @x80486, there was no hiccup, we stopped releasing 32-bit versions of Wire since Electron [discontinued support for 32-bit Linux](https://electronjs.org/blog/linux-32bit-support).

**Comment by nidico** [comment]
:disappointed:

**Comment by artenaki** [comment]
I was able to get wire-desktop 3.25.2940 to work in Ubuntu 16.04 x86. I grabbed package from Void Linux x86 and installed electron10 from npm. Yes, electron doesn't officially support Linux 32 bit, but files keep getting updated and published to npm (maybe unofficially).

Attempt to build git version from source failed in the second step LINUX_TARGET=deb yarn build:linux Installer downloads electron x64. Void Linux somehow did it successfully. But they don't have the git version, but 3.25.2940.

There is also an x86 version in flathub. Of course, wire-desktop will not work on Windows XP. Except for the browser, maybe the Chinese Chromium builds.

https://nodejs.org/en/download/
https://unofficial-builds.nodejs.org/download/release/
https://www.npmjs.com/package/electron-releases
sudo npm install --global yarn
npm install electron@10-x-y
electron 10.4.7
chromium 85.0.4183.121

ftp://mirror.yandex.ru/mirrors/voidlinux/current/ (FileZilla)
wire-desktop-3.25.2940.i686.xbps.zst
/usr/local/lib/wire-desktop/app.asar
/usr/local/bin/wire-desktop:
exec /home/denis/node_modules/electron/dist/electron "/usr/local/lib/wire-desktop/app.asar" --disable-smooth-scrolling

See also examples:
https://github.com/void-linux/void-packages/blob/master/srcpkgs/wire-desktop/template
https://github.com/archlinux/svntogit-community/blob/packages/wire-desktop/trunk/PKGBUILD

Failed:
cd wire-desktop
yarn
LINUX_TARGET=deb ENABLE_ASAR=true yarn build:linux

**Comment by artenaki** [comment]
By the way, I was not able to compile new Signal x86 version. I was able to compile an older version of Signal 2018 (the same as in Void Linux x86 repository), but it doesn't connect. So Wire is better than Signal for me.
Thanks to the developers.
