### ISSUE TITLE
Emphasise new messages in conversations

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#223]
New messages should be emphasised in conversations, i. e. by bold text or a colored background. An optical divider (like a red line) between old and new messages would help, too.

**Comment by ConorIA** [comment]
New messages are indicated by a coloured dot beside the new messages.

**Comment by herrpoerner** [comment]
Well, I use Wire for several weeks now and I never noticed these dots. What
does this tell us about their visibility?

**Comment by helenakos** [comment]
Besides the dots there is a line separating new messages and timestamps e.g. "9 minutes ago". We don't have plans to change these in the next few months. Therefore closing this issue.
