### ISSUE TITLE
Reaching Wire support via Wire messenger

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#224]
Wire support should be reachable via Wire messenger, not only via e-mail.

**Comment by lipis** [comment]
On top of that we have [Twitter](https://twitter.com/wire), [GitHub](https://github.com/wireapp) and other resources if people want to communicate with us.. plus bunch of group chats that you could be part of if you want to contribute with some beta tests.. So currently we don't have many resources to have a dedicated system internally from the app.

**Comment by herrpoerner** [comment]
Somehow it's sad, that the producer of a communication solution won't use
it's own product for communicating with it's users.

**Comment by lipis** [comment]
We already have a few chats for some testing groups.. do you want to be part of any of those?

**Comment by herrpoerner** [comment]
Sure, Why Not? 😊

**Comment by lipis** [comment]
@helenakos will hook you up :)

**Comment by helenakos** [comment]
@herrpoerner Hey, sorry for the late reply - what's your Wire username?

**Comment by herrpoerner** [comment]
@herrpoerner :)

On 6. March 2017 at 15:10:52, helenakos (notifications@github.com) wrote:

@herrpoerner <https://github.com/herrpoerner> Hey, sorry for the late reply
- what's your Wire username?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wireapp/wire-desktop/issues/224#issuecomment-284405873>,
or mute the thread

**Comment by helenakos** [comment]
@herrpoerner Awesome, will add you

**Comment by mat1th** [comment]
@helenakos Hey, could you also add me? My Wire user name is: `@matth`;
