### ISSUE TITLE
Deactivating notifications for group chats / Mentions in group chats

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-desktop#225]
Notifications for specific group chats should be mutable. If implemented then how about a mention function, where users, who have muted notifications for a group chat get a notification if they are mentioned personally?

**Comment by lipis** [comment]
We don't support mentions as we don't have usernames..  But this might change in the [future](https://github.com/wireapp/wire-webapp/pull/478).. as for muted:

<img width="352" alt="screen shot 2016-11-26 at 01 12 13" src="https://cloud.githubusercontent.com/assets/125676/20636863/677a9f9a-b375-11e6-8cb9-cb210909fb2e.png">
