### ISSUE TITLE
verifying signature fails

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#2251]
Wire version: 3.6.2885

downloads + signature:
https://github.com/wireapp/wire-desktop/releases

against this key:
https://wire-app.wire.com/linux/releases.key

result: fail, the file has been modified

**Comment by maximbaz** [comment]
This has been fixed 😉 

```
❯ gpg --verify wire-desktop-linux-3.6.2885.tar.gz.sig 
gpg: assuming signed data in 'wire-desktop-linux-3.6.2885.tar.gz'
gpg: Signature made Tue 19 Feb 2019 12:34:55 PM CET
gpg:                using RSA key ABBA007D6E14E2DB5B283C45D599C1AA126762B1
gpg: Good signature from "Wire Releases Signing Key <releases@wire.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: ABBA 007D 6E14 E2DB 5B28  3C45 D599 C1AA 1267 62B1
```

**Comment by Blackoe** [comment]
Got the same issue while trying to verify the following files.

Wire-3.6.2885-amd64.deb
Wire-3.6.2885-i386.AppImage
Wire-3.6.2885-i386.deb
Wire-3.6.2885-x86_64.AppImage

gpg: using RSA key ABBA007D6E14E2DB5B283C45D599C1AA126762B1
gpg: BAD signature from "Wire Releases Signing Key <releases@wire.com>" [unknown]

----------------------------------------------------------------------------------------------------------------------

This file is fine > Source code (tar.gz)

gpg: Good signature from "Wire Releases Signing Key <releases@wire.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: ABBA 007D 6E14 E2DB 5B28  3C45 D599 C1AA 1267 62B1

----------------------------------------------------------------------------------------------------------------------

Are the failing files unsigned?

**Comment by maximbaz** [comment]
yes, the provided signature is only for the source tarball, not for the other attached files.

it seems though there might be a demand for providing signatures for other files 😉

**Comment by Blackoe** [comment]
How else can files be verified?
Don't know about the numbers of other users, but that can make this much better to trust in general so please do.

**Comment by maximbaz** [comment]
> How else can files be verified?

Every release contains a PGP-signed `sha256sum.txt.asc` file with hashsums for every attached file, you can check PGP signature of that file and then compare sha256sum on the files you downloaded.

I asked Wire guys to additionally provide a dedicated signature for sources tarball only because Arch Linux packaging infrastructure cannot work with signed hashsums, but for manual validations `sha256sum.txt.asc` should be more than enough.

**Comment by ffflorian** [comment]
Thanks for answering @maximbaz!
