### ISSUE TITLE
OSX Desktop. Screen Sharing.  A Kaleidoscope of Infinite Recursion

### ISSUE THREAD

**Issue by madranet** [wireapp/wire-desktop#2263]
Wire version: 3.6.2923
System: OSX 10.14.3

What steps will reproduce the problem? 
Make a video call. When other person connects, click the Screen Sharing button

What is the expected result? 
Screen Sharing

What is the actual result?
Bad LSD trip

---------

Whenever I try to initiate screen sharing between 2 OSX laptops [both running the same versions of OSX and Wire] I get a recursive visual tunnel effect as if both computers are behaving like an old VHS video camera pointed at its own monitor. This happens whichever end  of the conversation initiates the Screen Sharing.

![2019-02-27_17-26-31](https://user-images.githubusercontent.com/669658/53510382-c29be900-3ab5-11e9-9874-e5796ec15f0c.png)

If I move the cursor about inside the window, the effect increases and the images tunnel off into infinity. It also affects other windows outside of Wire. Here's what happened when I tried to screenshot the effect and my laptop brought the Finder forward to save the screenshot .  You can't tell from this still image but where the grey misty area is in the screenshot, I'm actually seeing the Finder windows continually zooming off into infinity and getting smaller and smaller:

![2019-02-27_17-38-08](https://user-images.githubusercontent.com/669658/53510832-cf6d0c80-3ab6-11e9-9b02-3c486db2c569.png)

I know I'm going out on a bit of a limb here. But I venture to suggest this is not the intended behaviour!

**Comment by ffflorian** [comment]
Hi @madranet, this is normal as your own screen is visible while screensharing. Please click on the conversations icon to return to the conversation or minimize the app. The effect is gone then.

**Comment by madranet** [comment]
Am I being dumb here?

What is the purpose of the Screen Sharing facility then, if it produces this crazy kaleidoscope effect unless minimised?  

Because of the similarity in name to OSX's Screen Sharing feature [available in OSX Messages.app], I supposed Screen Sharing in Wire would serve a similar purpose; namely allowing one of the parties in a conversation to view [and interact with] the other party's screen, for purposes such as tech support, etc.  It doesn't seem that there'd be much hope of achieving any kind of meaningful interaction with the other screen if it needs to be kept minimised to display properly.  

Am I missing something?

**Comment by ffflorian** [comment]
Of course you need to minimize the app only on the computer which initiates the screen share. Did you try that?
