### ISSUE TITLE
Desktop version screen is either all black or all white

### ISSUE THREAD

**Issue by owlbrudder** [wireapp/wire-desktop#227]
Fedora 24 x86_64 on an HP Pavilion Intel® Core™ i7-2670QM CPU @ 2.20GHz × 8, 8Gb memory Radeon HD2770-2.5GB Graphics

I have just compiled the desktop version of Wire. The login screen behaves normally, but the main window comes up either solid black* or solid white. In either case, I cannot see 
any option selected from the menus, but they seem to be rendering invisibly as the cursor changes shape as I move the mouse around.

*I have started the application ten times and only once did it work for a while before going black.

The version running in my Firefox browser works perfectly.

Screenshot:
![screenshot from 2016-11-28 12-32-29](https://cloud.githubusercontent.com/assets/20263907/20654996/2f389406-b56a-11e6-8b27-7d28a6f680c4.png)

**Comment by ConorIA** [comment]
How odd. Does the AppImage version work on your machine? 
Normally, Wire should complain if you are missing any dependencies, but do you have all of these installed: (packages from Arch / Ubuntu)

- alsa-lib / libasound2
- gconf / libgconf-2-4
- libxss / libxss1
- nss / libnss3

**Comment by owlbrudder** [comment]
Hi Conor.

Thanks for the prompt reply. Yes, I have all those installed - my
libXss has an upper case 'X', but I presum that's OK.

Kind regards,
Doug

On Sun, 2016-11-27 at 21:08 -0800, Conor Anderson wrote:
> How odd. Does the AppImage version work on your machine?
> 
> > Normally, Wire should complain if you are missing any dependencies,
but do you have all of these installed: (packages from Arch / Ubuntu)
> 
> alsa-lib / libasound2
> gconf / libgconf-2-4
> libxss / libxss1
> nss / libnss3
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/wireapp/w
ire-desktop","title":"wireapp/wire-desktop","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/wireapp/wire-
desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ConorI
A in #227: How odd. Does the AppImage version work on your machine?
\r\nNormally, Wire should complain if you are missing any
dependencies, but do you have all of these installed: (packages from
Arch / Ubuntu)\r\n\r\n- alsa-lib / libasound2\r\n- gconf / libgconf-
2-4\r\n- libxss / libxss1\r\n- nss /
libnss3"}],"action":{"name":"View
Issue","url":"https://github.com/wireapp/wire-
desktop/issues/227#issuecomment-263184645"}}}

**Comment by owlbrudder** [comment]
Sorry - I forgot to mention this is the Appimage version that is
misbehaving.

On Sun, 2016-11-27 at 21:08 -0800, Conor Anderson wrote:
> How odd. Does the AppImage version work on your machine?
> 
> > Normally, Wire should complain if you are missing any dependencies,
but do you have all of these installed: (packages from Arch / Ubuntu)
> 
> alsa-lib / libasound2
> gconf / libgconf-2-4
> libxss / libxss1
> nss / libnss3
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/wireapp/w
ire-desktop","title":"wireapp/wire-desktop","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/wireapp/wire-
desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ConorI
A in #227: How odd. Does the AppImage version work on your machine?
\r\nNormally, Wire should complain if you are missing any
dependencies, but do you have all of these installed: (packages from
Arch / Ubuntu)\r\n\r\n- alsa-lib / libasound2\r\n- gconf / libgconf-
2-4\r\n- libxss / libxss1\r\n- nss /
libnss3"}],"action":{"name":"View
Issue","url":"https://github.com/wireapp/wire-
desktop/issues/227#issuecomment-263184645"}}}

**Comment by ConorIA** [comment]
If you compiled form the GitHub source, there should be a folder called 'linux-unpacked' in `dist`. Try running Wire in that folder, to see if it is an issue with the AppImage and not with the program.

**Comment by owlbrudder** [comment]
Thanks Conor.

I found that version and tried it just now - same result. I tried twice
with the same result.
"8-(

Cheers,
Doug

On Sun, 2016-11-27 at 21:42 -0800, Conor Anderson wrote:
> > > If you compiled form the GitHub source, there should be a folder
called 'linux-unpacked' in dist. Try running Wire in that folder, to
see if it is an issue with the AppImage and not with the program.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/wireapp/w
ire-desktop","title":"wireapp/wire-desktop","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/wireapp/wire-
desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ConorI
A in #227: If you compiled form the GitHub source, there should be a
folder called 'linux-unpacked' in `dist`. Try running Wire in that
folder, to see if it is an issue with the AppImage and not with the
program."}],"action":{"name":"View
Issue","url":"https://github.com/wireapp/wire-
desktop/issues/227#issuecomment-263187870"}}}

**Comment by ConorIA** [comment]
@lipis, any hints on how to debug this? I haven't encountered the problem on my machine, which also uses a radeon card (with the open source driver).

**Comment by lipis** [comment]
@ConorIA Unfortunately no hints.. very strange. Will take another look when I'm back in the office on Thursday.

**Comment by owlbrudder** [comment]
Hi Conor.
Thanks again for your responses.
I upgraded to Fedora 25 overnight and the problem seems to have gone
away. If it reappears, I will get back to you. Don't you love transient
bugs that just go away with no rhyme or reason?   "8-[
Kind regards,Doug.

**Comment by ConorIA** [comment]
@owlbrudder happy to hear it. The best kind of issues are the ones that disappear in their own!   😊

**Comment by soamaven** [comment]
Having this problem after building from source on Fedora25. I'd like to figure out what is wrong rather than using the AppImage blob. I have all the dependencies installed that dnf could find: couldn't find gconf or libxss.

**Comment by ConorIA** [comment]
@soamaven, start by making sure you have all deps: 
https://admin.fedoraproject.org/pkgdb/package/rpms/GConf2/
https://admin.fedoraproject.org/pkgdb/package/rpms/libXScrnSaver/

There is also a new grunt task that hasn't been added to the README yet. You need to add "bundle" to the end of the first line. I'll submit a PR shortly.

**Comment by soamaven** [comment]
I have made sure the deps are installed, they are.

Adding the "bundle" argument to the first line helped. I was able to run these commands without error:

```
$grunt 'clean:linux' 'update-keys' 'release-prod' 'bundle'
Running "clean:linux" (clean) task
>> 16 paths cleaned.

Running "update-keys" task

Running "release-prod" task
Releases URL points to https://wire-app.wire.com/win/prod/ OK

Running "bundle" task

Done.

$grunt --arch="x64" --target="rpm" 'electronbuilder:linux_other'
Running "electronbuilder:linux_other" (electronbuilder) task
electron-builder 18.6.2
Rebuilding native production dependencies for linux:x64
⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for linux x64 using electron 1.6.11 to wrap/dist/linux-unpacked
Building rpm
```

I could then install the rpm without error:

`dnf install ./wrap/dist/wire-desktop-2.15.2750-1.x86_64`

However when I go to run the acutal app, I just get a useless blue screen. No conversations, dropdowns don't work. Only responsive element is the "quit" hotkey.

**Comment by ConorIA** [comment]
I wonder if the build `electron-builder` produces is junk. 

I've been tinkering this week, so if you want an RPM try https://conoria.gitlab.io/wire-builds

Also, I've just tried using create repo, so https://conoria.gitlab.io/wire-builds/repo might work as a fin repo. 

If you're interested, please test and let me know if either work.

**Comment by soamaven** [comment]
Thanks! I was really hoping to build it from source myself though, I just want to know what I am compiling. I tried your `build_wire.sh script` to compile your gitlab code. I commented out the portion creating a new user and giving sudo access (wasn't sure why that was necessary and made me uncomforable), adjusted the paths, and ran it as sudo myself. Looks like `mock` has me installing 450MB of packages , I looks like to build the final rpm -- unfortunately since I don't build rpms often, not worth the disk space. I tired letting it install the dependencies (I was going to dnf rollback), but it failed any way at the `npm` portion. [Errors Here](https://ghostbin.com/paste/o3q2v)

The `grunt` build unfortunately seems cleaner. Perhaps you can submit a pull request that fixes the issue as you have?

**Comment by soamaven** [comment]
@ConorIA I threw caution to the wind out of frustration lol. Your `.rpm` works great on fc26, thanks for taking the time. I won't be using the desktop client for anything i really need to be encrypted until I can build from the official source myself (¯\_(ツ)_/¯ ), but as I have been getting friends and family to start caring about their privacy by showing them how awesome Wire is, the `.rpm` accomplishes that goal.

**Comment by ConorIA** [comment]
@soamaven the build scripts are fully open and the rpms are gpg-signed. No caution needed!

**Comment by soamaven** [comment]
@ConorIA I wish I could take the conversation off this thread, I'm curious to know how I could verify that the rpms came from the compiled source if I can't build them myself.

**Comment by ConorIA** [comment]
Take it to Wire if you like! Same username.

**Comment by silvernode** [comment]
I have the white screen issue when building the RPM on Fedora 26. I have all the deps, and a few builds have worked fine in the fast but when 2.15 hit the git repo, ever since has been the white screen of death. The Appimage works fine but the client crashes around 30 minutes in a voice and/or video call. This is why I want to build it myself since I don't have issues like that outside of the Appimage. Could we Reopen this issue? Thanks

**Comment by soamaven** [comment]
@silvernode check out this [gist](https://gist.github.com/soamaven/6b5cd523dc2c72be7c5b012a63184335) for a quick bash script that worked for me to make the rpm on fc26. @ConorIA is [credited for the work](https://gitlab.com/ConorIA/wire-builds), i just modified it for my needs a bit since I couldn't get his exact script to work.

Using `mock` is probably the correct way to do it, I just installed all the dependencies onto my system.
