### ISSUE TITLE
Screen Sharing - Cannot choose which screen to share

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [wireapp/wire-desktop#228]
Unlike the macOS app, linux app **doesn't give a prompt which screen to share before sharing**.
It shares all of the screens without the ability to choose one of them.

Linux distro: ubuntu 16.10

Please fix it, it is a very important issue.

**Comment by OlzhasAlexandrov** [comment]
Thank you for the attention. I really like the app, more than I do skype or any other app out there.

**Comment by lipis** [comment]
We hear you.. thank you very much for the report.. all issues are important and we'll fix them when we can depending on our priority.

**Comment by OlzhasAlexandrov** [comment]
Btw, skype for linux also shares all screens, but they have another feature that you might want to copy: "Share selection". So when I use skype on linux, at least I can share selected area on the screen.

This note is just to help you, if it is impossible or too difficult for some reason on linux to select a screen for sharing.
Thank you

**Comment by gregor** [comment]
Screensharing will be reenabled in our next release. If you continue to be unable to select which desktop to share, please raise this issue with electron. The desktopCapturer reports all your screens as on big screen if you do not see the selection dialog and get an image of all desktops afterwards.

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/wire-webapp/pull/8848
