### ISSUE TITLE
Remember when autodelete msg is checked.

### ISSUE THREAD

**Issue by Kasmetski** [wireapp/wire-desktop#233]
When I close the app, it forgot that I want to delete all my messages after some time.. It would be great if Wire remember this option and I don't need to check it after every start of the program.

**Comment by gregor** [comment]
Thanks for your message. This is definitely something we should see when to fit it into our schedule as your described behavior matches that of the mobile clients.

**Comment by gregor** [comment]
I have been bothered with this in the past as well and decided to go ahead and implement right away. Will most likely be part of a webapp release next week that is available in the desktop apps after a page reload as well.

https://github.com/wireapp/wire-webapp/pull/512

**Comment by Kasmetski** [comment]
Good to see someone is working on this. Thanks.

**Comment by gregor** [comment]
The change to store the temporary message setting for each conversation is live by now. Re-reading your initial request I am no longer sure whether this is actually what you asked for. Can you elaborate again what you wanted?

**Comment by Kasmetski** [comment]
Yes the change is working. Now after every restart of the program I don't need to click auto-delete timer again, because Wire remember it. Thank you,

**Comment by gregor** [comment]
Great - thanks for letting me know. I will go ahead and close this issue then.
