### ISSUE TITLE
"Someone sent you a message" even though they liked a message

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-desktop#234]
I'm on Ubuntu 16.10 and I've noticed that when people like one of my messages, I get a notification saying that I got a new message instead. It would be nice if it wais something like "Someone liked your message", instead of "Someone sent you a message". Thank you!

**Comment by gregor** [comment]
Receiving notifications with the content "Someone sent you a message" means that they are either ephemeral or you have disabled showing message content. I agree that we could finetune the notification. But for now all notifications get replaced with fully anonymized version in those cases.

**Comment by helenakos** [comment]
If someone likes your message you will see it in the notification (Helena <3 your message) unless you have "Hide details" set in your Preferences or you sent a Timed message. Closing this issue.
