### ISSUE TITLE
Popping noises during video call

### ISSUE THREAD

**Issue by jack-cole** [wireapp/wire-desktop#2370]
Wire version: 3.7.2917
Operating system: Windows 10
Which antivirus software do you have installed: Avast Free Antivirus+

What steps will reproduce the problem?

1.  Start video call

What is the expected result?
No popping noises

What is the actual result?
Popping noises

Please provide any additional information below. Attach a screenshot if possible.
The other person can have their Mic muted and I still hear the popping noises.

**Comment by bennyn** [comment]
Hi @jack-cole, thanks for your report. Do you hear the popping noises constantly or only when a participant joins the call?

**Comment by jack-cole** [comment]
It can occur every several seconds to not once in several hours. It seems to correlate with how much the other person is lagging.

**Comment by jack-cole** [comment]
Here is a recording of the sound: 
[popping sound wire lagging.zip](https://github.com/wireapp/wire-desktop/files/3149152/popping.sound.wire.lagging.zip)

**Comment by ffflorian** [comment]
This was fixed in the meantime.
