### ISSUE TITLE
Menu text for context menu on trayicon stays English despite different language setting

### ISSUE THREAD

**Issue by dietmarw** [wireapp/wire-desktop#245]
I changed the language of the Wiredesktop app (64bit linux) to German. Even after a restart I noticed that the menu of the tray icon is still in English despite the rest being in German:

![screenshot from 2016-12-02 18-32-13](https://cloud.githubusercontent.com/assets/9332/20844014/1dfa581c-b8be-11e6-8780-7e74c2c2a9c6.png)

**Comment by dietmarw** [comment]
I noticed this behaviour also for the other languages.

**Comment by lipis** [comment]
Nice catch.. thanks :)

**Comment by gregor** [comment]
Fix is merged to master and will be part of the next public release

**Comment by dietmarw** [comment]
I just checked and it is still not fixed in version 2.11.2685

**Comment by lipis** [comment]
we haven't released a new version yet..

**Comment by dietmarw** [comment]
Ah right, I was confused since under `/releases` there are new releases all the time and I wasn't sure what the indicator for "public" release is.
