### ISSUE TITLE
Wire doesnt start after update to 3.8.2894

### ISSUE THREAD

**Issue by asiudoisjdfo** [wireapp/wire-desktop#2486]
Wire version: Linux 3.8.2894
Wire for web version: N/A
Operating system: Ubuntu 18.04
Which antivirus software do you have installed: Clam

What steps will reproduce the problem?

1.  Start application via any means

What is the expected result?  app should start

What is the actual result?  app doesnt start - White window appears, user selector visible to the right. Cant click existing user or the "new user" grey cirle.

Please provide any additional information below. Attach a screenshot if possible.

**Comment by Fluffkin** [comment]
It was happening with an earlier version than that. I just upgraded to Wire-3.9.2895_x86_64 to try and fix it, and if anything it's worse. Before if I restarted Wire a few times it would eventually load up ok. I haven't managed that yet with the latest version.

**Comment by ffflorian** [comment]
Yes, we had a small server hiccup on the WebApp yesterday, that's why the desktop version didn't load after reinstalling. Should be resolved now. Can you confirm? @Fluffkin @asiudoisjdfo

**Comment by asiudoisjdfo** [comment]
Yerps. good work :)
