### ISSUE TITLE
[Need Information] Is the local data encrypted ?

### ISSUE THREAD

**Issue by macheta746** [wireapp/wire-desktop#2493]
According to the security whitepaper, local data is stored in IndexedDB. 
Is it encrypted while the application is not in use ? If yes, Can it be only decrypted by Wire ? Does the local data stay decrypted when the application is in use ? 
considering the threat model is another malicious application which actively scans the drive to find sensitive files.  

Sorry if it's a noob question as I'm a newbie. I searched about this but couldn't get proper info.  I'm curious to know about how wire handles local data after knowing signal desktop app stores the keys in plain text which is able to decrypt whole sqlite db file exposing all the messages. Is it the same with Wire ?

**Comment by ffflorian** [comment]
Hi @macheta746, please see https://github.com/wireapp/wire-desktop/issues/1833#issuecomment-434387638.
