### ISSUE TITLE
Feature request: alias of a contact

### ISSUE THREAD

**Issue by gkarag** [wireapp/wire-desktop#25]
The contacts in my list show with their user names and sometimes I would like to assign them some different name with which they would appear in my contact list. 

Thanks for your efforts!

**Comment by david-wire** [comment]
Hello, thanks for writing and for the suggestion. 
We did receive similar feedback from other users and we take this into consideration. We are always looking for ways to improve Wire for our users, and we appreciate your taking the time to send us your comments.

**Comment by lipis** [comment]
Will close it for now.. :)
