### ISSUE TITLE
How do I type *_* as an emoticon in Desktop Wire?

### ISSUE THREAD

**Issue by Fluffkin** [wireapp/wire-desktop#2532]
Wire version: Linux Desktop 3.9.2895
Operating system: Gentoo

What steps will reproduce the problem?

1.  Try and type `*_*` to send to a friend
2.  Get `_`
3.  Try all sorts of tricks, none of them work

What is the expected result?
`*_*`

What is the actual result?
`_`

`\*_*` used to work, but it doesn't any more.

Edit hang on ... Github markup messes this up, editing for clarity!

**Comment by Fluffkin** [comment]
I've found one way of doing it using ``` <- one of those not 3! (not ' or ")
to surround the `*_*`
But I'd still like to know if there's an easier method. Thanks.

**Comment by ffflorian** [comment]
Hi @Fluffkin, writing it as code is the easiest option right now.
