### ISSUE TITLE
Fails to start with Electron 5.x

### ISSUE THREAD

**Issue by rawlife56** [wireapp/wire-desktop#2544]
Wire version: 3.9.2895-2
Operating system: Linux (Arch-KDE)

What steps will reproduce the problem?

1. Launch wire-desktop with Electron 5.0.

What is the expected result?
Opens

What is the actual result?

```
[6010:0426/080703.047497:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/electron/chrome-sandbox is owned by root and has mode 4755.
/usr/bin/wire-desktop: line 3:  6010 Trace/breakpoint trap   (core dumped) electron "/usr/lib/wire-desktop" "$@"
```

**Comment by ffflorian** [comment]
Hi @rawlife56, there is no official version of wire-desktop for Electron 5 yet. Unfortunately we can't provide support for custom builds with other versions of Electron.

**Comment by ffflorian** [comment]
In the meantime, you can try starting the app from [our Electron 5 branch](https://github.com/wireapp/wire-desktop/tree/ffflorian/electron-5).

**Comment by ffflorian** [comment]
Btw, see https://github.com/electron/electron/issues/17972.

**Comment by maximbaz** [comment]
Electron 5 has landed in the official repos for Arch Linux, and Wire behaves weirdly when running against it. I think I can lock it down to Electron 4 for the moment, but if possible, please prioritize Electron 5 migration @ffflorian 😉

**Comment by ffflorian** [comment]
@maximbaz why is Electron 5 a high priority for Arch Linux?

Some reasons for us to not switch right now:
- electron/electron#17972 is still open
- our tests are failing and need to be rewritten completely as it seems
- Electron 5 still has [106 open issues](https://github.com/electron/electron/issues?q=is%3Aopen+is%3Aissue+label%3A5-0-x).

**Comment by maximbaz** [comment]
Thanks for the quick reply 👍 

Arch Linux simply always follows the latest stable releases, and so because v5 is marked as stable by upstream, the package got upgraded to v5.

However I can see you have some good reasons for sticking to v4 for the moment, so I've locked Wire down to `electron4` dependency, and we are back to normal 🙂

**Comment by ffflorian** [comment]
@maximbaz great, thanks for the explanation! I'll notify you if we switch to Electron 5.
