### ISSUE TITLE
[Kubuntu 19.04] Tray icon is too big and square

### ISSUE THREAD

**Issue by ntilotta** [wireapp/wire-desktop#2579]
Wire version: 3.9.2895
Operating system: Kubuntu 19.04

What is the actual result?
![](https://i.imgur.com/4KtQHyF.jpg)

Additional information:
I have installed the .deb package, I do not use the AppImage or repository.

**Comment by rawlife56** [comment]
It's an electron issue with KDE. Workaround is to launch Wire using 'XDG_CURRENT_DESKTOP=Unity' or removing libappindicator-gtk3. 
Anyways, it's fixed in Electron 5.0.

**Comment by ntilotta** [comment]
It's not Wire related, I close it.
