### ISSUE TITLE
"Production" build for Linux

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-desktop#26]
With the Wire Desktop app really coming into its own on Linux (soon it will have a tray icon! :+1:) it would be really nice if we could have a production build task with an app icon and with the title "Wire" instead of "WireInternal". Again, I know you are not officially supporting Linux, but making the app a little more polished can't hurt. EDIT: Took a shot in #27.

**Comment by lipis** [comment]
Merged in #27
