### ISSUE TITLE
voice call fails

### ISSUE THREAD

**Issue by atansa** [wireapp/wire-desktop#2604]
version = 3.9.2895 - Linux

when clicking on voice call icon to call a contact the following error occurs:

CertificateVerifyProcManager Internal Chrome TLS verification failed. Hostname: turn01.de.prod.wire.com. Verification result: net::ERR_CERT_AUTHORITY_INVALID. Error code: -202

**Comment by ffflorian** [comment]
Hi @atansa, sorry I can't reproduce your issue. Could it be a problem in your network? Did you try it with another network?

**Comment by atansa** [comment]
Hi @ffflorian 
I couldn't test this on another network however the strange thing is it works perfectly on android without any issues and used to work on linux in previous versions without this error, and nothing changed on my side same device, same network and same settings.

What does this error message actually mean?

**Comment by ffflorian** [comment]
@atansa
> What does this error message actually mean?

It means that the secure connection to our backend could not be verified. On some networks we rely on a TLS connection and it failed. We just deployed a fix for that, can you recheck?

**Comment by atansa** [comment]
@ffflorian It is fixed now thank you! I hope it stays that way in future releases.
What did you do to fix this? Does this now mean the calls are no longer e2e encrypted?

**Comment by ffflorian** [comment]
> Does this now mean the calls are no longer e2e encrypted?

No, they are always end-to-end encrypted.
