### ISSUE TITLE
Desktop Sharing Issues

### ISSUE THREAD

**Issue by fredfortier** [wireapp/wire-desktop#2629]
Wire version: 3.9.2895
Operating system: Linux 4.19.15-300.fc29.x86_64

I'd like to be able to share a specific application window instead of the whole desktop.

Not only would it be more private, but sharing the desktop doesn't always work. With Gnome 3.30 + Wayland + dual-monitor, desktop sharing from the Wire app renders a black screen. For comparison, in appear.in -- another WebRTC conferencing app which includes the two sharing options -- sharing the desktop renders the same black screen while sharing a window renders correctly.

**Comment by ffflorian** [comment]
Hi @fredfortier, this is due to the Chrome version in Electron not having the window sharing option. As soon as the Chrome version in Electron is updated, the desktop app will have this feature, too.

**Comment by fredfortier** [comment]
Is this feature available in the browser client?

**Comment by ffflorian** [comment]
@fredfortier it should be possible with Firefox, yes.

**Comment by ffflorian** [comment]
This is fixed by now.
