### ISSUE TITLE
Wire keeps asking to integrate with desktop on startup

### ISSUE THREAD

**Issue by Abnaxos** [wireapp/wire-desktop#2648]
Wire version: 3.5.2881
Wire for web version: 2019.05.16.0926
Operating system: openSUSE 15.0
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  start wire

What is the expected result?

Wire just starts.

What is the actual result?

Each and every time Wire asks whether I want to integrate it with my desktop. It's perfectly integrated with my i3 desktop, so stop asking, it's annoying. I understand that Wire doesn't know how to integrate with a handmade i3 environment, but there should be a way to suppress this question.

Please provide any additional information below. Attach a screenshot if possible.

![screenshot](https://user-images.githubusercontent.com/659778/58244665-5f87be80-7d53-11e9-94ac-a69f6acf473d.png)

**Comment by x80486** [comment]
If you are into Flatpaks you can give it a try :wink: ...you won't see anything like that anymore :rofl:

**Comment by ffflorian** [comment]
@Abnaxos sorry for the late response. This will be fixed in the next release.

Until then you can use this workaround:

> To disable — create file $HOME/.local/share/appimagekit/no_desktopintegration

(taken from https://github.com/electron-userland/electron-builder/issues/1962#issuecomment-352531262)
