### ISSUE TITLE
Missing messages until restart

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-desktop#270]
I've never had this problem in the past, but today I noticed that sometimes my Wire 2.11.2670 (.deb package) does not receive messages. My phone rings, but my desktop app doesn't do anything. If I open the conversation where the missing message should be, nothing happens. If I send a message, it gets sent/delivered correctly, but the incoming missing message still doesn't show up.
Restarting the app fixes the problem, with all the messages being displayed correctly (and in the right order).

**Comment by nidico** [comment]
I also have this issue in Wire 2.11.2685 and it currently stops me introducing Wire broadly in our team as messages need to be sent reliably to all devices.

**Comment by lipis** [comment]
Hey guys.. we might need some extra logs in order to check what is going on. In order to get them you can open the developer's console and execute: `wire.app.enable_debugging()`. After that you can get the `console.log` from `~/.config/WireInternal/`

**Comment by someoneEsle** [comment]
I don't remember if I noticed this when I posted the issue, but I seem to be affected only after I've put my computer to sleep. Missing messages doesn't happen at random times, it only seems to occur after computer resumes from sleeping. I'll get the logs if I remember.

**Comment by nidico** [comment]
> developer's console

Is there a developer console in the desktop app? I wouldn't know how to open it (F12 doesn't do it).

> I seem to be affected only after I've put my computer to sleep

I indeed also had this feeling, but I haven't verified this yet.

**Comment by ConorIA** [comment]
I can't recall 100%, but I think you can start the app with the `--devtools` flag. Also, `ctrl+alt+j` might work.

**Comment by nidico** [comment]
Neither of both seems to work for me.

**Comment by lipis** [comment]
From the Wire directory (`/opt/Wire/` on my machine) the following should work:

```
./wire --devtools
```

and you should start with the dev tools opened.

**Comment by nidico** [comment]
That's what I tried, but I don't notice any dev tools.

**Comment by nidico** [comment]
Correction: I do get the devtools if I **log out**, end wire and start with `--devtools`.

**Comment by lipis** [comment]
probably because the instance was running in the background..

**Comment by nidico** [comment]
Very likely! I didn't notice wire was still running "in the systray".

**Comment by nidico** [comment]
Btw I'm also experiencing delayed delivery in the android app (non-google), so this might be an issue on the sync / webserver server side as well. (don't know much about the wire architecture)

**Comment by lipis** [comment]
Is that still an issue?! Please report back and I'll reopen it if needed.

**Comment by someoneEsle** [comment]
It is, sorry I didn't get the logs. Workaround I've been living with when I don't get messages is
- turn off wifi
- turn on wifi
- wire starts receiving messages again

**Comment by nidico** [comment]
Yeah, I think it is still an issue, but I have no time to investigate.

I regularly hard-quit and restart wire after standby in order to make sure I receive all messages.
