### ISSUE TITLE
Re-enable hardware acceleration on Linux

### ISSUE THREAD

**Issue by schorlton** [wireapp/wire-desktop#2758]
Linux hardware acceleration was disabled due to a bug in Electron:
https://github.com/wireapp/wire-desktop-packages/pull/6

I ?think the Electron bug has now been fixed, given that the issue is closed:
https://github.com/electron/electron/issues/13415

Can we re-enable hardware acceleration in Wire for Linux?

Currently:
Wire version: 3.9.2895
Video calling uses ~100% cpu.
Electron is launched with flag `--disable-gpu-compositing` by default

Expected behaviour: Video calling uses ~30% of my cpu with other apps.

**Comment by ffflorian** [comment]
@schorlton thanks for the info! I tested it on Debian + Gnome and it works so far. We will test this a bit more and if it's fine include it in our next release.
