### ISSUE TITLE
Update without any "What's new"

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#2772]
![image](https://user-images.githubusercontent.com/388716/60521893-0bf38380-9cb6-11e9-9068-ce0478dfc6f4.png)

Last update at https://medium.com/wire-news/desktop-updates/home was on may 31st.

Is this just a backdoor update? I wish we could skip the annoying top notification.

**Comment by bennyn** [comment]
> Is this just a backdoor update?

No. The release was caused by an update of our web application which is loaded inside of our desktop application. It includes [the following changes](https://github.com/wireapp/wire-webapp/releases/tag/2019-07-02-12-29). Release notes on Medium will follow later.

**Comment by bennyn** [comment]
@Transisto Release notes are live: https://medium.com/wire-news/wire-for-web-2019-07-02-a17e2ecc98f7 — Sorry for the inconvenience. We will adjust our release process to prevent such issues in the future.
