### ISSUE TITLE
Anonymity in Wire

### ISSUE THREAD

**Issue by ElvisPresly** [wireapp/wire-desktop#278]
Hi, everybody!
Today our favourite client was updated. Wire positions itself as the private and safe client of message exchange. But with the last updates, and I will remind added the short names @nickname. The fact that cleaned from a profile the e-mail address it well and the privacy remains. But with new functions new problems are also added.
For example I can learn without effort who in contact lists from my friend. That is I see in search of friends of friends... It is clear that you want to popularize the client, but it reduces my anonymity.

How to reproduce:

to enter searching "@a" and it will be shown there is 1 general friend
then to enter "@b" and it will be shown there are 2 general friends
...
to enter "@z" and it is visible how many the general friends

Sentence:
I suggest to make a checkbox in settings, "To show your list of friends" if a tick it is worth offering friends searching if it isn't present, then to hide friends. After all it is not a social network, but the client are instantaneous messages.

Thanks for attention)

**Comment by mohammadrafigh** [comment]
completely agree. also I suggest to keep that setting false by default to save the privacy. but it's related to backend and webapp project.

**Comment by ElvisPresly** [comment]
@mohammadrafigh I need to copy it in webapp the project?

**Comment by mohammadrafigh** [comment]
no just leave it here maintainers will do it if needed :+1:

**Comment by helenakos** [comment]
Currently we display only the number of mutual connections and not the names of the connections. That is what you meant? 

Wire is undergoing a lot of changes in this aspect and will continue focusing on being the most private messenger. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by ElvisPresly** [comment]
I will continue here https://github.com/wireapp/wire/issues/32
