### ISSUE TITLE
Wire (Linux) doesn't connect when VPN is in use.

### ISSUE THREAD

**Issue by Raffles727** [wireapp/wire-desktop#2794]
Wire version:  3.9.2895
Wire for web version:  N/A
Operating system:  Ubuntu 18.04 LTS with Cinnamon
Which antivirus software do you have installed:  Sophos for Linux

What steps will reproduce the problem?

1.  ...While running Wire on a Linux system, connect to a VPN (in my case, Express VPN).
2.  ...
3.  ...

What is the expected result?

...A normal connection

What is the actual result?

...Wire says, "TRYING TO CONNECT. WIRE MAY NOT BE ABLE TO DELIVER MESSAGES."

Please provide any additional information below. Attach a screenshot if possible.

...1. Ignore the antivirus since I only installed it very recently and this problem manifested itself a while back.
2. The web version doesn't seem to be affected.
3. I use ExpressVPN for Linux, X64, on my system.

![Screenshot from 2019-07-07 22-07-10](https://user-images.githubusercontent.com/29001558/60773948-b92a2980-a104-11e9-8674-f10153585746.png)

**Comment by ffflorian** [comment]
Can't reproduce with another VPN provider on Linux. Did you try restarting?

**Comment by Raffles727** [comment]
Hi Florian,

I suspect it is ExpressVPN so I will send them the same information and see
what they say.
It also causes my flight simulator to fail to start with the following
message :
[image: Screenshot from 2019-07-07 21-35-25.png]

So it might be something to do with ExpressVPN meddling with the IPv6.
Best regards
Ralph Wigzell

**Comment by ffflorian** [comment]
@Raffles727, thanks for the feedback. Hope you can resolve the issues with your VPN provider!
