### ISSUE TITLE
Wire can't reconnect after OSX has been to sleep.

### ISSUE THREAD

**Issue by 73656e** [wireapp/wire-desktop#28]
If you put OSX to sleep for a while (until the OS goes into proper sleep mode), then wake it up, Wire is disconnected and fails to reconnect. Need to kill Wire and relaunch.

Latest Macbook with OSX El Capitan 10.11.6, latest Wire Desktop (2.10.2652)

(I'll try test some other OSX devices we have to try narrow down if it's just this version of OSX or Wire in general)

**Comment by 73656e** [comment]
Just an update after more testing.. 50% of the time (almost exactly) it will reconnect if you leave it for a solid 5-10 minutes. The other 50% you just get the green "reconnecting" bar and nothing happens. 

Something is obviously hanging/sticking though in the reconnection process. Have also confirmed it's the same on an older 20013 Macbook Air running same OSX version.

**Comment by gregor** [comment]
We have vastly improved the experience in this area and have not seen a client stuck in reconnect state for a long time. We thuse believe to have this fully fixed. Thereby closing this issue. Please report if you encounter new problems.
