### ISSUE TITLE
Battery consumption is pretty high when idling

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-desktop#280]
Don't know much about how this look on other platforms, but wire uses a lot more energy when idling compared to every other program I use.

Would be great if something could be done to address that problem.

edit: Problem only occurs when the window is actually opened, not when it's closed and wire is minimized.

**Comment by ConorIA** [comment]
This is likely related to #135.

Do you have any gifs in the conversation that Wire is idling on? That seems to use a lok of CPU cycles and thus battery.

**Comment by Sopsys** [comment]
Any gifs in the backlog definitely shoots up CPU usage. A feature to turn them off completely would be nice - I don't need nor want them.

**Comment by DragonzMaster** [comment]
#120

**Comment by rbieb** [comment]
This issue is not related to gifs. I have no gifs in my conversations, yet still quite high battery drain.

**Comment by silvether** [comment]
Could it be some of the Java code?

**Comment by herrmannplatz** [comment]
I will close this one. Lets move the discussion to #135
