### ISSUE TITLE
Group messages created in wire-webapp not visible in wire-desktop

### ISSUE THREAD

**Issue by supersexy** [wireapp/wire-desktop#2804]
Account type: Personal
I created messages in wire web-app via https://app.wire.com.
Because of an [issue adding users to a group](https://github.com/wireapp/wire-webapp/issues/6900) in the web-app I installed wire-desktop. 

The desktop app after login with the same user does not show the messages already posted to the group:

![Screenshot_2019-07-08_16-38-02](https://user-images.githubusercontent.com/11744844/60819151-65205300-a19f-11e9-98ab-a90975c2cf30.png)

**Comment by supersexy** [comment]
I just double checked this with another user, that is a participant in the same group. 
If the user-b logs out, then a message is posted to the group by another user-a, then user-b logs in again, the message posted by user-a is not visible to user-b. 
This looks like a bug to me, as it is very limiting the groups feature.
If messages are not persisted across logins, that should be mentioned somewhere.
Is persisting messages available in the paid account types?
If persistent group messages are not available in the personal account type only, this should be mentioned somewhere clearly.

**Comment by Astrid-Wire** [comment]
To protect your privacy, messages are only stored on your devices. This means that only new messages, not conversation history, will be displayed after you uninstall/install Wire, or start using Wire on a new device.

**Comment by ffflorian** [comment]
Closing as "as designed".
