### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by barkingbandicoot** [wireapp/wire-desktop#2834]
Wire version: Appimage 3.9.2895

Operating system: Linux - Kubuntu 19.04
Which antivirus software do you have installed: 

What steps will reproduce the problem?

1.  ...open app
2.  ...no messages or contacts
3.  ...close app

What is the expected result?
open to contacts and messages

...

What is the actual result?
blank screen
It was working - now no longer
...

deb version works

...

**Comment by fermulator** [comment]
similar to https://github.com/wireapp/wire-desktop/issues/2114 ?

**Comment by ffflorian** [comment]
Hi @barkingbandicoot, sorry for the late response. Does the issue still exist for you? And if yes, are you using a proxy or a VPN?

**Comment by barkingbandicoot** [comment]
> Hi @barkingbandicoot, sorry for the late response. Does the issue still exist for you? And if yes, are you using a proxy or a VPN?

Contacts and messages are loading now.
I cannot say if the app is working though.
Thanks for the follow up.
I will close the issue report.
