### ISSUE TITLE
Compact view to conversation list and chats

### ISSUE THREAD

**Issue by Sopsys** [wireapp/wire-desktop#285]
I would prefer a more compact view with a smaller font to chats and the conversation/contact list, so I could use a smaller window and save some screen estate for other things.

I'd also prefer the conversations to have a little more contrast - maybe a text color setting too, so I could set it to #000000 instead of that #333333 or something it currently is.

These would be nice customization settings. The default theme needs not to be changed.

**Comment by Simplenuity** [comment]
There is a reason so many other messenger apps, and even the good old SMS applications use the "bubble" approach. Easy to distinguish and quite compact.

**Comment by Sopsys** [comment]
Bubble approach is fine. What I don't like is the requirement to keep the window size to occupy at least half of my screen just to have some backlog visible and conversations wider than a few centimeters.

**Comment by helenakos** [comment]
Thanks for your request and comments. Unfortunately we don't have immediate plans to implement this, it is a very resourceful task and we are currently working on other priorities. Similar discussion was held here for a more compact Wire app: https://github.com/wireapp/wire-webapp/pull/543 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
