### ISSUE TITLE
Moving the mouse over conversations uses a LOT of CPU

### ISSUE THREAD

**Issue by Sopsys** [wireapp/wire-desktop#286]
Just by moving your mouse over any conversation uses a lot of CPU. Increased CPU usage when moving the mouse over them is normal for any program, but for example with Firefox, Chrome and Skype it's under 5% vs. 20% with Wire, so I presume there are some CPU heavy onmousemove or onhover hooks.

![a](https://cloud.githubusercontent.com/assets/721951/21430914/86651a8e-c865-11e6-88d2-1e953a41fa64.png)

Cpu is a quite powerful i7-6700HQ paired with enough memory. OS Windows 10 Enterprise 2016 LTSB N.
![untitled](https://cloud.githubusercontent.com/assets/721951/21431000/d75eacca-c865-11e6-8996-5a01812f4603.png)

**Comment by timur-davletshin** [comment]
Yep, that's true. It's also especially heavy if you have very long conversation opened.

**Comment by lipis** [comment]
I will close this in favour of #135 to keep a better track of CPU issues, so please subscribe/vote the other one if you want to keep following it. Thank you.
