### ISSUE TITLE
Images load but do not show

### ISSUE THREAD

**Issue by jestarray** [wireapp/wire-desktop#2864]
Wire version: 3.9.2895
Wire for web version: 2019.07.11.1318
Operating system: Arch Linux
Which antivirus software do you have installed: None

**What steps will reproduce the problem?**

Recently images have been loaded and sent but not displaying. I've sent the wikipedia https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/200px-Wikipedia-logo-v2-en.svg.png to a friend and this is what happened.

![bug](https://user-images.githubusercontent.com/34615798/61504968-25711c80-a992-11e9-8a0d-5808279b54c0.png)

He has the same issue on Windows 10, latest version of Wire, no antivirus. This problem does not occur on mobile.

**Comment by ffflorian** [comment]
Hi @jestarray, I can't reproduce this. Maybe there was a hiccup with your internet connection or with the assets server.

![Screenshot from 2019-07-19 09-51-02](https://user-images.githubusercontent.com/5497598/61518810-c13e6f00-aa0a-11e9-86c9-9e8b37c2c224.png)

**Comment by selurvedu** [comment]
@ffflorian, same problem here. It works fine in a web browser, so this is unlikely due to issues with the internet connection.

@jestarray, I noticed that you use Arch. I'm seeing these gray rectangles on Manjaro as well, so this might be a packaging issue. CC @maximbaz

**Comment by maximbaz** [comment]
I've heard one other person mentioning this exact issue to me, I'm wondering if the root cause is the same as in https://github.com/wireapp/wire-desktop/issues/2833#issuecomment-511519878, Manjaro not synchronizing Arch repos properly and therefore causing a [partial upgrade](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported) for you.

That person has shared with me the following _less than ideal_ workaround, but it worked for him:

- Backup data and close Wire
- `rm -rf ~/.config/Wire`
- Restart Wire and restore from backup

**Comment by selurvedu** [comment]
> _UPDATE_: I didn't notice at first the quote below from the first message, this kinda implies that the issue is not with Arch or a single package...

Oh sh-, me too. Sorry for the noise.

**Comment by dklann** [comment]
I experienced this condition as well. Backing up conversations, removing *~/.config/Wire* and then restoring the conversations corrected it for me. Thanks for the tips!

**Comment by verbal007** [comment]
Same problem here under Manjaro/Arch linux.

I forgot to backup my conversations, but the deletion of the ~./config folder brought things back to normal.

**Comment by selurvedu** [comment]
Fixed it!

I ran `wire-desktop --enable-logging` in console hoping to find some helpful info there. There were two messages that looked promising:

```
[8890:0819/154501.079960:ERROR:simple_backend_impl.cc(711)] Simple Cache Backend: wrong file structure on disk: /home/user/.config/Wire/Service Worker/CacheStorage/0123456789abcdef0123456789abcdef01234567/01234567-89ab-cdef-0123-456789abcdef
[8890:0819/154501.080102:ERROR:disk_cache.cc(168)] Unable to create cache
```

I quit Wire and ran this:

```
cd ~/.config/Wire/Service\ Worker/
mv CacheStorage CacheStorage_backup
```
After starting Wire again, I saw that images are working normally at last.

**Comment by ffflorian** [comment]
@selurvedu that's helpful, thanks and glad you got it fixed!
