### ISSUE TITLE
Request: Password lock to open the application

### ISSUE THREAD

**Issue by pathetiq** [wireapp/wire-desktop#287]
Hi,

A password lock when opening the application on the phone and a password timeout would add another level of security and would be really appreciate by many people I am sure. 

Great app keep it up!

Thanks

**Comment by ConorIA** [comment]
See here as well https://github.com/wireapp/wire-android/issues/289.

**Comment by gregor** [comment]
@pathetiq Thank you very much for your feature request. We will continue to track this internally but close the public issue as we do some housekeeping as we want to keep the public issues for bugs and problems our users have.

**Comment by udf2457** [comment]
Has there been any progress on this @gregor ? Its been three years and the ability to adequately secure a logged-in wire on the desktop is missing ?   Passwords, touch-id on MacBook ... we really need this functionality !

**Comment by gregor** [comment]
@udf2457 I have parted ways with Wire 16 months ago. I don't know what's going on anymore and what's the state of the feature roadmap.
