### ISSUE TITLE
App tries to load non-existing notification image

### ISSUE THREAD

**Issue by nidico** [wireapp/wire-desktop#288]
While debugging #270, I stumbled upon a few 404s in the console:

    GET https://app.wire.com/opt/Wire/resources/app.asar/img/notification.png 404 (NOT FOUND)

**Comment by lipis** [comment]
We'll have to investigate but this might have been fixed here: https://github.com/wireapp/wire-webapp/pull/588 which will be part of our next release.

**Comment by gregor** [comment]
We believe to have this fixed with the latest notification changes. Please file a new issue if you run into problems again.
