### ISSUE TITLE
[Desktop] Allow the desktop app to be used without the need to provide an email address and a password

### ISSUE THREAD

**Issue by devdan** [wireapp/wire-desktop#2893]
If you have installed Wire via phone, you already have an account registered with your number. It should not be necessary to provide more information such as an email address or password. 

Implement linking between phone and desktop via QR code as seen in Signal and  WhatsApp.

**Comment by ArchiveBase** [comment]
Just add a comment @tokariu✌️ If wire implement that someday you guys can fulfill everyone needs like this

![67516052-1ead2080-f6ca-11e9-8d15-e225f309131e](https://user-images.githubusercontent.com/46082456/67516156-55833680-f6ca-11e9-90e6-d90ce7e58fdf.png)

Sign-in using

- Username and Password (already)
- Email and Password (already)
- Phone number and Password (already)
- QR code (these users looking for have)
- Without password (consider)
  (How it works? Just user enter phone number or email then click sign in without password and it send login request to mobile app. after that, user need tap approve)

**Comment by KizunaH** [comment]
> Without password (consider)

That feature has on telegram. client applications are opensource. it send login code to already signed devices (mobile or other desktop device) https://github.com/TelegramOrg

>QR code (these users looking for have) - Discord

![Screenshot from 2020-08-21 15-22-03](https://user-images.githubusercontent.com/63988538/90869316-3f193a80-e3c2-11ea-8d27-3ee633542329.png)
