### ISSUE TITLE
Local grunt not found (build issue)

### ISSUE THREAD

**Issue by chazanov** [wireapp/wire-desktop#2896]
Wire version: 3.9.2895 (not installed, to be built)
Wire for web version: /
Operating system: ArchLinux
Which antivirus software do you have installed: /

What steps will reproduce the problem?

1.  Build wire-desktop with ArchLinux's [vanilla build script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/wire-desktop)

What is the expected result?

builds fine

What is the actual result?

fails after successful yarn job
```
ℹ️  @wireapp/copy-config/cli Copied 79 files.
Done in 2.65s.
yarn run v1.17.3
$ electron-rebuild -f -w @wireapp/node-addressbook
✔ Rebuild Complete
Done in 0.62s.
Done in 4.31s.
yarn run v1.17.3
$ yarn clear:ts && tsc
$ rimraf electron/dist
Done in 5.53s.

grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

[..]
```

**Comment by ffflorian** [comment]
@chazanov The build script is written for the [master](https://github.com/wireapp/wire-desktop/tree/master) branch. If you want to build the [master](https://github.com/wireapp/wire-desktop/tree/staging) branch, you can't use the script.

**Comment by chazanov** [comment]
@ffflorian How may I build staging? Actually I've tried to work with https://github.com/wireapp/wire-desktop/tree/ffflorian/electron-5

**Comment by ffflorian** [comment]
@chazanov please see https://github.com/wireapp/wire-desktop/blob/staging/README.md#tasks

**Comment by chazanov** [comment]
@ffflorian Sorry for bothering, but do you know why the server team is ignoring my issue at https://github.com/wireapp/wire-server/issues/810 ?

**Comment by fisx** [comment]
> @ffflorian Sorry for bothering, but do you know why the server team is ignoring my issue at [wireapp/wire-server#810](https://github.com/wireapp/wire-server/issues/810) ?

I'm sorry the backend team has failed to meet your expectations.  But if you want to continue enjoying free developer support, please stop causing noise in teams that have nothing to do with your problem.
