### ISSUE TITLE
Wire on App store doesn't update.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#29]
After running the update - Wire doesn't restart and if i do a manual restart of the App, it's still the previous version (2.9) and not 2.10.

**Comment by helenakos** [comment]
Hey @tmikaeld, can you give us more details on the issue? The app updated and shows 2.10 in the AppStore but the app itself is 2.9?

**Comment by tmikaeld** [comment]
Correct.

![image](https://cloud.githubusercontent.com/assets/907195/18267716/bde857b2-7420-11e6-8cb8-de3175acbb33.png)

**Comment by david-wire** [comment]
OK. What if you sign out/sign back in on the App Store, try to update again. Does it make a difference?
If not, please contact us here and we will follow up: https://support.wire.com/hc/en-us/requests/new

**Comment by helenakos** [comment]
👍 @tmikaeld
