### ISSUE TITLE
weird "no microphone" problem

### ISSUE THREAD

**Issue by kolAflash** [wireapp/wire-desktop#2900]
Wire version: 3.9.2895 (2019.07.11.1318 - manually extracted Wire-3.9.2895_amd64.deb)
Operating system: Linux (openSUSE-15.1)

What steps will reproduce the problem?
1. Run Wire on PC with integrated soundcard and a graphiccard which shows up as HDMI audio output
2. make a Wire call via intergrated soundcard
3. Attach additional external USB soundcard
4. Use "pavucontrol" (Pulseaudio) to make Wire calls trough the external soundcard
5. remove external soundcard
6. make a Wire call

What is the expected result?
Call via internal soundcard works.

What is the actual result?
Wire says, my PC has no microphone and no camera, and so I can't start a call.

In the Audio/Video settings, the Microphone section only appears if the USB soundcard is attached. I see that the external soundcard is selected, but I can't change it. I can only click `Enable from your browser Preferences`, which openes "https://support.wire.com/hc/en-us/articles/213512545" in my default browser (Firefox).

Workaround: Use https://app.wire.com in Firefox. **(same problem in Chromium)**

I tried something similar with "Skype for Linux". But because Skype lets me make a call knowing which microphone to use, I can start the call and use "pavucontrol" to set which soundcard to use. So it's not a problem for Skype.

- Tried:
  - deleting ~/.config/wire and logging in again
    - works while first run - stops working after restarting the app
  - `pulseaudio -k; rm -r ~/.config/pulse ~/config/pavucontrol.ini`
    - doesn't help

- Maybe related:
  - #806 [Lesser issue] Wrong warning/error message
  - #1616 Microphone issue (USB with headset)
  - #2901 enable "calls" without microphone / soundcard or webcam (e.g for screensharing and debugging)

**Comment by ffflorian** [comment]
@kolAflash can you please visit https://test.webrtc.org/ in Chrome (not Chromium), start the test and post the result here?

**Comment by kolAflash** [comment]
Tested in Chrome-74.

```Welcome to WebRTC Troubleshooter
Failed to access your computer's camera and microphone (TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': At least one of audio and video must be requested).
"FILE A BUG"    "CONTINUE WITHOUT AUDIO/OR VIDEO"```

Selected "CONTINUE... -> START".

```Microphone NO
Audio capture NO

Camera NO
Check resolution 320x240 NO
Check resolution 640x480 NO
Check resolution 1280x720 NO
Check supported resolutions NO

Network YES
Connectivity YES

Throughput NO
Data throughput NO
Video bandwidth NO```


If tested in Firefox-68, Microphone gets a YES.

**Comment by ffflorian** [comment]
@kolAflash that means Chrome doesn't recognize your camera. And if Chrome doesn't recognize it, Wire also can't use it, sorry.
