### ISSUE TITLE
enable "calls" without microphone / soundcard or webcam (e.g for screensharing and debugging)

### ISSUE THREAD

**Issue by kolAflash** [wireapp/wire-desktop#2901]
Please enable "calling" without a microphone/soundcard or webcam. This will be useful:
- for screensharing
- for debugging - see #2900 weird "no microphone" problem

Currently the app won't allow to call without a working soundcard or webcam.

**Comment by ffflorian** [comment]
Duplicate of https://github.com/wireapp/wire-webapp/issues/7018
