### ISSUE TITLE
[Desktop] Conflicting packages from another installed program

### ISSUE THREAD

**Issue by rottenwheel** [wireapp/wire-desktop#2938]
Wire version: 3.10.0.
Wire for web version: N/A.
Operating system: Fedora 29.
Which antivirus software do you have installed: GNU/Linux?

What steps will reproduce the problem?

1. Follow experimental step-by-step guide provided by Wire at: https://github.com/wireapp/wire-desktop.
2. export LINUX_TARGET=rpm
yarn build:linux
3. Try to install such .rpm file recently compiled via dnf and...

What is the expected result?
For it to install successfully...

What is the actual result?
Conflicted packages with another program (Signal). Currently running unofficial releases because Signal does not support Fedora officially as of yet. See: https://github.com/drahnr/signal-desktop-rpm. Also, since the initial guy ran into some dependencies problems I started simply grabbing the .rpm from https://github.com/drahnr/signal-desktop-rpm/releases and manually installing the builds via dnf.

Please provide any additional information below. Attach a screenshot if possible.

Output when running sudo dnf install Wire-3.10.0-7b2ba7d_x86_64.rpm is as follows:

```Running transaction test
Error: Transaction check error:
  file /usr/lib/.build-id/23/0a1cc6287c539684f850259f8a2b8b4e9d7a55 from install of wire-desktop-3.10.0_7b2ba7d-1.x86_64 conflicts with file from package signal-desktop-1.25.1-0.fc29.x86_64
  file /usr/lib/.build-id/8c/d139bfd975615e5db1fb708025081e049bd2fb from install of wire-desktop-3.10.0_7b2ba7d-1.x86_64 conflicts with file from package signal-desktop-1.25.1-0.fc29.x86_64
  file /usr/lib/.build-id/8f/72e2e94969745fdd95ac2943fb04ce28a0f880 from install of wire-desktop-3.10.0_7b2ba7d-1.x86_64 conflicts with file from package signal-desktop-1.25.1-0.fc29.x86_64
  file /usr/lib/.build-id/9b/4fc63f21fdad54c6180de0bcc28f91b1f0530e from install of wire-desktop-3.10.0_7b2ba7d-1.x86_64 conflicts with file from package signal-desktop-1.25.1-0.fc29.x86_64

Error Summary
-------------
```

Is there a chance I could possibly hack this in order for me to use both Signal and Wire while on desktop or I must decide between the two? Thanks in advance...

**Comment by ffflorian** [comment]
Hi @rottenwheel, please refer to https://access.redhat.com/solutions/158883.

As this is not a Wire issue but rather an issue with your setup I am going to close this one.
