### ISSUE TITLE
Send by Ctrl+Enter, new line by Enter 

### ISSUE THREAD

**Issue by h4tr3d** [wireapp/wire-desktop#294]
Hi, most of IM allows to configure sending by Ctrl+Enter and use enter for new line. Skype too (except web one).

Could you please add such settings too?

**Comment by lipis** [comment]
We'll see what we can do :) But until then.. it works with `Shift+Enter` and `Alt+Enter`..

**Comment by h4tr3d** [comment]
@lipis, I know about new line Shift+Enter :-) But in some cases (short code snippets or long messages) it is uncomfortable to hit Shift/Alt before Enter.

**Comment by BennySamir** [comment]
Most of the time the user send short messages, so only enter to submit the message is the best soultion. For line-breaks use shift-enter.

**Comment by h4tr3d** [comment]
I known! Simple add setting for that. Like Skype and other IMs (Psi+ and some other)

**Comment by tmikaeld** [comment]
Default should always be Enter to send a message, Shift+Enter for new line.

This is due to this being the default on 99% of WYSIWYG editors.

I'm all for a new option though to enable power users better.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
