### ISSUE TITLE
Copy context menu has no effect

### ISSUE THREAD

**Issue by Nateowami** [wireapp/wire-desktop#296]
On Ubuntu 16.04 with Wire 2.11.2670, if you right click a message there is a context menu with the single option "Copy." Presumably this is intended to copy the message. However, there is no change to the text on the clipboard.

**Comment by maximbaz** [comment]
It's not a Linux-related bug, it's just a functionality that was never implemented, on any platform :wink: 

I made a pull request with the implementation #318.

**Comment by Nateowami** [comment]
Thanks. Looking forward to seeing this working.

:+!:
