### ISSUE TITLE
[Windows] login loop

### ISSUE THREAD

**Issue by miicha** [wireapp/wire-desktop#2967]
Wire version: 3.10.3138
Wire for web version: 2019.08.21.1333
Operating system: Windows 10
Which antivirus software do you have installed: Defender

What steps will reproduce the problem?

1.  Update from previous Wire version
2.  Restart Wire

What is the expected result?

Wire should be logged in with both existing accounts

What is the actual result?

One account is logged in, the other not.
If I try to log in the progress bar shows fetching something, fetching events and I am back at the log in screen...

Please provide any additional information below. Attach a screenshot if possible.

[console.log](https://github.com/wireapp/wire-desktop/files/3526279/console.log)

**Comment by miicha** [comment]
#2968 is the same problem...
I got the same problem now without clicking the update button but simply restarting Wire.
This one is a major bummer

**Comment by ffflorian** [comment]
@miicha what do you mean by "Update from previous Wire version"? Did you click the "update now" button in Wire or did you install the latest version?

**Comment by pfitzseb** [comment]
I'm running into a similar problem on Windows after using the "Update Now" button inside of Wire, but I'm redirected to the login screen at the "Checking for new messages" step.

Let me know if I can provide any debug info.

**Comment by miicha** [comment]
@ffflorian on one PC I actually click the update button inside Wire, on another PC I just restarted Wire without clicking anything.

**What I tried so far**
- On the first PC (Wire with two accounts and one still working) I installed the previous version of Wire (from github releases) and got the same problem...
- installed 3.7.2917, same problem
- installed newest version, same problem
- renamed %appdata%\Wire, login possible, but as new device without any chat history

@ffflorian what is the minimal data in %appdata%\Wire to log in as existing device and get the chat history back?

**Comment by ffflorian** [comment]
@miicha thanks for the details.

@miicha @pfitzseb Can you please zip the `%APPDATA%\Wire\logs\` dir and post it here or send it so support@wire.com?

**Comment by pfitzseb** [comment]
Logs are empty for me: [logs.zip](https://github.com/wireapp/wire-desktop/files/3529007/logs.zip)

An additional data point: If I rename of `%APPDATA%\Wire\logs\` and restart Wire, I end up in the same login loop. Logs are still empty afterwards.

**Comment by bennyn** [comment]
@miicha Thanks for writing us. We have the guess that a bug slipped through in our [latest webapp release](https://github.com/wireapp/wire-webapp/releases/tag/2019-08-21-production.0). To verify that we need to get webapp log files from people that are affected. You can [enable debugging](https://github.com/wireapp/wire-desktop/wiki/Debugging) for our webapp by starting the Wire desktop application with `--devtools --enable-logging`:

![image](https://user-images.githubusercontent.com/469989/63499321-ea4d9600-c4c7-11e9-95af-171186177da8.png)

If you do that, a "Developer Tools" panel will show up from which you can click "Save as..." to save logs written to that window:

![image](https://user-images.githubusercontent.com/469989/63499492-3ef11100-c4c8-11e9-8e2e-8e645b8e386c.png)

Do you have the problem on both of your computers?

**Comment by miicha** [comment]
@bennyn Now I got the problem on all 3 Computers but only with one account...
The console log doesnt seem to be very helpful
console log just after starting Wire
[-1566463184659.log](https://github.com/wireapp/wire-desktop/files/3529152/-1566463184659.log)
and after failed login:
[-1566463365641.log](https://github.com/wireapp/wire-desktop/files/3529154/-1566463365641.log)

**Comment by pfitzseb** [comment]
Neither the terminal nor the devtools output seems terribly helpful:
[wire_logs.zip](https://github.com/wireapp/wire-desktop/files/3529162/wire_logs.zip)

**Comment by tonirug** [comment]
I have the same problem on wire-desktop Linux. Tried the Debian, Ubuntu PPA, flatpak and appimage versions. All have the same problem. 
The only versions working for my account are the browser web app and the Android app.
[-1566466244415.log](https://github.com/wireapp/wire-desktop/files/3529390/-1566466244415.log)

**Comment by bennyn** [comment]
Thank you all for taking the time helping us with the login loop issue. We are very thankful for your reports and it helps us to narrow down the problem. At the moment we think that some local client data might be invalid. 

To debug further we need information about the JSON payload of your local clients. If you don't mind then please send us a screenshot of your "local_client" from the "clients" table of your IndexedDB.

It should look like this:

![vlcsnap-2019-08-22-11h46m12s347](https://user-images.githubusercontent.com/469989/63504788-8bd9e500-c4d2-11e9-914c-56b922d83c56.png)

You can get this information the following way:

1. Open Windows Explorer
1. Navigate to `%LOCALAPPDATA%`
1. Navigate to `wire\app-[latest-version]`
1. Create a shortcut for `Wire.exe`
1. Open properties of the shortcut
1. Append `--devtools --enable-debugging` to the shortcut's target
1. Start the shortcut ("Chrome Developer Tools" plus "Wire" will open)
1. Open the "Elements" tab within the Developer Tools
1. Select the `<webview>` HTML tag of your account (you may have multiple)
1. Open the "Console" tab within the Developer Tools
1. Enable "Preserve log" to keep console log statements
1. Run `$0.openDevTools()` from the "Console" ("Chrome Developer Tools" for our webapp will open)
1. Open the "Application" tab
1. Select "IndexedDB"
1. Select the database name of your active account (`wire@production@...`)
1. Select "clients" table
1. Search for key "local_identity"

We know that getting this information requires some steps. That's why we just recorded a video tutorial: 
[Enable Debugging in Wire Desktop Application.zip](https://github.com/wireapp/wire-desktop/files/3529471/Enable.Debugging.in.Wire.Desktop.Application.zip)

**Comment by pfitzseb** [comment]
![grafik](https://user-images.githubusercontent.com/6735977/63506228-5f739800-c4d5-11e9-9fe4-f8059ca2fe3f.png)

**Comment by miicha** [comment]
![Wire local_identity](https://user-images.githubusercontent.com/3731697/63506299-8a5dec00-c4d5-11e9-861c-d30032d02c26.jpg)

**Comment by pfitzseb** [comment]
The webview devtools also spit out a couple errors that might be relevant:

![grafik](https://user-images.githubusercontent.com/6735977/63506540-022c1680-c4d6-11e9-8c3e-42fa9e9f10ac.png)

**Comment by miicha** [comment]
Great, I finally also found some errors...
![Wire errors](https://user-images.githubusercontent.com/3731697/63506681-461f1b80-c4d6-11e9-8f55-ec1dfdf2e52c.jpg)

**Comment by tonirug** [comment]
![Schermata a 2019-08-22 12-14-27](https://user-images.githubusercontent.com/19492480/63506824-a0b87780-c4d6-11e9-9b1c-075be763212f.png)

local_identity

**Comment by bennyn** [comment]
Thanks for sending in your identities. We now have enough sample data for the identities.

Next thing we will focus on is the `readAsDataUrl` error. To the ones who have it, can you please click on the `at Promise (/min/app.js?...)` link to see if you can get a more detailed stracktrace? And is the affected account part of a team in Wire?

**Comment by miicha** [comment]
![grafik](https://user-images.githubusercontent.com/3731697/63507737-b62ea100-c4d8-11e9-9719-5baead099674.png)
do you mean that one?
and no, its a "normal" account

**Comment by pfitzseb** [comment]
Full stacktrace:
![grafik](https://user-images.githubusercontent.com/6735977/63507699-9a2aff80-c4d8-11e9-848f-c98496e5fd31.png)

And no, my account is not part of any team (as far as I'm aware).

**Comment by tonirug** [comment]
My account is not a team account. I get a different error. See  the attached stacktrace.
[app.wire.com-1566469753758.log](https://github.com/wireapp/wire-desktop/files/3529666/app.wire.com-1566469753758.log)

**Comment by pfitzseb** [comment]
Breaking on uncaught exception produces something more useful:
![grafik](https://user-images.githubusercontent.com/6735977/63508325-078b6000-c4da-11e9-8e58-63894f3fe878.png)
![grafik](https://user-images.githubusercontent.com/6735977/63508909-38b86000-c4db-11e9-93ec-9eda7fa18f65.png)

Couldn't figure out how to acces those local variables, but ¯\\_(ツ)\_/¯

**Comment by miicha** [comment]
after cleaning console and another login attempt I get the following:
![grafik](https://user-images.githubusercontent.com/3731697/63511384-5be60e00-c4e1-11e9-93b6-8aaf9684d7be.png)

**Comment by ffflorian** [comment]
@miicha @tonirug @pfitzseb
Thank you very much for your debugging help!

We just deployed a [hotfix](https://github.com/wireapp/wire-webapp/releases/tag/2019-08-22-production.0), can you please restart Wire for Desktop and check if you can log in now?

**Comment by tonirug** [comment]
Login OK on both Windows and Linux!
Thanks a lot

**Comment by miicha** [comment]
great work
login fixed on all 3 Windows machines

**Comment by bennyn** [comment]
Whoop! Whoop! Thanks everyone for your significant help. @miicha @tonirug @pfitzseb we would like to name your handles in our release notes to credit you. Are you okay with that?

**Comment by tonirug** [comment]
ok for me

**Comment by pfitzseb** [comment]
> We just deployed a hotfix, can you please restart Wire for Desktop and check if you can log in now?

Works. Thanks for the quick fix!

> Are you okay with that?

Sure.

**Comment by miicha** [comment]
yes sure

**Comment by ffflorian** [comment]
@miicha @tonirug @pfitzseb

Now it would be great to get your logs one more time, since we are now catching and logging the error which prevented you from logging in.

**Comment by tonirug** [comment]
Here the log from the Linux box:
![immagine](https://user-images.githubusercontent.com/19492480/63514087-1711a580-c4e8-11e9-85ce-aaf9a05f209d.png)

**Comment by miicha** [comment]
which ones do you mean? %appdata%\wire\logs contains nothing new...
and I got these:
![wire hotfix (1)](https://user-images.githubusercontent.com/3731697/63514138-33154700-c4e8-11e9-998e-619f0d8f2563.jpg)
![wire hotfix (2)](https://user-images.githubusercontent.com/3731697/63514143-37416480-c4e8-11e9-868d-218ec33b5769.jpg)

**Comment by pfitzseb** [comment]
![grafik](https://user-images.githubusercontent.com/6735977/63514438-e41be180-c4e8-11e9-8545-bd1de1055153.png)
![grafik](https://user-images.githubusercontent.com/6735977/63514475-fc8bfc00-c4e8-11e9-9eb8-a8d0c95ef305.png)

**Comment by ffflorian** [comment]
Thanks, that was helpful :slightly_smiling_face:
