### ISSUE TITLE
macOS 10.15 alerts on launch about “.EDF3JCE8BC.com.wearezeta.zclient.mac.vIGaLP”

### ISSUE THREAD

**Issue by antons** [wireapp/wire-desktop#2969]
Wire version: 3.8.2940
Wire for web version: 2019.07.11.1318
Operating system: 10.15 Beta (19A536g)
Which antivirus software do you have installed: None

What steps will reproduce the problem?

Launch Wire on macOS 10.15.

What is the expected result?

App launches.

What is the actual result?

When the progress bar “Almost done - Enjoy Wire” macOS pops up an [alert](https://user-images.githubusercontent.com/129705/63487944-caad7200-c4b5-11e9-9fa9-c7dc59e7def8.png): “.EDF3JCE8BC.com.wearezeta.zclient.mac.vIGaLP” can’t be opened because its integrity cannot be verified. This software needs to be updated. Contact the developer for more information. 

When I click Cancel in the alert Wire finishes launching and appears to work normally.

**Comment by ffflorian** [comment]
@antons and does it work with the latest version of Wire for macOS (3.10.3133)?

**Comment by ffflorian** [comment]
This is probably due to macOS 10.15 [requiring apps to be notarized](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution):

> Beginning in macOS 10.15, notarization is required by default for all software.

**Comment by antons** [comment]
@ffflorian I get the same message in Version 3.10.3133. Notarization is only for apps distributed directly to customers and signed with Developer ID, not for Mac App Store.

**Comment by antons** [comment]
It appears that on every launch Wire creates and attempts to launch an unsigned binary with a randomized name. I clicked “Move to Trash” a few times, and got a [new copy every time](https://user-images.githubusercontent.com/129705/63599579-924b8800-c5ca-11e9-9187-e86e630e7c28.png). The binary appears to contain [code for accessing macOS address book](https://user-images.githubusercontent.com/129705/63599722-cfb01580-c5ca-11e9-82d4-a40b75b33430.png).

**Comment by ffflorian** [comment]
@antons Thanks, that's helpful! We'll have too look into signing this.

**Comment by ffflorian** [comment]
Hi @antons, this will be fixed with the next release.

**Comment by antons** [comment]
@ffflorian Happy to hear this! Thank you.

**Comment by ffflorian** [comment]
This was fixed with [version 3.10.3215](https://github.com/wireapp/wire-desktop/releases/tag/macos%2F3.10.3215).
