### ISSUE TITLE
Non-App Store macOS distribution

### ISSUE THREAD

**Issue by bensleveritt** [wireapp/wire-desktop#297]
I'd like to distribute Wire by `brew cask`. Is this possible to do without codesigning? Are there any implications of using the internal build?

**Comment by lipis** [comment]
I'm not sure if that's a good idea for a secure messaging app to distribute it without the code signing. But there were some requests on distributing the app not only the App Store, so we'll take another look, although it's not in our current timeline.

**Comment by bensleveritt** [comment]
That's a valid point. A non-App Store version would be appreciated, just a binary kept somewhere secure would be sufficient.

**Comment by lipis** [comment]
One issue with it is the autoupdate.. we will have to handle that ourselves. I'll keep this issue open so we could track it. Thank you.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by r0bbie** [comment]
Sorry to comment on a closed issue - but just adding that I would also be really keen to have a way to download/update the app which isn't dependent on the App Store.
