### ISSUE TITLE
Feature request: Small/tiny sidebar with icons.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#30]
Similar to what Facebook Messenger and Skype has, where you can have a large chat area and only icons for the contacts on the left side.

That's basically what you get when you click "contacts" at the bottom left, but then when you open a contact the icons becomes name texts instead.

I'm sure not everyone agrees with these, so it should be optional.
Shouldn't be too hard to make the side-bar resizable?

**Comment by helenakos** [comment]
Hey @tmikaeld, thanks for the feedback, keep it coming! Sounds like an interesting idea, I've forwarded it to our design team to have in mind for the future.

**Comment by ruuter** [comment]
@helenakos any chance this gets done in near future?

It does not have to be resizeable per se. Simple open/close would be sufficient.
Toggling sidebar to have full window for chat itself seems like a common need.

**Comment by omarkohl** [comment]
Making the "list of conversations" area a lot smaller or closing it completely to have more space for the chat itself would be very helpful! It takes up too much space when placing windows side by side and works better in other Apps such as Slack or Skype.
