### ISSUE TITLE
Clipboard content not pasted when using menu

### ISSUE THREAD

**Issue by macexpertsusa** [wireapp/wire-desktop#3012]
on desktop version of wire with 2 or more accounts functional

if you switch to the 2nd account or 3rd account
click on a contact
right click (mouse) to paste clipboard contents nothing appears

if you control V (pasted) the clipboard contents will appear but nothing appears when right click is invoked (though it seems like it pasted you don't see anything)

click on 1st login/account then click last contact

the contents of the clip are found posted in the typing field (from when you right clicked by mouse previously on the other contact in the 2nd/3rd account and it didn't appear there as intended)

so wire is pasting the clipboard contents when you 'right-click' but into the 1st accounts/last used contact but not where intended to contact in 2nd or 3rd account

**Comment by ffflorian** [comment]
Hi @macexpertsusa,
I can't reproduce this behavior. We have a [known issue](https://github.com/wireapp/wire-desktop/issues/1175) that pasting images takes some time. Is it possible that you pasted something but just didn't wait long enough for it to appear?

Can you try again with a smaller picture or just text in your clipboard?

**Comment by macexpertsusa** [comment]
hi ffflorian, thanks for the followup , this is regarding the windows desktop version
this isn't related to photos pasting just text 

copy some text of any type to your clipboard

if you have 2 or 3 accounts on left side
click on 2nd or 3rd account
click on any contact
right click  mouse - select paste in drop down menu (text) - nothing will appear
goto left side click 1st account the pasted text appears in the 1st account on last open contact

control V for pasting works anywhere normally

**Comment by ffflorian** [comment]
@macexpertsusa ah, sorry I missed the fact that you were using the menu. Now I can reproduce it :slightly_smiling_face:

**Comment by ffflorian** [comment]
@macexpertsusa 
Which version of Wire Desktop are you using (see Help -> About Wire)?

**Comment by macexpertsusa** [comment]
version 3.10.3138 wire for web 2019.09.02.1032

**Comment by macexpertsusa** [comment]
i see you were able to reproduce it - did you notice how it pastes into the first account input line for the last contact?   took a while to catch what was happening
thanks for looking into it

**Comment by ffflorian** [comment]
I tried it again with version 3.10.3138 and I can't reproduce that - only with our internal version (which uses Electron 5) I can reproduce it due to https://github.com/electron/electron/issues/18518.

**Comment by macexpertsusa** [comment]
Thanks for the follow-up
I just tested with 3.10.3138 that rolled out last night I believe
It's still doing the same thing here. 
copy something to clipboard
 goto the 2nd or 3rd account on Wire Desktop 3.10.3138
  select any user - goto - 'type here' input field -    right click drop down menu and paste and nothing will appear

 it still is pasting in the 1st accounts last user input field
control V pasting works properly as always

**Comment by mielouk** [comment]
I've had this problem for more than a year now. At first I thought it is related to the flatpak version and I didn't realize that the inserted content is being pasted in the other account.

Arch Linux with Cinnamon 4.4.4 and [sway](https://github.com/swaywm/sway) master. It's present in the DE and the WM.
Flatpak 1.5.2
Wire 3.11.2912

Please let me know if I can help with logs or troubleshooting.

**Comment by macexpertsusa** [comment]
> 
> 
> I've had this problem for more than a year now. At first I thought it is related to the flatpak version and I didn't realize that the inserted content is being pasted in the other account.


Yes it took me a while to figure out it WAS pasting with right click but in the 1st account last chat area
Still ongoing in 3.12.3234  2020.01.22.1255 Windows

**Comment by radarlog** [comment]
It's reproducible on my machine out of the box. Can help to debug:

Cinnamon 4.4.8
Linux Mint 19.3 with latest updates
Wine (Version 3.16.2923) from the official repo

**Comment by macexpertsusa** [comment]
still ongoing wire for windows v3.17

**Comment by lrenaud** [comment]
Persists in Wire for Linux 3.17.2924 with Wire For Web Version 2020.05.20.1224
