### ISSUE TITLE
2 step verification 

### ISSUE THREAD

**Issue by JasperWeiss** [wireapp/wire-desktop#302]
Currently anyone who obtains a user's password can login, receive all messages and lock the user out of his account (e.g remove devices, change passwords etc). 

There should probably be some form of 2nd factor authentication. (e.g confirm new device on any existing device or alternatively send an email/SMS message). TOTP tokens could also be used but I feel it doesn't suit the use case.

**Comment by BennySamir** [comment]
Reference to my feature request in the web app repo -> https://github.com/wireapp/wire-webapp/issues/446

**Comment by lipis** [comment]
So I'll close it as duplicate of wireapp/wire-webapp#446.. please upvote it to show support.
