### ISSUE TITLE
Wire 3.11 hangs on incoming calls

### ISSUE THREAD

**Issue by thisnickwasfree** [wireapp/wire-desktop#3026]
Wire version: Wire-3.11.0-6bb3223_x86_64 and Wire-3.11.0-f6917f9_x86_64
Wire for web version: 
Operating system: Incoming call from Wire 3.10 Win 10 to Wire-desktop 3.11 at Fedora. Calls from from 3.11 (Fedora) to 3.10 (Windows) works fine.
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Call from Wire 3.10 to Wire 3.11.
2. Push «answer» (button with a green tube).

What is the expected result?

Call accepted, so you can start your talk.

What is the actual result?

1.  Roster loses all elements except it`s background and an avatar and chat area becomes gray.
2.  Wire hangs until restart.

Please provide any additional information below. Attach a screenshot if possible.

100% of reproducing at the 3.11 side, so you can tell me what to do to gather as much information as possible.

**Comment by ffflorian** [comment]
Hi @thisnickwasfree, thanks for the report, but Wire 3.11 is not released yet. Please use Wire 3.10. Thanks :slightly_smiling_face:
