### ISSUE TITLE
Wire crashes when sending repl.it links

### ISSUE THREAD

**Issue by jestarray** [wireapp/wire-desktop#3038]
Wire version: Version 3.10.3138
Wire for web version: Wire for Web Version undefined
Operating system: Windows 10
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Send any repl link to a friend : https://repl.it/repls/WarmEvergreenTranslation
2.  Wire will freeze and not allow any further text input.

**Comment by ffflorian** [comment]
This will be fixed with the next release.

**Comment by ffflorian** [comment]
@jestarray This should be fixed now.
