### ISSUE TITLE
Missing dependency on Kubuntu (KDE desktop) linux

### ISSUE THREAD

**Issue by EliasA** [wireapp/wire-desktop#3053]
Wire Desktop on Linux seems to require libnotify-bin. Standard Ubuntu has it installed but Kubuntu which uses KDE desktop does not. Wire installation does not seem to require it -> installation does not work.

**Comment by ffflorian** [comment]
@EliasA which version of Wire are you trying to install?

**Comment by ffflorian** [comment]
@EliasA the `.deb` installation file for Wire Desktop indeed requires `libnotify-bin`. You can easily check that before installing:

```
$ dpkg-deb --info Wire-3.11.2912_amd64.deb
 new Debian package, version 2.0.
 size 44428922 bytes: control archive=96622 bytes.
     387 bytes,    13 lines      control              
  338680 bytes,  3510 lines      md5sums              
     977 bytes,    22 lines   *  postinst             #!/bin/bash
      75 bytes,     4 lines   *  postrm               #!/bin/bash
 Package: wire-desktop
 Version: 3.11.2912-2912
 License: GPL-3.0
 Vendor: Wire Swiss <wireapp@wire.com>
 Architecture: amd64
 Maintainer: Wire Swiss <wireapp@wire.com>
 Installed-Size: 171193
 Depends: libappindicator1, libasound2, libgconf-2-4, libnotify-bin, libnss3, libxss1
 Section: default
 Priority: extra
 Homepage: https://wire.com
 Description: 
   The most secure collaboration platform.
```

It's possible that you need to install `libnotify-bin` before you are able to install Wire Desktop. After a failed installation of Wire Desktop you can run

```bash
sudo dpkg install --force
```

to force installing all missing dependencies.
