### ISSUE TITLE
No 2.11.x release in Apple App Store

### ISSUE THREAD

**Issue by brettlangdon** [wireapp/wire-desktop#309]
It appears there are a few `2.11.x` releases in here GitHub, but the Apple App Store still shows version `2.10`.

I just uninstalled and did a clean install, just in case it was just the description that didn't get updated, but still only installed version `2.10.2652`.

![image](https://cloud.githubusercontent.com/assets/1320353/21768830/af23e5bc-d649-11e6-8f0d-dec2544a1da7.png)

**Comment by helenakos** [comment]
@brettlangdon Apple Store has the 2.10 version as we didn't release 2.11. It's currently blocked from being released by a an electron crash issue. Everything looks fine on your side.

**Comment by brettlangdon** [comment]
@helenakos good to know. Is there some place where I can track the releases?

**Comment by helenakos** [comment]
@brettlangdon We post all the client release notes here: https://medium.com/@wireupdates

**Comment by brettlangdon** [comment]
@helenakos thanks :+1: appreciate the quick reply.
