### ISSUE TITLE
Feature suggestion: Private/Work groups or account(s).

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#31]
Similar to what Android has with different users, but in a single (or more) account(s).

This would make it perfect to separate work-life with private-life.

You could be able to set auto-online/offline per group so that when you get off work you will be online to your private contacts and when you are on work, you will be online to colleagues but offline to friends.

**Comment by helenakos** [comment]
Love this feedback @tmikaeld. Noting it down for internal ideas. Thanks!
