### ISSUE TITLE
macOS: installer is incorrectly signed

### ISSUE THREAD

**Issue by core-code** [wireapp/wire-desktop#3100]
the installer available here 
`https://github.com/wireapp/wire-desktop/releases/download/macos%2F3.10.3133/Wire.pkg
`

is incorrectly signed
`installer: Certificate used to sign package is not trusted. `

because of this issue 'Wire Desktop' has already been removed from 'Homebrew Cask'. for more information see this:
https://github.com/Homebrew/homebrew-cask/pull/70311

i'm sure the Homebrew-Cask project would be happy to re-add Wire Desktop once the code signing issues are worked out

**Comment by ffflorian** [comment]
@core-code thank you for the heads up! I will investigate this.

**Comment by ffflorian** [comment]
@core-code We updated our certificate used to sign the macOS packages, but this will be visible only with the next release.

**Comment by core-code** [comment]
thanks. if you close this bug once a fixed release is available, i'll inform the Homebrew Cask guys to re-add it.

**Comment by ffflorian** [comment]
@core-code We just released a new version with an updated certificate: [v3.12.3490](https://github.com/wireapp/wire-desktop/releases/tag/macos/3.12.3490)
