### ISSUE TITLE
Feature Request: removing Alt hotkey from showing/hiding menu

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#3140]
Platform: GNU\Linux (or any other open source nix-like system with Xorg and window manager)
The problem is:
Xorg is using ab Alt-hold hotkey to move a window/frame using any it's point for dragging.
Hotkeys for switching  workspaces (virtual desktops) usually uses Alt + … hotkeys.
So, any time a user is using Alt-hotkey, the status of wire-app changes.
This looks not very good.

**Comment by ffflorian** [comment]
Hi @thisnickwasfree, the Alt key behavior was implemented due to a bug fix reported in https://github.com/wireapp/wire-desktop/issues/901. Unfortunately we can't provide support for all window managers and Linux support is experimental.
