### ISSUE TITLE
False positive flag by an anti-virus program?

### ISSUE THREAD

**Issue by manasb** [wireapp/wire-desktop#315]
Hello,

I recently found out that McAffee anti-virus may be flagging the desktop version of Wire as containing a virus? I have few details to share at the moment but will try to gather more details.

Has anyone else noticed this?

Thank you

**Comment by lipis** [comment]
We used to have that in the past.. but not recently.. please gather as much data as you can and send it over.. thank you.

**Comment by manasb** [comment]
Hello,

Here's a screenshot of the alert:
![Screenshot of McAffee WebAdvisor Alert](https://raw.githubusercontent.com/manasb/IMAGES/master/wire-mcaffee-alert.jpg)

It was seen on Windows 10 with the McAffee WebAdvisor plugin on Chrome.

**Comment by ffflorian** [comment]
@manasb 

From what I [learned about SiteAdvisor](http://ask.metafilter.com/265657/Why-does-McAfee-have-a-problem-with-my-website) (which includes WebAdvisor) is, that it warns you about every download when it's domain is not explicitly whitelisted by McAfee's "TrustedSource" Network.

For example: there is a Test Page by SiteAdvisor to find out if McAfee would consider this page safe or not. When [testing the Download for Wire executable](http://www.siteadvisor.com/sites/https://wire-app.wire.com/win/prod/WireSetup.exe) it warns that they found "potential security risks" without stating any reasons. This just means - AFAIK - that they didn't whitelist this executable yet.
Now you can try this with many other direct links to executables (e.g. [IrfanView](http://www.siteadvisor.com/sites/http://www.irfanview.info/files/iview444_setup.exe), [PCI File Recovery](http://www.siteadvisor.com/sites/http://download.pcinspector.de/pci_filerecovery.exe), [WinDirStat](http://www.siteadvisor.com/sites/http://download01.windirstat.info/wds_current_setup.exe)...). They are all blacklisted, even though these are the official download links for the corresponding app.

I personally think there's nothing to worry about, as long as you download the Wire App from the [official download page](https://wire.com/download/). Of course, you can also always [build the app on your own](https://github.com/wireapp/wire-desktop#wire-desktop) :slightly_smiling_face:.

**Comment by manasb** [comment]
@ffflorian 

Thanks for the well written explanation. 

I hope it will allay concerns about using Wire on their desktop in the future :)

**Comment by ffflorian** [comment]
Alright, closing this for now.
