### ISSUE TITLE
Client displays messages in wrong order

### ISSUE THREAD

**Issue by 2001db8** [wireapp/wire-desktop#316]
Hi,

I've noticed that the client (Win v2.11.2673) will display the messages in a conversation in a wrong order if a new message is received while one is typing a message:

Conversation between Alice and Bob. Alice starts typing a message. While she is still typing a new message from Bob is received. When Alice then transmits her message the clients displays her message above Bob's message albeit Alice's message was sent after Bob's message.

Seems like the order of messages (sometimes?) is determined by "typing started" rather than "time received/sent). Without having timestamps this can be confusing.

Regards

Jens

**Comment by lipis** [comment]
Can you check if your system time is completely in sync and precise?

**Comment by 2001db8** [comment]
System time is in sync, ntp is running.

**Comment by maximbaz** [comment]
@2001db8 I observed the same behavior on Windows, I had to disable and re-enable the automatic time sync for this issue to be gone. Try that, out of curiosity. See also https://github.com/wireapp/wire-webapp/issues/600 for reference.

**Comment by 2001db8** [comment]
@maximbaz system time was in sync and ntp service was running fine. I'll restart the service the next time I'll encounter the issue although I don't see why this should help when the systems time is aleady synced.

Wouldn't it be best to determine the sorting order of the messages to be displayed by timestamps assigned by the displaying client? Show received messages according to the time they were received by my client and sent messages by the time they were sent from my client? This way it won't be an issue if the participating clients/systems are not completely in sync.

**Comment by maximbaz** [comment]
Honestly I don't see any good reason as well why that should help, but that action did help me once, and so I suggested it :) I can only guess that maybe the time goes out of sync even though Windows still _pretends_ that it is synchronized, but I do not know.

I think using your client's timestamps to order messages could be error-prone: imagine I send you two messages [M1, M2], your first device indeed receives them in this order [M1, M2], but your second device for whatever reason receives M2 first [M2, M1]. I imagine this scenario is possible, and thus it is not reliable to use the time when your client received a message to determine the order of messages.

The less error-prone solution would be to use server's timestamps, i.e. the time of when server acknowledged receiving a message. That way the ordering would be identical regardless of time zones and differences in time on any given device. To my understanding that is what the team is going to do in future according to @gregor's explaination in https://github.com/wireapp/wire-webapp/issues/600, though the exact timing is not known.

**Comment by 2001db8** [comment]
I agree that the message order could be different on several devices but since I'm normally not typing simultaniously on two or more devices this still would be an improvement ;) At least it is good to know they are aware of this issue.

**Comment by 2001db8** [comment]
Since @bennyn already [commented](https://github.com/wireapp/wire-webapp/issues/600#issuecomment-272715438) that they'll investigate this further feel free to close this isse if needed.

**Comment by gregor** [comment]
This is not specific to Windows.

**Comment by DetlevCM** [comment]
This issue persists. I believe it is fine on Windows (not seeing it) but this does occur with a family member on Linux.

I get messages in the correct order, but on the Linux laptop they are shuffled/ordered incorrectly.
There is a 1 minute difference in the displayed time in the OS - plus a 1 hour time zone difference.

**Comment by ConorIA** [comment]
Are you both using NTP / internet time?

**Comment by DetlevCM** [comment]
The Windows lapop synchronises the time - the LInux one does not (just changed it).
(I suspect it was switched off due to some issue - I vaguely remember something along those lines...)

**Comment by gregor** [comment]
Messages should be sorted correctly once send. We are now changing the message timestamp to the server time once sending was successful.
