### ISSUE TITLE
Add audio volume control within the application

### ISSUE THREAD

**Issue by Porkepix** [wireapp/wire-desktop#3171]
It would be a nice addition within the application to be able to have audio volume control, both in the form of controlling global volume and individual audio level for every participant in an audio call (this can include adjusting audio levels if the sound is loud for some and very light for some others, or muting someone that let mic one with noises and so on).

**Comment by ffflorian** [comment]
Hi @Porkepix, good idea! I added a feature request label and will notify you if we implement this at some point.
