### ISSUE TITLE
Can't copy device fingerprint

### ISSUE THREAD

**Issue by Kasmetski** [wireapp/wire-desktop#320]
When I go to my devices I can't select the fingerprint to copy/paste it.

This is on Linux.

**Comment by Strit** [comment]
Not Linux specific. Same problem on Windows.

**Comment by lipis** [comment]
Making them selectable in the https://github.com/wireapp/wire-desktop/issues/320.. no context menu but I think `ctrl+c` or `cmd+c` is enough in this case!

**Comment by gregor** [comment]
We decided to fix things on the webapp side. https://github.com/wireapp/wire-webapp/pull/681 was merged and will be part of the next release. Thereby closing this.
