### ISSUE TITLE
Unable to paste image from clipboard

### ISSUE THREAD

**Issue by MichielBijl** [wireapp/wire-desktop#327]
I’m unable to paste an image into the chat window on macOS 10.12.2 (16C67) / Wire 2.10.2652.

This goes for images copied from the internet or other places.

**Comment by herrmannplatz** [comment]
What kind of image.

**Comment by MichielBijl** [comment]
Any bitmap image. Can be a screenshot capture via ⌘⇧^3 or a JPG files copied from the web via the context menu.

**Comment by maximbaz** [comment]
I'm also eagerly waiting for this feature, but from what I can tell it didn't make to production yet :disappointed:

It was only merged in `dev` on [December 15](https://github.com/wireapp/wire-webapp/pull/570), while the latest commit in `prod` is still December 13.

Hoping to see a release soon :crossed_fingers:

**Comment by herrmannplatz** [comment]
@maximbaz you are right. And it was actually me who implemented it. Even better :)

To give an update. This is already merged to our staging branch and ready to be pushed to production. There is also other stuff included in the next release that needs to be tested first. But next release is close.

Coming back to the actual feature. I used the standard clipboard API to get this working, which is a pretty interesting API. Didn't had so much fun in ages. So depending on how you copied the image, the api returns either a proper image or ◾️. We might be able to improve this in the desktop clients using electrons clipboard api.

So sry for the confusion.

**Comment by MichielBijl** [comment]
This is excellent to hear, look forward to annoying my friends with images I paste into chats 🎉.

**Comment by maximbaz** [comment]
It is on production now 🎉 🎉 🎉

**Comment by herrmannplatz** [comment]
Indeed :)

**Comment by MichielBijl** [comment]
Not seeing it in the Mac App Store yet, but I’m guessing that has to do with Apple approving the update and such.

I’ll be patient 😇. Thanks for this anyway 👍.

**Comment by maximbaz** [comment]
@MichielBijl that was a webapp feature, you just need to fully restart the app to see it. No changes to the desktop app required. Try 😉 

It's easy to visually tell if you see a new version, there is a new icon on the left of the conversation title:

![image](https://cloud.githubusercontent.com/assets/1177900/22228689/25f9c80c-e1d3-11e6-9e7d-5206e24be387.png)

**Comment by MichielBijl** [comment]
Ah, I see, it works 🎉.
