### ISSUE TITLE
Arch Linux 4.8.14-1

### ISSUE THREAD

**Issue by Freshman4754** [wireapp/wire-desktop#339]
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x39310b19daa0)" of type `gboolean'

**Comment by lipis** [comment]
Can you provide more information? Are you trying to run it from source? Production build..? etc..

**Comment by Freshman4754** [comment]
Already solved, the issue was in two different icon packs I used simultaneously (Breeze-Dark in KDE, Papirus-Dark with hardcode-tray). When I changed icon pack back to Papirus-Dark - everything just worked.

**Comment by lipis** [comment]
👍
