### ISSUE TITLE
Linux flatpak distribution of Wire sandboxing error

### ISSUE THREAD

**Issue by iKarith** [wireapp/wire-desktop#3410]
Wire version: wire desktop release 3.12.2916 (7524dd21)
Wire for web version: can't check
Operating system: Debian sid (updated today, 2020-01-04), using the flatpak distribution com.wire.WireDesktop found on flathub.
Which antivirus software do you have installed: Nothing resident.

What steps will reproduce the problem?

1.  Click the wire-desktop shortcut
2.  Observe no Wire appears
3.  Open a terminal and run `flatpak run com.wire.WireDesktop`

What is the expected result?

I expect an Electron window to pop up and show me my contacts and conversations.

What is the actual result?

I receive this error:

```
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/Wire/chrome-sandbox is owned by root and has mode 4755.
```

This file is, I assume, located elsewhere outside the chroot. I find it located here:

`/var/lib/flatpak/app/com.wire.WireDesktop/x86_64/stable/<hex string>/files/Wire/chrome-sandbox`

The file is root:root, mode 755. Making it 4755 changes the error, but doesn't cause electron to start.

Please provide any additional information below. Attach a screenshot if possible.

In case it's relevant:

```
ii  flatpak        1.6.0-1      amd64        Application deployment framework for desktop apps
```

I thought to work around this using the web app, but when I attempt to login using Firefox, the web app tells me "not enough disk space". Um, I know javascript turns hello world into a 1GB application and all, but I have 246GB free at the moment. Pretty sure that I do in fact have enough disk space. I'm gonna guess this works in Chrome just fine—will report an issue if it doesn't. Else I'll see if I can debug the issue a bit first when I get a chance and make a better report.

**Comment by iKarith** [comment]
I have downgraded to 3.11.2912, and that version does work as expected.

**Comment by kaymio** [comment]
Got the same issue on Arch, since 22nd or 23rd of December.

**Comment by aidalgol** [comment]
I'm also getting this on Debian stable, using the flathub flatpak.

**Comment by ffflorian** [comment]
Since we don't build the Flatpak ourselves, I can't help with that. But I just saw that this was fixed in https://github.com/flathub/com.wire.WireDesktop/pull/25.
