### ISSUE TITLE
Tray icon issue in Gnome with X11

### ISSUE THREAD

**Issue by Dvlnst** [wireapp/wire-desktop#3416]
· Wire version: 3.12.2916.
· Operating system: Debian Buster + Gnome 3.30.2 (X11).
· Installed from: Debian repository.

Tray icons look deformed. I usually solved this editing the icons (tray.badge.gnome.png and tray.gnome.png) cropping the unwanted space, but I cannot do it since asar packaging was added.

![Screenshot from 2020-01-06 19-28-56](https://user-images.githubusercontent.com/36289254/71839144-cb3c5300-30ba-11ea-8f82-df5ac9560ee4.png)
![Screenshot from 2020-01-06 19-27-48](https://user-images.githubusercontent.com/36289254/71839266-0fc7ee80-30bb-11ea-9903-76aea83e2b08.png)

Kind regards.

**Comment by ffflorian** [comment]
Hi @Dvlnst, are you using Wayland or X11?

**Comment by Dvlnst** [comment]
It works fine in wayland. It only happens in X11.

**Comment by GitStorageOne** [comment]
On Kubuntu 21.4 (X11 session) tray icon looks Low-res
![image](https://user-images.githubusercontent.com/3978064/119368992-5328fa00-bcbc-11eb-84ad-9b867ffe4a79.png)

**Comment by dumprop** [comment]
Same on suse kde (x11)
![Screenshot_20211129_202045](https://user-images.githubusercontent.com/34004367/143914034-c09c01f3-8b22-4755-b956-3d2abd672ca5.png)
also, the icon does not work if there is an unread message
![Screenshot_20211129_202154](https://user-images.githubusercontent.com/34004367/143913993-4a48a3d0-ca38-4e3b-8d4d-b30c876d1e27.png)
Installed via flatpak from flathub
