### ISSUE TITLE
Icon in tray looks ugly (KDE)

### ISSUE THREAD

**Issue by Freshman4754** [wireapp/wire-desktop#342]
I have to use this to beautify it.

https://github.com/bil-elmoussaoui/Hardcode-Tray

**Comment by ConorIA** [comment]
What would the recommended fix be? A smaller icon?
A commit to unpack the asar file has just been merged, so the tray icons can be easily replaced by a user in the next release.

**Comment by lipis** [comment]
There way too many flavours and it's hard to satisfy them all. Maybe in the future, we'll have more customizations when it comes to icons (possibly two versions), but for now, as @ConorIA mentioned it won't be hard to replace it..

**Comment by varlesh** [comment]
Will be cool use `QSystemTray` if possible for Qt-based desktops (KDE, LXQt and etc..)

For example, on Plasma Desktop `libappindicator ` icons looking ugly and have wrong rendering. See bug: https://bugs.kde.org/show_bug.cgi?id=366062
![image](https://user-images.githubusercontent.com/8083855/32317341-fcc602e2-bfcc-11e7-8d2e-f9cd88c98abd.png)

hardcode-tray partially solve this, but icon anyway blurred and have wrong rendering:
![image](https://user-images.githubusercontent.com/8083855/32317405-2c90d0ce-bfcd-11e7-9a7b-0de968bbf5b5.png)

All non-Qt (QSystemTray) apps have  bugged icon on plasma tray
