### ISSUE TITLE
Electron sandbox options

### ISSUE THREAD

**Issue by Paragis** [wireapp/wire-desktop#3442]
Wire version: 3.12.2916
Wire for web version: 2020.01.06.0957
Operating system: Debian 10
Which antivirus software do you have installed: none

Is there a way to change the behavior of the electron sandbox that is active since the last release with electron6?
I would like to look into ways to tighten the electron sandbox used by wire. The Wire process does not need access to my private ssh keys...

**Comment by ffflorian** [comment]
Hi @Paragis, what do you mean by "change the behavior of the electron sandbox"? In general, you can use Electron's supported [start parameters](https://github.com/electron/electron/blob/v6.1.7/docs/api/chrome-command-line-switches.md) to change some of the behavior.

**Comment by vladimiry** [comment]
You could also try [Firejail](https://firejail.wordpress.com/) tool to set up directories whitelist to which Wire is allowed to access.

**Comment by Paragis** [comment]
> Hi @Paragis, what do you mean by "change the behavior of the electron sandbox"? In general, you can use Electron's supported [start parameters](https://github.com/electron/electron/blob/v6.1.7/docs/api/chrome-command-line-switches.md) to change some of the behavior.

I am asking if there are options to further restrict the sandboxed application, like in flatpak for example.
Preventing access to arbitrary file in the home directory would be a good start.

**Comment by ffflorian** [comment]
> I am asking if there are options to further restrict the sandboxed application, like in flatpak for example.

There are no options like that, AFAIK.
