### ISSUE TITLE
Wire Audio broken on linux with electron6

### ISSUE THREAD

**Issue by Paragis** [wireapp/wire-desktop#3472]
Wire version: 3.12.2916
Wire for Web Version 2020.01.13.1120
Operating system: Debian 10
Which antivirus software do you have installed: none

Using the newest wire-desktop release on linux, the audio devices are no longer recognized and therefore it is no longer possible to do audio calls.

Workaround: 
When starting wire with the --no-sandbox option and thereby disabling the chrome sandbox in electron6, everything works as expected. Maybe there is an option in the electron framework to allow devices within the sandbox that could provide a solution without disabling the sandbox

**Comment by ffflorian** [comment]
Hi @Paragis, we can't disable the sandbox due to security. Furthermore, we don't support Electron 6 anymore - if you want to use Electron 6 and/or disable the sandbox, you need to build your own desktop client.
