### ISSUE TITLE
Linux - stucks on loading screen

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-desktop#349]
![_2017-01-24_11-29-01](https://cloud.githubusercontent.com/assets/11610652/22241557/8a63153c-e228-11e6-9330-08ca1f8e643b.png)

Wire stucks on loading after second launch. Ubuntu 16.04 (Mint 18) x64 Xfce.
This helps:
```
cd ~/.config/Wire
rm -r Cache GPUCache
```

**Comment by alien2003** [comment]
The same happenned on Windows 8.1. Can't fix it :(

**Comment by lipis** [comment]
It stucks every time on the second launch?!

**Comment by alien2003** [comment]
Not an issue. It just takes too long to sync history. Sorry

**Comment by lipis** [comment]
Yes.. unfortunately it's a known issue, but we are working on it to speed it up! Thank you..

**Comment by gregor** [comment]
@alien2003 We are decrypting all the events for messages you have received while you were not using the app at this stage of the progess bar. This currently can take a very long time depending on the number of missed actions. We are hard at work improving the performance in this area.
