### ISSUE TITLE
Copy image from chat to clipboard

### ISSUE THREAD

**Issue by mvdwoord** [wireapp/wire-desktop#351]
Currently it is only possible to "Save Picture As ..." when right clicking an image in a chat. I would like to have an option to "Copy To Clipboard" as well.

**Comment by helenakos** [comment]
@mvdwoord We have in our plans to unify the tools and menus, which means adding more options.

**Comment by ffflorian** [comment]
Done with https://github.com/wireapp/wire-desktop/pull/4141 and will be available with 3.20.

**Comment by Filbuntu** [comment]
@ffflorian Thanks a lot for working on this and sharing the good news!
