### ISSUE TITLE
Incorrect time on PC causes messages to display in an incorrect order

### ISSUE THREAD

**Issue by lightswitchr** [wireapp/wire-desktop#352]
### Expected behaviour

Messages should appear in the order they have been received.

### Actual behaviour

Messages are ordered by (arrival/delivery) time. If the time on the PC is incorrect, the messages are displayed in time order, instead of the order they were actually sent in.

### Steps to reproduce the behaviour

1.  Set your PC time to be behind actual time by 10 minutes.
2.  Send a message to the PC using the Android app with the correct time.
3.  Reply using the PC. 
4.  Repeat until necessary to observe issue.

### Version of project in use

* Desktop: 2.11.2683
* Android: 2.25.305

**Comment by gregor** [comment]
This is a known limitation with our current implementation. We are tracking this in #316. Please upvote that issue.

**Comment by gregor** [comment]
For your understanding: Incoming messages are ordered by by server timestamp. Outgoing messages will be inserted using the local time and the timestamp is never updated to the server time - resulting in out of order messages if your local clock has drift.

**Comment by lightswitchr** [comment]
Thanks @gregor - I should have searched first!
