### ISSUE TITLE
Chat lines do not fill the entire window

### ISSUE THREAD

**Issue by lightswitchr** [wireapp/wire-desktop#353]
### Expected behaviour

The chat lines should fill the entire window.

### Actual behaviour

The chat lines do not fill the entire window. See image:

![screenshot 92](https://cloud.githubusercontent.com/assets/7480500/22247039/afec6cc0-e22f-11e6-8cd8-0cb26b56d41e.jpg)

### Steps to reproduce the behaviour

1) Open a chat and maximise the window.

### Version of project in use

   * 2.11.2683

**Comment by lipis** [comment]
This is by design.. as it would be really hard to read long long lines..

**Comment by lightswitchr** [comment]
Oh, really? It just doesn't look right to me, but okay.
