### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by lightswitchr** [wireapp/wire-desktop#355]
I cannot get notifications on Windows to work at all, on any notification setting. The sound does play.

Windows 7, Wire version 2.11.2673

**Comment by GopianiS** [comment]
Same for me talking to lightswitchr and dont receive popup notifications

**Comment by gregor** [comment]
There is no notifications support in Windows 7.

**Comment by lightswitchr** [comment]
@gregor - Why is that? You have a notification icon in the tray, it is trivial to provide balloon notifications through that.

**Comment by lightswitchr** [comment]
See [this in the Electron documentation](http://electron.atom.io/docs/api/tray/#traydisplayballoonoptions-windows).

**Comment by gregor** [comment]
We have a limited amount of resources and implementing a feature like this for legacy OS support was never prioritized high enough to actually implement it. It is currently not on our list. I am sure we would accept a contribution in this area though and are always evaluating priorities taking user demand into account.

**Comment by lipis** [comment]
Windows 7 is already a 7 years old OS.. what stops you to upgrade to something newer?

**Comment by lightswitchr** [comment]
@gregor, I am aiming to make a pull request, however npm install is failing for me at the moment.

@lipis - work licences. Also, I like it, and according to [this source](https://netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0) Windows 7 still has a 48% market share. I would hardly call it legacy.

**Comment by lipis** [comment]
There are at least 3 major version after Windows 7.. and Microsoft is trying hard to get all those people upgrade to something newer!

**Comment by lightswitchr** [comment]
All I want is notifications from a chat app, shouldn't need a whole new operating system for that :)

**Comment by lipis** [comment]
Point taken :) and yes.. we are off topic.. :)

**Comment by lightswitchr** [comment]
@gregor @lipis I have the balloon working - I've been trying to push the branch but I get this:

> ERROR: Permission to wireapp/wire-desktop.git denied to lightswitchr.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

How do you want me to proceed?

**Comment by lightswitchr** [comment]
Never mind, I found out how. Pull request created.

**Comment by lipis** [comment]
As we are not able to spend resources on this one, the best way is to follow this issue on Electron's issue tracker: https://github.com/electron/electron/issues/8384. I hope it will be OK to close it here.
