### ISSUE TITLE
Can't change input device after call has been established.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#36]
There also really need to be an indicator somewhere that shows what input device is **currently** being used.

Showing the current input device should be possible, it's available in the JS debug.

**Comment by gregor** [comment]
Thanks for the report. I can assure that it is on the list of things to do. You can change the camera during a video call. Similar functionality to change audio input and audio output is there in the code but not yet exposed in the user interface. You can change devices using the Javascript console though. Check the VideoCallViewModel.coffee and the MediaDevicesHandler.coffee for which not fully tested and thus unsupported calls to make to use this as a sneak peak.

**Comment by gregor** [comment]
@tmikaeld We have now implemented a Preference section to choose your media devices. The selection should be remembered between logouts. Just reload and go to Preferences -> Audio / Video.

**Comment by tmikaeld** [comment]
Superb! Thank you!
