### ISSUE TITLE
Drag & drop images directly from browsers is not supported

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-desktop#360]
Rewrite: apparently it's been updated in the meantime. Apologies for the incorrect title.

It would be great if I could drag'n'drop images from a webbrowser to Wire, preferably sharing the image directly rather than a link to the image.

**Comment by lipis** [comment]
You can paste images from clipboard now (restart your app if it doesn't work for you) and you can drag the images from the file system into conversations.. but dragging them directly from the webapp is still not working.

**Comment by MadEgg** [comment]
Oh, you're right. Copy+paste does work. Sorry. Drag'n'drop doesn't work, yet, so I'll update the title.

**Comment by helenakos** [comment]
@madegg Could you update it to say drag'n'drop from websites to Wire does not work. Drag'n'drop from desktop to Wire works.

**Comment by MadEgg** [comment]
I don't know the implementation details, but it's not just from websites to Wire. Dragging from another application (such as KSnapshot) to Wire also doesn't work.

Drag'n'drop from a file manager such as Dolphin does work, like you said. I'll try to update it accordingly.

**Comment by MadEgg** [comment]
Done!

**Comment by lipis** [comment]
I updated it for you! Thank you @MadEgg

**Comment by helenakos** [comment]
We don't have immediate plans to implement this therefore I will close the issue.
