### ISSUE TITLE
Connection-sound plays after interrupted connection establishment 

### ISSUE THREAD

**Issue by vonMitzscha** [wireapp/wire-desktop#3665]
**Wire version:** Versio 3.15.3621
**Wire for web version:** Wiren verkkoversio 2020.03.03.1405
**Operating system:** macOS 10.15.13
**Which antivirus software do you have installed**: nothing additional installed 

**What steps will reproduce the problem?**

1. Try to call somebody 
2. The recipes don't accept the call and Wire automatically stops the connection establishment 
3. Push the play button of the Macs keyboard 

**What is the expected result?**

Nothing should happen (maybe the Music in Spotify, etc. starts or continue)

**What is the actual result?**

The ringing tone plays again, but Wire don't try a new call

**Please provide any additional information below. Attach a screenshot if possible.**

[Wire-aeb9-Calling_2020-03-14.log](https://github.com/wireapp/wire-desktop/files/4333161/Wire-aeb9-Calling_2020-03-14.log)

**Comment by mythsunwind** [comment]
Thanks for the report. This issue was fixed with the release 2020.03.23.1558. If you experience still issues, please let us know. 

https://github.com/wireapp/wire-webapp/pull/8311
