### ISSUE TITLE
USB headset muting

### ISSUE THREAD

**Issue by ViRGiL175** [wireapp/wire-desktop#369]
Hi! Thanks for great app!

I have some trouble with my USB headset on WIndows 10.
I use Desktop Wire and today we tested last Wire version after long time.

When I switch on/off screen sharing and webcam back and forth in one moment my mate say that don't hear me. Sound came back only when I came to settings and switched my mic from Default to USB and again on Default.

Maybe there are some missed device check in code or smth.

Thanks. Have a nice day!

**Comment by gregor** [comment]
This is most likely related to #321 and https://github.com/wireapp/wire-webapp/issues/219
