### ISSUE TITLE
Scroll-Wheel not working in "Media Archive"

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#370]
Vertical scroll also does not appear until you scroll horizontally first.

Only tested on MacOS, but is probably the same in Windows and Linux (Looks like it's been forgotten rather than technically missing)

**Comment by tmikaeld** [comment]
I saw that this was fixed now - except now the left scroll lost it's black styling.

**Comment by tmikaeld** [comment]
Screenshot:
![screenshot_2017-03-21_04-18-49_pm](https://cloud.githubusercontent.com/assets/907195/24154668/262b0182-0e52-11e7-9d5c-78ff6f2acdfe.png)

**Comment by tmikaeld** [comment]
The latest Wire version is a regression to the issue at hand, now the scroll wheel does not work again.

**Comment by gregor** [comment]
Whether scrolling on this screen works or not depends on the width of the window. We have a known issue there if you scale down the window too much.

**Comment by gregor** [comment]
As https://github.com/wireapp/wire-desktop/issues/370 describes the issue of decreasing the the window size below a certain threshold disabling scrolling on some screens of the app, I am going ahead with closing this one to have single ticket to track the issue.
