### ISSUE TITLE
Wire on 32bit linux stopped working - both desktop and browser versions

### ISSUE THREAD

**Issue by ebym** [wireapp/wire-desktop#3712]
Wire version: 3.4.2879
Wire for web version: Firefox 64, 32bit.
Operating system: Linux Mint 17.3, 32bit
Which antivirus software do you have installed: None.

What steps will reproduce the problem?
Upgrade Wire 3.4.2879, 32bit build from top of main window.

What is the expected result?
Wire desktop window with contacts and conversations or login page on Firefox.

What is the actual result?
Wire desktop - white window with menus, only "quit wire" works.
Web - empty firefox page.

Please provide any additional information below. Attach a screenshot if possible.

wire-desktop: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by wire-desktop)

Wire on 32bit linux stopped working.
I had the desktop version 3.4.2879 and browser version(FF64) working on Linux Mint 17.3, 32bit, Now the desktop and web versions stopped working and i don't have a recent conversation history backup.

Is it possible to get everything back by editing some files in ".config/Wire" folder to undo upgrade and save conversation history backup ?.

![Wire_257](https://user-images.githubusercontent.com/16803049/77353902-da50aa00-6d67-11ea-86c6-accb82272812.png)

**Comment by mythsunwind** [comment]
Version 3.4 is very outdated and should not be used anymore. We support Firefox up to the latest ESR (Extended Support Release) version which is currently Firefox 68. You can update to Firefox ESR or try to build the linux version for 32 bit yourself.

**Comment by ebym** [comment]
the question is "is there any way to save my conversation history backup" so i can restore it to a 64bit linux system.

**Comment by mythsunwind** [comment]
Sorry to hear that. You can usually save your history with the backup functionality in the settings, but as you already might know, you need to be logged in on the same machine with the same profile. Upgrading your Firefox might work the best for this. Firefox itself should be able to read the old profile directory which also contains your old conversations.

You can also try the last 32 bit version we had released: https://github.com/wireapp/wire-desktop/releases/tag/linux%2F3.6.2885

But better make a backup of the profile directory before. For example like this:
`cp -r ~/.config/Wire/ ~/.config/Wire.bak`

**Comment by ebym** [comment]
FF66.0.3 is the latest in the repo, with that i get "fetching your conversations" and goes back to the login page.

v3.6.2885 wont launch, v3.4.2879 is the last one to support 32bit linux.

How do i read old profile directory from Firefox ?.

**Comment by mythsunwind** [comment]
https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles

**Comment by ebym** [comment]
unable to retrieve messages, is there a way to manually set device ID and try to recover ?.
