### ISSUE TITLE
Modify e-mail address

### ISSUE THREAD

**Issue by Post-Scriptum06** [wireapp/wire-desktop#373]
Hello,
Is it possible to add the ability to modify our e-mail adress on the Windows app?
(We can't clic on it [V2.11.2673])
(Because I can do it on the Android app.)

Thanks :)

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by anatoli26** [comment]
Why not? If it's already possible in other versions..

**Comment by helenakos** [comment]
@anatoli26 We're working on new features that will enable teams to use Wire. This includes many changes and it's a matter of limited resources, not a matter of dismissing feature consistency between mobile and desktop clients.
