### ISSUE TITLE
Camera doesn't work when a virtual camera is also present, (logicapture)

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#3739]
![image](https://user-images.githubusercontent.com/388716/78303304-6900bc00-750a-11ea-8c20-fac4405d1f2b.png)

**Comment by ffflorian** [comment]
@Transisto without any kind of background information on this we are not able to find out what's going wrong. Please fill out the issue template instead of just posting screenshots. Thanks!

**Comment by Transisto** [comment]
Window 10

How to reproduce : install logicapture
https://www.logitech.com/en-ca/product/capture

Try using / selecting a webcam afterwards.

**Comment by Transisto** [comment]
@ffflorian The same problem also happens in Chrome so don't bother, Will try finding the Chrome issue.

Basically if there is nothing on the Virtual camera stream it freeze the selection of another camera.

**Comment by ffflorian** [comment]
@Transisto then I will close this for now since it's not a Wire-specific issue.

**Comment by Transisto** [comment]
Lol, it's on you to fix your dependencies.
... Whatever
