### ISSUE TITLE
🤷‍♂️ 

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#3740]
https://youtu.be/SbIijFJ71m0

**Comment by ffflorian** [comment]
@Transisto without any kind of background information on this we are not able to find out what's going wrong. Please fill out the issue template instead of just posting YouTube links. Thanks!

**Comment by Transisto** [comment]
Windows 10,

How to reproduce : launch wire normally, (happens rarely)

Problem : ask to login when already logged in

Workaround : close wire and open again.

I assume if someone were to try logging at that point he might have his
whole chat history reset.

**Comment by ffflorian** [comment]
Duplicate of https://github.com/wireapp/wire-desktop/issues/3790.
