### ISSUE TITLE
windows client won't login

### ISSUE THREAD

**Issue by rosspi** [wireapp/wire-desktop#3741]
If I try to login with the Windows client, it goes through the loading process
.. updating message.. etc.. looks like it's about to work, and let me in.
But then it just returns back to the login 'Welcome to Wire' screen.
Is anybody else having this issue?

**Comment by ebym** [comment]
have same problem with linux client(32bit OS), how did you resolve the issue ? have you lost any data ?.

**Comment by rosspi** [comment]
I did not solve the issue, but noticed it's common to the website as well (for me at least).

**Comment by ebym** [comment]
i'm able to login using browser on 64bit OS, however my chat history is not there, i assume 32bit os is no longer supported.
