### ISSUE TITLE
Spellchecker not available (anymore)

### ISSUE THREAD

**Issue by jeroenpraat** [wireapp/wire-desktop#3743]
Wire version: Versie 3.16.2923
Wire for web version: 2020.03.23.1558
Operating system: Ubuntu Linux 19.10 (via the official Wire repo)
Which antivirus software do you have installed: N/A

According [this](https://github.com/wireapp/wire-desktop/pull/207) merged pull request from November 2016, the desktop app should have a spellchecker (English only at that moment). Unfortunately this is not available in the current version and I can't remember it ever was.

Is this somehow removed or is this not available in the Ubuntu Linux build?

For both cases, I really would ask you to re-add this  IMO important feature?

**Comment by ffflorian** [comment]
Hi @jeroenpraat, the spell checker was [removed](https://github.com/wireapp/wire-desktop/pull/2023) over a year ago. We are planning to bring it back, but I can't give you an estimate yet.

**Comment by jeroenpraat** [comment]
@ffflorian Thank you for your reply. I found these two resources. Hopefully it can be of any help.

https://github.com/electron-userland/electron-spellchecker

https://github.com/electron/electron/pull/20897

**Comment by ffflorian** [comment]
The spell checker will be back with the next release :tada:

**Comment by jeroenpraat** [comment]
@ffflorian Thanks. Unfortunately it only uses the Dutch spelling (my desktop language). I have a lot of communication in English. How to use an English spellchecker?

Ubuntu 20.04

**Comment by ffflorian** [comment]
@jeroenpraat please set the app to English, then the spell checker will also use English.
