### ISSUE TITLE
[Windows] [Feature Request] Same feature on Windows app as Android app

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#375]
Hello,

I think is plane but I still ask, is it possible to have the same feature on Windows app as Android app?
(I didn't test the Linux and Mac version but the remark is the same)

I mean :

- the ability to draw (with mouse or like with phone for tablet version)
- emoji
- GIF
- voice message
- (add video message?)
- location
- take a photo

For finish I think you do deleted "Add picture" and just keep "Add file" (this will make you win the place and at the end its options are duplicate (for me).

Have a good day !

**Comment by Termuellinator** [comment]
Absolutely need that - i took a look at the mobile app and was quite pleased while toying around with it. convinced a friend to give it a try and tried the desktop-version...and most of the nice features that stood out are not there!?

**Comment by anatoli26** [comment]
Send voice messages is indeed an important feature to have in all clients

**Comment by alexleonard** [comment]
In favour of this. I have a drawing tablet and would love to be able to mark up images that people send me or draw simple sketches

**Comment by gregor** [comment]
Thank you very much for your feature request. While it would be great to see all features found in the mobile implementations we currently cannot provide and if or when the missing bits will be added to the desktop application. We are currently undergoing some cleanup and I will go ahead and close this request. We will continue to track them internally and prioritize them on our roadmap. The issues list here will be focussed on bugs.
