### ISSUE TITLE
Uncaught Reference Error

### ISSUE THREAD

**Issue by DaylightCulture** [wireapp/wire-desktop#3763]
When building from source for MacOS, and running these commands, im getting this error:

git clone https://github.com/wireapp/wire-desktop.git
cd wire-desktop
yarn
yarn start

Uncaught ReferenceError: require is not defined
    at Object.util (bundle.js:3878)
    at __webpack_require__ (bundle.js:20)
    at eval (webpack-internal:///./node_modules/uuid/v4.js:1)
    at Object../node_modules/uuid/v4.js (bundle.js:3856)
    at __webpack_require__ (bundle.js:20)
    at eval (webpack-internal:///./electron/renderer/src/actions/index.js:17)
    at Module../electron/renderer/src/actions/index.js (bundle.js:132)
    at __webpack_require__ (bundle.js:20)
    at eval (webpack-internal:///./electron/renderer/src/components/App.jsx:7)
    at Module../electron/renderer/src/components/App.jsx (bundle.js:167)
/Users/User1/wire-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:189 Electron Security Warning (enableBlinkFeatures) This renderer process has additional "enableBlinkFeatures"
  enabled. This exposes users of this app to some security risk. If you do not
  need this feature, you should disable it.For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutEnableBlinkFeatures @ /Users/User1/wire-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:189
/Users/User1/wire-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.

Wire version: 
Wire for web version: 
Operating system: 
Which antivirus software do you have installed: 

What is the expected result?

Expecting Electron to start and open the wire application

What is the actual result?

An error window pops up with the error description

Please provide any additional information below. Attach a screenshot if possible.
Running the latest MacOS version

**Comment by ffflorian** [comment]
Thank you @DaylightCulture!
