### ISSUE TITLE
[All app] [Feature Request] Add an unsufull feature => games (as the old time of MSN messenger ^^)

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#377]
Hello,

All is on the title, adding a games to play with a contact or group.

For example:

- card game
- old classic game as pong or space invader
- checkers
- chess game

(Edit: It can be an enable/disable option or some can of add-on. For not overload the app.)

**Comment by githubbantor** [comment]
Don't "include" it - it must be an add-on.

**Comment by herrmannplatz** [comment]
Sorry to tell you that this is not on our roadmap at the moment. But we will come up with a couple of useful feature instead.
