### ISSUE TITLE
[Desktop - MacOS] Distorted appearance in client

### ISSUE THREAD

**Issue by stinsonga** [wireapp/wire-desktop#3789]
Wire version: 3.16.3630
Operating system: 10.15.4
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1. Launch Wire
2. The problem shows up right away

What is the expected result?

1. No distortion

What is the actual result?

1. Strange distortion in the window. It does not go away if the window is dragged to an external monitor with a different resolution.

Please provide any additional information below. Attach a screenshot if possible.

Sometimes switching between conversations temporarily fixes the problem, but it usually returns

<img width="1020" alt="Screen Shot 2020-04-15 at 9 56 12 PM" src="https://user-images.githubusercontent.com/2532623/79407458-530de500-7f67-11ea-9cb6-f422a6effd57.png">

**Comment by ffflorian** [comment]
Hi @stinsonga,

this seems to be a known macOS problem with Chrome or Chrome-based applications:

https://support.google.com/chrome/thread/35828402?hl=en

Could you try running the app from the terminal like this:

```
open -a Wire.app --args --disable-gpu
```

and see if the problem persists?

**Comment by stinsonga** [comment]
FWIW, I haven't seen the issue in the last week or so. Did the latest update(s) to Wire contain a fix?

**Comment by ffflorian** [comment]
> FWIW, I haven't seen the issue in the last week or so. Did the latest update(s) to Wire contain a fix?

No, we didn't fix it. As I already mentioned, this seems to be known macOS problem, not a Wire problem.

Closing this since the bug is gone and this is not a Wire-specific issue.
