### ISSUE TITLE
Reaktion when tipping is slow

### ISSUE THREAD

**Issue by CordlessWool** [wireapp/wire-desktop#379]
When I write message I have tipped one or two word before it appear on the textbox. I am no slow tipper but also not the fastest. 

If it is important. I am using a Ubuntu 16.04 with latest updates. 
I also use Atom some times, which also use electro as basement, there I have no problems.

**Comment by ConorIA** [comment]
I haven't encountered this before. Do you have hardware acceleration enabled in Atom? I know that on one of my machines with an old AMD card, it was sometimes faster to run with `--disable-gpu` to disable hardware accel. You might try that, at least to eliminate it as a culprit.

**Comment by ffflorian** [comment]
Closing this in reference to https://github.com/wireapp/wire-desktop/issues/479#issuecomment-283332426.
