### ISSUE TITLE
[Linux] The about window stays on top of everything

### ISSUE THREAD

**Issue by Porkepix** [wireapp/wire-desktop#3803]
Wire version: Version 3.16.2923
Wire for web version: Wire for Web Version 2020.04.07.1425
Operating system: ArchLinux. Rolling release.

What steps will reproduce the problem?

1.  Open the About dialog
2.  Alt-tab to anything else

What is the expected result?
Other windows should be on foreground, and Wire behind it.

What is the actual result?
Other windows take place on foreground, but the About window from Wire keeps getting on top of those and is shown on foreground.

Environment is latest Gnome running on Wayland. Didn't tested other environments.

**Comment by GeckoEidechse** [comment]
Same here on Ubuntu 20.04 LTS with X.org:
![image](https://user-images.githubusercontent.com/40122905/83363830-e034be00-a39c-11ea-9ca0-acc4450c9b3d.png)

Note that the window that is focused is the Firefox window behind the about dialogue of Wire. The expected result would be for Firefox to cover both the Wire window (which it does) and the about dialogue of the Wire window (which it doesn't).

***

Also @ffflorian, this is NOT a feature request but a **bug report**. Would be very much appreciated if you could update the label accordingly <3

**Comment by ffflorian** [comment]
@GeckoEidechse this is not a bug report since this was added intentionally in https://github.com/wireapp/wire-desktop/pull/1101. I will talk to the team to see if we can revert this change.

**Comment by ffflorian** [comment]
@GeckoEidechse @Porkepix in the next release of Wire for Desktop the about window will not stay on top anymore.
