### ISSUE TITLE
Add push-to-talk for gamers

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-desktop#382]
Ad push-to-talk to voice calls for gaming purposes f. e.

**Comment by helenakos** [comment]
Thanks for your request. We don't have plans to implement this at the moment, therefore I will close this issue.

**Comment by AlexFolland** [comment]
I'm also interested in this, but not just for gaming.  I want to be able to be silent unless I'm talking, so I can sniffle or sneeze without disrupting the conversation.
