### ISSUE TITLE
PSA: DO NOT UPDATE WIRE ON DESKTOP! - Possible security vulnerability.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#3833]
![image](https://user-images.githubusercontent.com/388716/80649528-3a5dfe80-8a40-11ea-9e6c-0fcbc32071b1.png)

While it's very tempting to click **UPDATE NOW** to get rid of that giant orange alert notification, 

Github shows there has been **no new version** in the last 24 days.
https://github.com/wireapp/wire-desktop/releases

1. **You should never update software automatically,**
2. You should always wait a bit and review that **WHAT"S NEW** makes any sense.  Currently it doesn't, At all.

**Comment by Transisto** [comment]
Update: It must be related to that other, nobody gives a fuck, minor update on the web version that got forced on us.

- Mute state was not considered when muting before the call got connected.
- Auto submit first SSO login if default SSO code is present (custom backends)
https://medium.com/wire-news/wire-for-web-2020-04-29-89c12831b8e1

**Comment by ffflorian** [comment]
@Transisto
As already explained in https://github.com/wireapp/wire-desktop/issues/3802, this banner notifies the user that there is a new **WebApp** version available. As you can see in https://github.com/wireapp/wire-webapp/releases, we just released a new version of the WebApp.

**Comment by Transisto** [comment]
> @Transisto
> As already explained in #3802, this banner notifies the user that there is a new **WebApp** version available. As you can see in https://github.com/wireapp/wire-webapp/releases, we just released a new version of the WebApp.

You're still sending people to a page with nothing relevant on it, "WHAT"S NEW"
