### ISSUE TITLE
Permanent Rooms/Channels

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#385]
Similar to Discord, it would enable Gamers to use Wire for this purpose.

Similar: #382

**Comment by alien2003** [comment]
anyway Wire is not a good solution for games. It's not low-latency like Mumble or Discord

**Comment by tmikaeld** [comment]
That's actually incorrect, they use the same tech. Both use Electron + WebRTC

**Comment by ConorIA** [comment]
Is that much of a use case here? There are a lot of apps in the gaming sector. How would Wire pull users from those other apps?

**Comment by tmikaeld** [comment]
@ConorIA I think that if Wire can get a hold of the business users, they can wire that into gaming when the platform has matured and they have added third-party-integrations. That, coupled with privacy, encryption and open source (unlike competitors) - i really think it can work.

**Comment by Strit** [comment]
Discord is a much better solution for gamers at this point.

Only downside to Discord is that it's not Open Source and you can't host a/the server your self.

**Comment by MadEgg** [comment]
Discord lacks any kind of privacy and encryption. All chat is disclosed to all current and future users of a server, and the company behind it.

On the other hand: Wire can't be self-hostes either.

Discord mobile app is no match for Wire. I use Discord with a group of gaming buddies, if Wire would support low latency in-game voice chat channels, I could get them to switch.

Still, I have to agree that it's quite a deviation and shouldn't be a priority in my opinion.

**Comment by Strit** [comment]
Most gamers do not care very much about encryption though. At least not in the games I've played with people. They want something easy to setup and use.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by pYFZOS5** [comment]
https://github.com/wireapp/wire-android/issues/2042

**Comment by pYFZOS5** [comment]
https://github.com/wireapp/wire/issues/360
