### ISSUE TITLE
[Desktop - Windows] Checksums do not match

### ISSUE THREAD

**Issue by fl4w** [wireapp/wire-desktop#3850]
Wire version: 3.16.3562
Wire for web version: 2020.04.29.1041
Operating system: Windows 10
Which antivirus software do you have installed: 

What steps will reproduce the problem?

1.  Go to https://wire-app.wire.com/win/prod/WireSetup.exe
2.  Download the .exe files
3.  Generate SHA256 checksum locally
4.  Compare the checksum against the one written on the download page, under "Details"

What is the expected result?

Locally generated SHA256 checksum matches the one written on the download page (under details)

What is the actual result?

The checksum does not match

Please provide any additional information below. Attach a screenshot if possible.

By inspecting the installer, I noticed it reports the version 3.14.3539 even if the software (once installed) reports 3.16.3562. Is it possible that the checksum written on the download page refers to the new build but the download link still points to the previous version (which was updated as soon as I installed the desktop app)?
The application run smoothly but I would like to be sure if I actually downloaded the official app.

Thank you in advance for your reply.

**Comment by ffflorian** [comment]
Hi @fl4w,
thank you very much for the report. There was a small mixup with uploaded files - it should now be fixed.

If in doubt, you can also always check https://github.com/wireapp/wire-desktop/releases. With every Windows release, there is an additional file called `sha256sum.txt.asc`. How to verify our releases is described [in the Wiki](https://github.com/wireapp/wire-desktop/wiki/Authenticity).
