### ISSUE TITLE
Links act as relative links inside Filesystem

### ISSUE THREAD

**Issue by Wurzelkoch** [wireapp/wire-desktop#3853]
Operating system

Debian 10
Wire-Desktop Version 3.16.2923
Wire for Web Version 2020.04.29.1041
What steps will reproduce the problem?

    Send or receive any link
    Click on it

What is the expected result?

External browser opening and displaying whatever that link led to.
What is the actual result?

An error message popup:
/home/user/https:/my.link/complete_path.html: Datei oder Verzeichnis nicht gefunden

**Comment by Wurzelkoch** [comment]
Does not occur with wire-desktop 3.15 and same wire-webapp version.

**Comment by ffflorian** [comment]
Hi @Wurzelkoch,
is it possible that you forgot to add a second `/` after `https:/`?

Seems like you sent the text `https:/my.link/complete_path.html`, which is not a valid URL.

**Comment by Wurzelkoch** [comment]
No, as you see, i copy-pasted the link to your comment into wire, send it and then clicked on it. This is the result. When I copy the link from wire and paste it into the browser, it works fine.
![WireBug](https://user-images.githubusercontent.com/9682300/81054560-5392ff00-8ec7-11ea-82b6-01d60ed1b1f5.png)

**Comment by ffflorian** [comment]
Ah, I see. Thanks, I'll investigate.

**Comment by ffflorian** [comment]
@Wurzelkoch I can't reproduce this behavior. Is the link still correct after you pasted it?

**Comment by Wurzelkoch** [comment]
Turns out this is a bug with Debian. The same problem happens to the owncloud client.

**Comment by ffflorian** [comment]
Thanks for the info @Wurzelkoch!
