### ISSUE TITLE
Chat group icon

### ISSUE THREAD

**Issue by lk16** [wireapp/wire-desktop#387]
It would be nice if each chat would have an icon, similar to whatsapp. For group chats this is could be chosen by the group members and for 1:1 chats this would be the icon of the other people.

Thanks for putting your time in this wonderful project!

**Comment by helenakos** [comment]
This is being changed in the very near future, the conversation list is undergoing big changes. Stay tuned and update your clients regularly :) 

Closing this issue as part of cleanup.

**Comment by Konpaku-LVX** [comment]
its been 3 years where are these very near changes?
