### ISSUE TITLE
Ubuntu 20.04 and other spins

### ISSUE THREAD

**Issue by salemboot** [wireapp/wire-desktop#3880]
You may want to update the readme.
For Ubuntu 20.04
sudo apt -y install yarnpkg
git clone https://github.com/wireapp/wire-desktop.git
cd wire-desktop
yarnpkg
yarnpkg start

.....
Thanks

Wire version: 
Wire for web version: 
Operating system: 
Which antivirus software do you have installed: 

What steps will reproduce the problem?

1.  ...
2.  ...
3.  ...

What is the expected result?

...

What is the actual result?

...

Please provide any additional information below. Attach a screenshot if possible.

...

**Comment by ffflorian** [comment]
Hi @salemboot, the official yarn executable is still called `yarn`, see https://yarnpkg.com/getting-started/install.
