### ISSUE TITLE
"This server can't be reached" when YouTube preview can't be loaded

### ISSUE THREAD

**Issue by Bust3D** [wireapp/wire-desktop#3898]
Hello dear devs.

i have this screen on wire when someone try to send me youtube clip and there is no close button.
Please put a close button to this error message.

![image](https://user-images.githubusercontent.com/9987318/76164919-ee36c200-6152-11ea-9063-c8ff28360fb6.png)

I cant use my WIRE anymore if this cannot be closed.
And before someone write me that i should allow this host to access form my network i will not do this.

Kind Regards.

**Comment by ffflorian** [comment]
Hi @Bust3D, which version of Wire are you using? I can't reproduce this behavior on version 3.18.

**Comment by Bust3D** [comment]
Hi @ffflorian, it seems to be fixed, because me too no more got this error. And i use every time the latestWire from Android Playstore or Desktop also updated to last. Desktop Version 3.18.3660 , Android 3:50:922

**Comment by ffflorian** [comment]
Alright, good to hear :)
