### ISSUE TITLE
Add new langauge to wire platform

### ISSUE THREAD

**Issue by valaria247** [wireapp/wire-desktop#3959]
Since months i tried to contact wire through all support emails and crowdin for request to add new language but none of them respond However crowdin maintainers silently approve when asked to join for translate existing languages. It's disappointing to see that wire team irresponsible like that.

**Requested language**
Sinhala - enable for all projects (10)

**Is it difficult to do?**
No. only few steps to enable new language in crowdin **(several clicks)** However you can add that language to source codes later if difficult to spare some minutes for it or i can PR.

**Does that langauge available on other products or services?** 
Windows, Android, Gmail, Hotmail and more. You can check that as well.

**Comment by ffflorian** [comment]
Hi @valaria247, I added Sinhala to the Wire Desktop project on crowdin.

**Comment by valaria247** [comment]
> Hi @valaria247, I added Sinhala to the Wire Desktop project on crowdin.

@ffflorian Can you inform someone to enable 'Sinhala' language for below projects soon? Desktop project has few strings then only takes some minutes to finish. I noticed "Astrid Pahl" has access to all projects.

https://crowdin.com/project/wire-integrations
https://crowdin.com/project/wire-team-settings
https://crowdin.com/project/wire-account
https://crowdin.com/project/wire-webapp
https://crowdin.com/project/wirecom
https://crowdin.com/project/wire-launch
https://crowdin.com/project/wire-cs
https://crowdin.com/project/wire-android
https://crowdin.com/project/wire-ios
