### ISSUE TITLE
Big Audio clip download

### ISSUE THREAD

**Issue by elthanor** [wireapp/wire-desktop#396]
On the desktop app when a big audio clip is sent to me(in my case from android app of wire) and it is loaded then there is the option to download it. When i click download then nothing happens.

Windows 10 x64
Wire 2.11.2673

**Comment by herrmannplatz** [comment]
Can you play it?

**Comment by elthanor** [comment]
@herrmannplatz nope i cannot play it. Also tried on ubuntu x64 with v.2.11.2685 and the problem is there too
