### ISSUE TITLE
No portable version?

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#397]
Only installer version is a show stopper.

related: qtox.github.io provides installer AND portable.

**Comment by lightswitchr** [comment]
Don't need a portable version. Use https://app.wire.com instead.

**Comment by maximbaz** [comment]
For curious minds, there is a way to package app in [AppImage](http://appimage.org/) format, which is basically a portable version for Linux. 

That being said, I double the suggestion to just use website.

**Comment by ConorIA** [comment]
@maximbaz, I almost suggested the AppImage too (btw Wire provides AppImage bins on the download page!) but figured the request was more about Windows. 

In terms of privacy, does the webapp cache anything on the host system that wouldn't get flushed with a simple "clear private data"?

**Comment by maximbaz** [comment]
> btw Wire provides AppImage bins on the download page!

Wow I've never noticed that, cool!

> In terms of privacy, does the webapp cache anything on the host system that wouldn't get flushed with a simple "clear private data"?

You will find this page interesting to read: https://github.com/wireapp/wire-webapp/issues/688
In short, if you don't enable "Remember me", nothing will be cached after "Log out".

**Comment by githubbantor** [comment]
webpage version is not usable via tbb. https://github.com/wireapp/wire-webapp/issues/722

**Comment by githubbantor** [comment]
I'm talking about zip/rar/7z format, not AppImage. I'm expecting a windows portable version.

**Comment by sergeevabc** [comment]
+1 for Windows Portable.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
