### ISSUE TITLE
Wire fails to start after update to 2.11.2701; Likely an incompatibility with Electron

### ISSUE THREAD

**Issue by bernandosoares** [wireapp/wire-desktop#398]
After upgrading to 2.11.2701, Wire fails to start with this message being printed to STDOUT:

```path.js:202: Uncaught TypeError: Path must be a string. Received undefined```

After googling the message a bit, it seems like the error occurs when there is an unaccounted-for API break between Electron and the codebase. Maybe downgrade electron for now?

If it's any help, my system is Arch Linux x86_64 with GNOME 3.22.

**Comment by nvllvs** [comment]
Same problem here.

**Comment by lipis** [comment]
Thanks for the report guys.. It's a beta version anyway and we won't release anything official with it, just checking with every OS what is breaking.. also there are issues on macOS.

**Comment by herrmannplatz** [comment]
Thanks for reporting. Should be fixed with #401

**Comment by ConorIA** [comment]
@bernandosoares, @nvllvs, @user1791, sorry about that! The fact that this made it into the PKGBUILD was my fault. I'm the maintainer of the PKGBUILD, but I wrote a script to automatically update and push the package to the AUR. The script makes sure the package can build and install, but doesn't actually make sure it can run. (Oops!) I've added a check function to the makepkg to avoid this issue in the future. Sorry it took me so long to respond too, it seems my mail server decided I didn't need to get any email these past couple of days!  AUR package is now 2.11.2703.

**Comment by maximbaz** [comment]
@ConorIA is your script monitoring new releases automatically, or you are manually triggering it? I was looking recently for implementing automatic monitoring for a different project, I would be very interested to learn how you did this 🙂 I would actually be curious to have a look at your script in any case, is it possible for you to publish it somewhere, maybe temporarily?

Sorry for the offtopic 🙂

**Comment by ConorIA** [comment]
@maximbaz, happy to share. It's a bit of a mess though. 

https://gist.github.com/ConorIA/f34b4437f955971b3628c76746517a20

The weird "oldpure" bit is there because the Zazu devs don't always tag the most recent version last, so that is to prevent the script from accidentally downgrading. Everything else should be pretty easy to follow.

**Comment by ConorIA** [comment]
P.S. I trigger the script manually, but it is written such that it requires no interaction, so I could set it on a systemd timer.
