### ISSUE TITLE
Add offline support

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#40]
The Atom desktop app cannot work without network on Windows.

Expected: be able to browse previous conversations and  so on. Even be able to send offline messages (see https://github.com/wireapp/wire-ios/issues/197)

**Comment by lipis** [comment]
I think you mean Wire :P Not the easiest feature to achieve, but it's something that quite a few people asked us already..

**Comment by IpsmLorem** [comment]
No I really meaned Electron/Atom Wire desktop app :p (http://electron.atom.io/).
Chrome (as the browser into Electron/Atom) ecosystem could reach that goal: https://developer.chrome.com/apps/offline_apps

**Comment by lipis** [comment]
Oh yes..! Still not the easiest task though.. :)

**Comment by IpsmLorem** [comment]
No pain, no ga.. glory ! ;D

**Comment by gregor** [comment]
Renaming to identify more easily

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by doctorcolossus** [comment]
Why is this feature difficult to achieve?
Are conversations stored server-side?
