### ISSUE TITLE
Which is better: qTox and Wire? And why?

### ISSUE THREAD

**Issue by githubbantor** [wireapp/wire-desktop#400]
I was using qTox for a long time. I used "Wire" today and it was impressive.
It support desktop, android, iOS, and webapp. "Tox" support only desktop and android
and Antox is unusable condition(crash instantly, see their issues).
Why not collaborate Wire development instead? If you really think qTox is way better than Wire, then tell me, I want to know(not insulting, just for discussion).

https://wire.com/en/
https://github.com/wireapp

**Comment by githubbantor** [comment]
https://github.com/qTox/qTox/issues/4125

**Comment by lightswitchr** [comment]
I think you may have posted this in the wrong place. This is an issue tracker for Wire, and it's not really the best place for discussion about other chat software.

**Comment by lipis** [comment]
We are obviously biased and it won't make much sense to discuss any other chat app that exists in the wild here.. Therefore I'll close this issue..
