### ISSUE TITLE
[Linux] Not minimized at startup

### ISSUE THREAD

**Issue by KimHono** [wireapp/wire-desktop#4011]
Hi !

Since about a week, Wire isn't launched minimized at startup anymore.
Usually I'm using the command : `/usr/bin/wire-desktop --startup`.

My system is Linux Arch x86_64
Linux version :  5.7.6-arch1-1
Wire version : 3.18.2925

**Comment by ffflorian** [comment]
I can't reproduce this on Debian. When starting with `--startup` it starts minimized for me.

**Comment by KimHono** [comment]
Hi !
As you, I'm also using GTK with Mutter.
But, my desktop manager is frequently changing because it's a beta version.
