### ISSUE TITLE
Screen Share in MacOS app (desktop to desktop) leads to audio failing

### ISSUE THREAD

**Issue by waltsims** [wireapp/wire-desktop#406]
after using screen share between two MacOS devices, the audio cuts out

**Comment by bernandosoares** [comment]
same on linux, except switching to desktop sharing mode on an ordinary video call cuts the audio out on the end of whoever switched to desktop mode

**Comment by mythsunwind** [comment]
Unfortunately this is a known bug and not specific to a platform. We are currently working on it. In the meantime there is a workaround by starting an audio call (not a video call) and then switch to screen sharing. You will not loose audio in this case. Sorry for the inconvenience!

**Comment by gregor** [comment]
This is a known issue in the webapp side of things (https://github.com/wireapp/wire-webapp/issues/219)

**Comment by gregor** [comment]
https://github.com/wireapp/wire-webapp/pull/915

**Comment by gregor** [comment]
This has been addressed and will no longer happen once we enable screensharing again with our next release.
