### ISSUE TITLE
Contact discovery privacy

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#41]
When looking for contact, one can browse the directory and get profile picture of any user.

It would be better to not display the profile picture in the search menu and display only when people are connected.

**Comment by lipis** [comment]
But sometimes it's easier to recognize something familiar when looking for a common name :)

**Comment by helenakos** [comment]
Hey @IpsmLorem, duly noted, we will take this into consideration. But I have to agree with @lipis , it's easier to recognize :)

**Comment by IpsmLorem** [comment]
Privacy against friendlyness, as often :)
In that case, give users the option to hide their pricture from public search.

**Comment by helenakos** [comment]
Yes we had previous discussions about giving users the option to hide not only the picture but hide themselves from search.

**Comment by IpsmLorem** [comment]
That's a good idea, since there is a way (at least in the webapp/desktop) to get a unique (anonymous ?) invitation link.
