### ISSUE TITLE
Linux - Webcam upside-down

### ISSUE THREAD

**Issue by d7rk** [wireapp/wire-desktop#410]
Hi,

With wire-desktop 2.11.2703-1 on an Asus U36SG with linux 4.8.17-1-MANJARO x86_64, my webcam displays the image upside-down.
It works properly with applications using libv4l2, and those using v4l1compat.so (such as firefox) with LD_PRELOAD. 
However `Exec=LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so wire`  does not work with wire-desktop.

In any case, thanks for this great app!

**Comment by mythsunwind** [comment]
Hi, we recently included Chrome 54 in our builds, might be that this is the reason. We have a new build 2704 were we downgraded to Chrome 53. Would it be possible for you to re-check and see if the issue is still there?

**Comment by d7rk** [comment]
Hi @mythsunwind ,
Thank you for the swift reply (sorry for the delay in replaying, I have this issue only on one computer).
The problem still exists in 2.11.2715-1.
Cheers,
