### ISSUE TITLE
Debian: sigsys_handlers.cc:**CRASHING**

### ISSUE THREAD

**Issue by berni421** [wireapp/wire-desktop#4131]
Wire version: 3.19.2928
Wire for web version: n/a
Operating system: Debian GNU/Linux 9 (stretch)
Which antivirus software do you have installed: eset 4.0.93.0

What steps will reproduce the problem?

1.  ... start wire-desktop, open main window, login prompt appears

What is the expected result? Previous login details should be restore and messages displayed.

What is the actual result? 2. login prompt clears and repeat.

NB: --no-sandbox option works as expected.

Please provide any additional information below. Attach a screenshot if possible. 

[wire-bug-logs.txt](https://github.com/wireapp/wire-desktop/files/5057414/wire-bug-logs.txt)

Logs

**Comment by ffflorian** [comment]
Hi @berni421, you seem to have a problem with your mesa drivers. I'm not sure if this is connected but it doesn't look like a problem we can solve. I also can't reproduce this on Debian so this is at most an Electron problem or a problem on your machine.

**Comment by berni421** [comment]
Huge thanks - I was a bit stuck where to look.

Intriguingly I have another laptop with Debian 10 Buster. Wire-desktop Version 3.19.2928 is working just fine on that machine. I'll home in on the mesa parts.  I've not come across Electron before - gives me something to investigate too .. possibly right now the problem fix is "just" to upgrade to buster.

More to follow.

**Comment by berni421** [comment]
I was unable to pin down the fault but can confirm at least upgrading to Debian 10 fixes. I can see that the glx packages are different. Perhaps a documentation update is needed to clarify which gui versions are tested before release might help others.

This is a bit generic ... https://github.com/wireapp/wire-desktop/wiki/How-to-install-Wire-for-Desktop-on-Linux
