### ISSUE TITLE
Indicator icon notification

### ISSUE THREAD

**Issue by fungs** [wireapp/wire-desktop#416]
I use the wire app under Linux and it is really easy to miss post or calls when you are not looking at the screen or coming back to your computer after a while. So IMO wire should be able to (a) change the tray indicator icon if new calls or messages arrived and (b) be able to pop up the application when minimized to the tray.

**Comment by ConorIA** [comment]
The tray icon does change, but the current published build contains a bug preventing it from changing. It is fixed in the upstream code.

**Comment by fungs** [comment]
Then, I suppose to add the popup feature as well, that is how many chat programs behave (making it optional). Thanks for the great app!

**Comment by maximbaz** [comment]
But the desktop notifications are also supported, unless you turned them off in the settings.

Besides the tray icon and desktop notifications, Wire also sends urgency hint (at least, for now #371), which if interpreted by your desktop environment provides yet another way to notify you about updates.

**Comment by fungs** [comment]
I get your point @maximbaz, the desktop should handle the notification, fine. However, it's quite inconvenient that I have to double-click the tray icon to pop up the chat window, which in my case opens minimized, so I have to double-click, then click on the minimized window to open it. This might seem minor, but if you have to do this really often per day, this is annoying.

Using MATE desktop environment.

**Comment by maximbaz** [comment]
Sorry I guess I simply don't understand what you mean by "popup feature" then :)

You want wire to be automatically maximized and brought in the foreground as soon as any message appears?

**Comment by fungs** [comment]
> You want wire to be automatically maximized and brought in the foreground as soon as any message appears?

This is how many messengers work, because you don't need to switch from keyboard to mouse to keyboard.

However, the minimum would be that the message windows opens **not minimized** when you (double)click on the tray icon, so that you are ready to type.

Please note: I'm not talking about maximizing the window, it should just not be minimized and it should be the active window.

**Comment by maximbaz** [comment]
> This is how many messengers work...

Interesting, thanks for explanation - I really didn't know that. I assume these messengers usually have a pretty narrow window? It's just hard to imagine that it's not annoying when you are browsing internet and every 5 seconds your browser is suddenly becoming fully covered by a messenger window. But if it's a small narrow window on the side, I can see how this can be useful...

> However, the minimum would be that the message windows opens not minimized when you (double)click on the tray icon, so that you are ready to type.

Yeah, now I get what you mean, that definitely sounds like an issue to be fixed.

**Comment by fungs** [comment]
Would be nice that you can choose, there is a whole palette of options with modern window managers and it's all about a good balance between getting disturbed and overseeing incoming chats. That's why sometimes you can choose to open a window, but not in the foreground. This way, it's just alt+tab for most systems. Some chat programs keep notifications open in the tray and when you click on them, the windows opens. Anyways, this can get messy and it's all about usability, but maybe there is an easy way to set the behavior the way the user actually likes it without having to go to deep into platform specifics.

**Comment by ConorIA** [comment]
#419 should address *most* of this issue. While the app won't appear automatically when a new message appears, clicking on the notification will bring the app to the foreground, ready to type. Same goes for clicking on the tray icon and when trying to launch a second instance of Wire.

**Comment by lipis** [comment]
As this is already fixed.. I will close this issue for the time being.

**Comment by lipis** [comment]
The version 2.11.2722 is finally released :) https://wire.com/download/

**Comment by anatoli26** [comment]
The new version adds a red dot to the tray icon in Ubuntu, but doesn't add a badge to the launcher icon (highly desired, e.g. like Thunderbird does), nor opens the Wire window (put it in front, but do NOT steal the focus; this behavior could be an option as some would not want it), so the red dot is the only clue for now.

**Comment by anatoli26** [comment]
Just dug it up a bit, here is the same request with a patch in Electron: https://github.com/electron/electron/issues/4193, and here is the official Ubuntu Unity API documentation: https://wiki.ubuntu.com/Unity/LauncherAPI

**Comment by maximbaz** [comment]
To add to your discovery, https://github.com/electron/electron/issues/4193 is already implemented in Electron: 

[app.setBadgeCount(count)](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetbadgecountcount-linux-macos), works on Linux (only Unity) and macOS.

**Comment by anatoli26** [comment]
So, looks like an easy fix?

**Comment by lipis** [comment]
Can someone please open a new issue for it?

**Comment by anatoli26** [comment]
Done #469
