### ISSUE TITLE
Clicking on the notification doesn't bring app window to foreground

### ISSUE THREAD

**Issue by norstbox** [wireapp/wire-desktop#4160]
Wire version: 3.19.3731
Wire for web version: 2020.07.24.1346
Operating system: Windows 10, 1909
Which antivirus software do you have installed: none

## What steps will reproduce the problem?

1.  Minimize or "close to tray" Wire window
2.  Wait for incoming message or call
3.  Click on the corresponding notification

## What is the expected result?

Wire window is brought to foreground. I.e. same behavior as in wire-webapp

## What is the actual result?

Clicking on the notification does nothing

**Comment by ffflorian** [comment]
Hi @norstbox, thanks for reporting. We are aware of the issue - it's an Rlectron bug, see https://github.com/electron/windows-installer/issues/296.

We are working on providing a workaround.
