### ISSUE TITLE
Feature request: keyboard shortcut for switching conversations

### ISSUE THREAD

**Issue by tnguyen14** [wireapp/wire-desktop#423]
It would be great if I could switch between my conversations using the same keyboard shortcuts as tab switching, such as `ctrl+tab` and `ctrl+shift+tab`, or `cmd+shift+]` and `cmd+shift+[` on macOS.

**Comment by maximbaz** [comment]
Just to point this out, the current shortcut is <kbd>Alt+Shift+⬆/⬇</kbd>. 

Please join me in complaining that this is... _not the most convenient_ key combination :smile:
https://github.com/wireapp/wire-webapp/issues/733

**Comment by manasb** [comment]
@maximbaz Thanks for pointing out the shortcut. I had tried `ctrl/alt+tab` and was disappointed.

**Comment by tnguyen14** [comment]
@maximbaz hmm that combination isn't working for me. Are you on Windows or macOS?

**Comment by maximbaz** [comment]
These shortcuts are advertised to work on all platforms, including Web. I'm personally on Linux.

```
Previous Conversation	⌥⌘↓	alt + shift + ↓
Next Conversation	⌥⌘↑	alt + shift + ↓
```

Docs: https://support.wire.com/hc/en-us/articles/203673061-What-shortcuts-can-I-use-on-MacOS-Windows-and-Wire-for-Web-

**Comment by GopianiS** [comment]
Slack uses Ctrl+K which gives an input box to type the name of the chat/person and also shows a list of unread chats for convenience

![image](https://cloud.githubusercontent.com/assets/15341271/22879974/43e0d15c-f1d8-11e6-908e-21a63b074e48.png)

**Comment by bennyn** [comment]
Very good input! Also configurable shortcuts would be nice (so that everyone can use his/her favorite). 

Unfortunately our product owners don't plan to redesign keyboard shortcuts any time soon (https://github.com/wireapp/wire-webapp/issues/94#issuecomment-290714090). I will close this ticket here until we have other news.
