### ISSUE TITLE
Flatpak package for Linux users

### ISSUE THREAD

**Issue by grafenhofer** [wireapp/wire-desktop#424]
Please provide a flatpak package for Linux users (http://flatpak.org/). Flatpak is currently taking off as a 3rd-party package format supported on many distros. This makes providing rpms etc. for different distros superfluous.

**Comment by maximbaz** [comment]
@grafenhofer could you please elaborate what advantage(s) will Flatpack packages provide comparing to the AppImage ones which are [already available](https://wire.com/download/) today? I'm asking simply to learn, they both seem to serve the same purposes, unless I missed some significant competitive advantages of Flatpack?

**Comment by grafenhofer** [comment]
I have to admit, that I know too little about AppImage to make a fair comparison.

What I love about flatpak is integration into the gnome software center (packages provide appstream metadata), which includes support for automatic updates including the installed flatpak packages. Keeping your software updated, does not require to different systems (e.g. built-in updaters,...). Furthermore, Flatpak is more decentralized than Snap.

**Comment by grafenhofer** [comment]
It seems that KDE is leaning towards adopting flatpak: https://vizzzion.org/blog/2017/02/plasma-meeting-web-browsers-and-app-bundles/

**Comment by ConorIA** [comment]
Wire uses electron-builder to generate the packages. Flatpak support has been requested there (https://github.com/electron-userland/electron-builder/issues/512), but I don't think it is actively being worked on. You should add your voice there as well.

**Comment by probonopd** [comment]
> It seems that KDE is leaning towards adopting flatpak

...and AppImage: KDevelop, Krita, Kexi, digiKam and many other KDE apps are already provided as AppImages. More coming!

**Comment by grafenhofer** [comment]
@probonopd: AppImage provides/will provide out of the box integration in GNOME and KDE software centers? I have not heard of that yet. This is a huge usability improvement over other distro-independent package formats (e.g. snap). See http://www.jgrulich.cz/2017/02/14/kde-discover-flatpak-backend/

**Comment by lipis** [comment]
We are depending on electron-builder. Also since we don't have the resources to support it at the moment and AppImage is covering quite a few distributions.. we will close this issue.

**Comment by probonopd** [comment]
@grafenhofer 
> AppImage provides/will provide out of the box integration in GNOME and KDE software centers? I have not heard of that yet.

Discussion is [underway](https://github.com/probonopd/AppImageKit/issues/48). Want to contribute coding? (I won't do it myself, but support anyone doing it)

**Comment by fbruetting** [comment]
This may help:
https://github.com/endlessm/electron-flatpak-base-app
http://blog.manuq.com.ar/posts/building-electron-apps-offline-for-flathub/

Would be nice if you could flatpak this and make it available via flathub.org! Then we don’t have to do things manually, plus it has many more advantages.

**Comment by ConorIA** [comment]
I was playing around with https://github.com/endlessm/electron-installer-flatpak/, but the last step kept failing. Here are the commands I was running, if anyone wants to give it a shot: 

# On Fedora docker image

``` bash
# This works on a fresh Fedora Docker image with a tarball of the latest release. Note that the bundle task fails if run with root rights, so I needed to add a non-root user to this script. Don't blindly copy and paste! This is based on: https://github.com/endlessm/electron-installer-flatpak

dnf install -y flatpak flatpak-builder gcc-c++ git nodejs sudo wget

adduser -m maker
cd /home/maker
sudo -u maker wget https://codeload.github.com/wireapp/wire-desktop/tar.gz/release/2.15.2751
sudo -u maker tar -xvf 2.15.2751
cd wire-desktop-release-2.15.2751

npm install -g electron-installer-flatpak
sudo -u maker npm install
sudo -u maker $(npm bin)/grunt 'clean:linux' 'update-keys' 'release-prod' 'bundle'

$(npm bin)/electron-packager . wire-desktop --platform linux --arch x64 --icon resources/icons/256x256.png --out wrap/build

$(npm bin)/electron-installer-flatpak --src $PWD/wrap/build/wire-desktop-linux-x64/ --dest $PWD/wrap/dist/ --arch x64 #FAILS when flatpak-builder is called!
```

# On real machine (Manjaro)

```
# This was on my production Manjaro machine. You might need to install some missing dev libs or something.

sudo pacman -S flatpak
sudo pacman -S --asdeps --needed elfutils patch
sudo npm install -g npm@5.4 # this is messy, but otherwise electron-packager fails

wget https://codeload.github.com/wireapp/wire-desktop/tar.gz/release/2.15.2751
tar -xvf 2.15.2751
cd wire-desktop-release-2.15.2751

sudo npm install -g electron-installer-flatpak
npm install
$(npm bin)/grunt 'clean:linux' 'update-keys' 'release-prod' 'bundle'

$(npm bin)/electron-packager . wire-desktop --platform linux --arch x64 --icon resources/icons/256x256.png --out wrap/build

$(npm bin)/electron-installer-flatpak --src $PWD/wrap/build/wire-desktop-linux-x64/ --dest $PWD/wrap/dist/ --arch x64 #FAILS when flatpak-builder is called!
```

**Comment by DCKcode** [comment]
@ConorIA It seems either Wire or the Electron Flatpak packaging processes have since been fixed using the procedure you described, and you can now build a `io.atom.electron.wire-desktop .flatpakref` file - tested using the Wire 3.0.2816 tarball and Electron Flatpak Installer 0.80 on Fedora 27.
However, if you install and run the resulting Flatpak you get the following error:
```
$ flatpak run io.atom.electron.wire-desktop 
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/app/lib/io.atom.electron.wire-desktop/resources/app/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/app/lib/io.atom.electron.wire-desktop/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (/app/lib/io.atom.electron.wire-desktop/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/app/lib/io.atom.electron.wire-desktop/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
It seems the resulting Flatpak is referring to an `/app` directory in the root of the file systems, which of course does not exist. The binary at `/var/lib/flatpak/app/io.atom.electron.wire-desktop/current/active/files/bin/wire-desktop` also symlinks to a non-existent `/app` directory.

Digging deeper, there *is* a binary executable `wire-desktop` file that is installed, at `/var/lib/flatpak/app/io.atom.electron.wire-desktop/x86_64/master/active/files/lib/io.atom.electron.wire-desktop/wire-desktop`. Running this file results in a different error:

```
$ /var/lib/flatpak/app/io.atom.electron.wire-desktop/x86_64/master/active/files/lib/io.atom.electron.wire-desktop/wire-desktop
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/var/lib/flatpak/app/io.atom.electron.wire-desktop/x86_64/master/9e961ee08b6f7fab5993eb3f20e17444846a3fecf15c32d8ec0156d6ef8b3a7c/files/lib/io.atom.electron.wire-desktop/resources/app/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/var/lib/flatpak/app/io.atom.electron.wire-desktop/x86_64/master/9e961ee08b6f7fab5993eb3f20e17444846a3fecf15c32d8ec0156d6ef8b3a7c/files/lib/io.atom.electron.wire-desktop/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (/var/lib/flatpak/app/io.atom.electron.wire-desktop/x86_64/master/9e961ee08b6f7fab5993eb3f20e17444846a3fecf15c32d8ec0156d6ef8b3a7c/files/lib/io.atom.electron.wire-desktop/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/var/lib/flatpak/app/io.atom.electron.wire-desktop/x86_64/master/9e961ee08b6f7fab5993eb3f20e17444846a3fecf15c32d8ec0156d6ef8b3a7c/files/lib/io.atom.electron.wire-desktop/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
I see no obvious candidate for this missing `index.js` file. Interestingly, the same error is also thrown when running the `wire-desktop` binary that is generated in the build process (.i.e. running `./dist/dist/wire-desktop-linux-x64/wire-desktop`).

It seems to be something to do with Wire's specific build configuration at this point. Unfortunately I don't know enough about Flatpak, Electron or Wire's build processes to proceed after this but I thought I'd share the progress.

**Comment by x80486** [comment]
I'm ready to submit a pull request for this work to Flathub. Is that OK? – @maximbaz or @lipis

If so, do you want **write access** to the final repository if everything goes fine (read: approach accepted, reviewed, repository created, etc.)?

**Comment by ConorIA** [comment]
Well done @x80486!

**Comment by ConorIA** [comment]
If this is a fairly simple solution, I'd really suggest that it get baked into the official release toolchain. @x80486, @ffflorian and @lipis are the folks you are looking for!

P.S. If Fedora moving away from RPMs? If this Flatpak is published, does it still make sense for me to maintain my copr repo?
https://copr.fedorainfracloud.org/coprs/conoria/wire-desktop/

**Comment by fbruetting** [comment]
Fedora aims to separate the system (organized in read-only layers) from applications (Flatpaks & containers) and user-data. You will still be able to layer RPM packages via `rpm-ostree install …` on top of the system layers, but that violates the separation quite a bit und thus should ideally just be done for rather core or system packages (I use this currently for fonts and neovim, for example). Real applications would be way better installed via flatpaks (and things like ngnix etc. in containers).

**Comment by x80486** [comment]
Hi @lipis and @ffflorian, I would like to merge the work for the Flatpak and this is the only relevant question that remains "unsolved" on my end. Is it possible you can chime in and let me know if any (or both) of you would like to have write access the final repository in FlatHub? It's a normal requirement that folks over there ask for this – and it's also fine if you don't want to. You can always request that later on; in the end you are the actual maintainers/makers of this software.

I will keep maintaining the Flatpak anyway :wink:

**Comment by ffflorian** [comment]
Thanks @x80486, I won't need access to the repository.
The fix for https://github.com/wireapp/wire-desktop/issues/1768 will come in the next release btw :tada:

**Comment by x80486** [comment]
OK, no problem! I'll move forward with the Flatpak artifact then and will delete the line that's patching the `Version` attribute in the Desktop Entry later on — that's an easy change.

For the record, if you (or anyone for that matter) wants access later on to the FlatHub's repository, just ask — I know I'm (sometimes a little bit) "pushy" 😉...but just saying 😄

**Comment by silvernode** [comment]
Thank you for creating the flatpak @x80486 since over time on rolling distros, the appimage seems to stop working probably due to constantly changing going libraries all over the place or something. Hopefully this flatpak proves to last. I have been using it now for a month so we will see.
