### ISSUE TITLE
Polish locale to WIRE

### ISSUE THREAD

**Issue by Xyroqs** [wireapp/wire-desktop#426]
Is it possible that soon will be WIRE in Polish language?

**Comment by maximbaz** [comment]
The interface is being translated by regular people, once the translation is ready it is integrated in the app.
The Polish translation is [70% complete](https://crowdin.com/project/wire-cs/pl), you may very well contribute to get it faster 😉

**Comment by ConorIA** [comment]
Wire translations happen in [Crowdin](https://crowdin.com/projects/wire). You can ask to join the project and contribute translations there!

**Comment by ConorIA** [comment]
@maximbaz ... Too fast, as usual!

**Comment by maximbaz** [comment]
I beat you by a whole minute 😄

**Comment by lipis** [comment]
As already mentioned.. translations are tracked on Crowdin :)
