### ISSUE TITLE
Context menu holds GIFs

### ISSUE THREAD

**Issue by TalviT** [wireapp/wire-desktop#428]
Hi,
I found a small bug in WIRE (2.11.2712) for Linux, this [GIF](https://imgur.com/a/UBBAE) shows the bug.
I'm running Antergos (x86_64 Linux 4.9.8-1-ARCH) using GNOME 3.22.
-- Talvi

**Comment by lipis** [comment]
Can you check if that is still an issue with 2.11.2722 https://wire.com/download/

**Comment by TalviT** [comment]
Yes, the bug still occurs in the updated version.

**Comment by herrmannplatz** [comment]
https://github.com/electron/electron/pull/8702

**Comment by gregor** [comment]
Electron has merged their fix and we have upgraded to a more recent electron release.
