### ISSUE TITLE
PPA for stable builds

### ISSUE THREAD

**Issue by darkwyrm** [wireapp/wire-desktop#430]
Could it be possible to publish Linux .deb files via a PPA so that users can get updates using the package manager?

**Comment by ConorIA** [comment]
Once set-up, this might be as simple as adding an extra task to the build process.
https://help.launchpad.net/Packaging/PPA/Uploading

**Comment by anatoli26** [comment]
Any ETA for this?

**Comment by RebelCoderRU** [comment]
We absolutely need PPA/Repo for .deb packages. for example, I installed Wire .deb file on 3 computers of my relatives + 2 computers of non-technical friends.

Now, to update to a latest build, I have to remote-in to 5 PCs, download new .deb file and install it. this leaves bad negative taste in generic users mouth.

Please organize this ASAP, so we can just install the first .deb file and it will link to your repos automatically, like 99.9% of other apps do.

**Comment by anatoli26** [comment]
@lipis, @gregor, could this be setup in the nearest future?

**Comment by lipis** [comment]
This definitely something that we are looking into it.. there is no committed date yet but we would like ta have it.

**Comment by aquatooth** [comment]
Yes please! Definitely look into setting up a PPA to publish Linux .deb files so that users can get updates using the package manager.
Users of Skype that are or have migrated to Wire really do need this as soon as possible.

**Comment by RebelCoderRU** [comment]
Agree! To much hassle for "moms and paps" kind of users without updates.

**Comment by aquatooth** [comment]
Manually updating a number of installations with version 2.12.2729 today

**Comment by lipis** [comment]
Point taken.. :)

**Comment by aquatooth** [comment]
ah, damn good to know your team is on this issue, as it will cause trouble for every single install on Linux.
in this case, i must remote into several boxes in order to upgrade it, but after PPA it will be 'set and forget' So, thank you and your team!

**Comment by RebelCoderRU** [comment]
Huston... Huston... we are loosing potential users.......

**Comment by RebelCoderRU** [comment]
We still need PPA/Repo :/

**Comment by aquatooth** [comment]
@RebelCoderRU Yes, posting in agreement especially as @ConorIA has posted what seems a straightforward method of ending the Linux manual update misery :)

**Comment by RebelCoderRU** [comment]
@aquatooth Sorry, but I am not sure If I understood what you meant... Is this being done now ?

**Comment by aquatooth** [comment]
@RebelCoderRU agree that your comment; 'We still need PPA/Repo'
I like 100% of Linux users do hope that this is being worked on now, but I cannot confirm that.
Just have to wait in 'manual update misery' until it is completed. Patience required!

**Comment by lipis** [comment]
It's on our list and we'll get to it soon, since the demand is growing :)

**Comment by aquatooth** [comment]
6 weeks?! yes many users hope that your team will get to it soon, otherwise, I guess you could wait until users get frustrated enough to go elsewhere, then your demand will cease to grow.

**Comment by RebelCoderRU** [comment]
Hmm.... tic-tac...

**Comment by lipis** [comment]
Step #1: https://github.com/wireapp/wire-desktop/pull/550

**Comment by ffflorian** [comment]
Related to https://github.com/wireapp/wire-desktop/issues/542.

**Comment by mythsunwind** [comment]
https://medium.com/@wireapp/a-step-forward-for-wire-for-linux-52f0538cac15

**Comment by anatoli26** [comment]
Great! Thanks
