### ISSUE TITLE
Occasionally no sound in video - then no image in video... (win app to win app)

### ISSUE THREAD

**Issue by DetlevCM** [wireapp/wire-desktop#433]
Ok, this has happened at least twice - and apparently the app has also updated?
(At least labels appeared)

My friend called me (video) and while the call was established, I could not hear my friend - however my audio was transmitted.
Next I called (audio only) - now we could hear each other, but when we turned on the video, I received only a black screen.

The third time, I started a video call and all worked...

I'm not sure why and how this is happening - and when it works, it works very well (which is most of the time overall).

**Comment by wangkesen** [comment]
I also get the same issue with regards to video, but it's not a one time issue it's happened about 50 percent of the time when using the desktop app. Changing to video when in an audio call or disabling video and then restarting -  both result in the app crashing
