### ISSUE TITLE
Screen sharing during video call causes no sound for the rest of the call

### ISSUE THREAD

**Issue by NikEfth** [wireapp/wire-desktop#437]
Hi, 
Just installed in two machines. One Ubuntu and one Arch. We shared desktops from Ubuntu and sound crashed.

**Comment by DetlevCM** [comment]
I just observed the same - on this occasion using Windows to Windows.

**Comment by wangkesen** [comment]
Also have this problem as well!

**Comment by gregor** [comment]
Closing as dupe of https://github.com/wireapp/wire-webapp/issues/219 and #406
