### ISSUE TITLE
An ARM64 build cannot be compiled

### ISSUE THREAD

**Issue by marek-lach** [wireapp/wire-desktop#4384]
Currently it seems a build for the arm64 architecture cannot be compiled. I am not really sure, however, what is stopping that.

**Comment by ffflorian** [comment]
Hi @marek-lach, electron-builder doesn't support ARM64, see https://github.com/electron-userland/electron-builder/issues/5095.

**Comment by basicasicmatrix** [comment]
ARM is now supported by electron. Any chance to include support, now with ARM computing becoming a mainstream trend?

**Comment by ffflorian** [comment]
See https://github.com/wireapp/wire-desktop/pull/5634
