### ISSUE TITLE
Multi account support

### ISSUE THREAD

**Issue by tommorris** [wireapp/wire-desktop#439]
It'd be useful to be able to have multiple Wire accounts/personas.

Use cases include having separate personal and professional accounts, or for people who use pseudonyms (e.g. online games, artists etc.).

This feature would put Wire a whole step further than similar apps (WhatsApp, Telegram, Signal etc.)

**Comment by helenakos** [comment]
@tommorris It's something we already discussed and considered. Stay tuned :)

**Comment by anatoli26** [comment]
Would be a killer feature

**Comment by jaredwray** [comment]
Do you need help with this?

**Comment by helenakos** [comment]
@jaredwray Not just yet, it's on the roadmap and will be designed and thought through once it's scheduled.

**Comment by gregor** [comment]
This is a feature we have added with our 2.15 releases. I am thus going ahead with closing this issue.
