### ISSUE TITLE
JavaScript Error: Unable to find tray icon

### ISSUE THREAD

**Issue by bkeys** [wireapp/wire-desktop#444]
My friend who uses windows says he has been getting recently; I tried to get more information about it but that was all he was able to tell me. Hopefully the error message will be of help.
![error](https://cloud.githubusercontent.com/assets/12195202/23087252/a4556ee2-f540-11e6-80d4-274b25298429.png)

**Comment by maximbaz** [comment]
@bkeys before investigating this further I would recommend your friend to upgrade the app and confirming that the issue persists. They are running v2.11.2673, and there have been 42 new releases since then. The current version is v2.11.2715.

**Comment by ConorIA** [comment]
That particular error happens when Electron can't find the tray icon. I've had this window pop up a couple of times when my app was updated, but I hadn't restarted it for a while. It might just be that the app has been updated and the client needs to be restarted.

**Comment by ffflorian** [comment]
@bkeys Can you check if this error message still appears for your friend?

**Comment by ffflorian** [comment]
@bkeys Seems like this issue is fixed? I'll close this here. Feel free to reopen if the bug still exists.
