### ISSUE TITLE
Left panel width changes at certain window size

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#445]
Hi!

Just testing the app, it's great! Migrating from Signal.

A minor issue with the left panel (contacts, options) width is that if the app window is wider than certain amount of pixels (1310 to be precise), the left panel starts increasing its width and looks distorted.

**Comment by helenakos** [comment]
@anatoli26 Thanks! We will have a look.

**Comment by lipis** [comment]
This is by design actually.. for very huge screen we had to do something :)

**Comment by anatoli26** [comment]
It would be better to keep it same width no matter the overall size of the window as it looks like being broken, left-aligned elements (contact button at the bottom, the contacts, etc.) become unaligned. Why not to keep it same width at any size? Actually, my 14" notebook screen with 1366x768 is nothing big. Because of this issue I don't maximize Wire window.

**Comment by Simplenuity** [comment]
I second anatoli26's request.

I would like to extend it to the opposite use case - making the window smaller. If the window width gets under a certain size the left contacts panel should disappear and only the chat column should be possible - see Telegram. Right now the chat panel disappears!

Thanks for your consideration!
