### ISSUE TITLE
Music play volume during call

### ISSUE THREAD

**Issue by DOFfactory** [wireapp/wire-desktop#446]
This is an idea for enhancement. I often receive calls while listening to music, which then I have to pause manually. Both iMessages and Facetime have the option to mute/pause/lower the volume of music when a call occurs. 

Personally, I prefer the lowering of the volume to +-10% of the volume of the call (similar to Facetime) rather than completely pausing the call (as iMessages behaves). 

Would you consider such an option, maybe in settings?

**Comment by helenakos** [comment]
@DOFfactory Thanks for the request. We will discuss it internally and see the feasibility. Cannot promise anything now.

**Comment by helenakos** [comment]
Thanks again for the request. We don't have immediate plans to implement this. Closing this issue for cleanup purposes. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
