### ISSUE TITLE
Camera not turning off after call

### ISSUE THREAD

**Issue by hansvurst-foss** [wireapp/wire-desktop#4461]
Wire version: Version 3.20.3912
Wire for web version: Wire for Web Version 2020.10.28.12.23
Operating system: macOS 10.15.7

**What steps will reproduce the problem?**
1.  Start video call
2.  End video call
3.  Camera indicator still on

**What is the expected result?**
Camera turning off after call is ended.

**What is the actual result?**
Camera stays on after the ended call.

I checked open issues and there were none that exactly covered the bug. Issues like #879 or #48 are different. I understand why you dont turn the camrea off during the call. But the camera being on endless after a call ist just creepy. 😄 

When I go in the settings menu after the call (Audio/ Video) and leave it again I can somehow manually power off the camera.

**Comment by ffflorian** [comment]
This should be fixed with version 3.23.
