### ISSUE TITLE
When minimizing Wire please make a make small video window on top of everything else

### ISSUE THREAD

**Issue by Quantum00** [wireapp/wire-desktop#447]
...so people can still watch each other when multitasking. Skype and Viber for Windows already have this while Wire doesn't. It's keeping me from switching.

**Comment by farfeduc** [comment]
Hi, it is also a feature I would like.

Pointer to realize that : 
https://discuss.atom.io/t/proper-way-to-open-new-window/33224
with options `alwaysOnTop : true` and `frame : false` I guess.

I guess you knew that but all window-related options are documented here : https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

And by listening to the events `blur`, `focus`, `show`, `hide`, `minimize` and `restore` emitted by the main window according to the documentation here : https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-blur it should be quite easy to show/hide or open/close our small secondary window.

I hope it helps a bit. If you want I could try to create a pull request but I don't know the app, so it will take me some time to understand it properly to make these modifications.

**Comment by gregor** [comment]
We will continue to keep this in mind but have no immediate plans to implement it. I am closing this being a feature request that will be tracked internally.
