### ISSUE TITLE
'Places' uses wrong path on Linux

### ISSUE THREAD

**Issue by kbrandwijk** [wireapp/wire-desktop#45]
I know Linux desktop support is still experimental, but I've been using it with great success for a while now. However, I ran into an issue that when selecting a background, or a file or picture to send in a conversation, when selecting a location from 'Places' (such as Pictures), the path shown is /root/Pictures, which is wrong. It should be /home/Pictures.
Using the same functionality from the browser works as intended.

![wire open file](https://cloud.githubusercontent.com/assets/852069/18564437/c44331aa-7b8b-11e6-9601-9a6be7acf017.png)

**Comment by ConorIA** [comment]
How are you building / installing Wire? That looks like Linux Mint, am I correct?

My guess is that Wire is running as the root user (this is generally bad.) You can check by running `ps aux | grep Wire` on a terminal.

I don't think that this is anything set in the Wire app, for instance, when I open a photo, it automatically starts on the Nautilus Recents page.

**Comment by kbrandwijk** [comment]
@ConorIA Very well noticed, I feel kinda stupid missing that. I restarted the app, and now it's fine. In short, the app behaves exactly as expected. Let's close this one quickly :-)
