### ISSUE TITLE
Interface zoom level is not saved after restart

### ISSUE THREAD

**Issue by shvchk** [wireapp/wire-desktop#4539]
Wire version: 3.21.2936
Wire for web version: 2020.11.09.14.31
Operating system: Ubuntu 20.04
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1. Increase zoom level (<kbd>Ctrl</kbd> + <kbd>=</kbd>)
2. Restart Wire

What is the expected result?
Zoom level should be saved.

What is the actual result?
Zoom level is reset.

**Comment by ffflorian** [comment]
@shvchk We just released v3.24 which includes this freature.
