### ISSUE TITLE
/me

### ISSUE THREAD

**Issue by Deathsbreed** [wireapp/wire-desktop#454]
I guess this is mostly because I'm an IRC user (but Skype also has it), but it would be nice if there was a `/me <does something>` feature in Wire. Those of you who are on IRC know exactly what I'm walking about :^)

It's something small, but it's nice.

**Comment by jdries3** [comment]
See also https://github.com/wireapp/wire-android/issues/655

**Comment by Deathsbreed** [comment]
@jdries3, I did not see that, although that's probably because I only searched through the desktop :P

**Comment by helenakos** [comment]
@Deathsbreed Thanks for your request! We don't have plans to implement this at the moment so will have to close the issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
