### ISSUE TITLE
Mailinglists for dev/user/announce?

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#458]
Subj. Would like to be part of the 3

**Comment by lipis** [comment]
I really don't get this one.. could you please explain a little bit more on what you want?

**Comment by anatoli26** [comment]
It would be great to have mailing lists for developers (discussion of development-related issues), users (discussions of user-related issues like usability, etc.), and an announce mailing list for official announces (new releases, etc.). Like here: http://www.postfix.org/lists.html#lists.

**Comment by lipis** [comment]
At the moment we don't have the resources to maintain and follow extra lists. I think the best is to subscribe and start watching our public repositories and you can subscribe to https://medium.com/@wireupdates to get notified whenever we have a new version in any platform.

**Comment by anatoli26** [comment]
Lipis, OK, got it. Though I think the announce mailinglist could be created anyway... It's just initial setup time and for the users it would be much simpler to receive mails to their mailboxes than to follow you on medium (personally (and I guess a lot of other users too), I don't have an account there, don't plan to have one and I would need to enter there from time to time to stay updated).

**Comment by anatoli26** [comment]
That could be made unnecessary though when #47 is implemented and you create a global "Wire announce" channel that includes all wire users.

**Comment by lipis** [comment]
People also tend to reply to those mails and we can just ignore that :) and yes.. maybe we'll solve that with the broadcast lists.. stay tuned!
