### ISSUE TITLE
Improve interaction/attract attention on new messages

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#469]
Wire should show on its icon in the launcher/taskbar unread messages counter badge, like Thunderbird and other apps do.

![tb](https://cloud.githubusercontent.com/assets/22968420/23329918/e4bd8516-fb42-11e6-87a0-7bdd827a354b.png)

One possible solution is to use [app.setBadgeCount(count)](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetbadgecountcount-linux-macos) available directly in Electron, that works on Linux (only Unity) and macOS.

Also, a number of users desire to bring to front the Wire window on new message. This action should NOT steal focus from the currently active application and the Wire window possibly should NOT become the topmost, but rather _the second_ window so alt+tab offers it as the first option (or if the topmost window is minimized, the wire window becomes the topmost). This behavior should be optional.

**Comment by lipis** [comment]
We are actually using the `[app.setBadgeCount(count)](https://github.com/wireapp/wire-desktop/blob/master/electron/js/menu/tray.js#L74)` and not restricting it on any platform.. so in theory it should work! Can anyone verify that?

As for bringing the app to topmost or the second spot is a bit intrusive and not something that we would like to implement. Every platform is behaving differently in that area and will just going to introduce more complexity without many benefits.

**Comment by anatoli26** [comment]
> so in theory it should work! Can anyone verify that?

At least on stock Ubuntu 16.04 it's not working, though I don't have other examples of Electron that are working, so it could be that the Electron's app.setBadgeCount is not working. Could you please point to the part there it's called? I'll try to make some tests.

> As for bringing the app to topmost or the second spot is a bit intrusive

Looks like at least some users would like to have this feature. It could be an option and turned off by default, so only those, who'd like this behavior, would have it.

Though I do agree that it doesn't look like an easy fix, especially on all the platforms. Would you accept PRs? I guess it could be implemented conditionally for each platform, i.e. someone builds this functionality for Linux, then this option could be compiled for Linux. If someone adds this for Windows too, then only OS X would be without it.
