### ISSUE TITLE
Be able to make a broadcast list

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#47]
It would be interesting to make a broadcast sending. 
For exemple, when creating a group discussion, choosing (without being able to change it) if this is a regular group discussion or a broadcast list.

Exemple: create a broadcast list with 5 contacts. Write a message and Wire sends 5 messages, one to each one. If one reply, a new discussion is made accordingly, one to one.

**Comment by lipis** [comment]
I think it's not the most common use case.. You can do that with SMS apps but that's because groups are not supported there and it's the only way to save some time :)

**Comment by IpsmLorem** [comment]
Yes you can do that to SMS apps, but Wire is all about message privacy, right (SMS nto at all!) ? 
Why not having the same feature in the Wire app backpack :)

That may not be the most common use case for sure, but can be handy when you want to send some news to several peoples without any relathionship between them.

**Comment by anatoli26** [comment]
That's sort of like channels in Telegram. Quite a useful feature, especially when feedback is possible (like/dislike, comment, etc.). If given enough care and thought, it could replace some day RSS feeds and even facebook news feeds. Not a high-priority feature, but it has a great potential.

**Comment by dkovacevic** [comment]
Have you tried /wireapp/broadcast-bot

**Comment by anatoli26** [comment]
Looks like an interesting feature. Didn't know it exists, thanks!

**Comment by helenakos** [comment]
Try out the bot, hope you like it. We won't have this as a feature in the near future, so closing this issue.

**Comment by dkovacevic** [comment]
@anatoli26 Let me know if you need help with setting up the Broadcast for you. I am: @dejan at Wire
