### ISSUE TITLE
Signup Validation Page Broken

### ISSUE THREAD

**Issue by mikebronner** [wireapp/wire-desktop#471]
Well, it's actually the entire wire.com site that is throwing nasty blocked frame errors, preventing validation of new accounts, as well as reporting bugs through the intended support page. It does seem to work in Chrome, but not in Safari.

![screen shot 2017-02-25 at 10 25 36 am](https://cloud.githubusercontent.com/assets/1791050/23333696/ce9caba2-fb44-11e6-8e39-9c4c442a6686.png)

**Comment by lipis** [comment]
Safari is not supported so you will have to use Chrome or Firefox. I just verified the whole process and it seems to work fine..

**Comment by mikebronner** [comment]
I was able to get past it. Perhaps it was a temporary issue. Thanks :)
