### ISSUE TITLE
Issues with media uploading/downloading

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#472]
I was uploading some videos and photos (from iOS), there were problems uploading them (apparently due to connectivity issues), so I canceled and re-uploaded some of them. One of the re-uploaded videos showed on my Wire-desktop as 3 entries: one with the video itself + 2 entries with the "downloading" placeholder. When clicking on the "3 dots" menu at all 3 entries and choosing "Download", the same video was saved, so I decided to delete one of the placeholders.

With this, the other placeholder and the entry showing the video were deleted as well.

I guess that this happened due to the reservation of a slot for each download and some synchronization issues there. So I'm wondering if it's necessary to reserve a slot and show to the peer that something is there before the video/photo is fully uploaded to the server?

Also, one of the re-uploaded photos appeared twice. The photo never appeared as "sent" before I re-uploaded it, it was either in the "failed, retry?" state, or uploading with the big X in circle and this X was pressed, then "retry".

**Comment by gregor** [comment]
We have lately fixed issues in this area where merging of multipart messages did not go as smooth as we wanted it to before. You should now see all your videos from mobile platforms.
