### ISSUE TITLE
[Linux] How to change user in wire?

### ISSUE THREAD

**Issue by nail1962** [wireapp/wire-desktop#475]
I did not find where I may change user of wire, like in skype "change user". There is no this possibility or I have to search more carefully?  Now, to change user I simply change config dir in /home/nail/.config from my to another user, but it is not comfortable. I use Linux Mint  Mate 17.3 (Ubuntu 14.04).  I use last version of wire wire_2.11.2722_i386.deb.

**Comment by Strit** [comment]
There should be a "log Out" from the settings menu.

**Comment by lipis** [comment]
Yes, you should just "Log out" and then login again.. as mentioned already from the menu.
