### ISSUE TITLE
Add option to hide/toggle menu bar

### ISSUE THREAD

**Issue by nunocastromartins** [wireapp/wire-desktop#476]
**Main reason:** it looks bad on Gnome (Linux).
Toggling the menu bar by pressing `Alt`, for example, would be really nice.

Thank you!

**Comment by ConorIA** [comment]
Was there in #83. I was asked to remove it at that time, but after explaining my use case (same as @nunocastromartins), the idea was "left on the table" so to speak.

**Comment by lipis** [comment]
So let's do this :)

**Comment by ConorIA** [comment]
#483 adds the toggle button, but the preference doesn't seem to stick. I am seeing the menu bar on restart.

**Comment by lipis** [comment]
Yes, toggle menu was not storing anything even on Windows.. maybe it's time for a change :D

**Comment by mythsunwind** [comment]
Was released with 2.12.2729
