### ISSUE TITLE
Exit conversation

### ISSUE THREAD

**Issue by agurenko** [wireapp/wire-desktop#477]
It would be great if you can be at some screen where no conversations are open (by pressing ESC for example). I'd prefer to keep main window with Wire logo for example and open conversations as the messages come in. Sometimes it's very distracting when people send you GIF and if you keep conversation open it plays even when not being in a foreground. Here is an example in Telegram app attached
![telegram](https://cloud.githubusercontent.com/assets/6168150/23394851/0b43a46a-fd94-11e6-94e8-5926309d9409.jpg)

**Comment by helenakos** [comment]
@agurenko Thanks for the request, we will have a look!

**Comment by agurenko** [comment]
Great, thank you @helenakos

**Comment by herrmannplatz** [comment]
UI is actually already in place. We just dont have the close functionality.

![bildschirmfoto 2017-02-28 um 13 55 58](https://cloud.githubusercontent.com/assets/174685/23406203/1c1db8dc-fdbe-11e6-99dd-f6176b4165e0.png)

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by agurenko** [comment]
But didn't @herrmannplatz said that it's basically already there...?! whatever then...
