### ISSUE TITLE
Writing delay

### ISSUE THREAD

**Issue by mimf** [wireapp/wire-desktop#479]
I'm using Wire 2.11.2722 on Xubuntu 16.04 and there's a huge delay when typing fast. It's absolutely noticeably.

**Comment by herrmannplatz** [comment]
Can you try to turn off the spell checking.

**Comment by ConorIA** [comment]
@herrmannplatz, does Wire use hardware accel by default? I used to find that Atom was slow unless I used `--disable-gpu` (I mentioned this in #379, but the user never responded). I have a dedicated video card now, so can't test locally.

**Comment by mimf** [comment]
Spell checking was the problem I think. With it disabled, I don't have delay.

**Comment by anatoli26** [comment]
Same here on Ubuntu 16.04. I had to disable the spell checker to get a normal type rate. Anyway, as it doesn't have any options (i.e. to chose the input language, manage exceptions, etc.) IMO in its current state it doesn't add much value.

I would suggest to disable it by default before it is on par with other spell checkers.

**Comment by lipis** [comment]
Addressed for now in #424.. the spell checker is the problem and other Electron users are reporting this issue..so I'll close this for now.
