### ISSUE TITLE
Marking something and right-click-copying copies whole line and not only marked part

### ISSUE THREAD

**Issue by 2001db8** [wireapp/wire-desktop#480]
Hi,

in the windows desktop app (2.11.2712), when you mark a part of a line and copy it into the clipboard using right-click -> copy the whole line gets copied into the clipboard. Using ctrl+c only copies the marked part.

Regards

Jens

**Comment by anatoli26** [comment]
Same on Ubuntu 16.04

**Comment by mi-gri** [comment]
I can confirm the behavior for Linux Mint 18.1 using 2.11.2722 but not for the older version 2.11.2670.

**Comment by aquatooth** [comment]
I confirm this behaviour using wire_2.12.2729_amd64 on Ubuntu

Select some text, copy, then paste and the result is the whole paragraph, not just selected text.

**Comment by 2001db8** [comment]
Bug is still there in Windows version 2.15.2750 (Web Version 2017.8.24.1057).

**Comment by gregor** [comment]
This was fixed with https://github.com/wireapp/wire-desktop/pull/856 which will be part of the next public release.
