### ISSUE TITLE
Add option to display timestamp on every message

### ISSUE THREAD

**Issue by Linus9000** [wireapp/wire-desktop#481]
I'd love to see an option to always display the timestamp on messages instead of only on mouseover. As all timestamps are shown when I hover over the right edge of the window I can at least see that this wouldn't look awful or something like that.

**Comment by gregor** [comment]
We have a design for this interally but have not found and comitted the resources to implement it yet.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
