### ISSUE TITLE
Wire desktop app version 3.22 not released here / is missing

### ISSUE THREAD

**Issue by sheesupport** [wireapp/wire-desktop#4843]
On Feb 19 a new version (3.22) of the Wire desktop app was announced : 

https://medium.com/wire-news/desktop-updates/home

but no release can be downloaded here:

https://github.com/wireapp/wire-desktop/releases

In particular the Wire-${VERSION}_x86_64.AppImage variant.

Do I miss some changes here? Thanks!

**Comment by ajakk** [comment]
I see this too, my Wire on Linux complains it's out of date but I can't find a tarball to update it from.

**Comment by ffflorian** [comment]
Hi @sheesupport, sorry for the delay. The release is now published and can also be found here: https://github.com/wireapp/wire-desktop/releases/tag/linux%2F3.22.2937

**Comment by ehdis** [comment]
Hallo Florian,
thank you for your feedback. Unfortunately corresponding signed sha256sums are missing. Important
for the integrity! BTW, the OSX version is also missing. I hope that this is still in the pipeline? Danke!

**Comment by ffflorian** [comment]
The sha256sum was just added, sorry for the confusion.
The macOS version is not released (yet) as it's not approved by Apple. We are working on that.
