### ISSUE TITLE
No screen-sharing in Linux (bug?)

### ISSUE THREAD

**Issue by qazip** [wireapp/wire-desktop#491]
Hello,

There seems to be a bug on the Linux version of wire. There's no screen-sharing option when one starts a voice/video-call. I know there's already issue https://github.com/wireapp/wire-desktop/issues/68 but that one seems to be closed so I've decided to create this one.

There's no screen-sharing option in:
- Wire 2.11.2722;
- xubuntu 16.04 and Ubuntu 14.04/16.04;

**Comment by mimf** [comment]
I installed wire_2.12.2729_amd64.deb and the share-screen seems to work. 

Why isnt this new version yet on wire.com? Supposedly, it should've been there yesterday.

**Comment by mythsunwind** [comment]
The new version is not on wire.com? You can grab 2.12.2729 from https://wire.com/en/download/

If you found an old or broken link please let us know.

**Comment by qazip** [comment]
It is on wire now, it wasn't when I created this issue.

**Comment by arrufat** [comment]
I noticed screen sharing does not work on Wayland (I only get a blank screen)

**Comment by StevenMapes** [comment]
Screen sharing also seems to be missing on Windows 2.12.2729 and 2.11 as well

**Comment by gregor** [comment]
Screen sharing 1to1 calls is currently disabled due to the upgrade of our call signaling protocol. We will get it back to you as soon as possible.

**Comment by DOFfactory** [comment]
Can you please provide an ETA when it will be enabled again? I switched to wire because of this functionality, pretty annoying that it has been removed. :-/

**Comment by gregor** [comment]
I understand your frustration. Same for me. In this case security won over usability and functionality. It will not be reenabled in this weeks release. But I have already finished most of the work and we are testing it internally https://github.com/wireapp/wire-webapp/pull/915. It should be out by the end of next week.

**Comment by DOFfactory** [comment]
Excellent, thanks for the reply.

**Comment by gregor** [comment]
Screen sharing will finally be reenabled with our next release in the coming days.

**Comment by braniii** [comment]
For me screen sharing still doesn't work. It's just a black screen with the cursor.
I guess it is still an issue of wayland support.

Here on link to an FOSS software which implemented screen recording on wayland:
https://github.com/foss-project/green-recorder

OS: Arch Linux (up to date)
Display server: Wayland 1.14.0
Version: 2.17.0-undefined (from AUR) 
Web-version: 2017.09.26.1300

**Comment by beew** [comment]
Actually it still doesn't work for me. It just shows a blackbox and I am not on Wayland, just good old x.
Ubuntu 16.0.4.3 (also 17.10) 

Wire 3.0.2816
