### ISSUE TITLE
[Linux] Please provide a desktop file

### ISSUE THREAD

**Issue by Veganizer** [wireapp/wire-desktop#4920]
Wire version: All
Operating system: General all Linux Systems

What steps will reproduce the problem?

1. Install Wire manual or compile it with yarn

What is the expected result?
To have a desktop file

What is the actual result?
To don't have a desktop file.

Please provide any additional information below. Attach a screenshot if possible.
Could you provide a desktop file in the ressources please? 

Following suggestion I got:
```bash
[Desktop Entry]
Name=Wire
Comment=The most secure collaboration platform.
Exec=wire-desktop %U
Terminal=false
Type=Application
Icon=wire-desktop
StartupWMClass=Wire
Categories=Network;
GenericName=Secure messenger
Keywords=chat;encrypt;e2e;messenger;videocall
MimeType=x-scheme-handler/wire
Version=1.1
```

**Comment by ffflorian** [comment]
Hi @Veganizer, you can now build a Linux desktop file with this command on dev:
```
yarn
npx ts-node -P tsconfig.bin.json ./bin/build-tools/build-linux-desktop-file.ts
```

**Comment by Veganizer** [comment]
Thank you very much! I will wait for next release then to implement it in Void Linux Repository :-)

**Comment by Veganizer** [comment]
Sadly the new release "3.25.2940 - Linux" doesn't contain a /bin/build-tools/build-linux-desktop-file.ts in the source. Can you check this please? @mythsunwind

**Comment by ffflorian** [comment]
Well, the file is in this repo.
