### ISSUE TITLE
Group conversations: Max users?

### ISSUE THREAD

**Issue by qazip** [wireapp/wire-desktop#499]
Hello,

Upon reading your blog, I came across this line, which refers to "Group calls":

`Up to 5 participants (Edit: Increased to 10 in July, 2016)`

I suppose that limit is for group calls only, that is, voice/video, right? Is there a limit for group conversations (text only)?

**Comment by herrmannplatz** [comment]
Yes, 128 people.

**Comment by qazip** [comment]
I suggest adding that somewhere in the faq or even in the blog post I posted. It's not all that clear.

**Comment by herrmannplatz** [comment]
Thanks, will check it.

**Comment by gregor** [comment]
It can be found in our FAQs at https://support.wire.com/hc/en-us/articles/203122040

**Comment by qazip** [comment]
Ups, my bad!
