### ISSUE TITLE
BUG: The app on OS X shows a scroll bar on a narrow window

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-desktop#50]
# Short description

When I have resized the app to a narrow window the app shows a scroll bar on the bottom and I can't scroll anymore. 
# Behavior:

The app is opened on a full screen window, then I resize the app to the narrowest size. Than I can't scroll in the app an it has a vertical scrollbar. (see the image for the picture of the scollbar) 
# Expected behavior

I suspect that the app can be resized to the small window and will word correctly. So I can scroll. 

![screenshot](https://cloud.githubusercontent.com/assets/6486389/18807607/e7ddd036-824b-11e6-970a-9f3536ba76ad.png)

**Comment by mat1th** [comment]
This is fixed in on of latest releases.

**Comment by lipis** [comment]
😎
