### ISSUE TITLE
Linux: Dark Theme not applied at start-up

### ISSUE THREAD

**Issue by Urfoex** [wireapp/wire-desktop#5006]
Version 3.25.2940
Wire for Web Version 2021.05.10.14.51
https://wire-app.wire.com/linux/debian/pool/main/Wire-3.25.2940_amd64.deb
$ uname -a
Linux Ryzen 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

What steps will reproduce the problem?

1.  start wire desktop
2.  set Dark Theme
3.  quit wire desktop
4.  start wire desktop

What is the expected result?

Dark Theme is turned on.

What is the actual result?

Dark Theme is turned off.

Please provide any additional information below. Attach a screenshot if possible.

From the logs:
[2021-05-13 04:10:14] [@wireapp/desktop/preload-webview.js] Switching initial dark mode off ...
[2021-05-13 04:10:14] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.loaded", forwarding event ...
[2021-05-13 04:10:15] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.unread_count" (count: "1"), forwarding event ...
[2021-05-13 04:10:16] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.unread_count" (count: "1"), forwarding event ...
[2021-05-13 04:10:15] [@wireapp/desktop/preload-webview.js] Switching initial dark mode off ...
[2021-05-13 04:10:15] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.loaded", forwarding event ...
[2021-05-13 04:10:16] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.unread_count" (count: "0"), forwarding event ...
[2021-05-13 04:10:16] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.unread_count" (count: "0"), forwarding event ...
[2021-05-13 04:10:39] [@wireapp/desktop/preload-webview.js] Received amplify event "wire.webapp.lifecycle.unread_count" (count: "0"), forwarding event ...

**Comment by Shadzillo** [comment]
Same for the Windows desktop client. Always reproducible!

**Comment by Filbuntu** [comment]
Still happening on Version 3.25.2940, Wire for Web Version 2021.06.01.12.23 (Ubuntu 20.04).
It does happen more often when the app works in the background (no quitting of the Desktop App) and the app is opened again, maybe after it was idle for a time. 
It is almost every day and sometimes more than once a day. Very annoying.
It is happens in both accounts (signed in in the same app) but not always synchronously.
Thanks for looking into this!

**Comment by toonn** [comment]
On macOS it hasn't happened to me except when starting the app.

**Comment by JCmAxohtwEoK0fdaQip7** [comment]
Version 3.26.4124
Wire for Web Version 2021.06.01.12.23
Win7 x64 using Wire Desktop client

Every launch of the application causes wire to forget dark mode and go back to light

**Comment by Bust3D** [comment]
Same here,
Dark Mode after Exit or Restart Wire app in Windows doesn't preserve the settings.

**Comment by JD906** [comment]
Hoping for a fix. 👍

**Comment by toonn** [comment]
Is anyone looking into this? It's pretty frustrating because it happened in a release that claimed to fix the dark theme, "Dark mode is not applied at startup". So all it would take is reverting the, at this point rather obviously broken, fix and only reapplying it after proper testing.

I realize the desktop app might be a second-class citizen but this is a very annoying problem that would be rather easily fixed, at least temporarily.

**Comment by GraOrigin** [comment]
one does also get blinded (by a white screen) at night when updating to a new version on macOS..

Please fix this simple issue.

**Comment by epixinvites** [comment]
Same here, running on `wire-desktop 3.26.2941-1`, Arch Linux

**Comment by iverik-no** [comment]
I have this issue when running the Flatpak version 3.26.2941-2941, installed via Discover (KDE) and Flathub.

The theme resets on every quit/reopen of the app. Also, the menu bar is white, even if Dark Theme is set.
The file picker dialogue is also white theme, no matter what.

Installing with the deb Version 3.26.2941, the theme follows system theme, and the menubar is dark if dark is set.
The file dialogue is dark, though the icons are from white-theme (i.e. they are grey/dark in color).

**Comment by not-a-lot** [comment]
Still happens on the latest desktop version for Windows (3.26.4124)

**Comment by toonn** [comment]
This has actually stopped being broken for me on macOS. I did not update Wire so it must have been fixed in the "Wire for Web" that runs in the Wire Desktop Electron app. I'm currently on Wire for Web version 2022.02.15.14.47 but it was fixed a week or two ago.

**Comment by Filbuntu** [comment]
It looks like this bug is really fixed with Wire for Web Version 2022.02.15.14.47 (or earlier) on Linux, too. I have monitored the behaviour the past days and the random dark to light theme switch did not happen. It is a pity they have not linked this bug report with the release notes and closed this bug. On the other hand it is great this annoying issue is (most likely) solved ☀.

**Comment by Urfoex** [comment]
As it is the same here, I close it.
**\*Mysteriously Fixed\***
