### ISSUE TITLE
Search function?

### ISSUE THREAD

**Issue by autismismydrug** [wireapp/wire-desktop#505]
Are there plans to add a search feature to Wire? there are some convos I dont delete and would love the ability to search instead of scrolling to look for what im looking for.

**Comment by ConorIA** [comment]
https://medium.com/wire-news/search-text-messages-1939c3b472e6#.6mhzlw936

**Comment by autismismydrug** [comment]
Thanks a heap!
You have to forgive me I just came back from Mars and still catching up :)
