### ISSUE TITLE
UX improvement: when untrusted device is added, mark all incoming messages as "trusted" / "untrusted"

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#507]
When untrusted device is added, from that moment all incoming messages should be marked as "trusted" / "untrusted" (could be text, color and/or symbol - alternatively only untrusted messages may be marked as such, so this feature could be enabled always without a UX impact -OR- messages may be marked as trusted/untrusted only when there are untrusted devices, and no mark at all when all are trusted) so one can write to the peer something like "Have you added a new device? Reply from some old device" and if a positive reply comes from a previously trusted devices (and this is indicated in the chat as such) then one can safely add the new device as trusted, no need to verify it via some external channel.

**Comment by raphaelrobert** [comment]
Hi @anatoli26,

Thanks for the suggestion! We have some ideas in mind on how to simplify the verification process and we will start implementing them in the near future. They should address what you are concerned about.

**Comment by anatoli26** [comment]
@raphaelrobert thanks for the update. Just got an additional idea (and maybe this is what you're already implementing): if my peer adds a device and he/she marks it as trusted* from one of his/her already trusted devices, then my Wire could trust this new device too without even asking me to review it. I.e. if I already trust some of my peer's devices, I should trust everything (in the sense of messages and delegations) coming from them.

This would be sort of like presenting me a new device certificate signed by an already trusted device's certificate.

* IMO the process of adding one's own new device should be made more explicit for the user, nowadays I should explain to all my peers that they should go to Properties > Devices and mark there all their devices as trusted. A pop-up on an old device asking something like "Have you added a new device? Please enter its signature here" and a pop-up on the new device showing the signature, I believe, would be much simpler and secure.

**Comment by maximbaz** [comment]
> if my peer adds a device and he/she marks it as trusted* from one of his/her already trusted devices, then my Wire could trust this new device too without even asking me to review it

This is an interesting idea, but it simplifies hijacking a lot. Suppose this example: 

A malicious thirdparty visits your friend's house, and while she is looking away uses her computer (where she is logged in Wire and Lastpass) to look up her password, create a new device and mark it as trusted device from her current Wire app. This takes 5 minutes, and the malicious user is fully equipped to listen to all conversations of your friend. Since your approval of a new device was not required (only your friend's approval, which was done by the malicious user), you (and everyone else) cannot detect that your conversations are not private anymore.

**Comment by anatoli26** [comment]
Yes, but if you have such an access to someone's computer, you could copy just everything (including the device keys and just replicate her device on you own device), install backdoors, etc., i.e. you already have everything needed, the user is fully compromised.

Also, the user would be able to see in the list of his/her own devices that there's a new device (if he/she checks the list, alternatively a mail could be sent, but again, if you control everything, nothing will help the user).

IMO, the threat vector you describe just is not included in the scenarios Wire protects you from. The same way as full-disk encryption is not protecting you from viruses, Wire can't protect you if all your credentials are compromised and the adversary has a physical access to your computer with all the keys unencrypted.

We could think of additional security steps, like locking Wire window (and the keys) with a pin (already proposed), adding a second-factor (like FIDO U2F) for encryption/decryption of the device keys, etc.

**Comment by anatoli26** [comment]
And I can propose an additional protection step in this case: if your peer gets a new device and the trust is propagated automatically, there could be some clue added to the shield to the left of the username (like a "+" sign or a badge with the number of devices could be shown) or a tooltip could appear. These clues probably should be turned off by default and available as options in the Advanced settings tab, so common users are not confused. An option to warn you the same way you're warned now could also be placed there, also disabled by default.

**Comment by gregor** [comment]
Thank you for your suggestions. We will continue to evaluate them and consider for future roadmap. As an act of housekeeping I am closing this isssue at this time in order to focus on tracking bugs publicly for easier discovery.
