### ISSUE TITLE
UX improvement: special user "myself"

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#508]
Add a special user "me" or "self", or any other name that would always be present in the contacts list (with possibility to delete it and find again as all other users) and that would be used to pass text, photos, files from one device to all others.

For example, today if I need to pass a photo from my phone to my desktop (or a pdf from desktop to phone), I have to mail it to myself, share it with some service, upload it via USB, etc. All this (except for USB, which is uncomfortable) is insecure/non-private. With this option one could transmit all types of content between own devices with ease and security.

**Comment by maximbaz** [comment]
@anatoli26 see [here](https://github.com/wireapp/wire-webapp/issues/576), there's also a workaround that I've been using ever since. It's a hack, but you do it once and it serves you well 😉

**Comment by anatoli26** [comment]
Thanks! So it's a dup, but the feature is definitely useful. Will comment there.

**Comment by gregor** [comment]
You can now create conversation with just yourself. Today we released a new version of the webapp with an updated way to create groups. You can skip the step to select participants and can create a conversation with just yourself that way.

**Comment by gregor** [comment]
You don't need to search for your self. Make sure you restart Wire and check that on the about page the version of the webapp component is 2018.02.16.0754 or newer. All you have to do is create on the person icon in the lower left of the conversation list and then choose "Create group" below the search box. Just name the conversation, click next, and click skip to not add anyone else but you to the new conversation.

**Comment by anatoli26** [comment]
Works, thanks!
