### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [wireapp/wire-desktop#51]
[AppImage](http://appimage.org/) is a bundling format for Linux that lets users download one single file, set the executable bit and run the application (here: Wire). AppImage is entirely __distribution-agnostic__ and requires no special runtime infrastructure on the target system(s). This means that the user can run the application on almost any recent Linux distribution.

This shows how to generate the AppImage:
https://github.com/probonopd/AppImages/blob/master/recipes/wire/Recipe

The resulting AppImage can be found here: 
[ ![Download](https://api.bintray.com/packages/probono/AppImages/Wire/images/download.svg) ](https://bintray.com/probono/AppImages/Wire/_latestVersion#files)

Just download, set the executable bit (e.g., chmod a+x), and run!

**Comment by lipis** [comment]
@probonopd Thank you very much for the effort and the recipe :) We will take a deeper look on the AppImage, to check our options on how we could start distributing the Linux version.. We don't have a committed timeline .. but we definitely hear you guys and we want that as well! Sit tight..

**Comment by ConorIA** [comment]
This is very neat. Will you maintain an up to date image? I might throw together an applmage based pkgbuild to test.

**Comment by probonopd** [comment]
> Will you maintain an up to date image?

The script above is fully automated; it will produce an AppImage of the latest version. I provide some AppImages as examples, but in the hope that upstream software projects "adopt" them and put out official, upstream-provided releases.

**Comment by lipis** [comment]
Hey @probonopd I tried to generate the AppImage with https://github.com/electron-userland/electron-builder but run into some issues.. have you used it?

**Comment by probonopd** [comment]
No but @ develar is very helpful; what kind of issues are you running into?

**Comment by lipis** [comment]
Once we'll publish the `.deb` I'll have another PR for AppImage.. so we could take it there with more specific questions. Thanks.

**Comment by develar** [comment]
@lipis electron-builder can produce deb, rpm, freebsd, pacman, p5p, apk and snaps (soon). So, I suggest you to not waste time to implement only deb support ;) Feel free to file issue using https://github.com/electron-userland/electron-builder/issues and ping me directly if issue is not handled in several days.

**Comment by lipis** [comment]
@develar Awesome.. I found it after I started with it https://github.com/wireapp/wire-desktop/pull/63 so I won't spend more time on it and will continue with the builder.. thanks! I'll keep you guys posted..

**Comment by zgrimshell** [comment]
Instead of going with AppImage, it would be better to go with Flatpak which is more modern, better in design and it will be integrated into probably all distributions. Also kudos for .deb, you should maybe even try to push it directly into Debian.

**Comment by probonopd** [comment]
@zgrimshell take a CentOS 7 Live ISO, boot it, and run a Flatpak on it. Then we talk again :-)

**Comment by lipis** [comment]
We will continue with `AppImage`, `.rpm` and we'll see what comes next.. The list is endless in the Linux world..

@zgrimshell We will try to push it directly to Debian once the Linux version is more polished.. there quite a few things needs to be addressed.. menu and icons are just a few of those :)

**Comment by develar** [comment]
@zgrimshell For electron-builder user it is one line to add/change some Linux format. Well, flatpak not yet supported — AppImage is more requested and popular.

**Comment by ConorIA** [comment]
@lipis, please let me know once you have the electron-builder "methodology" figured out. I'd like to make sure that my pkgbuild follows as close to the 'official' procedure as can be.

**Comment by zgrimshell** [comment]
@probonopd your point is what? To say CentOS 7 is too old or that it didn't implement flatpak yet? Ubuntu re-invented their own thing called Snaps which still isn't better than Flatpak.

@develar Windows is more popular than Linux, so what? Flatpak is better technology which in turns is better for users, it just needs to gain foothold (which it will). AppImage already existed, and they knew about it and also - AppImage will never be integrated with OS as Flatpak will be (bundles are already a security nightmare, we don't need to make it worse)

**Comment by ConorIA** [comment]
@zgrimshell, @develar was just saying the they haven't implemented flatpak in electron-builder yet. AppImage was implemented due to popular demand. I did a quick search and someone requested AppImage back in June, but it is in the backlog with a HelpWanted tag. I'm sure you are welcome to implement it if you know how. Otherwise, raise you voice over at https://github.com/electron-userland/electron-builder/issues.

**Comment by develar** [comment]
@zgrimshell https://github.com/electron-userland/electron-builder/issues/512

**Comment by probonopd** [comment]
@zgrimshell my point is that AppImages run (almost) everywhere, and can serve certain purposes Flatpak and Snap{py,craft} don't.

**Comment by zgrimshell** [comment]
@probonopd your point is pretty much not correct. Properly built snap and flatpak should run anywhere as well and the advantage of flatpak over appimage is obvious to all technical enough (twice run lib compared to shared lib, and also that flatpak is moving with ecosystem) and the things of relying on modern Linux parts of ecosystem as well as its integration into GNOME Software will make it the probably the most common choice. Is Flatpak perfect from all PoV - certainly not, but currently it is the best on market.

@develar yea, I misinterpreted your point. Glad to see it coming to your software (I'll be sure to check it).

**Comment by probonopd** [comment]
@zgrimshell this is getting OT here, but let's just say the different systems serve vastly different purposes.

**Comment by lipis** [comment]
and with that.. let's get back on topic.. support this [project/issue](https://github.com/electron-userland/electron-builder/issues/512) that makes all our lives easier.. that what Electron actually solved. Let's build the tools that extend it even further!

**Comment by lipis** [comment]
Closing this one to continue the conversation in #92 :) It's ON..
