### ISSUE TITLE
Update notification Ubuntu

### ISSUE THREAD

**Issue by aquatooth** [wireapp/wire-desktop#513]
The update notification is displayed and when clicked appears that it does nothing except to restart Wire.
Refer issue [#430](https://github.com/wireapp/wire-desktop/issues/430) PPA is required for Linux/ Ubuntu versions.

Wire version 2.12.2729 [both before and after clicking on 'update']
Ubuntu 16.04 LTS 64 bit and Ubuntu 14.04 LTS 64 bit and Ubuntu 12.04 LTS 64 bit [yes, on all three currently used Ubuntu versions]

**Comment by maximbaz** [comment]
So just to confirm with someone from the team, what does this notification mean? 

![image](https://cloud.githubusercontent.com/assets/1177900/24076540/864335d8-0c33-11e7-96ae-cbdaf5e7cc79.png)

* Desktop app has an update?
* Webapp got updated and requires page refresh?
* Both?

Given that Linux desktop versions are coming from different sources which have their own way of handling updates, this "Update now" button will indeed do nothing except restarting Wire. 

So _if_ it means "desktop app has an update", I would prefer to not see this notification at all. Or at the very least, give me a :heavy_multiplication_x: button 😉

**Comment by ConorIA** [comment]
I image it means a webapp update, because I've gotten a couple of these notifications without any change on the desktop.

**Comment by maximbaz** [comment]
I've got them twice today, and that's why I started wondering - it's Saturday, the team is unlikely to be updating production today, twice 🙂 

The package on AUR is `2.13.2730-1`, while the latest tag is `2.13.2734`, so I thought maybe it means there is a newer desktop binary?

**Comment by ConorIA** [comment]
2.13.2734 runs fine I think, but I though I would try and sync up to the stable official releases. 2.13.2731 through 2.13.2733 were giving me a blank screen, and the Wire devs have often referred to the point releases as experiments, so I am holding on 2.13.2730 until the next stable release. The -git package keeps ya current though!

**Comment by maximbaz** [comment]
I'm quite happy with staying on the stable release, thanks for testing those by the way!

I only meant that if that blue bar is trying to update me to the latest binary release, (1) it's doing a poor job of updating Wire and (2) it is quite annoying 🙂 But if it means "webapp update", then we are good.

**Comment by gregor** [comment]
Currently this means that a new version of the webapp component ist available. In some intermediate internal Windows builds it would also show when a new version of the container app was available but we had to remove that for the time being due to issues in the Squirrel updater used. We will revisit out update process down the road and want to make it more obvious what get's updated when. Hard to communicate that in case of a browser based container app.

**Comment by aquatooth** [comment]
@maximbaz This should never be displayed on Linux version especially when the PPA is completed and I agree quite annoying method even on Windows.
Team, send you strength to tease out these issues with the different OS versions rather than using a big paintbrush!

**Comment by aquatooth** [comment]
these annoying messages are continuing to irritate all users on Linux.
since as @gregor mentioned that it means a new version of webapp component is available, then may I suggest that all changes to webapp are stopped until this is resolved properly.

**Comment by ConorIA** [comment]
The webapp is wrapped by the desktop app. The update notifications mean that there is something that your Wire Desktop client needs to download an updated version of the webapp core. This isn't a bug, just a slightly uninformative update banner. Further reading: https://support.wire.com/hc/en-us/articles/115001919905-How-do-Wire-updates-work-

**Comment by aquatooth** [comment]
ah, thanks, informative further reading.
So, what we get is an update that seems to do nothing, but actually does even though it is not apparent.
this is a highly foreign concept for users as one would expect a different version increment. 
I do hope your team can work on this to make better sense of it all.

**Comment by aquatooth** [comment]
a simple suggestion to make this clearer would be to display the webapp version in the webapp, perhaps only when the update bar is displayed. doing that would wipe out these issues because users would better understand what is in fact happening.

**Comment by lipis** [comment]
More information about the updates and versions was merged yesterday.. https://github.com/wireapp/wire-desktop/pull/539

**Comment by aquatooth** [comment]
@lipis Yes, well done. More or less similar to my simple suggestion above. Thanks for you and your teams work on this.

**Comment by gregor** [comment]
We also plan to add a link to the release notes on the update bar itself. That will obviously on show for the update after the next one at the earliest.

**Comment by aquatooth** [comment]
@gregor Yes, all good because that makes it clear to users what it is that is occurring.

**Comment by aquatooth** [comment]
A bump for this as 20 days have passed but Linux is still stuck on 2.12.2729 thus still without any of these changes.
hopefully there will be a container update soon, and hopefully it might include a PPA

**Comment by mythsunwind** [comment]
It is now possible to add our repository to your favorite Debian-based Linux distribution:
https://medium.com/@wireapp/52f0538cac15

Furthermore we now have implemented a new layout on the About dialog that gives you detailed information about which part of the application was updated. We also added a link to the release notes to the update banner.

**Comment by aquatooth** [comment]
medium.com is not accessible in China furthermore keeping instructions and information on the wire domain means that developers can keep control and maintain security.

**Comment by aquatooth** [comment]
the answer is here in case anyone is searching; https://github.com/wireapp/wire-desktop/wiki/How-to-install-Wire-for-Desktop-on-Linux

**Comment by aquatooth** [comment]
Thank you too all who worked on fixing this issue!
