### ISSUE TITLE
voice and video quality on slower/weaker/instable connections

### ISSUE THREAD

**Issue by Simplenuity** [wireapp/wire-desktop#515]
Both systems: Linux 64bit
Wire version: wire_2.12.2729_amd64 (no improvement compared to older versions)

On slower/weaker/instable network connections there are cut outs (voice), low video quality or even complete connection losses. Understandably to a certain degree of course.
BUT, why do other WebRTC applications like meet.jit.si still work? Do they have better package loss handling capability and/or less bandwidth requirements in general? 
And it seems that the quality deteriorates over time with Wire, too, under these network conditions.

PS: It goes without saying that on very poor connections video is turned off.

**Comment by RebelCoderRU** [comment]
Same here! Me and a person I call are both on the same country, both are on 100Mbps Up/Down (Same ISP). Skype, jitsi Meet, Hangouts are super clean an literally 0 problems. Wire, on the other hand, is actually unusable. 

List of constant issues;
1) Calls never arrive.
2) Calls are dropped/disconnected
3) Quality is very poor
4) A/V Quality degradation during a call

**Comment by Simplenuity** [comment]
If you need any further info or testing done, please let me know.

Question in regard to trouble shooting: Would it make a difference to use a non-desktop version, i.e. the web or android app? As I understand the underlying code is the same, isn't it? And the desktop app being only a wrapped web version, I assume it doesn't make a difference which platform to choose. But I might be wrong and therefore ask :)

**Comment by helenakos** [comment]
@Simplenuity The code is the same but there are differences such as the desktop clients using an older version of Chrome or if you use Firefox you might experience different calling issues than on Chrome. 

It's up to you what fits you the most, if you experience issues save the logs and send it to us :)

**Comment by Simplenuity** [comment]
Thanks @helenakos. I had a look around but couldn't find instructions of how to save logs on the desktop app like it's done on the Android version. Could you please advise?

**Comment by helenakos** [comment]
@Simplenuity You can get console.log and console.old from directory ~/.config/Wire/

Or run /opt/Wire/wire --args --devtools and look for errors in the console log when it happens

**Comment by Simplenuity** [comment]
Thank you @helenakos, I'll keep an eye on these files.
