### ISSUE TITLE
Wire auto-updates without any warning or prompt on Windows

### ISSUE THREAD

**Issue by Shadzillo** [wireapp/wire-desktop#5153]
I downgraded to 3.24 because of the dark theme bug (issue #5006). Wire updated itself on reboot to version 3.26 without any prompt or warning. Previously, it would display a prompt to update on top. This is no longer the case. An acceptable workaround would be to know how to block auto-updating with hosts file or firewall. Thanks for looking into this!

**Comment by ffflorian** [comment]
Hello @Shadzillo, Wire always updated itself on reboot. The prompt you saw appears when Wire for Web is updated. Wire for Web is the web application which is loaded within Wire Desktop.

To block auto-updating, add the following entry to your `hosts` file:

```
127.0.0.1	wire-app.wire.com
```

or block all connections to `wire-app.wire.com` in your firewall.

**Comment by Shadzillo** [comment]
Got it, thank you!
