### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by DOFfactory** [wireapp/wire-desktop#519]
This is a request for enhancement. Could you please include a changelog under the Help menu point of the app?

**Comment by maximbaz** [comment]
Although I really want to see such feature as well, until recently I thought the changelog is not available anywhere... and then I discovered [this page](https://github.com/wireapp/wire-webapp/releases). Better than nothing 😉

**Comment by lipis** [comment]
I think we decided to use the releases tab here as well with the next release..

**Comment by gregor** [comment]
Release Notes can are also shared at https://medium.com/@wireupdates

**Comment by helenakos** [comment]
There's a link to Wire releases in the About Wire screen. Also with each update you will see an Update banner with link to latest changelog.
![screen shot 2017-04-19 at 4 33 25 pm](https://cloud.githubusercontent.com/assets/5180637/25185618/1d539014-251e-11e7-8c16-70d70f135230.png)
