### ISSUE TITLE
Black menu when selecting audio/video devices KDE Plasma.

### ISSUE THREAD

**Issue by linuxgator** [wireapp/wire-desktop#520]
Whenever I try to select the audio or video device I'd like to use in KDE Plasma (currently on version 5.9.3), I only get a black box that drops down.  I can click on different areas and select different devices, as well as use the arrow keys to change between them, but would like to be able to see what's going on. Not sure if this issue is due to the toolkit it's built with or what.  I'm currently running version 2.12.2729 of Wire.  I've taken a screenshot of it.
![wire_menu_kde_plasma_5 9](https://cloud.githubusercontent.com/assets/26509750/24075072/33e8c796-0beb-11e7-847e-1b2efdd79211.png)

**Comment by gregor** [comment]
Is that the only dropdown menu that shows as a black box for you?

**Comment by linuxgator** [comment]
It occurs with all three drop down menus on the audio/video section of
preferences, however I have not double this behavior anywhere else in the
program. I have tried disabling the desktop effects in plasma also, but saw
no change.

**Comment by ConorIA** [comment]
I do not experience this on Gnome / GTK3. I wonder if it is a desktop integration issue. Electron uses GTK2, so perhaps Plasma isn't playing nice.

**Comment by linuxgator** [comment]
I've seen similar issues with tooltip colors not playing nice, and have
attempted the various fixes for that as they relate to GTK2 issues, but
none of them seem to affect this specific program.  It's not a major
problem, just a bit of a nuisance though, so I guess I'll just deal with it
for now.

Thanks

**Comment by ffflorian** [comment]
This should be fixed by now.
