### ISSUE TITLE
Local cache in config folder

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#521]
Subj, just noticed that all the files (photos, etc.) are stored in `~/.config/Wire/` so this folder is more than 500Mb now on my machine (and I just have 3 contacts for a month, no heavy communications), when the `~/.config` folder is supposed to only hold configuration files and everything transient should go to `~/.cache`.

Is it a limitation of electron or is it possible to somehow indicate where to store the cache? The problem is that when you copy `~/.config` in a corporate environment for roaming, backup and other purposes, you don't expect to move and store with it GBs of user data.

I put "Linux" in the title, but this issue may be present on other platforms too, just don't have them to confirm this.

**Comment by aquatooth** [comment]
Yikes! I just looked in there and there are already 1007 files total 148MB.
This on a 'testing account' with very little usage.
I hope that by commenting that this can be worked on in order to rectify!

**Comment by anatoli26** [comment]
OK, I see that there's some discussion in https://github.com/electron/electron/issues/8124 about separating config, data and cache by default for all apps, but I also found that this could be solved in each app independently of electron.

As electron looks like hesitant on this change (expecting to break some apps), I believe we could change it in Wire without waiting years for them to finally make the transition to the standards-based locations on the major platforms (and yes, this problem exists on all platforms, removing "Linux" from the title).

**Comment by lipis** [comment]
This could be related #427

**Comment by ConorIA** [comment]
This is definitely Electron specific. Even Electron-based browsers like Brave and Min store all the cache in `~/.config/`. 

@lipis, I'm not sure what you mean by related to #427. _But_ if something does change to move the transient cache to `~/.cache/` we will need to change the code in #427 to account for that.

**Comment by lipis** [comment]
@ConorIA Thanks for the detailed answer and research. You can ignore my comment, I had something else in mind :)

**Comment by anatoli26** [comment]
@ConorIA, there are some technical details in https://github.com/atom/atom/issues/8281#issuecomment-146009021 (mixed with a lot of frustration feedback, so not so easy to distill the useful info). I don't have an exact code change to apply though (I don't have much experience with electron), but if nobody knows how to do it I could investigate it futher.

**Comment by ConorIA** [comment]
@anatoli26, thanks for the link. From both the issue that you have posted and the issue that I posted, I gather that this is an issue on the Electron side that needs to be resolved. For now it seems that the Wire devs could only change where the user data gets stored (ref: https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname), but that would include both the config and the transient files.

**Comment by ffflorian** [comment]
@anatoli26 As @ConorIA already mentioned, this is not Wire specific.

So while we wait for electron/electron#8124 I'll close this issue. If you have further comments or insight, feel free to share :slightly_smiling_face:
