### ISSUE TITLE
Scrolling in Sidebar on macOS broken

### ISSUE THREAD

**Issue by rkapur-gds** [wireapp/wire-desktop#5214]
Wire version: ﻿﻿﻿3.26.4145
Wire for web version: 2021.06.01.12.23
Operating system: macOS 11.5
Which antivirus software do you have installed: ESET

What steps will reproduce the problem?

1.  Open Wire
2.  Attempt to scroll in sidebar

What is the expected result?
The ability to scroll in the sidebar using a mouse or trackpad.
...

What is the actual result?
Unable to scroll in sidebar using mouse or trackpad.
...

Please provide any additional information below. Attach a screenshot if possible.
Clicking and dragging the scrollbar seems to work, but using two fingers on Mac trackpad or scrollwheel on a mouse doesn't. Using the scrollwheel/trackpad in chat windows (the right side) seems to continue to work fine.
...

**Comment by rkapur-gds** [comment]
This might be a wire web issue — appears to happen when a user zooms in or out.

**Comment by jopek** [comment]
> This might be a wire web issue — appears to happen when a user zooms in or out.

thanks for pointing out the ZOOM settings. I gave up a while ago and lived with the restrictions of not being able to scroll. :)

**Comment by mythsunwind** [comment]
The zoom feature had to be removed because of this bugs. But we recently introduced an option to set the font size in the preferences to adjust the app to make the text easier to read.
