### ISSUE TITLE
Messages being greyed out and not being delivered

### ISSUE THREAD

**Issue by TheMorpheus407** [wireapp/wire-desktop#522]
My messages are being greyed out and are not being delivered.
It started happening out of the blue, some days all went well, then it started.
After a while it was working again, now it's not for more than a week.
So I think it's not a misconfiguration on my side.
This bug can be reproduced with every client I tried: Linux Desktop, Firefox Browser, Chrome Browser, Chromium Browser under both Linux and Windows.
It happens with every message although I can stil "like" my friends message and see what they write.
It is also chat-independent. I can text either of my friends, none of my messages will get through.
And furthermore I cannot see my own messages in a different Client, so say I sent from the Linux Client a message, I can't read it in my (verified) browser.
I think that would be all Infos I got for now.
EDIT: The problem is Account-independent.  I created a new account and cannot sent out any message. I sent out a contactrequest, which was received and accepted, cant write a message.
Incoming friendrequests can't be answered.
EDIT2: The problem was solved by using a VPN on my windows machine. I don't quite know why this helps, but perhaps you do.

**Comment by tmikaeld** [comment]
@TheMorpheus407 I've seen this exact issue before and i doubt it's related to Wire at all, it is either your DNS or your router that is not negotiating the connections or letting through packets (packet-loss).

Can you watch Youtube videos with good streaming? No stopping/starting on and off all the time?

Do you have this issue on your smartphone using wire? Is it connected to WIFI or 3G/4G data?

**Comment by TheMorpheus407** [comment]
@tmikaeld Thanks for your reply. My packetloss is permanently 0% as ping and some speedtests suggest, but I think it's because of my router or DNS which is blocking several different packets. Which protocols do you use?
Smartphone on wifi is having the same issue, on 3G it works like a charm.
So not an issue, just a bad provider.
Thanks again.

**Comment by tmikaeld** [comment]
@TheMorpheus407 The issue we had was with routers cache, this cause issues with streaming and P2P connections (as with Wire). So while surfing and other stuff might work, other protocols have issue because they use more router cache. If the router is specially old, the cache flash memory is so worn out that it cause random issues that might not be logical at first.

I'd for sure try with a different router first of all, there are a lot of cheap ones.

**Comment by bablf** [comment]
Commenting because this is the first issue that pops up when you search for the problem (`Wire not sending messages grayed out`): 

The issue seems to occur if you use Wire on two devices at the same time. Simply close the application on one device and the issue should resolve itself.
