### ISSUE TITLE
Strange bar in contact-list

### ISSUE THREAD

**Issue by DOFfactory** [wireapp/wire-desktop#527]
Hi guys, in the last version of wire (2.10.2652) a strange bar appeared next to the list of contacts. There were no such issues in the previous versions. 

I assume it has something to do with the recent enhancement of scrollable contact-list. See the attached screenshot. 

![wire](https://cloud.githubusercontent.com/assets/10846169/24194970/e3aef87e-0eef-11e7-9b07-5cf86dff9661.jpg)

**Comment by herrmannplatz** [comment]
merged a fix. should be fine with the next release
