### ISSUE TITLE
Onclick error

### ISSUE THREAD

**Issue by azlux** [wireapp/wire-desktop#528]
If you send :
`https://t.facdn.net/22382738@400-1485204208.jpg`

You will receive :
`22382738@400-1485204208.jpg" target="_blank" rel="nofollow noopener noreferrer">https://t.facdn.net/22382738@400-1485204208.jpg`

The link related on wire will be :
`https://t.facdn.net/%3Ca%20onclick=`
and make a weird blank page on the app.

![image](https://cloud.githubusercontent.com/assets/11210117/24221553/0ae30dd6-0f4f-11e7-91cc-e5fb699b79c0.png)

**Comment by gregor** [comment]
This issue has been addressed and the links is now properly parsed thanks to linkify.
