### ISSUE TITLE
Documentation: installation in Spanish

### ISSUE THREAD

**Issue by rosa2** [wireapp/wire-desktop#5325]
Hello and thanks a lot for the app :)

I am teaching it and I just made a document on how to install it in Spanish.
I don't know if here is the right place to return to you a bit of what you gave to us, the users.
Please, tell to me if I should do it in other place, but I searched and didn't find a place.
Also, for the future, I would like to translate Wire in Catalan. Could you tell to me the instructions?

Thanks a lot and have a very good day :)
[wire_instalar.odt](https://github.com/wireapp/wire-desktop/files/7159143/wire_instalar.odt)

**Comment by ffflorian** [comment]
Hi @rosa2, thank you for the document! I'll forward it to our helpdesk.

Translating Wire to Catalan would be great - we are using Crowdin for that, please see https://crowdin.com/translate/wire-desktop/1286/en-ca.
