### ISSUE TITLE
[Feature request] Native interface on Windows like telegram

### ISSUE THREAD

**Issue by r57zone** [wireapp/wire-desktop#534]
![](https://cloud.githubusercontent.com/assets/9499881/24307615/5b38966c-10de-11e7-8a57-9ed53d03155e.png) Native interface on Windows like telegram. The interface of telegrams is very simple and convenient, it works quickly, it was very cool to have on Wire with such a convenient and native fast interface. You can just take it from here - https://github.com/telegramdesktop/tdesktop (GPL)

**Comment by mat1th** [comment]
They are working on it see: https://github.com/wireapp/coax

**Comment by theincogtion** [comment]
A (barely working) native Wire client for **Unix**

**Comment by helenakos** [comment]
@r57zone Thanks for the idea. However we won't have the resources for a Windows native look in the near future. We will stick to Wire look for now. Therefore closing this issue.

**Comment by r57zone** [comment]
Сurrent interface is inconvenient, because of it your product will not become popular.
