### ISSUE TITLE
[Feature Request] Group Video Calls

### ISSUE THREAD

**Issue by jtflynnz** [wireapp/wire-desktop#536]
I couldn't find an active or inactive feature request about this, but figured I would make one for the record for future development.

Having used Group Calls, which are audio only but work well, I was curious if there are any plans to roll out group video calls down the line? If this isn't the proper place to post this, please let me know!

On a side note, I understand that this is much more complex than audio, there are many other high priority issues in the meantime, and that resources are limited; it may take a long while. But it seems like a good goal to implement down the road, especially as the reliability of calling continues to improve and the platform begins maturing. Additionally, it may provide monetization opportunities (IE group video calls over a certain size, guesstimating say 5 or 10 based on existing alternatives).

**Comment by helenakos** [comment]
@jtflynnz Thanks for the request! Indeed it's a great feature and therefore more complex. It's definitely something we want to have but it will take time as you said. We don't have a committed date yet for group video calling.

**Comment by helenakos** [comment]
Closing this as we don't have a committed date and it's not planned for the near future.
