### ISSUE TITLE
[Windows 7] User Profile Tool-tip Clipped by Window Border in Certain Scenarios

### ISSUE THREAD

**Issue by jtflynnz** [wireapp/wire-desktop#537]
Not sure what is happening here, but having some issues with the user profile "too-tip" you get when clicking on a profile picture. Sometimes, ti doesn't seem to change it's opening direction correctly and gets clipped:

*PLease note:*  I clipped the sidebar intentionally for my own redacting sanity

![image](https://cloud.githubusercontent.com/assets/5449443/24365302/80de7f1a-12e3-11e7-885e-420a4f6f2cd6.png)

Expected behavior: tooltip populates above the profile picture clipped location.
![image](https://cloud.githubusercontent.com/assets/5449443/24364949/4e39a8d8-12e2-11e7-97eb-14559c486703.png)

*OR* View would scroll to allow the tool-tip in full view (or both?).

Note, this behavior is compounded by how the click can generate an auto-scroll down from higher up in the window, then populates below the profile picture that is now lower in the window. Sometimes, the previous location of the profile picture would have shown the full tool-tip with no issues; post auto-scrolling behavior, the new location causes the tool-tip to clip.

My monitor is a 1920x1080 screen, but I keep the window un-maximized. Resizing the un-maximized window does not limit this behavior much from what my testing saw. 

Wire app for windows version: 2.12.2729

**Comment by jtflynnz** [comment]
Still occurs after an update (still wire version 2.12.2729)

![image](https://cloud.githubusercontent.com/assets/5449443/24373415/4a762bfa-12ff-11e7-87bf-b68ef36be872.png)

**Comment by gregor** [comment]
We have removed the profile bubbles in the conversations. The problem no longer occurs. I am thus going to close this issue.
