### ISSUE TITLE
Please adapt your browser detection to allow for Firefox ESR

### ISSUE THREAD

**Issue by berni421** [wireapp/wire-desktop#538]
Your request (34975) has been updated. To add additional comments, please reply to this email.

Wire Support - KG (Wire Support)

Mar 28, 11:31 AM CEST

Hi and thanks for writing.

I've shared your feedback with the web team lead.

Can you please also open a ticket for this on Github - which goes directly to the developers? https://github.com/wireapp/wire-desktop/issues

All the best,
Wire Support

Berni421

Mar 27, 10:22 PM CEST

Please adapt your browser detection to allow for Firefox ESR. My particular version is on Debian Stable - 45.8.0 ... I am a bit miffed you have denied my access to messages on this device.
This email is a service from Wire Support. Delivered by Zendesk.
[JME28Y-94R4]

**Comment by gregor** [comment]
We already did that this morning: 

https://github.com/wireapp/wire-webapp/pull/937/commits/a6159f80bc02ebeb0db4df0f044538365994e49d

With the next release we will let you back in. Some calling functionality requires newer versions of Firefox. With Firefox ESR 52 out we thought we could cut 45 immediately to remove the legacy stuff. We will let you back in with the next release but will mostl likely cut support once 52 is the only active ESR in the near future.

**Comment by berni421** [comment]
Thank you - I am back in.  I am sure you do appreciate that ESR is not legacy. :-)

**Comment by gregor** [comment]
@berni421 We made a quick release today - Firefox 45 ESR is back in but calling is disabled.

**Comment by berni421** [comment]
It seems app.wire.com is not working again on ESR 45 today. 

A blue page opens and a horizontal animated line appears. However, the white solid bar does not appear or progress from left to right as before. 

I have migrated one of my customers to ESR 52 and they can again see messages. Please could someone investigate.

Note: ESR 45 is supported by Mozilla until June 
https://www.mozilla.org/en-US/firefox/organizations/faq/

**Comment by herrmannplatz** [comment]
Could you check the browser console?

**Comment by berni421** [comment]
Logs around the time app.wire.com is opened.....I was also updating this message so some entries relate to github... hope this helps

JS .... 
TypeError: asm.js type error: Disabled by debugger wire-vendor.min.js
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create wire-vendor.min.js:23:17629
SyntaxError: invalid for/in left-hand side wire-app.min.js:53:19619

Net ...
GET 
https://app.wire.com/ [0ms]
GET 
https://app.wire.com/ [HTTP/1.1 200 OK 171ms]
GET 
https://app.wire.com/style/main.css [HTTP/1.1 304 NOT MODIFIED 30ms]
GET 
https://app.wire.com/min/wire-vendor.min.js [HTTP/1.1 304 NOT MODIFIED 86ms]
GET 
https://app.wire.com/min/wire-component.min.js [HTTP/1.1 304 NOT MODIFIED 99ms]
GET 
https://app.wire.com/min/wire-app.min.js [HTTP/1.1 304 NOT MODIFIED 126ms]
POST 
https://www.google.co.uk/gen_204 [HTTP/2.0 204 No Content 38ms]
GET 
https://github.com/wireapp/wire-desktop/issues/538#issuecomment-292123862 [HTTP/1.1 200 OK 1282ms]
POST 
https://www.google.co.uk/gen_204

CSS....
Error in parsing value for 'display'.  Declaration dropped. widget:1:22871
Error in parsing value for 'display'.  Declaration dropped. widget:1:22892
Unknown property 'box-align'.  Declaration dropped. widget:1:22948
Unknown property 'box-orient'.  Declaration dropped. widget:1:23012
Unknown property '-moz-border-radius'.  Declaration dropped. widget:1:23095
Error in parsing value for 'display'.  Declaration dropped. widget:1:23311
Error in parsing value for 'display'.  Declaration dropped. widget:1:23348
Error in parsing value for 'display'.  Declaration dropped. widget:1:23369
Unknown property 'box-align'.  Declaration dropped. widget:1:23425
Unknown property 'box-orient'.  Declaration dropped. widget:1:23489
Error in parsing value for 'display'.  Declaration dropped. widget:1:24252
Error in parsing value for 'display'.  Declaration dropped. widget:1:24289

**Comment by berni421** [comment]
Growing a long beard waiting for a fix. I can confirm upgrading to ESR 52 fixes this problem. Meantime whatsapp web carried on working. Naughty wire.com - go to the back of the class ! 
;-)

**Comment by gregor** [comment]
We have no plans maintaining backwards compatibility long term. Seems like we broke support for FF45 with our ES6 migration. As ESR52 is maturing quickly we will not allocate the resources to continuously tests compatibility with FF45 during every step of our ES6 migration. Expect to see a browser not supported page on FF45 soon again instead.
