### ISSUE TITLE
Request for a linux version

### ISSUE THREAD

**Issue by mimf** [wireapp/wire-desktop#54]
I'm here requesting a linux version of the wire-desktop client. Is it in the works?

**Comment by ConorIA** [comment]
What distro are you running? Instructions for compiling on Linux are in the read me.

**Comment by ConorIA** [comment]
I just tried to edit my comment but the darn edit disappeared! Here goes again: 

- If you are on an Arch-based distro, I maintain a pkgbuild in the AUR. 
- If you are in a Debian- or Ubuntu-based distro, I have an experimental deb repo (see that last few comments of pull request #27. I'd be happy to give you a script to help you roll your own .deb packages.) 
- Another user has contributed a disto-agnostic AppImage. This can be run from any directory. See issue #53. 

Keep in mind that these are all unofficial (yay, community). But rest assured, Wire developer @lipis has confirmed that they are working on it.

**Comment by lipis** [comment]
I'll start closing those and redirect the conversation to #63

**Comment by lipis** [comment]
We just published our first Linux version [medium.com/wire-news/get-your-linux-on](https://medium.com/wire-news/get-your-linux-on-999403a1a4fe) :) Give it a shot..

**Comment by mimf** [comment]
I'm testing it.. I'd like two things:

- A way to remove the menu bar. Perhaps a "View" option where one could toggle the menu bar;
- A way to resize the different components of the UI, for example, left panel and right panel (I feel like the contacts panel is a bit too big);
- More contrast in the chat box. I can barely see where one is supposed to type;

**Comment by mimf** [comment]
Also, how do I find out my device fingerprint on Wire desktop (linux)?

**Comment by lipis** [comment]
The fingerprints are under settings/preferences that are currently not available on Linux.. good catch.. addressed in #71
