### ISSUE TITLE
Desktop app takes too much time to sync messages

### ISSUE THREAD

**Issue by mohammadrafigh** [wireapp/wire-desktop#546]
how I generated this issue:
I use Wire in Mac, Windows, Linux and Android, when I don't open up and use one of these desktop apps for a few days (say 2-3 days) and frequently use wire in these days with another platform (say Android) it takes too much time in loading screen to sync messages between the android device and my desktop client. at the time of writing this issue I'm waiting for 20 mins and still in loading screen.

I had a 1 hour record for this loading previously on a mac device which I didn't use wire on it about 1 week. so this is serious in my opinion, because if I don't open up wire after 1 months in one of my devices this may take forever to load contents.

**Comment by gregor** [comment]
Thanks for reporting this. We are aware of the decryption on startup being a performance bottleneck and are continuously working on improvements in this area. One thing you can do to improve performace is to keep Wire in the foreground as Electron/Chrome is throttling perf when the app is put into the background. The decryption of messages is a very resource intensive task. Be assured that we will continue to work on improvements in this area.
