### ISSUE TITLE
How to start with devtools closed?

### ISSUE THREAD

**Issue by voidzero** [wireapp/wire-desktop#547]
Wire on the desktop is simply magnificent. Thanks for that.

Now, when I start up wire on the desktop, it automatically opens Chrome's developer tools. Is there any way to start Wire without this opened? If not, could it be added? Maybe a startup option like `--no-devtools`.

Thanks.

**Comment by gregor** [comment]
Where did you install the app from onto which platform? Production builds should only start with devtools open if you add startup option.

**Comment by voidzero** [comment]
Sorry for omitting this in the initial report. I am using a Funtoo Linux x86_64 with node v7.5.0, npm version 4.1.2. I don't open the devtools via a startup option - it simply always opens for me.

**Comment by lipis** [comment]
try running: grunt release-prod

since it looks like you are running it from the source..

**Comment by voidzero** [comment]
Yeah, I am, using nvm. I just cloned the repo, and issued `npm install`. To start up wire I issue `npm start`. Works fine, just starts up with the dev tools. There is no `grunt` command in my search path, but there is a `node_modules/grunt/bin/grunt` executable. I ran `grunt release-prod`, which gave this output:

```
 % node_modules/grunt/bin/grunt release-prod
Running "release-prod" task
Releases URL points to https://wire-app.wire.com/win/prod/ OK

Done.
```

Then I started up wire again with `npm start`. It still opens with the devtools.

**Comment by lipis** [comment]
Yep.. Found it.. if you start with `npm start` the `--devtools` is there: https://github.com/wireapp/wire-desktop/blob/master/package.json#L8 just remove it and you'll be fine. Unless you can build it for your machine.

**Comment by voidzero** [comment]
Thanks! So I guess I haven't built it then? How do I do that?

**Comment by lipis** [comment]
Check in the tasks https://github.com/wireapp/wire-desktop#tasks

**Comment by voidzero** [comment]
derp, completely overlooked that. Thank you. I'll close this!

**Comment by lipis** [comment]
No problem.. come back anytime:)
