### ISSUE TITLE
Emoji keyboard and images

### ISSUE THREAD

**Issue by voidzero** [wireapp/wire-desktop#548]
Is it possible to add an emoji keyboard to the app? Or maybe an extension to do this - I don't know if it's possible to add Chrome extensions to an app, but in Chrome I'm using this one: https://chrome.google.com/webstore/detail/emoji-keyboard-2016-by-em/ipdjnhgkpapgippgcgkfcbpdpcgifncb

Also, it would be nice if you can add emoji images. Because they look a lot nicer than relying on the default font. :smile:

**Comment by gregor** [comment]
One of us made a experimental side project tom implement something like this. Not sure when we will have the resources to properly make it part of the product.

The request is tracked at https://github.com/wireapp/wire-webapp/issues/408. Thereby closing this.
