### ISSUE TITLE
ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by shrikumar** [wireapp/wire-desktop#551]
Hi, We started using wire today and we are having a strange issue. One of the user is having 7 requests in his account but whenever the user tries to connect the user the desktop app just sits without responding. So i decided to check on the web app and same thing happened. Getting infinite following errors on console. Sorry not good with formatting logs

OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=undefined&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=undefined&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=atul7&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=atul7&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=devasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=deeplaxmisagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=deeplaxmisagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=deeplaxmisagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=deeplaxmisagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=deeplaxmisagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=deeplaxmisagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=yogeshsagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES
prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1:1 OPTIONS https://prod-nginz-https.wire.com/search/contacts?q=gitasagesurfer&size=1 net::ERR_INSUFFICIENT_RESOURCES

**Comment by gregor** [comment]
This is Chrome browser that Electron relies on telling you that it ran out of RAM.
