### ISSUE TITLE
CPU usage is way too high!

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#5535]
Consume a constant 27% CPU on a M1 PRO 

On a fresh start, Wire idling.

The Wire Helper
![image](https://user-images.githubusercontent.com/388716/151257196-92793546-1f28-436b-b7d7-4c6c86df8b4d.png)

For an app that's supposed to stay open in the background it's really problematic, draining batteries.

**Comment by MarcOverIP** [comment]
Same here. Wire on macOS on intel arch: never below 12% cpu usage. This makes is the single biggest CPU hogger on my system.

There are enough issues reported on this problem. But sadly not addressed.

Dear developers, what info do you need from us?

**Comment by sayuri-gi** [comment]
https://github.com/wireapp/wire-desktop/issues/2239

**Comment by MarcOverIP** [comment]
Yet, at Slack they've been able to combat it while Wire is increasingly using more and more CPU.

**Comment by jviide** [comment]
At least some of the CPU usage can be attributed to an invisible loading spinner animation. Pull request #5164 addresses that. The pull request has been merged, but a Wire version containing it has not yet been released.

**Comment by jviide** [comment]
Seems that a version containing https://github.com/wireapp/wire-desktop/pull/5164 has now been released to Mac App Store.

**Comment by mythsunwind** [comment]
Please wait a bit before updating. We are currently releasing another version as hotfix to the Mac App Store. Hopefully this gets released soon.
