### ISSUE TITLE
[Feature request] Higher text-density interface

### ISSUE THREAD

**Issue by ruxandra-valcu** [wireapp/wire-desktop#556]
Could we have an optional interface mode where there's less white space all around the text, and not-so-used space all over, please? I prefer seeing as much of the backlog at once as possible, and I'm sure I'm not alone in this.

**Comment by helenakos** [comment]
@ruxandra-valcu Hi, thanks for your request. It's a good idea, however I think we won't get to it in the near future considering the current resources.

**Comment by hylkevds** [comment]
I would already be happy with the option to just leave links as links instead of showing things like videos in-line.

**Comment by helenakos** [comment]
@hylkevds This one with link previews will be addressed 👍
