### ISSUE TITLE
Password login every time

### ISSUE THREAD

**Issue by theincogtion** [wireapp/wire-desktop#557]
If I start the Windows app I am immediately logged into my Account. I would prefer to be asked at least for my password. There seems to be no option for it.

**Comment by helenakos** [comment]
@theincogtion Indeed we don't have this option. Workaround is to log out after each use.

**Comment by theincogtion** [comment]
I am asking this for security reasons. If somebody gets physical access to my device he can just start wire and read everything. Please consider to implement an option that I am asked for the password at startup.

**Comment by lipis** [comment]
Usually you would do that in some safe environments and if anything you should definitely password protect your OS first. In case you will lose access to your machine (stolen, lost, etc) you can simply remove that device from Wire and it will be automatically logged out even if somebody will manage access your computer/device.

**Comment by theincogtion** [comment]
You are right but would it be really a reason to discuss this? This should be an easy change and an improvement in security.

**Comment by helenakos** [comment]
@theincogtion Thanks again for your request. Indeed there is always room for security improvements. As @lipis mentioned, in case someone gets physical access to your device you can always remove that device while logged in to a different device and the compromised device will be logged out, meaning the attacker won't have access to your data. Besides that, whenever a new device is added to your account, you will receive an email from Wire notifying you that a new device has been added. These are all measures we implemented to prevent attacks. Once logged in, the desktop user remains logged in and uses Wire on a daily basis without wanting to be prompted to enter his credentials more than once. Having that in mind we don't have plans at the moment to implement this feature request. Therefore closing this issue.

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
