### ISSUE TITLE
yarn throw err on archlinux

### ISSUE THREAD

**Issue by TheWorldBreaker** [wireapp/wire-desktop#561]
**I have some problem on archlinux! example:**

npm run rebuild-native-modules

> wire-desktop@ rebuild-native-modules /home/kevin/Downloads/wire-desktop
> electron-rebuild -f -m ./electron/node_modules

gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1033:11)
gyp ERR! stack     at TLSWrap.onread (net.js:584:26)
gyp ERR! System Linux 4.10.8-1-ARCH
gyp ERR! command "/usr/bin/node" "/home/kevin/Downloads/wire-desktop/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=1.6.5" "--arch=x64" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! cwd /home/kevin/Downloads/wire-desktop
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/home/kevin/Downloads/wire-desktop/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! wire-desktop@ rebuild-native-modules: `electron-rebuild -f -m ./electron/node_modules`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the wire-desktop@ rebuild-native-modules script 'electron-rebuild -f -m ./electron/node_modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wire-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild -f -m ./electron/node_modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wire-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wire-desktop
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kevin/.npm/_logs/2017-04-07T14_04_40_013Z-debug.log
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by TheWorldBreaker** [comment]
may be network err

**Comment by lipis** [comment]
We dropped support for Yarn a while ago.. so this last line is very suspicious. In the body it looks like you are using `npm run` though.. :|

**Comment by ConorIA** [comment]
Have you built in this folder before? I'd recommend a `git clean -fdX` and then `git pull` and try again.

Also make sure that you have `python2` installed.

**Comment by ffflorian** [comment]
@TheWorldBreaker Do you have any news regarding this issue?

**Comment by world-breaker** [comment]
@ffflorian  I'hava solved this problem, I'm in China, the GFW cause this problem,during electronic build  process,it needs to download some source, but download failed cased the problem.

**Comment by ffflorian** [comment]
Alright then I'll close this issue for now since it's not Wire related. Feel free to reopen if you have news :)
