### ISSUE TITLE
Two .desktop icons

### ISSUE THREAD

**Issue by fbruetting** [wireapp/wire-desktop#564]
At first start, I chose to create a .desktop file, but when Wire is running, a second icon is appearing in my dock (Fedora 25, Gnome 3.22.2, Wayland). The first one is the static favorite one I use for starting the program, the second one is tied to the actual program (the first one isn't). How can I connect the two, so that the static favorite gets it's dot/underline for visualizing that the program is running?

**Comment by Raytar** [comment]
I fixed this by adding `StartupWMClass=Wire` to  `/usr/share/applications/wire-desktop.desktop`

**Comment by fbruetting** [comment]
I'd made a PR, but I haven't found the correct file. O_o
One further thing: The .desktop file states `Icon=appimagekit-wire-desktop`, whereas the icon actually is just `appimagekit-wire`. Please correct this!

**Comment by mythsunwind** [comment]
Opened PR for the fix https://github.com/wireapp/wire-desktop/pull/1040

**Comment by fbruetting** [comment]
Is the icon also fixed in the meantime?

**Comment by mythsunwind** [comment]
Unfortunately that seems not to be an easy fix. Changing the icon for AppImage name, will change the name for the deb package too.

**Comment by fbruetting** [comment]
O_o
