### ISSUE TITLE
Wire from Homebrew Cask is reported as malware by MacOS Monterey

### ISSUE THREAD

**Issue by a-kriya** [wireapp/wire-desktop#5641]
**Wire version**: 3.26.4145
**Wire for web version**: Did not run
**Operating system**: MacOS Monterey 12.3
**Which antivirus software do you have installed**: None

#### What steps will reproduce the problem?

1.  `brew install --cask wire`
2.  Launch Wire from /Applications/
3.  OS malware alert

#### What is the expected result?

Wire launches successfully.

#### What is the actual result?

>Wire will damage your computer. You should move it to the Trash.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/26761352/159989177-0b0b5ed5-7ae0-40df-83ee-7af490a314cf.png">

#### Additional info

I have not tried installing Wire directly from the package or the App Store.

```
~ % brew install --cask wire
==> Downloading https://github.com/wireapp/wire-desktop/releases/download/macos%2F3.26.4145/Wire.pkg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/64225407/7b48d300-d7fd-11eb-94d7-6bf89971ae50?X-
######################################################################## 100.0%
==> Installing Cask wire
==> Running installer for wire; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
installer: Package name is Wire
installer: Installing at base path /
installer: The install was successful.
🍺  wire was successfully installed!
```

**Comment by tlebon** [comment]
#5354 

This homebrew cask *may* very well be malware, it is not run by the wire team. 

Use at your own risk. or use our [webapp](https://app.wire.com)
