### ISSUE TITLE
Wire-Desktop for Linux missing zoom feature

### ISSUE THREAD

**Issue by jop30** [wireapp/wire-desktop#5650]
When switching from Version 3.21 to 3.27 the zoom feature (Menu: Window -> Zoom out) is missing.
This makes it impossible to use Wire-Desktop on small or narrow screens (example: smartphone display with 720x1440 resolution).
On small/narrow displays only the contact list is shown, the actual conversation is missing because it doesn't fit in the window.
The zoom-out feature was the only workaround. 
Please reactivate the zoom or make the window scale properly for small / narrow screens.

Edit:
Additional information:

Architecture: ARM64
OS: Mobian Bullseye
Deployment: AppImage

Steps to reproduce:

1) sudo apt install nodejs npm git
2) git clone https://github.com/wireapp/wire-desktop.git
3) cd wire-desktop
4) sudo npm install --global yarn 
5) yarn
6) yarn start
7) sudo apt install ruby ruby-dev
8) sudo gem install fpm
9) USE_SYSTEM_FPM=true yarn run electron-builder --linux AppImage --arm64

**Comment by rkapur-gds** [comment]
The appear to have removed zoom because of this bug: https://github.com/wireapp/wire-desktop/issues/5214

**Comment by mythsunwind** [comment]
The zoom feature had to be removed because of various bugs. But we recently introduced an option to set the font size in the preferences to adjust the app to make the text easier to read.
