### ISSUE TITLE
[Feature Request] Option to disable webcam

### ISSUE THREAD

**Issue by predator8bit** [wireapp/wire-desktop#569]
Nowadays many laptops have built-in webcams, and to avoid accidental usage, please implement an option to disable these devices. For the simple reasons of privacy and saving some data on calls.

**Comment by gregor** [comment]
The option is available called audio call. If you want to avoid accidental use of your camera you can always disable it on the system level.

**Comment by predator8bit** [comment]
My friend claims he presses the audio call and the camera turns on nonetheless, I can't be sure if it is an actual bug or he is just clumsy, I'd just like to have a decent workaround for the situation.

**Comment by gregor** [comment]
We have not had a report of an audio call involving video. Please reopen with steps any anything that could help to reproduce if this is actually the case. There are no plans to disable camera usage otherwise.
