### ISSUE TITLE
No system tray icon with Ubuntu 17.04

### ISSUE THREAD

**Issue by smares** [wireapp/wire-desktop#574]
After upgrading my Ubuntu 16.10 installation to 17.04, the Wire icon disappeared from the system tray. Using Wire 2.12.2729.

**Comment by ConorIA** [comment]
Unity is finicky. Please see if this works for you: http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html

Note that this is nor a Wire-specific bug, as it seems to affect all Electron-based apps.
