### ISSUE TITLE
VoIP over TCP

### ISSUE THREAD

**Issue by HulaHoopWhonix** [wireapp/wire-desktop#577]
Hi, I am a WhonixOS dev - an anonymity and privacy distro catering for journalists and human rights workers. Knowing that you are the guys behind the great UX in Skype, we are thrilled about Wire's decision to opensource client/server code and the auditing results of your implementation by some very smart cryptographers.

Since we route all OS traffic through the Tor anonymity network we are only limited to TCP supporting applications. Can you please consider adding a VoIP/Video conferencing implementation that is based on TCP like you did for Skype?

cc/ @adrelanos

**Comment by raphaelrobert** [comment]
Wire already supports a TLS fallback if UDP is not doable.
This might impact the call quality however (due to retransmission), and routing calls over the Tor network might prove to be difficult due to high latency.

**Comment by helenakos** [comment]
@HulaHoopWhonix Thanks for your request. Would you be interested in getting in touch with one of our colleagues doing business research to learn more about how you use Wire?
