### ISSUE TITLE
PQ Crypto KEM for Wire

### ISSUE THREAD

**Issue by HulaHoopWhonix** [wireapp/wire-desktop#578]
Its expected that large quantum computers will eventually be developed within 10-15 years.

https://pqcrypto.org/

Their cryptanalytic capabilities will render all asymmetrical encryption used to day useless and in the Snowden revelations it was shown that nation-states adversaries are already storing all encrypted traffic intercepted today for this eventuality.

Before the end of this year the Tor project will deploy a Post Qunatum lattice-based cipher (New Hope) as a Key Encapsulation Mechanism around contemporary ECC ciphers for protecting them against future decryption. The spec is available here:

https://gitweb.torproject.org/torspec.git/tree/proposals/270-newhope-hybrid-handshake.txt

It would be awesome if a similar implementation can be planned for Wire for future assurance.

cc/ @adrelanos

**Comment by raphaelrobert** [comment]
We keep an eye on post quantum cryptography. It is still early days for most PQ algorithms like New Hope.

The hybrid approach is of course interesting, although it is not an encapsulation but rather a concatenation of two independent key exchange algorithms it seems (https://gitweb.torproject.org/torspec.git/tree/proposals/270-newhope-hybrid-handshake.txt#n51).

The assumption is that this might be more secure once quantum computers exist that can efficiently break X25519. However this implies that New Hope is also resistant against more 'traditional' attacks, and this is too early to say for now. In essence the bet is that New Hope is resistant against both quantum attacks and 'traditional' attacks.

On a more practical level this would also affect how pre-keys and ratcheting work. Key sizes are typically bigger for PQ cryptography (kilobytes vs. bytes) and public keys shouldn't be re-used.
It is also not clear if pre-keys would still work the same way using a split-roundtrip.

**Comment by ffflorian** [comment]
@HulaHoopWhonix Did this answer your question? If yes, please close this issue. Thanks :slightly_smiling_face:
