### ISSUE TITLE
[Linux] Links won't open + Images are stretched

### ISSUE THREAD

**Issue by RebelCoderRU** [wireapp/wire-desktop#579]
Hello.

I am on Linux Debian 9 (KDE). Links from the chat do not open up, showing a strange error (image 1 attached).

Also, images are stretched when viewed (images 2 and 3 to compare).

P.S. It does look strange to me, that Wire, willing to be the main messaging platform with the best security, does not update or prioritize Linux as it is the most secure platform. Using Wire on Windows, Android or iOS for example, is not secure at all, as keyboard and screenshot logging is a thing there, everyone knows that. so you are only encrypting your stiff from your ISP, not MS/Google/Apple and whoever is above them. Linux build of Wire is the worst so far. Please review your priorities. I, my friends and family and my development team, we are all on Linux and open-source software. Wire on Linux has a poor performance. Video quality is 4:3 res, images and links are broken. Hope I can switch to Wire full-time soon, if you will work on a Linux client.

Just working on a secure, open-source software and not having a proper Linux app does not make sense.

![screenshot_20170416_123718](https://cloud.githubusercontent.com/assets/20476773/25070338/f6b81668-22a3-11e7-939e-27b53bb73f8b.png)

![screenshot_20170416_123933](https://cloud.githubusercontent.com/assets/20476773/25070340/0370745e-22a4-11e7-96b1-2bec08ad26db.png)

![screenshot_20170416_123911](https://cloud.githubusercontent.com/assets/20476773/25070341/074fec30-22a4-11e7-8c1f-ac77a4714ef3.png)

**Comment by hlwsmith** [comment]
I am not able to reproducing these issues with v2.12.2729 or  v2.13.2739 on Debian 8 (using the Gnome based desktop "Mate").

**Comment by RebelCoderRU** [comment]
Hmm.. where did you get v2.13.2739 ? We still don't have PPA/Repo for wire, which is sad.

**Comment by hlwsmith** [comment]
I've been using wire since before that made binaries available for Linux so am in the habit of building it.  It maybe worth noting that I don't use .debs for the nodejs either I download https://nodejs.org/en/ and install in /opt and sim link to there from ~/bin. I think (hope) for Deb 9 this is not needed, in fact it's probably not needed for Debian 8 but node has been such a fast moving target historically that I prefer to be using the latest. I bring this up since you need nodejs to build wire-desktop.

**Comment by hlwsmith** [comment]
Also I think a Debian repo fro Wire is coming soon.. https://github.com/wireapp/wire-desktop/pull/566

**Comment by RebelCoderRU** [comment]
For me, streams during video calls from Linux to Linux, never switch to widescreen HD. Always stay ion 4:3, 640x480 (or something liek that). Skype and Jitsi Meet kick in 720p right away. Jitsi actually goes to 1080 as me and my colleague, we both have 100 mbit up and down.

**Comment by ConorIA** [comment]
For your first issue, what do you have set as the default browser? It is odd that you are getting errors from KIO, which is a KDE-specific mechanism. Do links open on KDE from other apps? I'm not at home until tomorrow, but I can't recall having these issues on KDE on Manjaro Linux.

**Comment by hlwsmith** [comment]
For me @RebelCoderRU the video resizes along with the window, so I can just make it bigger and wider to get an (approximate) 16x9 view manually, at least.

**Comment by RebelCoderRU** [comment]
@hlwsmith It is still 4:3, just cropped. try double-clicking on it and you will see what I mean. It is not even 720p.

**Comment by ConorIA** [comment]
@RebelCoderRU, I've tested on two KDE machines now. No issues opening links. Haven't checked the video resolution though.

**Comment by mythsunwind** [comment]
The link opening issue might be related to AppImage. The reason is that xdg-open is sometimes not correctly set in the AppImage "container". See https://github.com/probonopd/AppImageKit/issues/124 for more information. Are you using the AppImage, @RebelCoderRU ?
