### ISSUE TITLE
[Suggestion] Personal device

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#580]
So of what I've used the application it's great, design wise is lacking (in more details) but good for what it is (I mean really it's slick, every time I use Wire I learn fast and notice why it was placed in the way it was). 
**Enough praising, to the point**. So here are a not-well-structured suggestions:

- If the personal online/busy/away/offline/show offline system is placed the application should recognize (an option for the user to place) if you are in an temporary device. This makes for security on a personal level. As it is not for the end user to bother in general, this is a feature to help the end user who to be trusted (on a personal level) which helps a great deal if you think about it. The whole premise make this app really a more safe place, the slogan in my head "Communication is key" (in how people communicate and in how the interaction with the application with the end user per say too), but I am going off track here.

- More options are needed in how to customize your own application (well it's not really a need but it is appreciated),  such as background pictures, group the contacts, notification setting on a group/contact level (if you want to turn on/off the notifiaction on that group/contact)

- The cellphone application (Android, installed from the google app store), you have no limit on ping. You can constantly do it without wait. And on a fun level, if someone pings another pongs (respond). If you have multiple contacts on a chat. Well I guess everyone "pongs" (just once).

- I should be able to remove all/some history without removing the device id, as it is now I want to keep my ID but remove all history (have the application installed on my Solus Linux OS).

- Call should not be able to be turned off to be able to put a webcam on, this means you need to drop the call and call again with webcam as it is right now. Also not EVERYONE need to have a webcam to have a video call.

- Ping to the contact/server is always appreciated, then the end user get to see how long of a delay answers can be and becomes a more prominent to understand if it's worth having a call/video call and/or even send files/pictures.

**Comment by gregor** [comment]
Thank you for your suggestions. We will continue to track them internally and close this public facing ticket.
