### ISSUE TITLE
[Linux client] Chat issue

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#581]
I noticed that the client I built with `npm run build:linux` works nicely but I noticed that the more words I write on the chatbox to a contact, the more consistent delay it start having.
So I tested a simple method, just typing gibberish with no spaces and there is no issue but writing gibberish with spaces in between and the delay/lag starts happening.

**Comment by ConorIA** [comment]
There is a known issue with the spell check function. If you disable spell check, does that lag go away?

**Comment by aquatooth** [comment]
really?! I do not see any spellcheck function? version 2.12.2729 on Ubuntu, nor any method to enable or disable same.

**Comment by aquatooth** [comment]
now i have updated using PPA to 2.13.2739 but spellcheck function while ticked ON does no spellcheck.

**Comment by ConorIA** [comment]
Spellcheck only works with US English locale.

**Comment by aquatooth** [comment]
@ConorIA Well, that was just tested on one of my installs here it is in fact US English, others are on Australian English.
All installs [8 boxes]are now updated to using PPA, that took me several hours, thanks for your team fixing that!
To be clear, 2.13.2739 on Ubuntu 12.04 set to US English does not perform spelcheck!

**Comment by aquatooth** [comment]
ok, been testing and after changing firefox to EN_US it seems to now work.

**Comment by aquatooth** [comment]
now I set firefox back to another english and it still does work, sorry I may have missed a reboot or something whacky occurred!

**Comment by lipis** [comment]
If you are using Firefox (or any other browser) you have to check the spellchecker from the browser's settings.. it has nothing to do with Wire. If you are using the desktop client then indeed it works only for English at the moment.

**Comment by aquatooth** [comment]
ah, apologies for confusion, it is the wire-desktop version, not using firefox, but in testing i had thought it might be related. thus the language setting used in firefox has zero bearing on the wire-desktop version.
@lipis Works only when Ubuntu locale is set to 'US English' at the moment!
Note that Ubuntu 'Language Support' 'Language for Menus and windows' and 'Regional Formats' are the terminology used in GUI settings. For CLI type locale and hit enter, and or localectl

**Comment by lipis** [comment]
@aquatooth Yes.. this is by design. We do not support more spell checking in other languages other than English.

**Comment by aquatooth** [comment]
May not be correct, it may not work if 'just set to English', it must be set to 'US English' 
Thus ONLY 'US English' is supported for spellcheck
Sorry to be pedantic, but it does keep things clear as 'English, US English, Australian English' are 3 different settings in Ubuntu

**Comment by ConorIA** [comment]
You're right. Just en-US.

**Comment by aquatooth** [comment]
Sorry Sethox if I have 'hijacked your issue', but this does seem related and I hope you can get yours working too!

**Comment by Sethox** [comment]
No worries, I should mention that I am using Solus-project linux.
As I read the posts, it's true to what it's claimed here. It's the spellcheck that causes the "lag". Removing the it removes it completely. I should close this issue since I bet it has been issued before. Going to look it up (the other related issues) and relate to those (and finally close this one).

**Comment by Sethox** [comment]
So searching for a bit on the term "spellcheck" it didn't hit many issues. Closest is #341 where linux application should get spellcheck. So I am leaving this issue open for the issue of the spellcheck.

The issue is having performance loss/"lag" while having spellchecking on. Turning it off works as a workaround for the moment to solve the lag.

Would be interesting to investigate to what causes the lag...

**Comment by aquatooth** [comment]
it seems such a simple thing, but after reading up, what a can of worms!
no wonder that Wire 'only supports' en_US [aka in GUI; English United States] and that @Sethox has 'a bit of a bug'
I guess this will wait until one of your team has an 'eureka moment!'

**Comment by ffflorian** [comment]
@Sethox: Duplicates: https://github.com/wireapp/wire-desktop/issues/479 and https://github.com/wireapp/wire-desktop/issues/379 :wink:

**Comment by Sethox** [comment]
As @ffflorian says:
Duplicates: #479 and #379 
Closing this issue

**Comment by dandv** [comment]
Pardon my ignorance, but where is the spell check option? I must be having temporary blindness, because I don't see it anywhere in Wire Desktop for Linux. And it's disabled.

Version 3.10.2904
Wire for Web Version 2019.10.16.1539

**Comment by ffflorian** [comment]
@dandv The spell checker was removed in January, see https://github.com/wireapp/wire-desktop/pull/2023
