### ISSUE TITLE
Disable typing / delivered / read indication

### ISSUE THREAD

**Issue by mirko** [wireapp/wire-desktop#582]
Hello,

maybe I just didn't find it yet, though I think I scrolled through all available settings dialogs a number of times so far:

Where can I disable notifying my roster buddy of me typing / having seen/read a message?

And if there's no such setting yet: I consider this quite an important privacy feature and would really like to see that making it into the app.

Any hint and/or status on this matter?

Thanks a lot in advance

  mirko

**Comment by helenakos** [comment]
Hi @mirko, we don't have such change planned at the moment. 

Wire clients currently have Sent and Delivered status. There is no Read/Seen status. We don't currently have plans to add a setting for Sent and Delivered status. 

Wire desktop clients don't have the typing indicator, only the mobile clients. Please see if they have an issue in wire-ios or wire-android repos. You can also open an issue for general comments here: https://github.com/wireapp/wire
