### ISSUE TITLE
macOS: Support Text Shortcuts

### ISSUE THREAD

**Issue by Dexwell** [wireapp/wire-desktop#583]
E.g. when you have set up (c) → © or text-to-emoji shortcuts in System Preferences. Can easily be implemented in Electron using [electron-text-substitutions](https://github.com/CharlieHess/electron-text-substitutions)

![SysPrefs](https://camo.githubusercontent.com/04a377ca6b0aa56a9da94106e672bf1d4f3b6fec/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f316c315931563046303432723243304c316532302f496d616765253230323031362d30362d30362532306174253230372e32382e3434253230504d2e706e673f763d3661613331353066)

**Comment by gregor** [comment]
Thanks for your feature request. There is no immediate plan to implement this but it will continue to be considered.
