### ISSUE TITLE
Don’t bounce the Dock icon

### ISSUE THREAD

**Issue by jaanus** [wireapp/wire-desktop#584]
OSX 10.12.4
Wire 2.13.2737
Wire for Web 2017.04.07.0942

Observed: with today’s update from App Store, Wire started bouncing the Dock icon. I don’t want that.

Expected: don’t bounce the dock icon at all OR provide me a switch to turn off this behavior.

**Comment by mat1th** [comment]
When you do not like the bouncing icons, you can also disable it system wide. See http://osxdaily.com/2010/02/19/disable-dock-bouncing/

**Comment by gregor** [comment]
Currently implementation is by design with no plans to change it.
