### ISSUE TITLE
The desktop app doesn't detect input channel of an audio device

### ISSUE THREAD

**Issue by sitzmoebelchronograph** [wireapp/wire-desktop#5840]
Dear all,

I'm using wire linux for a couple of years in our company and the environment works fine, but since a couple of month I have a problem with one of my audio devices.

## The working environments are

- Wire version: 3.27.2944
- Wire for web version: 2022.06.30.13.51
- Operating systems:
    - Kali GNU/Linux Rolling Release 2022.2
    - Debian SID 
- Antivirus software: none
- Audio Device: Jabra Evolve 75 connected by USB to the Linux device

## The problem
The Problem is, the wire-desktop app doesn't detect the mic input channel of my Jabra headset.
It detects only the the Jabra device output channel.

If I use the the wireweb version on a browser like Chrome/Edge/Firefox it works fine as well.
All other apps on my Linux machines detects the output and input of the Jabra headset.

## What I did to figure it out
- Installing a couple of different versions from "https://wire-app.wire.com/linux/debian stable main"
    - 3.27.2943
    - 3.26.2941
    - and some other but i can't remember the version numbers
- Switching between Linux Distributions Debian-Stable / Debian-Testing / Debian-Sid / Kali Rolling Releases
- Nothing happend in all combinations the same problem
- Deleting all wire realeted packages/files
- It's also happend on a fresh installed distri

I can't understand why I can use my audio device in the browser but not in the desktop-app.

Does anyone have an idea how I can fix this issue? Let me know if you need more informations.

greetz

Andreas

**Comment by tlebon** [comment]
@sitzmoebelchronograph Is this still an issue for you? 
Have you tried changing the input via the settings menu or if you are in a call via the dots below the audio icon? 
Please try in the current release and get back to me if it still isn't working.

**Comment by sitzmoebelchronograph** [comment]
@tlebon
There is no way to change the setting because the microphone is not recognized.
Not in the settings and not while doing a call.

And yes, sometimes it is (actually used version is Version 3.28.2946)
But maybe this is not an wire-issue. I switched from Gnome to KDE Plasma and at the moment it looks like the problem is gone.

**Comment by tlebon** [comment]
Hmm strange. 
I don't have any particular insight into this, unfortunately. 

My guess is that this is related to your Linux version? 

Or else its a linux/electron issue possibly we could try to debug. 

I do recommend updating to 3.29 as we recently released this for linux as well. 

In the meantime, I will close this for now, and if you find it happening again please simply comment.
