### ISSUE TITLE
No tray icon when installing from repository

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-desktop#585]
I know that there are other issues with the tray icon disappearing, but I think this one is different (as I didn't experience it until right now). I'm on Ubnutu 16.04 (yes, I need to upgrade, I know) and I just installed wire from the official repository following this guide: https://medium.com/@wireapp/a-step-forward-for-wire-for-linux-52f0538cac15.
Now I don't have an icon with the logo anymore, just a generic icon provided by ubuntu.

**Comment by someoneEsle** [comment]
More details:
right after I open Wire, two icons appear -- one has the logo, and one doesn't. The one with the logo disappears after a few seconds
![c](https://cloud.githubusercontent.com/assets/21009625/25135459/b61b5196-2452-11e7-9b81-7a43513169d3.jpg)

**Comment by aquatooth** [comment]
I too am using Ubuntu 16.04 LTS, but this did not occur. No icon appeared, the old one for 'Wire' remained present, so I clicked Dash and search for wire, found the new one now called wire-desktop and dragged that to the launcher bar, and right click unlock from launcher

**Comment by someoneEsle** [comment]
If I drag the new icon (the one with the logo) on the tray and then click it to launch Wire, a new icon (with the gears) is created :/

**Comment by someoneEsle** [comment]
I fixed it. I went to `.local/share/applications` and deleted some shit I had in there (aka I deleted random files), then I reinstalled wire and the icon works fine now.
