### ISSUE TITLE
Video Freezes/Pauses when right clicking in text box

### ISSUE THREAD

**Issue by slurps-mad-rips** [wireapp/wire-desktop#586]
Hello,

A friend and I were having a video call tonight, and we just happened to discover that when right clicking in the text box for the conversation area, that our video will pause/freeze until the context menu goes away. We're on different operating systems. They are on Fedora 25, and I am on Windows 10. We also tested this on macOS to Fedora 25 and we got the same issue. Audio continued to play just fine. Can't think of any other information, but please let us know if you need something.

**Comment by helenakos** [comment]
@slurps-mad-rips Did you notice this issue again?

**Comment by slurps-mad-rips** [comment]
@helenakos Hi, my friend and I successfully recreated this behavior last night.

**Comment by ffflorian** [comment]
This should be fixed by now. If not, feel free to comment here.
