### ISSUE TITLE
Launch Wire on startup stopped working

### ISSUE THREAD

**Issue by aquatooth** [wireapp/wire-desktop#588]
Ubuntu 12.04 LTS 64bit
Wire 2.13.2739 installed using PPA

Wire>tick ON 'Launch Wire on Startup'
Reboot, login and Wire does not start.....

**Comment by aquatooth** [comment]
Further testing;
Ubuntu 16.04 LTS 64bit
Wire 2.13.2739 installed using PPA

Wire>tick ON 'Launch Wire on Startup'
Reboot, login and Wire YES DOES start

**Comment by aquatooth** [comment]
Just a note that 12.04 LTS support ends this year and that I am yet to test 14.04 LTS, [support until 2019]

**Comment by ConorIA** [comment]
Was this an upgrade? It might have to do with with change in the name from wire to wire-desktop. Open `$HOME/.config/autostart` and see what Wire-related entries are there. Remove any you might see and try hitting the checkbox again to see if the correct `.desktop` file shows up.

**Comment by aquatooth** [comment]
ah, cannot really 'upgrade' from older 'wire' to 'wire-desktop' it is more or less a new installation? and a remove of old. although some old setting did seem to stay the same, not others, so i am not entirely sure about that.
i will continue testing in around 8-10 hours time. any further pointers appreciated.

**Comment by ConorIA** [comment]
@aquatooth, the startup function is provided by https://github.com/Teamwork/node-auto-launch. On Linux, it just checks `$HOME/.config/autostart` to see if there is a `.desktop` file, and creates one if there isn't. If you have that folder open, you can even watch the file disappear and re-appear when you toggle the checkbox. Before the upgrade, this file was called `wire.desktop`, now it is called `wire-desktop.desktop`. I have no other pointers to offer! 😉

**Comment by aquatooth** [comment]
@ConorIA Which means something is not right under Ubuntu 12.04 LTS with the desktop version of Wire, as that file is not created. I can see the old one $HOME/.config/autostart 
I did a lazy and simply re-named the old file to the new filename. now rebooting to see if that works as expected!

**Comment by aquatooth** [comment]
@ConorIA Which means something is not right under Ubuntu 12.04 LTS with the desktop version of Wire, as that file is not created. I can see the old one $HOME/.config/autostart 
I did a lazy and simply re-named the old file to the new filename. now rebooting to see if that works as expected!

**Comment by aquatooth** [comment]
ok, lazy works, but this is just a workaround and not bug fix.
now the .desktop file disappear and re-appear when you toggle the checkbox so that part does work, it just the initial creation of wire-desktop.desktop fails.

**Comment by aquatooth** [comment]
ok, so these are the steps taken to re-install Wire [wire-desktop] version using PPA on Ubuntu 12.04 LTS 64bit, and to apply workaround to get autostart to work as expected 
Terminal;
sudo apt-get install apt-transport-https
sudo apt-key adv --fetch-keys http://wire-app.wire.com/linux/releases.key
echo "deb https://wire-app.wire.com/linux/debian stable main" | sudo tee /etc/apt/sources.list.d/wire-desktop.list
sudo apt-get update
sudo apt-get install wire-desktop
sudo apt-get remove wire
sudo apt-get purge
Browse to $HOME/.config/autostart and delete wire.desktop
remove Wire icon on launcher, [right click unlock]
Dash search 'wire', drag ‘wire-desktop’ to launcher bar
start wire from icon
Wire>Launch Wire on Startup (shows already ticked ON) but wire-desktop.desktop does not exist, toggle OFF then back ON and  wire-desktop.desktop is now created
reboot to make sure all works!

**Comment by ffflorian** [comment]
@aquatooth Is this bug still present? I could not reproduce it on Debian. When I tick the menu to automatically launch Wire it creates the `.desktop` file and starts correctly.
