### ISSUE TITLE
Spammy "YOU HAVEN'T USED THIS DEVICE FOR A WHILE. SOME MESSAGES MAY NOT APPEAR HERE." message

### ISSUE THREAD

**Issue by moburkhardt** [wireapp/wire-desktop#5899]
Wire version: Versio. 3.28.4393
Wire for web version: 2022.06.30.13.51
Operating system: macOS
Which antivirus software do you have installed: HAHAHAHA

What steps will reproduce the problem?

1.  use the wire app and wait…
2.  ...
3.  ...

What is the expected result?
Not see any messages.

What is the actual result?
A huge amount of messages:
YOU HAVEN'T USED THIS DEVICE FOR A WHILE. SOME MESSAGES MAY NOT APPEAR HERE.

Please provide any additional information below. Attach a screenshot if possible.
I have wire constantly open and thus am using the app and the device.

![Screenshot 2022-08-05 at 13 50 42](https://user-images.githubusercontent.com/169051/183071739-74620b4b-1e7e-42e0-b5ba-586824481097.png)

**Comment by rosa2** [comment]
I got the same on Ubuntu 22.04 Wire 3.28.2946
Thanks for the software :)

**Comment by chriseomi** [comment]
I'm getting this all the time. I have Wire Desktop on macOS open mostly. People send me messages every day or so. Not sure what gives. I read something about 28 days, but that doesn't apply to me. I'm sending and receiving every day or every 2nd or 3rd day.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/49441974/188526180-4ef8364e-68c6-4ede-aadb-9d0caa95bf4e.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/49441974/188526235-675c435f-7fb1-431b-ab23-f58b7a157488.png">

**Comment by chriseomi** [comment]
Also not sure if it matters, but should mention I'm using wire with a sock5 proxy ` --proxy-server='socks5://localhost:5000`. Maybe not related but I guess it's a more unusual context.

**Comment by chriseomi** [comment]
Also just realized my Wire was on version`3.26.4145`, so just updated it now to `3.28.4393` and will see if it helps.

**Comment by timashev** [comment]
The same problem here:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/695076/201006091-3431b95b-c07a-4651-a623-e6fa52ad5887.png">
**REALLY ANNOYING!!! FIX THIS ASAP PLEASE!!!**

**Comment by tlebon** [comment]
This is fixed now! We haven't cleared the previous warnings that arrived but you shouldn't see any new messages of this kind (unless there is a valid reason for it which does happen occasionally).
