### ISSUE TITLE
Allow changing audio/video settings while on the call

### ISSUE THREAD

**Issue by agurenko** [wireapp/wire-desktop#591]
It would be great to be able to change audio/video settings during the call. Right now when you press preferences it opens settings, but "underneath" the video feed, so once the call ended you're at preferences window, but you cannot do it without ending the call. At least I'm talking about Linux app.

**Comment by agurenko** [comment]
So is it accepted as a bug? It's not an intended behavior?

**Comment by gregor** [comment]
Just retested this today. Definitely no longer happens in the new implementation that will be released soon.
