### ISSUE TITLE
Font formatting inline commands

### ISSUE THREAD

**Issue by hThoreau** [wireapp/wire-desktop#594]
Good evening,

I've notice that by putting words between asterisks or underlines in wire-desktop I can present them in their Italic variation, while the punctuation around them are omitted. Also, a friend of mine copied a piece of monospaced text into wire-desktop, and it that was displayed to me as such. Though this isn't an issue by itself, I found it troublesome that this feature isn't explained anywhere. Not in the app's preferences, not in its website, not in its blog, and not by asking Otto.

Thank you for your attention.

**Comment by helenakos** [comment]
@hThoreau Thanks for your feedback. We have to revisit this feature and improve on the basic formatting that's currently in the app. 

Bold: This is **bold**
Italic: This is _italic_
Bold italic: This is _*bold italic*_ and *_bold italic_*
Code: This is `inline code`

We'll see if we can have these somewhere ^
