### ISSUE TITLE
Long messages unencrypted if self-deleting messages is on

### ISSUE THREAD

**Issue by rosa2** [wireapp/wire-desktop#5961]
**Wire version:** 3.28.2946
**Operating system:** Ubuntu 22.04 and Windows 10 and MacOs Monterrey 12.2
**Which antivirus software do you have installed:** none

What steps will reproduce the problem?

1.  In a group of 4 people with messages set to 30 days self-deleting
2.  I write from Ubuntu a long message,
3.  The others when they have a bad connection (I think this is the reason) the message is not unencrypted, but if i write a short one, they can see it well.
4. Even if they stop Wire and in a good connection they start it, the old long messages don't get unencrypted. 

What is the expected result?
Long messages get unencrypted
...

What is the actual result?
Long messages don't get unencrypted
...

Please provide any additional information below. Attach a screenshot if possible.
Before we put the self-deleting, never had a problem.
...

**Comment by atomrc** [comment]
Hi @rosa2 Thanks for the report. 

There are 2 issues at hand: 
- the one with the bad internet, that is being addressed as of now and will go out with the next release
- the one with long messages that are longer than the viewport. This one has been addressed with this PR https://github.com/wireapp/wire-webapp/pull/13338 and has been released this week. 

Please let us know, once you restart your wire application, is the problem with long messages persists or not. 

Thanks again.

**Comment by rosa2** [comment]
Hello
Sorry to answer so late, but the person that had the problem didn't report to me (she wasn't in internet).
Problem solved! Thanks a lot :)
