### ISSUE TITLE
Trace/breakpoint trap   (core dumped) electron18 "/usr/lib/wire-desktop" "$@"

### ISSUE THREAD

**Issue by anfractuosity** [wireapp/wire-desktop#5992]
Wire version: Version 3.28.2946
Wire for web version: Wire for Web Version 2022.06.30.13.51
Operating system: Linux/Arch

What steps will reproduce the problem?

Just leave wire-desktop running for a few hours

What is the expected result?

No crash

What is the actual result?

```
/usr/bin/wire-desktop: line 3: 49960 Trace/breakpoint trap   (core dumped) electron18 "/usr/lib/wire-desktop" "$@"
```

**Comment by J-Brk** [comment]
How's your memory usage during this time?

**Comment by anfractuosity** [comment]
I'm not sure afraid, I'll have a look when it next happens.  I just rebuilt electron18 with debug symbols, to hopefully get more information next time.

**Comment by anfractuosity** [comment]
Haven't been able to replicate this recently, wire now seems to use electron19, rather than 18.
