### ISSUE TITLE
Linux starts in full screen

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-desktop#6]
Hi folks, I know you are not officially supporting Linux at the moment, but I figured I'd put this on your radar anyway. When the app is built on Linux, the login screen starts in a window on first run. However, subsequent runs of the app will launch in full-screen mode with no menu bar, and no way of returning to windowed mode. I'm happy to try and troubleshoot. 

On an unrelated note, I'm maintaining an AUR PKGBUILD over here: https://aur.archlinux.org/packages/wire-desktop/

**Comment by fenrig** [comment]
I second these on 2 different arch linux devices, needs to be fixed asap

**Comment by fenrig** [comment]
I think it has something to do with line 148 in "electron/main.js" but I dont have any experience with electron whatsoever

**Comment by lipis** [comment]
Fixed in #18 :) Thanks playing with it..

**Comment by ConorIA** [comment]
Cheers!

**Comment by fenrig** [comment]
Thank you!

**Comment by lipis** [comment]
![penguins-aqQsmtq6J2L16](https://camo.githubusercontent.com/b9c2c5bb168f15fc8fa35f160a62cf6c394c2a42/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f617151736d7471364a324c31362f67697068792e676966>)

**Comment by geileszeuch** [comment]
It definitely doesn't start in fullscreen anymore, but now I cannot see half of the screen. Is there some secret combination to go to fullscreen?
![1](https://cloud.githubusercontent.com/assets/1734974/17945967/7b63c108-6a46-11e6-98be-56e9a2db3ee4.jpg)

**Comment by ConorIA** [comment]
Can you resize the window in the bottom right? I had no trouble changing the width in GNOME (there does seem to be a minimum height though).

**Comment by geileszeuch** [comment]
I could not resize it before, but now it does work (even after reverting the change to utils.js). Must be something wrong with my system.
