### ISSUE TITLE
[macOS] Add menu bar icon

### ISSUE THREAD

**Issue by Sytten** [wireapp/wire-desktop#601]
It would be nice to have a menu bar icon with some options.
On macOS this is specially nice since you don't have to keep the app in your dock.
I might do a PR since its fairly simple to do with Electron.

**Comment by ConorIA** [comment]
Is #448 what you're looking for? If so, I think the devs have closed this as a WONTFIX, but the author of the PR seems to maintain a fork with the icon.

**Comment by lipis** [comment]
Thank you @Sytten but we decided to not have it on macOS as @ConorIA already mentioned and found the right PR for it, where you can find more info about it.

**Comment by Sytten** [comment]
I commented on the PR. It is still strange not to provide at least the option since it's such a common feature on macOS.
