### ISSUE TITLE
[Linux] bad link in /usr/local/bin

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-desktop#602]
When instaling wire-desktop on Ubuntu 16.04 from the PPA, the setup creates the following link in `/usr/local/bin`: `<%= executable %> -> /opt/<%= productFilename %>/<%= executable %>`.

It looks like the placeholders are not replaced with the actual values.

**Comment by aquatooth** [comment]
yes, I have this too.
Ubuntu 16.04 LTS wire-desktop 2.13.2739 installed via PPA web 2017.04.20.1554
