### ISSUE TITLE
[Linux] constant CPU use...

### ISSUE THREAD

**Issue by jdiercks** [wireapp/wire-desktop#607]
Wire for Linux 2.11.2685 appears to be using about 16% CPU constantly.

**Comment by ConorIA** [comment]
Likely related: #14 #122 #135 #280 #473 
Root cause: https://github.com/wireapp/wire-webapp/issues/1112
and fix: https://github.com/wireapp/wire-webapp/pull/1115

**Comment by ffflorian** [comment]
Closing because of duplication.
