### ISSUE TITLE
Custom installation Directory / Multiple Instances

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-desktop#61]
Would it be possible to set a custom installation dir?

I wasn't asked while installing the desktop client where to install the app. It's just putting everything to %appdata%\wire and
%localappdata%\wire (in production version)

First, as a desktop user, you're used to get asked where to install a program to.
Second, there are many reasons why you want to choose a different location, f.i.: hard drive space, ssd vs hd space, custom arrangements of program locations and backup processes, etc.

And if you think about that a bit further, you might want to have 2 wire accounts running simultaneously on your desktop, requireing a second instance of the wire desktop client.
I'm just describing an example:
one desktop client with a private account for family and friends and a second account running in another wire desktop client instance simultaneously for business contacts only.

You can't run 2 instances of the wire desktop client simultaneously at the moment, because they all use the same installation directory %appdata%/wire (and probably for a bunch of other reasons: like webcam/mic share, multiple process support, etc.)

Tox (µtox/qtox) resolved this issue somehow and it'd be wonderful to have this feature in wire too!

What are the chances that we get a feature like that?

**Comment by tokariu** [comment]
Just for the curious, if you want to use multiple windows wire clients at the same time: the workaround is the same as it's been with Skype:
You have to create a new windows-user for each instance of Wire-Client. Install the Wire-Client under the new User. Back to your main user-profile, create a copy of the Wire-Client shortcut and start it with a "Run as: <user you created>"-option. This way it's starting another instance of the Wire-Client.

This workaround is nothing new, though. I just hope we get a better, more convenient solution in time.

**Comment by helenakos** [comment]
@tokariu Hi, thanks for the idea and suggestion, we won't support running a few instances in the near future so will have to close this one.
