### ISSUE TITLE
[Linux] Cannot make or receive calls

### ISSUE THREAD

**Issue by Libbum** [wireapp/wire-desktop#612]
I'm using the latest Arch build from the AUR, and cannot seem to send or receive calls. I click the button to do so, and I hear the ringing sound, but after a while it hangs up and the call never happens. This occurs with any contact including the tutorial bot. 

The only lead I have for the problem is on stdout if I run from the terminal:

    [6622:0427/201514.285935:ERROR:audio_send_stream.cc(90)] Failed to set up send codec state.

**Comment by lsfxz** [comment]
Can confirm, same issue here. Also doesn't work with the git package. Slightly more output when directly running from git:

```
[22961:0504/084508.268394:ERROR:audio_send_stream.cc(90)] Failed to set up send codec state.
[22961:0504/084508.370254:WARNING:p2ptransportchannel.cc(518)] Jingle:Port[0x1074f6a58c00:audio:1:0:local:Net[wlp3s0:192.168.2.x/24:Wifi]]: SetOption(1, 65536) failed:
 0
[22961:0504/084508.370380:WARNING:p2ptransportchannel.cc(518)] Jingle:Port[0x1074f6a58c00:audio:1:0:local:Net[wlp3s0:192.168.2.x/24:Wifi]]: SetOption(2, 65536) failed:
 0
[22961:0504/084508.370545:WARNING:p2ptransportchannel.cc(518)] Jingle:Port[0x1074f6a58c00:audio:1:0:local:Net[wlp3s0:192.168.2.x/24:Wifi]]: SetOption(5, 0) failed: 0
[22961:0504/084541.813592:WARNING:audio_send_stream.cc(295)] SetSendCodec() failed: 8005
```

Running the webapp itself directly from git doesn't work at all, but when trying it with [app.wire.com](https://app.wire.com) it _does_ work (ie. making a call).


In case it's relevant: I'm using pulseaudio.

**Comment by Iridias** [comment]
Confirmed as well. Using KDE neon (Ubuntu based).
Looks like a regression, as it used to work some months ago.

**Comment by Iridias** [comment]
Seems, the problem is in electron:
```
cd wire-desktop
find . -type f | xargs -d '\n' grep 'Failed to set up send codec'
Übereinstimmungen in Binärdatei ./node_modules/electron/dist/electron
```

**Comment by rainmak33r** [comment]
Any idea on how to solve it ?

**Comment by ffflorian** [comment]
Maybe @ConorIA has an idea? Since I can't reproduce this on Debian 9, this seems to be an Arch Linux specific error.

**Comment by ConorIA** [comment]
@ffflorian, I'm overseas on a slow internet connection, so I haven't been using Wire for calls lately. I'm currently running 2.15.2750 and I just made a voice call. It worked fine, but I'm not sure whether it was working in earlier versions. @Libbum, can you test with the updated package (released today) and report back? @ffflorian, KDE neon is based on Ubuntu LTS, so it doesn't seem to be Arch-specific. Here's hoping its worked itself out.

**Comment by maximbaz** [comment]
FYI I can't repro it on my Arch either, so it must be something else, not necessarily OS dependent.

**Comment by ffflorian** [comment]
Thanks for the info @maximbaz!
I found this: https://github.com/electron/electron/issues/8991. Beside that I also don't see that it's Wire specific.

**Comment by Libbum** [comment]
Hi guys. So I just reinstalled the latest version and yes - it does seem to work now. Not sure how helpful that is for others on this thread, but for me at least this issue is now resolved. I'll leave the issue open for a little to let everyone else give the latest version a go and see what they find.
