### ISSUE TITLE
Wire desktop just shows a white screen because of restrictions over some countries from some Wire servers

### ISSUE THREAD

**Issue by mohammadrafigh** [wireapp/wire-desktop#614]
I don't know exactly why and how this happened but suddenly my Wire stopped working and just shows a white screen at startup. I updated to the latest version (2.13.2741) in repository everything worked fine but after a few days I faced this issue. removing and reinstalling doesn't work neither. this happened on Ubuntu 17.04. is there any logs that can help?

**Update**
I found the problem: it seems the policies on Wire servers are changed and Iran (where I live) is restricted so I was able to run wire again by using a proxy! that's funny because my phone and my other desktop clients are working without a proxy, so this may be because this Linux client is redirected to a server which blocks Iran.

It would be great if you remove this restriction 👍

**Comment by aquatooth** [comment]
After some similar issues here [China, Mainland] I found that Wire is using a Google IP address block. 
I will continue to post comments until Wire management change to use their own server. 
Germany would be a good choice since that is where they are physically based. 
I recently did a PPA update and it took more than 40 minutes to download the file which was about 35 mb all due to Wire using Google servers based in USA. 
I can see the IP address connections on my hardware firewall. 
This really concerns me as 'Privacy' using any US based provider is more easily compromised.

**Comment by alexboss** [comment]
Same problem here, blank / white screen. I'm using a proxy with IP based either in Belgium or Luxembourg. Very annoying :(
Version used: 2.13.2741 on Ubuntu.

**Comment by raphaelrobert** [comment]
While our website (wire.com) is indeed hosted on Google App Engine in Europe, the rest of the product is not.
We will change our website hosting in the future.

It would be great if you could provide more details regarding what domain names are blocked in what countries.

**Comment by aquatooth** [comment]
@raphaelrobert With all due respect I see no reason to create a listing of what domains might be blocked or rendered unreachable and the countries involved. It is essentially useless information as some countries can and do interfere on the fly, plus you would end up playing whack a mole.
With that in mind, Google, and similar 'cloud' services will be the ones that attract most attention, thus bringing your domain back under your control means you can monitor more closely and take a different approach depending on what might be done to make Wire more resilient and to keep under the radar until such time as Wire becomes too popular.

**Comment by shvchk** [comment]
Some of my friends in Russia have the same problem (I use Android client mostly, and haven't experienced this issue). Is it really location dependent?

**Comment by alexboss** [comment]
Indeed, as suggested by shvchk, what info do you need to help to resolve this ?
Don't hesitate to provide commands to execute to help you with this.
Also, is there some debug option to log the app desktop that could help to identify the origin of the blocking / white / blank screen ?

**Comment by mahdiG** [comment]
I'm facing the same issue. Google servers block Iranian IPs. But the interesting part is while wire.com is blocked I can access app.wire.com and the android client works well too. But wire-desktop version 2.13.2741 installed on Debian using your official repo shows the loading page at first but then only a blank white screen. It works fine with a vpn.
![image](https://cloud.githubusercontent.com/assets/4989445/26046958/8720d784-3966-11e7-91dc-bce910de4e14.png)

**Comment by kunev** [comment]
Does this affect UK IPs?
A network I connect to goes out through an IP that should be UK based. I have the same issue, but when I turn on my proxy through home, not a  UK based IP, everything's fine. I do see some logic in considering UK a dangerous place, however it seems like a weird choice.

**Comment by lipis** [comment]
The white screen inside the desktop app has nothing to do with wire.com which is the only part of Wire that runs on Google which it's blocked in Iran and it's only the marketing web page.

**Comment by mohammadrafigh** [comment]
if it helps one of the server IPs that has restrictions is: 34.252.240.57

**Comment by mohammadrafigh** [comment]
ah well... today the server which serves Android version also stopped serving here... so I cannot use Wire w/o a proxy here anymore!

**Comment by david-wire** [comment]
After some investigation it looks like Wire may be blocked in Iran. I am afraid we do not have a workaround to suggest at this stage. Apologies for the inconvenience.

**Comment by mohammadrafigh** [comment]
shame on govs... Linux client restriction is because of Google server restrictions, but yes I can confirm that the gov blocked Wire entirely from 2 days ago here...

**Comment by pepper-jk** [comment]
Got the white screen issue over here at Germany too now. Only Linux Clients, Android seems to work for now. Any other possible reasons for the issue? I doubt the German government even knows what wire is, although I don't want to eliminate the possibility that it's getting blocked here was well.

**Comment by mohammadrafigh** [comment]
to update this issue:

fortunately yesterday I saw that the Wire has been unblocked in Iran. so I can come back to Wire again 🎆

**Comment by aquatooth** [comment]
Due to this issue having not been resolved I now find that I get the following message when updating; 

Get:2 https://wire-app.wire.com/linux/debian stable/main amd64 wire-desktop amd64 2.15.2751-154 [49.8 MB]
Err:2 https://wire-app.wire.com/linux/debian stable/main amd64 wire-desktop amd64 2.15.2751-154
  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
Fetched 12.2 MB in 9min 7s (22.3 kB/s)
E: Failed to fetch https://wire-app.wire.com/linux/debian/pool/main/wire_2.15.2751_amd64.deb  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

So, I did a traceroute and sure enough, unable to reach from mainland China
Wire is using Cloudfront;
https://en.wikipedia.org/wiki/Amazon_CloudFront

It is a great pity that some more reliable servers have not been established as many 'in the cloud' services are unable to be reached from many locations.

**Comment by silvernode** [comment]
I have this problem on wire-desktop-2.16.0 on Fedora 26 (built the RPM myself using official instructions) and I live in America. The only thing coming from the terminal when I launch /opt/wire-desktop/wire-desktop is:

``Failed to rename log file (/home/mollusk/.config/Wire/logs/29cc363a-d2ff-4610-821f-f31872ea74d0/console.log) with error: ENOENT: no such file or directory, rename '/home/mollusk/.config/Wire/logs/29cc363a-d2ff-4610-821f-f31872ea74d0/console.log' -> '/home/mollusk/.config/Wire/logs/29cc363a-d2ff-4610-821f-f31872ea74d0/console.old'``  

The above message shouldn't seem to be the issue as I have created the path and made the error go away (until launching wire-desktop again of course).  

I should add that building my own RPM files has worked fine in he past but it's hit or miss when I build a new package and upgrade to a new version. This did not happen to me on wire-desktop-2.15 and I can't think of a way to get better output to narrow down the problem.   

Should I post my issue in it's own thread? Thanks in advance.

**Comment by manasb** [comment]
https://github.com/wireapp/wire-desktop/issues/85

Adding SOCKS proxy support could allow users in locations where certain network traffic may be blocked to get around the blockages by using, for example, Tor. Provided that Tor isn't also blocked, of course.

**Comment by gregor** [comment]
Currently we have no plans on changing our server setup. We hear your feedback and will continue to evaluate options to address this in the future.
