### ISSUE TITLE
Non-standard use of spaces in key fingerprints

### ISSUE THREAD

**Issue by sts10** [wireapp/wire-desktop#615]
I've noticed that when you copy (and paste) device key fingerprints from the web and desktop apps, the resulting paste does **not** have spaces between every other character. 

```
aa80a4d2f38b63ffeaff1686bf6d2906ad39bb3e117d0a56e64477085a80b6bb
```

While if you copy a key fingerprint from the IOS app, the resulting paste _does_ maintain the space every other character. 

```
aa 80 a4 d2 f3 8b 63 ff ea ff 16 86 bf 6d 29 06 ad 39 bb 3e 11 7d 0a 56 e6 44 77 08 5a 80 b6 bb
```

I'd argue that this might be confusing to users. It also may hamper any programmatic fingerprint comparisons. Unless there's some use case where this situation makes things easier? 

I'd suggest changing the desktop and web application to copy and paste with spaces-- I think it's easier to compare fingerprints by eye that way. I was poking around [the devices less](https://github.com/wireapp/wire-webapp/blob/dev/app/style/content/preferences/devices.less) file but couldn't find where to make this change.

**Comment by sts10** [comment]
Sorry-- realizing this is likely a better issue for the web-app repo as opposed to this one.

**Comment by lipis** [comment]
Thanks for the clean up! Yes it is indeed better 🍻
