### ISSUE TITLE
Wire on Android fails to receive notifications

### ISSUE THREAD

**Issue by nichii124** [wireapp/wire-desktop#616]
I apologize if this has already been posted. I use Wire on Linux and I send messages to my friend who uses Wire on Android. For quite a while now, she fails to get notifications on her Android phone. I'm able to receive them just fine on Linux, but when I send a message to her Android phone, she fails to receive the notification and she doesn't know I sent her a message until she opens up Wire and sees the message in the app. Are the devs aware of this problem and working to fix it?

**Comment by aquatooth** [comment]
@nichii124 I havent noticed any bug such as this one so its good that you have taken the time to post it here.

The Developers might need version information, so if you could look that up and post those too...

I did have a similar setup to you when I was first testing Wire. Wire on Ubuntu 12.04LTS and on Android 4.3 I think it was. Unfortunately I have now nuked the setup on that phone.

**Comment by gregor** [comment]
@bjoernherbig Something for our Android team to look at.

**Comment by nichii124** [comment]
@aquatooth My friend is using version 2.31.325 of Wire on Android and I'm using version 2.13.2741  on Linux.

**Comment by ConorIA** [comment]
This conversation is happening here: https://github.com/wireapp/wire-android/issues/254

**Comment by lipis** [comment]
Thanks @ConorIA! Then I'll close this one to continue on the Android side..
