### ISSUE TITLE
Backup conversation crash to a gray screen after 100%

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#6177]
Desktop,

This is what the process does then it stops.

![image](https://user-images.githubusercontent.com/388716/200927334-9a71cad8-9aeb-452a-b109-e6de60d0c31c.png)

According to the progess bar there is ~350k messages to save, at the last step the process crash and Wire turn gray

Should I try an older version of wire to see if it goes through?

**Comment by Sledge-Hammer** [comment]
I have the same problem with a similar amount of messages when I haven't restarted the PC in a few months.
It usually fixes itself after a reboot.

From my observations the reason might be either that I'm running the PC without a page file or something related to Windows' GPU acceleration (or a combination of both) because I'm also getting odd behavior in other apps after running non-stop for more than a month or two (mostly in Firefox).

**Comment by Transisto** [comment]
> This sounds possibly related to Windows bug where the app turns grey (in different situations) that we have been struggling to reproduce lately. Try the previous release, but I am not confident that will solve the issue here. Backups often slow down at the last step regardless of OS.
> 
> Follow up with any progress from your side please 👍

I really need to have a better access to searching conversations, I was gonna use backup to then use the extract to PDF software.

Is there a way to get some userful verbose logs?

Also if I could know what files in my OS need backuping I could copy that while this is getting resolved.

**Comment by tlebon** [comment]
@Transisto this is PC correct? what version of the app are you using? 
if it is PC you can open the application from the command line with debugging enabled 

`C:\Users\<username>\AppData\Local\wire\Wire.exe --devtools=1 --enable-logging`

if it doesn't appear verbose restart the app again and you should see full logs.

**Comment by macexpertsusa** [comment]
on Windows app   select backup conversation it runs through messages  goes to gray screen - the app isn't crashing fully because second account can be clicked and is operating normally - fortunately quitting and restarting brings you back to messages again but there is no way to actually run a backup with this issue presently

**Comment by macexpertsusa** [comment]
i tested this with a less used account with a much smaller message database and it properly goes to  SAVE FILE in green -- this might be an issue related to the size of the message DB - I will try to investigate further

**Comment by macexpertsusa** [comment]
i ran the backup on primary account (large message DB) and let it stay at the grey screen 20 to 30 minutes - it never makes it to SAVE FILE dialogue  -- this leads me to suspect it's an issue related to the size of the database

**Comment by Transisto** [comment]
Everything you wrote match my problem, It seems like each account is a separate sub process, and that's what crashes.

**Comment by macexpertsusa** [comment]
> Everything you wrote match my problem, It seems like each account is a separate sub process, and that's what crashes.

It appears that it's becoming hung at the final processing to export the messages - I don't recall the exact  # of messages in the first account I tested it on but it was nowhere near 350k messages as yours but IIRC over 200k.     The only other tidbit I can add is that backup was running fine for larger databases 3 or 4 months ago and seems to work properly if the database size is below some threshold as yet to be determined

**Comment by macexpertsusa** [comment]
> I have the same problem with a similar amount of messages when I haven't restarted the PC in a few months. It usually fixes itself after a reboot.
> 
> From my observations the reason might be either that I'm running the PC without a page file or something related to Windows' GPU acceleration (or a combination of both) because I'm also getting odd behavior in other apps after running non-stop for more than a month or two (mostly in Firefox).


I tried backup after a fresh reboot only to end up with the same grey screen after it counts through the messages.

**Comment by drewmnoel** [comment]
This seems to be related to a memory issue in 32-bit Electron or something. If the size of the exported conversation data is more than around 32 MB when stringified, the process crashes (at [this](https://github.com/wireapp/wire-webapp/blob/8d53741e5edc0f1799e8bc07546b2c1564be1b4d/src/script/backup/BackupRepository.ts#L210) line).

I was able to resolve this for myself by rebuilding with a 64-bit version by switching this line from "ia32" to "x64":
https://github.com/wireapp/wire-desktop/blob/de508fa29e0a263d2d7b7b47e24755219da2b929/bin/build-tools/lib/build-windows.ts#L40

**Comment by macexpertsusa** [comment]
issue persists in latest update 3.30.4368  web 2023.03.07.08.22

**Comment by Sledge-Hammer** [comment]
Any chance of this being fixed anytime soon?
I haven't been able to make a backup in the past few months.

**Comment by macexpertsusa** [comment]
update april 11, 2023   the issue persists on release web 2023.04.11.09.39  (3.30.4368)

**Comment by nostitos** [comment]
Update, Support for android has been officially dropped. 
Issue section closed. There are no more issues.

https://github.com/wireapp/wire-android/issues/3743#issuecomment-1471415253

**Comment by MacGurus** [comment]
todays update 2023.05.30.13.55.09 Win Desktop 3.31.4421 backups are still not operational for larger message history with same gray screen results as outlined in the thread here

**Comment by zstomp** [comment]
> This seems to be related to a memory issue in 32-bit Electron or something. If the size of the exported conversation data is more than around 32 MB when stringified, the process crashes (at [this](https://github.com/wireapp/wire-webapp/blob/8d53741e5edc0f1799e8bc07546b2c1564be1b4d/src/script/backup/BackupRepository.ts#L210) line).
> 
> I was able to resolve this for myself by rebuilding with a 64-bit version by switching this line from "ia32" to "x64":
> 
> https://github.com/wireapp/wire-desktop/blob/de508fa29e0a263d2d7b7b47e24755219da2b929/bin/build-tools/lib/build-windows.ts#L40

It does fix the backup, but it can't restore.

**Comment by tlebon** [comment]
This is indeed related to an issue with 32-bit electron. This will be fixed in the next desktop release.

**Comment by MacGurus** [comment]
> This is indeed related to an issue with 32-bit electron. This will be fixed in the next desktop release.

just got update 3.32.4459  2023.10.19.08.33.56  - same results-  runs through preparing then crashes to gray

**Comment by MacGurus** [comment]
this is still broken - further it appears something similar is happening when you have a large database of messages when you do a search it crashes in similar fashion - other logins remain operable -

**Comment by Sledge-Hammer** [comment]
Definitely not fixed yet, which is a problem since  version 3.32.4459 is supposed to be the last one for Windows 7/8/8.1
I also encountered the search issue once so far.

**Comment by MacGurus** [comment]
Just got around to testing on the update today Aug 2024 and with a database of nearly 300K it backed up without issues!
Maybe someone with a larger database can test it to verify and if so then this issue is resolved

**Comment by tlebon** [comment]
As this is apparently fixed, i will close it for the time being. If it reappears please reopen it.
