### ISSUE TITLE
local cache encryption

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-desktop#62]
When you make use of the user-search feature of the desktop client, f.i. enter some letters to get some suggestions, all the usernames and more important their user-pictures are loaded.
These user-pictures are cached in %appdata%/wire/cache and viewable for everyone who has access to it.

Now, as a user, you don't have any control over other users pics. So just after randomly searching for users in the desktop client I got all kinds of images in this folder: from cats, over mountains to more unpleasant pics like genitals and gore images. When there is no filtering of sensitive images, you can imagine that their will be someday some questionable images on your harddrive probably without even knowing it. This could be at least a problem when an adversary is going to analyse your hard drive.

So for the sake of security, is it really necessary to leave the image-cache files unencrypted on hd?

or in other words, should it belong to the user to take care of this (fumble with encrypted containers and other solutions) or should the app take care of this itself?

**Comment by bennyn** [comment]
@tokariu Thanks for raising this question. By default content stored in `%APPDATA%\Wire\Cache` cannot be viewed directly. You will need a tool like [ChromeCacheView](http://www.nirsoft.net/utils/chrome_cache_view.html).

The fact, that images are cached within this folder is part of [Electron](http://electron.atom.io/)'s behaviour. Please be aware, that our desktop app is an [Electron](http://electron.atom.io/)-based app, so we have the contraints given by this app development technology. And as it's based on Chromium, it's expected that images are cached (as it's still a browser engine). 

So the caching issue is best to be addressed on the [Electron](https://github.com/electron/electron/issues) project.

**Comment by tokariu** [comment]
@bennyn I see. However, it's not like the cached content is *only* viewable with ChromeCacheView!

The content stored in `%APPDATA%\Wire\Cache` is really viewable by anyone who has access to the files. For instance, the profile pics of other users (the sensitive data mentioned in the first post) are stored in files like `f_00001e`.
These files are just images without extensions (like: f_00001e.jpg). You can view the content with every image viewer you like. Or even with any explorer-like-app which doesn't only rely on file extensions.

Therefor, the only way to really make it save, is local encryption.

So I see you rely on electron respectively chromium and it is caching images by default. But couldn't it be possible to handle cached content/images independently and encrypted by a method invented by the wire client? Let chromium cache raw-encrypted data only and let wire decrypt the images out of it in real-time/memory only to view in the client?
See Signal Desktop Client for instance. It's a Chrome extension but as far as I know it is still capable of holding local cached content encrypted. (the same btw on android, local cache/content is still encrypted there).

**Comment by Post-Scriptum06** [comment]
Apart from the encryption aspect, could not Wire cache folder be emptied automatically at regular intervals?
The cache of the search could be emptied as soon as the user quits the search?

**Comment by chaos-prevails** [comment]
There is no forum or other discussion group for Wire(-Desktop) of Wire, so please excuse posting my question here:

Does wire-desktop (Windows, Mac, Linux) encrypt locally stored messages (except above mentioned usernames and profile pics)? Nobody seems to have posed that question, while e.g. for Signal there's a lot of discontent that it does not.

I think that Electron can encrypt the data, but I'm not sure whether wire does. The Whitepaper (version october 2017) says nothing of it.

**Comment by raphaelrobert** [comment]
Hi @chaos-prevails, this is explained in section 7.1 of the [security whitepaper](https://wire-docs.wire.com/download/Wire+Security+Whitepaper.pdf).

**Comment by chaos-prevails** [comment]
Thanks, I found the Wire Privacy Whitepaper and didn't look for the Wire Security Whitepaper any more. 

So neither Signal nor Wire encrypt locally stored data in their desktop versions. Is this something Wire works on? I have yet to meet somebody using Windows with FDE (Bitlocker or Veracrypt), let alone that person being aware that the desktop version of Wire does store data unencrypted. Also this makes "swiss-based" security dependent on 3rd party encryption. Microsoft, Apple, ... could weaken their encryption with every System update, e.g. due to changes of governmental regulation.

**Comment by tokariu** [comment]
Hello,
i came back to see if anything has changed on this issue since I wrote the initial post over a year ago.
and it's very sad to see that the issue has been swept under the carpet. it is still an issue for desktop-clients. as @chaos-prevails in the previous post mentions, if local data is still not encrypted you move the responsibilitiy of security over to 3rd party encryption solutions. These are in many cases not FOSS and and the user is often not able to handle it correctly. This is by design predestinated for security flaws.

As a wire supportive guy, I'm disappointed because i cannot understand why you didn't invent something to fix this security issue, or even going into detail why it's been closed.

**Comment by raphaelrobert** [comment]
We still maintain that this is best solved by encrypting the whole file system. Particularly on iOS and Android this is handled pretty well by the OS.
We are not ruling out that we will address this at some point, but for now we focused on securing messages and other data in transit with end-to-end encryption.
