### ISSUE TITLE
Need to be able to remove users without blocking them

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#620]
There are use cases for removing users (don't need them now and for the foreseeable future) and for blocking them (this user has harassed me and I want to forcibly prevent them from contacting me again).

At the moment, as far as I understand, wire tells you to block a user instead of deleting them from your contacts.

Removing a user is important because for some reason in the future you may wish to receive a message from them, you just don't want them on your contacts at the present time. For instance if you added someone by accident, your only recourse now is to permanently block them, and going nuclear on someone like that for no reason especially after you just got them to accept an invite seems rather rude. 

Add/remove/block is a pretty standard paradigm that wire is deviating from, this is confusing to users who are looking for remove functions and can't find them.

So, please consider conforming with standard messenger paradigms in this regard.,

**Comment by 2114L3** [comment]
there is a 'delete' and 'block' option on android mobile, but 'delete' is missing on the desktop app. in my case linux appimage.

**Comment by maximbaz** [comment]
Is this menu on the left panel what you are looking for?

![image](https://cloud.githubusercontent.com/assets/1177900/25702869/4e9a7276-30d3-11e7-8b27-a1753c34cb82.png)

**Comment by dbquarrel** [comment]
That button unintuitively deletes the conversation, though it is on the contact and is associated with Block which is a contact operation. So this points out another problem. That menu being for the conversation should be "Mute", "Archive" and "Clear" (clear all messages). Delete is ambiguous and as you thought it was for deleting the user. "Block" should not be on that menu as it is a contact operation and is confused with the other 3 being conversation operations. 

So there should be two menus here, maybe as submenus under one menu. Or the conversation menu moved to the conversation screen, and the user menu left here beside the user name.

Conversation > 
Mute
Archive
Clear

Contact >
Block
Delete

That would be correct and intuitive UI.

**Comment by maximbaz** [comment]
Aah, I see. Totally agree on your suggestion then, "Delete contact" and "Clear history" should be two separate unambiguous features.

**Comment by gregor** [comment]
Thank you for your feedback which will be considered for our future roadmap.

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11198 https://github.com/wireapp/wire/issues/206
