### ISSUE TITLE
better integration into Linux Desktops

### ISSUE THREAD

**Issue by markum** [wireapp/wire-desktop#621]
Linux Desktops have different messenger apps which integrate different chat services into their environments. There is a framework called telepathy (https://telepathy.freedesktop.org/ ) which is used. It would be good, if it would be possible to integrate Wire into this.

**Comment by lipis** [comment]
This is way beyond our scope as we have way too many other things to take care of first! For now will put our efforts on our own client before start integrating the protocol into other apps. Maybe in the future..
