### ISSUE TITLE
Since yesterday, Wire just shows a white screen after loading the messages

### ISSUE THREAD

**Issue by missytake** [wireapp/wire-desktop#6217]
Wire version: 3.27.2944
Wire for Web Version: 2022.11.28.08.15
Operating system: xubuntu 22.04
~~Which antivirus software do you have installed:~~

What steps will reproduce the problem?

1.  login to Wire
2.  wait for the initial loading bar to complete

What is the expected result?

To see my chats and messages, being able to open and reply to them.

What is the actual result?

I see a white screen where there should be chats and messages. This happens to virtually everyone I know who uses wire-desktop. Some users reported that they still get notifications for new messages in the white screen, I can't confirm nor deny it. It also happens in [rambox](https://github.com/ramboxapp/community-edition/), which wraps the web app somehow without using the normal wire-desktop client, I think. But app.wire.com works. As the problem just appeared yesterday, I think the problem might be in a server component which delivers the wire-webapp to desktop-clients? I don't know enough about the wire architecture to judge that.

Please provide any additional information below. Attach a screenshot if possible.

![Screenshot_2022-11-29_10-59-33](https://user-images.githubusercontent.com/57442838/204499803-adb3bf7f-cf40-4f3c-91d1-3fd9cd8f2314.png)

**Comment by missytake** [comment]
Updating desktop to 3.29 fixed it for me! Thanks, I hope with your fix rambox will continue to work as well.

**Comment by tlebon** [comment]
Follow up from our side: a fix for this was released today. It should solve the issue regardless of which desktop client you are using. Simply restart the application if you are still impacted.

**Comment by missytake** [comment]
It's fixed on rambox as well now :)

**Comment by missytake** [comment]
Thanks!
