### ISSUE TITLE
Timed Message (TM) unintended behavior [bug].

### ISSUE THREAD

**Issue by Nazgulion** [wireapp/wire-desktop#624]
I've been experimenting (security related) with your desktop app recently. During that time, I discovered some 'strange' behavior that is not mentioned anywhere - as far as I know, and it's related to Timed Messages Feature.
If I get TM, expiration time bar will be displayed right next to it, indicating time left. Once expired, message will be deleted. Nice, but not exactly true. 
Let's say I perform some actions during that count down, and no, I don't mean screenshot. What I mean is actions inside Wire App scope (e.g. click and open '...' menu on the right side of the message, and don't select anything, just stop there) message will expire but it won't be deleted. Same happens if I do Ctrl+LeftMouseClickHold on the text box etc. In other words, delete message action will NOT be executed once timer hits zero, and this applies to all timed messages, not last one only, everything will be frozen. Further, one can automate this 'block' actions etc. you get the point.
 P.S. Not sure if it's a bug or a feature. :)

**Comment by gregor** [comment]
Thanks for the report. This is essentially a duplicate of https://github.com/wireapp/wire-desktop/issues/586. Thus I am going ahead and closing this ticket.
