### ISSUE TITLE
Missing feedback after adding a large attachment such as a photo

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#626]
This is definitely minor but it's an issue so laying it out.

User adds a large attachment to a conversation, there is a significant pause... 5-10 seconds.

During this time the UI has shown no changes from the user's action. This can cause the user to repeat the action as it looks like nothing happened. This can cause the user to end up with multiple copies of the attachment sent.

A placeholder needs to be inserted with an activity animation (or just a message) indicating that wire is inserting the attachment into the conversation but it's not yet completed.

**Comment by gregor** [comment]
Thanks for your feedback. We will consider it when improving our implementation. Currently we process the image first which is why it takes a while for any visual feedback to show in the UI.
