### ISSUE TITLE
[Linux] Digital signatures and checksums

### ISSUE THREAD

**Issue by PiotrOrzechowski** [wireapp/wire-desktop#628]
Please provide GPG signatures and SHA-256 checksums of files available to download [here](https://wire.com/en/download/) and [here](https://github.com/wireapp/wire-desktop/releases).

**Comment by maximbaz** [comment]
A random example of how this could be implemented: https://github.com/syncthing/syncthing/releases/
See the `*.asc` files provided with every release.

**Comment by mythsunwind** [comment]
Opened PR for creating SHA-256 checksum file and signing it via GPG at wireapp/wire-desktop/pull/821
