### ISSUE TITLE
Please add emoji selector

### ISSUE THREAD

**Issue by pintergreg** [wireapp/wire-desktop#630]
Please add emoji selector to the interface, something like [this](https://github.com/notwaldorf/emoji-selector):
![](https://cloud.githubusercontent.com/assets/1369170/9456986/2bfca090-4a93-11e5-9787-b4c04fbe55db.gif)

Thanks for considering this

**Comment by PlugaruT** [comment]
and make them colorful

**Comment by maximbaz** [comment]
@PlugaruT the style of emoji depends on your own setup, they are colorful by default on Mac and Win10, and you can make them colorful on Linux by installing a colorful emoji font.

For example, I use [this one](https://github.com/Ranks/emojione/blob/master/extras/fonts/emojione-android.ttf) on my Linux and here's how it looks:

![image](https://cloud.githubusercontent.com/assets/1177900/25842061/e2a9746c-34a2-11e7-9518-473dd723a110.png)

**Comment by PlugaruT** [comment]
@maximbaz I have installed the font, what's next? should I set it up in the wire app?

**Comment by maximbaz** [comment]
Check out this comment: https://github.com/wireapp/wire-desktop/issues/622#issuecomment-300101249

**Comment by ffflorian** [comment]
Closing due to duplication of https://github.com/wireapp/wire-desktop/issues/161.

**Comment by pintergreg** [comment]
@ffflorian I've read #161, but it is an issue for two separate things (I dislike that by the way) and also closed. Primarily it is for colorful emojis and it is clearly stated that it depends on system configuration and fonts. (This issue is partially hijacked to that way.)

Secondarily #161 asks an emoji selector like this issue (so I acknowledge the duplication), but as I see the implementation stops at an auto-completion which is not the same as the selector hence one has to know the names of the emojis.

Can I assume that despite of the closed state of #161 the selector feature is considered to implement? Otherwise I'd like to get a clear answer if it is refused in the favor of auto-completion.
Thank you

**Comment by gregor** [comment]
Yes, it is being considered. The auto complete is an open source contribution by @maximbaz . We currently do not have the resources to work on it ourselves but we definitely want it. @ffflorian even put together a working prototype as a side projects outside of working ours but we have not had the resources to add a proper design to it and merge it into the product.

**Comment by gregor** [comment]
The emoji picker side project branch can be found in https://github.com/wireapp/wire-webapp/issues/408

**Comment by pintergreg** [comment]
@gregor I see, thank you!
