### ISSUE TITLE
[Windows] Wire keeps audio channel (speaker) open, even when not in use

### ISSUE THREAD

**Issue by lingfish** [wireapp/wire-desktop#636]
Wire Version: 2.12.2729
OS: Windows 7
Do you have an antivirus software installed: Built-in Microsoft one

What steps will reproduce the problem?
1. Preferences -> Audio/Video, select Jabra headset for speakers
2. Exit prefs, notice that the headset stays offhook

What is the expected result?
Close audio when not in use.

What happens instead?
Audio stays open

Please provide any additional information below. Attach a screenshot if
possible.

My Jabra headset has the capability to "offhook" the wireless headset when audio is detected being sent to it.  This is to make it useful with software where there is no Jabra driver/support.

Initially, when Wire Desktop is first started, things are fine.  After using it for a call, or changing the setting of speakers to point to it, it stays offhook (it has a little "in use" kinda icon on the base), and this means the software isn't closing the audio channel like it should.

**Comment by maximbaz** [comment]
Hey, join the discussion in #598 🙂

**Comment by ffflorian** [comment]
Closing this due to duplication.
