### ISSUE TITLE
Please let the user decide if they want to let other peoples see that they are typing a message

### ISSUE THREAD

**Issue by Bromton** [wireapp/wire-desktop#639]
Congratulation with all the new tricks and looks that you [recently announced at Medium](https://medium.com/@wireapp/new-tricks-and-looks-for-the-list-92fb68d85134), you've done a great job and the features are mostly very appreciated.

There is _one_ thing that caught my attention though. In the announcement you say:
> Oh, and in case someone happens to be typing a message while you are looking at the List you will see that too.

![1 fvjn6ptg2kodk_cvipgfmq](https://cloud.githubusercontent.com/assets/28670414/26024497/893752ae-37d2-11e7-945a-86c49b3f039f.png)

Will the typing user have the ability to disable this?

I think this feature can be very useful if you want to stay ready to respond immediately and to know that the person you have a conversation with is not "dead", but it can unfortunately also be very invading and obnoxious to some people. Let me give you some examples that I experienced from using Skype where you have a similar feature:

- Person A is one that put a lot of thinking into what s/he type before sending it off. S/he may stop multiple times when s/he type and if person B (the receiver) can see that the typing have stopped up or that the typing takes a long time then person B might think that person A forgot to hit enter and start asking about it. Person A then stops all up, person A deletes the answer, and s/he instead begin to explain to person B that the answer is still coming. Then person A start typing their answer all over again...

- It gives away the confidence of the person. In Skype you have a similar feature and I personally found Skype so invading that I started using Notepad to pre-type all my answers before copying it over to Skype. I eventually left Skype and started using Pidgin where I could disable it.

- If person A have typed something, but s/he have not hit the Enter button yet because s/he is unsure if it really should be said, person B might start asking about the content before person A have made a decision. Effectually forcing person A to give person B a answer.

Please don't get me wrong, I'm not all negative to a feature like this. I could have given a lot more examples where this is very useful! I just think that the user should have the option to decide themselves if it fits them or not.

**Comment by gregor** [comment]
The webapp and desktop clients do never share whether you are typing. Only people typing on the mobile client do so. The feature was never implemented on desktop platforms.

**Comment by ffflorian** [comment]
@Bromton please join the discussion here: https://github.com/wireapp/wire-android/issues/716.

**Comment by lipis** [comment]
So we will close this one as it's already referenced to the correct issue..
