### ISSUE TITLE
Can Wire leave a message as an audio?

### ISSUE THREAD

**Issue by rudolfschmidt** [wireapp/wire-desktop#6412]
Hi,
is there a way to leave an audio as a wire message? That feature would be great, because sometimes it feels greater to leave an audio or receive an audio instead dead typing your text.

**Comment by Transisto** [comment]
Yes but only on mobile,

On the plus side it's much faster to type on desktop.

**Comment by sysfu** [comment]
I spend all day on a desktop and being able to record voice messages from the desktop app would be hugely helpful.

**Comment by tlebon** [comment]
this is unfortunately not on the roadmap for now, hopefully sometime in the future though! I will close this for now and if the status changes I will update.
