### ISSUE TITLE
Shared video does not appear in desktop version

### ISSUE THREAD

**Issue by jsnjack** [wireapp/wire-desktop#644]
Wire Version: 2.13.2741
Wire for Web Version: 2017.05.03.1029
OS: Fedora 25
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Have wire installed on desktop and smartphone
2. Ask a friend to share video with you

What is the expected result?
Video can be viewed on both smartphone and desktop application

What happens instead?
the video is visible on the smartphone only

**Comment by gregor** [comment]
@jsnjack Thank you for your report. We have identified the issue. I will go ahead and close this ticket in favor of an issue that is describing the same problem where we have already added more context. #744
