### ISSUE TITLE
Desktop icon for wire is missing in Gnome

### ISSUE THREAD

**Issue by jsnjack** [wireapp/wire-desktop#645]
Wire Version: 2.13.2741
Wire for Web Version: 2017.05.03.1029
OS: Fedora 25
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Install wire-desktop using AppImage file
2. Go to Activities and find wire icon

What is the expected result?
Wire icon

What happens instead?
Wire icon is missing
![screenshot from 2017-05-18 14-34-32](https://cloud.githubusercontent.com/assets/5493713/26202374/85d7ba14-3bd7-11e7-9823-f9a1bcb273e7.png)

**Comment by jensome101** [comment]
Using Gnome 3.22.2 on Debian 9, the icon is still present.
However the icon on the tray is shown a second time if the application is running (called "Wire") and at the same time in favorites on the tray (called "wire-desktop"). Maybe this helps in finding whats wrong.

**Comment by HorlogeSkynet** [comment]
I can confirm that the icon is not present on Cinnamon as well, with an AppImage install.
However, it looks OK with a repository-installation.
Just take a look to #564, the @fbruetting's answer

And one desktop-file's name has to be changed as well, from `wire-desktop` to `wire` 😉

**Comment by jsnjack** [comment]
The issue is still exist in wire version 3.0.2816 :/

**Comment by fbruetting** [comment]
What is the content of your `~/.local/share/applications/appimagekit-wire-desktop.desktop`?

**Comment by fbruetting** [comment]
What exactly have you changed? There still is `"StartupWMClass": "Wire"` in the current file.

**Comment by jsnjack** [comment]
Yes, I'm on linux (fedora 27). I changed my desktop file per this comment https://github.com/wireapp/wire-desktop/issues/645#issuecomment-313158420

It looks like this:
```
[Desktop Entry]
Name=wire
Comment=Secure messenger for everyone.
Exec="/home/jsn/app/wire-3.0.2816-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-wire
X-AppImage-Version=3.0.2816.2816
X-AppImage-BuildId=2219a1a0-b4a8-11a7-3712-9b9413ffc7e4
StartupWMClass=Wire
Categories=Network;
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_7pP9eY/AppRun
TryExec=/home/jsn/app/wire-3.0.2816-x86_64.AppImage
```

The main difference is Icon key. It used to be `Icon=appimagekit-wire-desktop`

**Comment by fbruetting** [comment]
Couldn’t find the code part in this repository…
