### ISSUE TITLE
Feature request: Full screen image

### ISSUE THREAD

**Issue by alexleonard** [wireapp/wire-desktop#647]
Wire Version: 2.12.2729
Wire for Web Version: <Can be found in the About dialog>
OS: Windows 10 Build 15063.296
Do you have an antivirus software installed: Just windows defender

It would be great when clicking an image from a chat to be able to switch to 'full screen'. Currently the image is limited to the size of the chat window, and usually I have the chat window quite small on my desktop. Even maximising the desktop client doesn't really give the same effect as a 'full screen' image preview.

**Comment by gregor** [comment]
Thanks for the request. We will continue to track this internally but have no immediate plans of implementing this feature.
