### ISSUE TITLE
Feautre Request: Option to quickly go next/previous image when viewing images

### ISSUE THREAD

**Issue by alexleonard** [wireapp/wire-desktop#648]
Wire Version: 2.12.2729
Wire for Web Version: <Can be found in the About dialog>
OS: Windows 10 Build 15063.296
Do you have an antivirus software installed: Windows Defender

When viewing images either from the search icon or when clicking on an image to see the larger version, it would be great to be able to quickly navigate to next/previous images both through on-screen next/prev arrows and also through left/right cursor keys.

**Comment by gregor** [comment]
Refresh your app and try the arrow keys again... Not exposed in the UI due to missing animations etc: https://github.com/wireapp/wire-webapp/pull/1187
