### ISSUE TITLE
[Feature request] Windows portability

### ISSUE THREAD

**Issue by vatterspun** [wireapp/wire-desktop#649]
Obviously Wire is already platform-portable, meaning it works on multiple operating systems.  The goal here is to be settings-portable, meaning it would work across Windows machines.

## Current behavior

Writes the program to appdata and writes settings to appdata\local and appdata\roaming.

## Requested behavior

1. Write program and all settings to the same folder (or at least the same root folder) e.g. c:\wire\ and c:\wire\settings
2. When the folder is moved to another folder (like x:\wire or c:\Users\Admin\Desktop) the program should launch with the same settings as before

## Why is this useful?

* Ease of encryption e.g. store inside a TrueCrypt / VeraCrypt volume

* USB drive - Someone who uses a public terminal at an internet cafe, computer lab, etc. 

* Cloud capability - An individual who has this stored on their cloud drive (Dropbox, Google Drive, etc.) will have the same experience/settings from one machine to another without a reinstall 

* Ease of backup - just copy the folder to a backup drive -- no hunting for the proper files inside appdata

## Who cares?

Several messaging tools offer a portable version for greater anonymity (it's easy to dump a flash drive).  Pidgin, two Tox clients, Telegram and Microsoft's Skype all have this capability.

## Possible issues
	
Going this route can make updating the client more complicated. When a new version comes out, users will have to avoid overwriting the old config file or lose their settings. As such, I recommend this as an optional setting (a command argument like "--portable") or separate release version.

**Comment by smaragdus** [comment]
**1+** for portable version.
For example [Telegram](https://desktop.telegram.org/), [Isotoxin](http://www.isotoxin.im/) and all other [Tox clients](https://tox.chat/) offer portable versions or portable mode on Windows which facilitates usage and backup.

**Comment by ConorIA** [comment]
For reference #397 #427

**Comment by vatterspun** [comment]
> For reference #397 #427

Sorry @ConorIA I thought I ran a search before I posted.  My fault.

**Comment by lipis** [comment]
We have to do something about #427 :)

**Comment by janost** [comment]
+1, having a portable option would be nice.

**Comment by ConorIA** [comment]
#427 has been merged, which means that one could install to a USB stick and run with the --portable flag. The only thing I am not sure about is whether the install location is customizable.

**Comment by vatterspun** [comment]
@ConorIA Great news, thanks.

**Comment by sergeevabc** [comment]
Right now the only Windows distribution is WireSetup.exe, which silently installs the app into ```C:\Users\...\AppData\Local\wire```, creates settings’ folders in ```C:\Users\...\AppData\Roaming\Wire```, and immediately runs after that. So, why was this issue about portability feature marked as closed?

**Comment by vatterspun** [comment]
I don't know if this should be closed or what and yeah some clarity on this would be nice.  I was guessing the argument enabled path portability, which would let you move the program to a USB or cloud drive, use the "--portable"argument, and it would save settings to the local folder.  

Ultimately I'm waiting for a quiet weekend to test this.

**Comment by ConorIA** [comment]
@vatterspun, on Linux, this is especially useful with the AppImage, or even with an unpacked image from a built app. @sergeevabc is right that it is less useful when the installer automatically installs to a user's AppData folder. That said, I hope that you are right that you can just copy `C:\Users\...\AppData\Roaming\Wire` to a USB key and take it for a spin. Please do let me know if it works.

**Comment by vatterspun** [comment]
**Update**: I've verified the program as portable.  Here's my data:

My test was done in Win7x86 as it's probably the most popular Windows OS.

Steps:

1. Download and run the setup file 
2. Go to C:\Users\USERNAME\AppData\Local\wire and copy all files present to a folder of your choice
3. Run Wire.exe --portable
4. Sign up for an account and verify via email
5. Delete leftovers from C:\Users\USERNAME\AppData\Local\wire and C:\Users\USERNAME\AppData\Roaming\Wire

Seems portable, though it writes setting to a LOT of files and folders:

![2017-09-24 15_12_25-c__users_hybrid_desktop_est_ - everything](https://user-images.githubusercontent.com/1289134/30786451-6eefb3c8-a13b-11e7-844c-7e344b5e0db3.png)

**Comment by sergeevabc** [comment]
There is a precise word for how portability is ostensibly implemented in this case — _rush job_, i.e. in a slipshod manner, without due care of end-user expectations. Either installer should have portable option (see [WikidPad][1]’s installation routine for example) which allows the user to choose the path or Wire should be deployed as ZIP (see [Telegram][2]’s releases page for example).

[1]: https://vgy.me/yS1Nkn.png
[2]: https://github.com/telegramdesktop/tdesktop/releases

**Comment by ConorIA** [comment]
@sergeevabc, in this case, it wasn't so much a rush job as it was a climate scientist trying to implement a workaround! The Wire devs can produce true portable binaries with the `electron-builder`. I've got a PR to accomodate such a build, but I can't get the `Gruntfile` updated appropriately and don't have any more time to spend on this. Make some noise over on #982 if you wish!

**Comment by vatterspun** [comment]
I've asked a lot of programs and a lot of tools to enable portability and I'm just glad someone listened.  I agree that the approach that @sergeevabc is suggesting would ease the process of updating.

**Comment by sergeevabc** [comment]
Agggrrrhhh! Once again I face the need to update Wire without polluting OS, but there is no simple solution.

**Comment by vatterspun** [comment]
@sergeevabc Alternatively, Telegram has a portable application format that's a little easier to update via the PortableApps format: https://portableapps.com/apps/internet/telegram-desktop-portable

To be clear, I do prefer Wire, but if that's a critical feature for you.

Again, I'm just happy they were willing to add portable functionality.

**Comment by smaragdus** [comment]
**@sergeevabc**
I totally agree with you that the implementation of portable mode is disastrous, it is so terrible that it defeats the purpose of portability. Anyway, I do not care about **Wire** any more- portable or not I am no longer using JavaScript+Electron software- this is the death of programming. I removed all Electron stuff from my system (with one exception but I will remove it as well after I take some screen-shots).

**@vatterspun**
The manual update of **Telegram** is easy- download the archive, extract it and replace the old executable (**Telegram.exe**) with the new one. For me **Telegram** is by far superior than **Wire** but I am about to dump it too- the developers ruined the GUI and added a bug which they called a "feature". Anyway, why mess with the slower **PortableApps** version when **Telegram** offers a natively portable and stealth version?

**Comment by sergeevabc** [comment]
@smaragdus, +1

> Performance matters. Memory usage matters. Its simply not ok for apps to be sluggish.
[Electron is Flash for the desktop][1]

[1]: https://josephg.com/blog/electron-is-flash-for-the-desktop/

**Comment by vatterspun** [comment]
@sergeevabc I honestly don't know if thread hijacks are a thing on Github but maybe you could start a new issue encouraging the authors to move away from Electron and toward the React framework as the article suggests?  This thread is increasingly a comment on overall development direction and not on a specific feature.

**Comment by ConorIA** [comment]
@vatterspun #642 but see #994 and https://gitlab.com/ddobrev/Fibre/

**Comment by vatterspun** [comment]
@ConorIA That's not quite what I was looking for.  I think you meant to point that to smaragdus or sergeevabc.

**Comment by ConorIA** [comment]
Sorry @vatterspun, it was #567 I had meant to link.

**Comment by sergeevabc** [comment]
Revisiting ostensibly implemented portability feature in year 2019. Meh, still a desktop dinosaur.
