### ISSUE TITLE
Clause in README makes wire potentially non free

### ISSUE THREAD

**Issue by bhkeys** [wireapp/wire-desktop#651]
The Wire README file has a clause that reads such

```
a. You agree not to change the way the Open Source App connects and interacts with our servers; b. You agree not to weaken any of the security features of the Open Source App; c. You agree not to use our servers to store data for purposes other than the intended and original functionality of the Open Source App; d. You acknowledge that you are solely responsible for any and all updates to your Open Source App.
```

Doesn't this violate freedom 0 in the free software definition?
https://www.gnu.org/philosophy/free-sw.en.html

**Comment by Deathsbreed** [comment]
Aside from part b, the rest seem to refer to the service rather than the software itself.

**Comment by raphaelrobert** [comment]
The README quotes our [Terms of Use](wire.com/legal), and they only apply if the app is connecting to the Wire servers.
This doesn't limit what you can do with the code as such.

**Comment by vatterspun** [comment]
>> Doesn't this violate freedom 0 in the free software definition?

> The README quotes our Terms of Use, and they only apply if the app is connecting to the Wire servers.
This doesn't limit what you can do with the code as such.

I actually would point to FSF freedom 1: "The freedom to study how the program works, and change it so it does your computing as you wish"

You might want to rewrite it specifying use of your SERVICE rather than use of your CODE.  For example. there are good reasons to weaken a security feature if your interest is in making the program run as fast as possible (encryption has both a processor and data overhead) or the program is running over an already-established secure connection (like a VPN).

**Comment by raphaelrobert** [comment]
This is exactly how it is intended: The Terms of Use govern the Service and the GPL governs the Code.

> 1.2 You must agree to this ToU in order to use the Apps, the Site and/or the **Service**.

**Comment by vatterspun** [comment]
> This is exactly how it is intended: The Terms of Use govern the Service and the GPL governs the Code.

The suggestion is that they are in conflict.  Since the GPL has been tested in court more than once, it will probably supersede the Terms of Use.

**Comment by bhkeys** [comment]
It would probably be best in my opinion to make it a clear distinction that the clause is made for *the service* and not *the code*
@raphaelrobert That may be your intention but the wording in the terms of use is a bit unclear on that

**Comment by raphaelrobert** [comment]
Noted, we'll take that into consideration for the next iteration!

**Comment by vatterspun** [comment]
> @gregor closed this 2 days ago

Any update on what action was taken?

**Comment by devkev** [comment]
> Any update on what action was taken?

Nothing, apparently - the README still has the exact same unmodified text.

I also read the additional clauses as applying to the software, not the service.  Especially the way parts a and b very clearly describe changes that would be made to the code.  And the way the end of the following "clarifying" paragraph says `the foregoing will not apply to that application`, which also strongly implies that the foregoing clauses are intended to be applied to applications (ie. the software/code), not to the service.

If the clauses are truly intended to only apply to usage of the service, and not the actual derivative software, it would be helpful if that was stated much more clearly.
