### ISSUE TITLE
Add option to prevent converting ascii to emoji

### ISSUE THREAD

**Issue by phoenixeliot** [wireapp/wire-desktop#652]
Wire Version: 2.14.2743
OS: macOS 10.11.6 (15G1510)
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Open a chat with someone
2. Type ":)" or ":(" or "<3" etc
3. Type a space, or press enter

What is the expected result?
The text I typed used to (and in my opinion, should) remain unchanged.

What happens instead?
The ASCII is automatically converted into an emoji.

Please provide any additional information below. Attach a screenshot if
possible.

It appears that Wire has added one of my least-favorite antifeatures from Facebook Messenger, by making it impossible to type certain ascii sequences, instead forcing them into emojis that simply do not have the same emotional feeling for me (<3 especially).

I would love for there to at least be an option to turn this behavior off. I was pleasantly surprised when I originally started using Wire and it didn't do this behavior, and I'm disappointed that it's been forced upon me in my new favorite messenger.

<3
Phoenix

**Comment by gregor** [comment]
@phoenixeliot Thank you for your request. Closing this in favor of the issue this is duplicating: https://github.com/wireapp/wire-webapp/issues/1263
