### ISSUE TITLE
[Suggestion] Devices, less clicking

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#654]
Wire Version: 2.12.2729
OS: On all OS:es

The problem is more of a design problem. When it comes to the validation of devices you have to click and click. I have about 5 devices (2 devices on a computer because of 2 different Operative systems). You should be able to have a button to varify a device right there on the dialog box and the expanded info (the arrow).

**Comment by gregor** [comment]
@Sethox The omission of this button on the overview page was a concious security decisison. Verfying a device without comparing the fingerprints is not an actual verification and could lead to false impressions of security and privacy. While we know that it is cumbersome to manually compare the fingerprints for each device, it is the solution we currently have. We are continuously looking into ways to improve the usability of the verification process without compromising on the security.
