### ISSUE TITLE
Dozens of notices that "YOU HAVEN'T USED THIS DEVICE FOR A WHILE. SOME MESSAGES MAY NOT APPEAR HERE."

### ISSUE THREAD

**Issue by sumyungguy** [wireapp/wire-desktop#655]
Wire Version: 2.14.2743
Wire for Web Version: 2017.05.26.1203
OS: macOS 10.12.5
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Look at Wire
2.
3.

What is the expected result?
Not see any messages.

What happens instead?
Since May 23rd, dozens of messages, in every conversation, all saying:
YOU HAVEN'T USED THIS DEVICE FOR A WHILE. SOME MESSAGES MAY NOT APPEAR HERE.
![screenshot_204](https://cloud.githubusercontent.com/assets/5410893/26529883/439d03bc-43c9-11e7-822c-2c5170ab759b.png)

Please provide any additional information below. Attach a screenshot if
possible.

I have Wire set to open on startup on my computer, so it runs all day, every day. It has been doing so for several months. It's true that I haven't exchanged any messages with anyone for a few weeks. The last message I received was April 14. But I wouldn't have missed any messages, because the app has been running the whole time since then.

I also have Wire on my iPhone, and I haven't opened the app in several weeks. But the phone has been running and online every day, so there's no reason I would have missed any messages. I just opened the phone app, there is just one "YOU HAVEN'T USED THIS DEVICE" message, in each conversation, and it's dated the same day as the last time someone sent me a message, April 14.

**Comment by gregor** [comment]
This message should only appear, if you have not opened that particular device for more than 28 days. I guess if you refresh the page without receiving any messages we could falsely trigger the message additional times. But looking at your screenshot I doubt that you did not receive any events for days. I suspect you are running the public version of the macOS wrapper meaning that you do not happen to have collected logs for this incident?

**Comment by sumyungguy** [comment]
Thanks for your reply.

I open the device (my MacBook) several times a day, every day. Wire is always running, in the background.

I'm not sure what you mean by "refresh the page". But the error messages seem to appear any time the computer wakes from sleep or restarts. I don't know why it's sometimes repeated three or four times at the same time stamp, and sometimes only once.

I'm not sure what you mean by "I doubt that you did not receive any events for days." I have not exchanged any messages with anyone for more than 28 days. But the application goes online and connects to the servers every day.

I'm running the application from the Mac App Store. I don't see a log file anywhere, nor any messages in the Console.

I've now disabled Wire from automatically starting up, and stopped using it on my Mac, because the screen continues to fill up with more of these messages every day.

**Comment by sumyungguy** [comment]
Is there some other version of the macOS desktop app that enables logs? Or some other way I should collect logs?

I've determined that the messages are not necessarily related to computer sleep/wake or restart. Yesterday I left the application running in the background (hidden), and left the computer on overnight, set to "never sleep". Today I found this:

![screenshot_206](https://cloud.githubusercontent.com/assets/5410893/26576492/5778aa4c-4529-11e7-93a6-2ae3884b548d.png)

**Comment by sumyungguy** [comment]
I created a test account and sent a message to it, which was received. But I continued to get the warnings, for example when quitting and restarting the application:
![screenshot_213](https://user-images.githubusercontent.com/5410893/26969081-c3ea076a-4d04-11e7-9565-7f6c99bcbc38.png)

Finally, after I sent a message from the test account to my own, the warnings have stopped.

Seems to me there are two issues:
1. Whether you have "used this device for a while" is not determined by whether you have opened the app and connected to the server, but by whether you have received any messages. But this is not an appropriate test - maybe you didn't receive any messages because nobody sent you any. The timer should be reset by a successful connection to the server, not by receiving a message.
2. The check and warning message is done repeatedly: every time you open the device; i.e., start the app, or wake from sleep, as well as at other regular intervals while the app is running in the background. I suppose this wouldn't be an issue however, if the timer was reset the first time the app was opened and connected to the server.

**Comment by gregor** [comment]
@sumyungguy This is correct. We could improve this check in the future but for 99,9% of the cases it is fine for us to rely on the information from the backend that the ID of the last known local notification must be older than 28 days. A user that isn't receiving any message for more than a month can hardly be consired a very active customer.

**Comment by sumyungguy** [comment]
And a customer who isn't very active deserves to have buggy software and a poor user experience?

I haven't received any messages because I have trouble convincing other people to use Wire.

You have three kinds of customers: 
1. those who are true believers and are committed to using Wire, 
2. those who will never use Wire, and
3. those who have gone to the trouble of setting up Wire but still primarily use something else.

Most people I know primarily use SMS, Apple Messages, What's App, Facebook, etc., with Wire as a secondary service to communicate occassionally with people like me who ask them to use it. So I rather doubt it's safe to assume that 99.9% of your customers will _never_ have a period of 28 days with no Wire messages. And it's precisely that third group of "not very active" people that you and I want to convince to move to Wire as their primary service, and who will be the least likely to do so if they find bugs and problems with it.

**Comment by dead10ck** [comment]
This still seems to be an issue, at least on Android.

**Comment by sumyungguy** [comment]
@dead10ck what is the issue, do you see dozens of "you haven't used this device for a while" messages, every day? Or only one message (repeated in every conversation) once a month or so? I still get the latter, on Mac. Apparently Wire ~~doesn't give a fuck about that~~ is busy with other things, and won't get around to fixing it anytime soon.

**Comment by dead10ck** [comment]
@sumyungguy that's right, dozens of those messages. I assumed it was one per message from the device I haven't logged into in a while. After some more googling, it seems Wire intentionally makes messages inaccessible if they came from a device that hasn't logged in in 4 weeks. This seems unfortunate, since I think it would surprise most users when they find out that all their old messages are gone because they switched phones or something. I could see that being a major roadblock to longer-term adoption of Wire.

**Comment by dead10ck** [comment]
@gregor has the been any consideration of this problem?

**Comment by moburkhardt** [comment]
This is still occurring, any fix other then making a second account and sending messages to myself?

**Comment by timashev** [comment]
It is still an issue on Wire for macOS v3.29.4490 (from About: Wire for Web v2022.11.02.07.54). It is really annoying!!!!
<img width="509" alt="image" src="https://user-images.githubusercontent.com/695076/201005909-f27eeea6-838a-478a-b43e-05ef09b29f92.png">
