### ISSUE TITLE
No badge any more

### ISSUE THREAD

**Issue by Taddaeus** [wireapp/wire-desktop#657]
Wire for web 2017.05.03.1029
OS X 10.11.6

No red badge on app-icon any more!

**Comment by Taddaeus** [comment]
Still no badge after update to 2017.06.01.1002. Also no notification in the lock screen.Please fix it!! Thanks.

**Comment by gregor** [comment]
I suppose this was fixed by now. We had some issues with notifications for a while but have since addresed them.
