### ISSUE TITLE
Hide user agent

### ISSUE THREAD

**Issue by jensome101** [wireapp/wire-desktop#659]
Wire Version: 2.13.2741

While observing the traffic created by wire, I noticed that there is an http connection, apparently for the ocsp query. This transmission also includes the user agent:

User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Wire/2.13.2741 Chrome/56.0.2924.87 Electron/1.6.7 Safari/537.36\r\n

This does not only provide unnecessary information about the software installed, it also shows everyone listening, what operating system is used, something that people might want to keep private and that might give an attacker valuable information.

The ocsp request itself also leaks information about the target server that would otherwise be less visible (ip connection instead of certificate information)

By hiding the user agent and preferably using ocsp stapling, it could be made harder for an adversary to filter and detect wire transmissions. In an age where state agencies do exactly that, this is a real concern and should be addressed. Since ocsp stabling is easily deployed, I would recommend doing so.

**Comment by gregor** [comment]
Thank you very much for your request. At this time we have no plans for removing the user agent from our desktop apps.
