### ISSUE TITLE
Can't log in on Ubuntu 16.04

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-desktop#66]
Steps to reproduce (or at least this is what happened to me).
- Downloaded the app from wire.com/download
- Installed it
- Launched it
- Sent and received a few messages. Everything worked fine
- Closed the app by clicking on the "X"
- Now when I open the app I am not logged in, and it doesn't let me log in either. Says "problem with the connection" even if the connection is fine.
  I don't see a way to get a debug log

**Comment by someoneEsle** [comment]
FIx:
- I opened wire in the browser and removed the newly added device (which by the way is marked as "Windows desktop" and not "Linux desktop")
- tried to log in again -- worked

**Comment by lipis** [comment]
The issue name will be fixed in the next release: https://github.com/wireapp/wire-webapp/pull/303

**Comment by someoneEsle** [comment]
What about the closing/logging out issue? Anything I can do to help debug?

**Comment by lipis** [comment]
Does it still remain?

**Comment by someoneEsle** [comment]
Oh yeah, every time I close the app it logs me out and I have to remove the device to be able to log in again.

**Comment by lipis** [comment]
Can you try to quit from the Tray icon instead of the `X`?

**Comment by someoneEsle** [comment]
Done, same behavior

**Comment by lipis** [comment]
@someoneEsle Can you try with the latest version from https://wire.com/download/ if the issue remains?

**Comment by someoneEsle** [comment]
Ops sorry, I forgot to close this issue. It has indeed been fixed.

**Comment by lipis** [comment]
Thanks!
