### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by tomleb** [wireapp/wire-desktop#661]
Wire Version: 2.13.2714
Wire for Web Version: 2017.06.01.1002
OS: Archlinux 4.11.3-1-ARCH  x86_64 GNU/Linux
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Have a long chat history / conversation with someone.
2. Try using the app (anything, really)

What is the expected result?
Thing should be fast and responsive.

What happens instead?
Everything feels slow.
I get huge input lags (~0.5 s each key press). 
Scrolling is slow as well.
Changing conversation is very slow (up to 5 seconds).
The time between the app is shown to the app is usable can take up to 1 minute.

**Comment by utack** [comment]
For me it eats 100% CPU constantly, as in one core  
Same for the 2.14.2743 beta  
using cpulimit you can cut back the impact on the system, but then the app starts lagging

**Comment by theidiotyouyellat** [comment]
Wire: 2.13.2741-1
Wire for Web: 2017.06.07.1805

For me it spikes all cores with KDE Menubar style set to *Tile bar button*
![beforewire](https://user-images.githubusercontent.com/20326496/27061235-692f73ba-4fb0-11e7-8748-8c04f9d56680.png)
![highcpu](https://user-images.githubusercontent.com/20326496/27061236-69329900-4fb0-11e7-882b-407672033933.png)

Using Menubar style set to *In Application* fixes the cpu spike 
![plasmamenubarstyle](https://user-images.githubusercontent.com/20326496/27061667-c4719994-4fb3-11e7-853b-e8cada04e1da.png)

The issue seems to be Electron or KDE. I installed the [Min](https://minbrowser.github.io/min/) and set the style to *Tile bar button* which caused a spike in CPU as well.

**Comment by tomleb** [comment]
This is extremely annoying, especially for people with laptop / old computers. (It's probably Electron, but they don't seem to want to change their stack so I don't know, might need to change chat app)

**Comment by theidiotyouyellat** [comment]
@tomleb If you are on KDE set your Menubar style to **In Application**. 
![inapplication](https://user-images.githubusercontent.com/20326496/27062554-bea7eae4-4fb9-11e7-830d-ee427a9eba9c.png)
At least there is a work around but it would be nice if Electron and KDE teams could agree whose issue it is and fix it.

**Comment by tomleb** [comment]
I'm not on KDE though, I'm using i3wm

**Comment by theidiotyouyellat** [comment]
@tomleb does the /etc/environment trick work? Also have you confirmed that it is only wire or all Electron apps?

**Comment by utack** [comment]
@theidiotyouyellat wow, how did you even find that  
Fixes the problem for me, good workaround for now.  
Is there a bug filed for this with electron already?

**Comment by theidiotyouyellat** [comment]
@utack It was changing my Google search after seeing the electron bug. Ran across it in a [reddit](https://www.reddit.com/r/kde/comments/5x9t7j/electron_app_high_cpu_usage/) post. However @tomleb  is the first in all the threads to mention he has the issue outside KDE.

**Comment by tomleb** [comment]
The environment work around seemed to make it a little faster. Still unusable in my opinion. I just opened it now and it went to 72% CPU.

**Comment by theidiotyouyellat** [comment]
@tomleb Is it all Electron apps or just Wire? Also is there any more information about your setup that could help?

**Comment by tomleb** [comment]
Wire is the only Electron app I'm willing to install on my machine and it's the only one I ever installed. I'm using basic setup i3wm+compton on a Thinkpad T420 with 10Gb ram.
Kernel is 4.11.3-1-ARCH on Archlinux.

**Comment by theidiotyouyellat** [comment]
I don't blame you there. For the sake of finding the root cause, would you be willing to install [Min](https://minbrowser.github.io/min/) a small web browser? On Arch, the only dependency is electron. If it exhibits the same behavior, then we can let wire off the hook and move this issue over to electron.

**Comment by tomleb** [comment]
I've been pretty busy today so I'll try Min tomorrow and report back.
> If it exhibits the same behavior, then we can let wire off the hook and move this issue over to electron.
I do understand that as a dev, you want to know whether that is on your end or not to avoid wasting time solving a problem that isn't from you. But as an end user, whether it's electron's fault or not, I really don't care, I just want a software that works well.
I understand that Electron is nice for devs because it is an easy stack and is crossplatform, but it's pretty shitty in terms of performance (I know, visual studio code is supposed to be running fast, there are exception). I don't want to shit on anyone's work, but just know that if you often receive performance issues, it would be nice to switch to something else, like Qt or something.

**Comment by theidiotyouyellat** [comment]
> as an end user, whether it's electron's fault or not, I really don't care, I just want a software that works well.

I agree that electron is not the greatest. I am just a user as well and want to help others with their problems and maybe get some better applications in the process. 
Thanks for your time.

**Comment by tomleb** [comment]
Performance of Min is better. I'm getting ~5% cpu usage when idle with two reddit tabs open. Otherwise it can go up to ~60.
The scrolling is a bit weird but there is no latency like there is on Wire, in fact there is no latency at all.
I then went on https://unsplash.com and scrolled down for a while. CPU goes up, but I get no problem scrolling down.
(Sorry I couldn't test it earlier)
