### ISSUE TITLE
Feature request: Creating multiple aliases for the same user

### ISSUE THREAD

**Issue by hThoreau** [wireapp/wire-desktop#662]
Wire Version: 2.13.2741
Wire for Web Version: 2017.06.01.1002
OS: Debian Jessie (8.8)
Antivirus software installed: Clam
---
Good evening,

I've noticed a recent alteration in the contact list sidebar, which places my user icon in a thin column to the left of a wider column listing all of my contacts. At first, I though of it a waste of useful space. To cut away from the total width of the contact list in order to place a single icon. My own at that, as if it was needed to remind me that I am myself and these are my contacts.

Some time later, I tried to be more sympathetic to the idea. After all, Wire isn't being built with only my present needs in mind. And so I asked myself: in which situation would it be useful to be reminded of one's own identity, and have it be associated with the present contact list? If the identity in question was a pseudonym, I guessed. That would justify the contact list, by its layout, being associated _side-by-side_ with the identity in question, as a form of reminder to the user of how he is presenting himself to those interlocutors. What kind of disclosure is acceptable.

With that realization in mind, I remembered when I first started using Wire. At a time when I had only close friends as my contacts. By then, we communicated using aliases as handles, such as "@thomas.paine", "@virginia.woolf". Eventually, as I wanted to expand my usage of Wire for IM communications in general, including professionally and with my family, I saw myself forced to change my handle to match my social name.

Sure, If I wanted to keep my pseudonym, I could. It would be just a matter of creating another account and then launching multiple instances of Wire. At the present situation, that's not essential. Though someday it could be. And for when it is, it's better to have a couple of aliases available. So, with that possibility in mind, finally, here is my request: **Allow for an account to wield multiple handles, having them listed at the contact list sidebar, in the same column where the current user icon is shown, allowing the user to change between identities and their respective contact lists using the same Wire instance.**

Thank you for your attention.

**Comment by gregor** [comment]
Thank you for your suggestion. The new bar obviously has it's purpose that might not be obvious right now but it will be in the coming weeks and months. We will keep your ideas in mind.
