### ISSUE TITLE
Inverted Scroll-direction (i.e. *not* "natural scroll") on Ubuntu

### ISSUE THREAD

**Issue by m0ru** [wireapp/wire-desktop#663]
Wire Version: 2.13.2741
Wire for Web Version: <Can be found in the About dialog>
OS: Ubuntu 16.04 LTS
Do you have an antivirus software installed: nope

What steps will reproduce the problem?
1. set up Ubuntu to use "natural scroll" on the trackpad (i.e. smartphone-style scrolling)
2. use multi-touch on touch-pad to scroll in a wire-desktop chat

What is the expected result?
I've set my Ubuntu to use "natural scroll", so moving my fingers up should scroll down / towards the latest message.

What happens instead?
It scrolls up / towards the first message.

My naive guess would be, that you handle touch-scrolling yourself / have a lib that does that, bypassing the system's config somehow.

**Comment by ffflorian** [comment]
Hi @m0ru, I just checked natural scrolling with a touchpad on Debian with Gnome 3.22. It works the same in Wire as in other programs, so I can not reproduce your bug. :thinking:
AFAIK we also don't use any touch / scrolling libraries, so I'm afraid I can't help you for now. Are you sure that it is inverted only in Wire?
