### ISSUE TITLE
opt-in to show my user name and picture in contact search, should be off by default

### ISSUE THREAD

**Issue by darkbluelight** [wireapp/wire-desktop#664]
This is why I still need to use Threema. I can't use Wire for anonymous communication.
Please duplicate this behavior for the user picture:
https://threema.ch/en/blog/posts/profile-pictures

And for the user name:
If I give to some stranger my @.... handle so they can find and contact me, they as well see my user name that I chose to display for my family and real friends. But if I change my user name to some pseudonym all my real friends also get to see my pseudonym. Let me opt in on a contact per contact base what user name I want them to show if any. If I don't opt in, just show them my @somestrangepseudonym handle.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have no immediate plans of changing our profile picture implementation but will consider your feedback for a future addition to the roadmap.
