### ISSUE TITLE
Feature Request: Linux native application that performs better and isn't so bloated.

### ISSUE THREAD

**Issue by klundry** [wireapp/wire-desktop#665]
Wire Version: ALL
Wire for Web Version: <Can be found in the About dialog>
OS: Linux/ALL Distros
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?
1. Install Wire Desktop
2. Open Wire Desktop
3. Use Wire Desktop

What is the expected result?
A well performing optimized messenging app.

What happens instead?
A huge and bloated application that is slow to open because it is an electron app.  

Please provide any additional information below. Attach a screenshot if
possible.

It would be great if we could get a native linux application that isn't electron.  The current desktop app is very slow to open on my modest but not low end or old hardware.  It is ok on my beefy i7 desktop but on anything less it is annoyingly slow to load for something that shouldn't need a ton of resources.

150MB for a messenger is also kind of ridiculous in my opinion.

**Comment by KingDuckZ** [comment]
I just got here following a link that presents Wire as a good alternative to Skype. Then I read this comment.

**Comment by tomleb** [comment]
It's very slow indeed. It's almost unusable once you get pretty big conversations with people. There really should be an actual native application.

**Comment by qazip** [comment]
I think their main focus is not desktop, sadly. Desktop desperately needs a dark theme and a native application. They've a native linux app, but it's going slow and it's not usable yet:

https://github.com/wireapp/coax

**Comment by lipis** [comment]
Unfortunately we don't have the capacity to deliver the fully blown native app for Linux in the near future. We are using [Electron](https://electron.atom.io/) for all our Desktop clients and there is no plan to change that at the moment. Therefore I will close this issue. But you should see improvements regarding the loading times some time soon.

**Comment by qazip** [comment]
What about a pidgin extension or something like that? Would that be possible?

**Comment by lipis** [comment]
I'm not even sure if it's possible at all, since the client has to do quite a few things in order to encrypt/decrypt.

**Comment by klundry** [comment]
This is a rather disappointing response.  What is the purpose of releasing across multiple platforms if you are going to release poorly optimized and slow apps that make people not want to use them? Will that not just put people off the platform as a whole?

**Comment by ddobrev** [comment]
@lipis @qazip @klundry I have started a prototype for a much lighter desktop client for Wire. It's called Fibre - https://gitlab.com/ddobrev/Fibre/ . It consumes 80 % less memory and less power as well.

**Comment by ddobrev** [comment]
@klundry there are no binary releases yet, I'm afraid. Building from source code is really easy, though: simply install Qt, open the .pro with Qt Creator and build.

**Comment by klundry** [comment]
Just tried it. Loaded way faster than the official app.

**Comment by mythsunwind** [comment]
I will lock the conversation now. Please remember that this is a bug tracker in a source repository, not a discussion board. Feel free to contact the the author of Fibre directly.
