### ISSUE TITLE
Wire Web Very VERY slow

### ISSUE THREAD

**Issue by berni421** [wireapp/wire-desktop#666]
Wire Version: been waiting 20 minutes for it to open
Wire for Web Version: Still waiting so no version yet
OS: Debian 8, Firefox 52.1 64 bit
Do you have an antivirus software installed: yes - nod32

What steps will reproduce the problem?
1. Use wire for a few weeks
2.
3.

What is the expected result?

Should be as fast as whatsapp

What happens instead?

Still waiting 25 minutes
![screenshot - 040617 - 21 37 31](https://cloud.githubusercontent.com/assets/12982367/26765155/182f301a-496e-11e7-9e90-1855bcc7a421.png)

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by berni421** [comment]
![screenshot - 040617 - 21 54 34](https://cloud.githubusercontent.com/assets/12982367/26765267/6c5f09ba-4970-11e7-9ba7-c52ee824aa17.png)

Progress is slow, but I am giving up after another 5 minutes

**Comment by ConorIA** [comment]
This tends to happen if you haven't opened Wire for a while. If it is any consolation, the next  version of the webapp will have a bit of text under the progress bar to explain what is happening (or what is taking so long!)

**Comment by berni421** [comment]
Thanks. So assuming the progress bar is linear - it means I will have to wait several hours to access my wire message system. No one, certainly not me, is going to wait that long. Effectively wire becomes unusable after any prolonged period of use.

I have to say it is somewhat ironic for a cloud based secure service to provide "designed in" denial of service like this. Wire needs to allow for recent messages to be displayed within a few seconds. With a background catchup protocol for older and possibly historically irrelevant ones. e.g scrolling back in time presents a "read more" button. 

By the way I had not opened wire for about a week on the web --- I have some pretty active groups but a week is not unusual for a vacation.

**Comment by maximbaz** [comment]
See also https://github.com/wireapp/wire-webapp/issues/734

**Comment by bennyn** [comment]
@berni421 If you are on macOS or Linux then you can download our [native apps](https://wire.com/download/) which are way faster than our web app: https://medium.com/@wireapp/speeding-up-crypto-on-wire-desktop-apps-3ff37fc98c3f 😃
