### ISSUE TITLE
make contacts column collapsable

### ISSUE THREAD

**Issue by MoritzFago** [wireapp/wire-desktop#668]
Wire Version: 2.14.2743
Wire for Web Version: 2017.06.01.1002
OS: macOS 10.12.5
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. open Wire app
2. look at the big contacts column
3. appreciate that everyone has nice pictures to represent themselfs, so the names could be optional
4. notice that the column isn't collapsable
5. write bug report 

What is the expected result?
only the pictures should be displayable

What happens instead?
the pictures and names are displayed and not collapsable

For a possible layout see attached mockup
![wire](https://cloud.githubusercontent.com/assets/4459068/26794412/d872be4c-4a21-11e7-8532-e13650aefbee.png)

**Comment by lipis** [comment]
Closing this one as it was already mentioned a few times: 
- https://github.com/wireapp/wire-desktop/issues/298
- https://github.com/wireapp/wire-webapp/pull/543
