### ISSUE TITLE
Link preview too aggressive

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#672]
Wire Version: 2.14.2743
Wire for Web Version: 2017.05.26.1203
OS: OS X 10.12.5 (16F73)
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Post this to somebody
```python
def is_ending(self):
        return self.is_next_all_player_step('EndRun')
    
    def has_ended(self):
        return self._already_called.get('destroy', False)
```
2. Watch the link previewer try thinking it found a link to self.is in there.

What is the expected result?
No link preview should be rendered

What happens instead?
A link preview is rendered.

Please provide any additional information below. Attach a screenshot if
possible.

![bildschirmfoto 2017-06-06 um 18 40 02](https://user-images.githubusercontent.com/57199/26840783-94089ca6-4ae7-11e7-92ca-b352c7a59355.png)

**Comment by dwt** [comment]
I also noted this bug in https://github.com/wireapp/wire-desktop/issues/293

**Comment by maximbaz** [comment]
I also reported this in https://github.com/wireapp/wire-webapp/issues/776, which was accidentally closed.

**Comment by lipis** [comment]
I will close this one as duplicate in favour of https://github.com/wireapp/wire-webapp/issues/776 Thank you guys!
