### ISSUE TITLE
Feature Request: Ability to select which window to share when screen sharing

### ISSUE THREAD

**Issue by alexleonard** [wireapp/wire-desktop#676]
Wire Version: 2.12.2729
Wire for Web Version: 
OS: Windows 10 Pro Version 1703, Build 15063.296
Do you have an antivirus software installed: Windows Defender Only

When starting a screen share it would be very useful to be able to select to either share all screens, a particular screen, or a particular application window. This is something I've gotten used to on Skype and HipChat and is very useful for business calls with clients where I want to demo something but not necessarily have them seeing other apps on my system.

**Comment by gregor** [comment]
For simplification reasons with the user experience we opted to only offer the option to select a particular screen in now. If this is not working, please open a new issue. Your request for a more versatile feature set has been noted. We use this place to track issues though and track feature requests. Thus I am closing this issue.

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/wire-webapp/pull/8848
