### ISSUE TITLE
Request screen-sharing for the linux version

### ISSUE THREAD

**Issue by mimf** [wireapp/wire-desktop#68]
It seems like the Linux version does not support screen-sharing. I'm hereby requesting that feature.

**Comment by MaCroX95** [comment]
Screen sharing works well for me on Ubuntu 16.04? How is it missing for you? :)

**Comment by ConorIA** [comment]
Yep, no problems here. @mimf have you figured this out? If so, you should close this issue. Otherwise, a little more info would help.

**Comment by lipis** [comment]
I'll close it for now since it looks like it works.. @mimf feel free to ping here if you still have issues with it..

**Comment by romanfazulianov** [comment]
Hey guys, i have such problem in ubuntu 16.04.1
![image](https://cloud.githubusercontent.com/assets/5006121/23341584/d2e69e50-fc63-11e6-9a10-af4e6d12141e.png)
no button for screen sharing
version of wire 
![image](https://cloud.githubusercontent.com/assets/5006121/23341592/fc2c0b10-fc63-11e6-9b2f-6490b6aa3b3a.png)
`uname -a` says:
`4.8.0-34-generic #36~16.04.1-Ubuntu SMP Wed Dec 21 18:55:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

well i checked in web version in firefox - button is on its place while calling.

do u have any ideas of resolving this problem?

**Comment by diego-treitos** [comment]
No button for screen sharing here either on ubuntu 16.10

**Comment by lipis** [comment]
Are you using the desktop version or through the browser?

**Comment by diego-treitos** [comment]
I am using the desktop version
