### ISSUE TITLE
[Bug/Feature Reqest] Fit video to window size

### ISSUE THREAD

**Issue by keksbaecker** [wireapp/wire-desktop#680]
Wire Version: 2.12.2729
OS: Windows 10 1703
Do you have an antivirus software installed: Windows Defender

as well as

Wire Version: 2.13.2741
Wire for web version: 2017.06.07.1805
OS: Fedora Linux 24
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Start an audio or a video call
2. share your screen

What is the expected result?

The video feed scaled down to show the whole shared screen inside of the window.

What happens instead?

Depending of the size and proportions of the window different parts of the shared screen are shown.
Only if I have the wire app in full screen I can see the complete shared screen which does not seem to be possible for windows #679

Please provide any additional information below. Attach a screenshot if
possible.

![screenshot 38](https://user-images.githubusercontent.com/15347943/26941983-bf4b8078-4c80-11e7-8c99-a6ef49039db8.png)
![screenshot 39](https://user-images.githubusercontent.com/15347943/26941984-bf4f7f2a-4c80-11e7-90df-aac01b95ba34.png)

**Comment by gregor** [comment]
You can change the object-fit of the remote video by double clicking on it.

**Comment by keksbaecker** [comment]
@gregor thank you very much. I really wouldn't have thought to double click on the video to change the fit of it.

Would it be possible to change the default to fit and to fill the window on double click? Or is there a reason I am not realizing for this default?

**Comment by gregor** [comment]
The default actually depends on the aspect ratio of the given video. It will be set to fit in case you have a portrait video from mobile by default. This is a deliberate decision by our design team that is unlikely to change.

The double click option was added as a user contribution as other solutions provide the same user experience on double click. We do not plan to clutter the UI with additional buttons to expose this feature further.

**Comment by keksbaecker** [comment]
> The default actually depends on the aspect ratio of the given video. It will be set to fit in case you have a portrait video from mobile by default.

That is definitely a valid decision and I won't try to argue with it. 😃 I hope you keep up the great work and thanks again.
