### ISSUE TITLE
[Bug] About window has no title

### ISSUE THREAD

**Issue by keksbaecker** [wireapp/wire-desktop#681]
The about window is missing a title which looks kind of odd if you show the text on the taskbar or try to switch to it using alt-tab

**Comment by gregor** [comment]
I suppose this is on Windows?

**Comment by lipis** [comment]
Maybe adding `About Wire` or something

**Comment by keksbaecker** [comment]
@gregor I can reproduce this behavior on windows and on linux (Fedora 24)

**Comment by gregor** [comment]
@lipis A one line fix that we should consider.
