### ISSUE TITLE
Wire on Fedora

### ISSUE THREAD

**Issue by Darknessraptor** [wireapp/wire-desktop#682]
Hi guys!
Wire Version: Desktop client (latest)
Wire for Web Version: <Can be found in the About dialog>
OS: Fedora 25
Do you have an antivirus software installed: No, real man don't use that!

What steps will reproduce the problem?

1. How can I compile the client for Fedora 25?

2. The process you describe on GitHub is using npm command, so, what is npm? 

3. Is it some kind of scrip?

4. So then first commands are running over a regular users?

What is the expected result?
A rpm/flatpack/snap instance.

What happens instead?
Nothing

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ConorIA** [comment]
npm is the node package manager. You can run the AppImage from the download page without diving into compilation. If you would rather compile, the steps in the README are enough to get you up and running, as long as you have npm installed. If I'm not mistaken, the README should link to the npm documentation.

**Comment by Darknessraptor** [comment]
OK, I'll try to download the appimage. Thank you.

**Comment by ffflorian** [comment]
I'll close this issue for now. @Darknessraptor feel free to reopen if you have more questions.
