### ISSUE TITLE
How to exit fullscreen?

### ISSUE THREAD

**Issue by ljn917** [wireapp/wire-desktop#684]
Wire Version: wire-2.13.2741-x86_64.AppImage
OS: Linux/Fedora 25
Do you have an antivirus software installed: Sophos

What steps will reproduce the problem?
1. Call someone
2. Menu->View->Fullscreen
3. How to quit fullscreen?

What is the expected result?
There should be at least some messages reminding people how to quit fullscreen.

What happens instead?
I did not find a way to quit fullscreen.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ffflorian** [comment]
Hi @ljn917, did you try pressing `F11`?

**Comment by ljn917** [comment]
I figured it out in the end. But the real problem is the UI is not self-explanatory. It should show a reminder on how to exit fullscreen, other than force users to google or try every possible keys/combos.

BTW, the other one is hide/show menu.
