### ISSUE TITLE
Wire fails to identify previous device (loses history)

### ISSUE THREAD

**Issue by andredasilvapinto** [wireapp/wire-desktop#685]
Wire Version: 2.14.2743
Wire for Web Version: 2017.06.07.1805
OS: macOS 10.12.4
Do you have an antivirus software installed: no
What steps will reproduce the problem?
1. Use wire
2. Close wire
3. Open wire

What is the expected result?
Device correctly detected as the same device.

What happens instead?
Wire tells me it's the first time using this device and loses all the conversation history. This doesn't happen every time I follow the steps above, but it is frequent enough (2 or 3 times per week) that it seriously affects my experience with the app.

It seems similar to https://github.com/wireapp/wire-webapp/issues/688 but I am posting this here as I am using the desktop app.

The "new" device has a different fingerprint than the previous ones. What is Wire using to compute this fingerprint? I think that part of that might not be stable enough.

**Comment by andredasilvapinto** [comment]
just happened again, this time when my computer ran out of memory and I had to force quit some applications (including the wire desktop app)

**Comment by gregor** [comment]
Running out of memory will cause parts of our database being deleted by the system. Nothing we can prevent unfortunately.

**Comment by andredasilvapinto** [comment]
seems like a strange database! I wouldn't expect that to happen with old data which was already persisted to disk, but thanks for replying.

**Comment by andredasilvapinto** [comment]
Just happened again, this time without any out of memory problem. Losing your history this often is a really bad experience.

**Comment by AnnanFay** [comment]
This just happened for me on Debian Jessie. There haven't been any memory issues as far as I am aware.

I was away from the computer for a few weeks. When I got back I started up Wire and it asked me to login, after logging in it notified me about it being a new device.

**Comment by porresuppe** [comment]
This has just happened for me. I'm using the Wire web interface (Firefox) on Gnome 20.04. I haven't been notified about it being a new device (which it definitely isn't).

**Comment by Mibou** [comment]
> This has just happened for me. I'm using the Wire web interface (Firefox) on Gnome 20.04. I haven't been notified about it being a new device (which it definitely isn't).

Exact same issue on Google Chrome 89.0.4389.90 on Windows 10. I was connected for a long long time, then it asked me to reconnect and I lost all the history.

**Comment by rosa2** [comment]
Same several times in different Ubuntus, 20.04 and 21.04. I was in a video-conference with my screen sharing. The Wire notifications were coming, so I closed the program. Then when I open it, said I was in new device.
Thanks a lot and have a good day :)
