### ISSUE TITLE
UI: Compact Mode

### ISSUE THREAD

**Issue by viviengarcia** [wireapp/wire-desktop#688]
**FEATURE REQUEST**

OS: All

Let's be totally clear: having a (fantastic) IM app occupying more than one quarter of a 1920x1200 screen isn't cool, especially when the conversation zone is half of this surface.

So you should implement 2 things:

1. Have a button to collapse (or reduce significantly the size) of the second side bar, the middle one.
2. Have a menu option to reduce some (not all) paddings and/or margins between elements of the UI. It's ok to have whitespace, but sometime we want to be compact, and anyway some icons have too much whitespace around them. Trust me, I'm a webdesigner.

What is the expected result?
Less useless UI, more usable space for my **other** apps (not everyone has two screens)

An example of a more compact UI
![screen shot 2017-06-13 at 12 37 01](https://user-images.githubusercontent.com/1825862/27084182-3a1399ee-504b-11e7-979e-8c7bf4c18964.jpg)

**Comment by viviengarcia** [comment]
Well, I'm not bitchin', but after 3 days, no answer **at all**? o_O
At least, could someone tag this post as a Feature Request, as I can't find a way to do it myself?

**Comment by qazip** [comment]
Well, I +1d this. I definitely think they should spend some time improving their desktop client. I said elsewhere that I dread using the desktop client, it's horrible. They are losing people due to this. They should provide both a dark-theme and a compact mode.

**Comment by viviengarcia** [comment]
@qazip At least someone answer me :). Thanks for the +1 btw, at least I feel the time I spent doing this  infographic was't wasted ;). I had another issue and got an answer less than a day after, so I think this is prioritizing and perhaps the devs don't have manpower for now to adress lesser issues.

To be perfectly clear, I was aware of the +1s, so I knew people had at least read my post, but I ranted a bit in order to up the topic because I thought it would be beneficial for everyone if this issue could be tagged as Feature Request, making it easier to find and preventing multiple posts on the same subject.

**Comment by maximbaz** [comment]
I raised this topic earlier in https://github.com/wireapp/wire-webapp/pull/543, no changes were made at that time because a redesign of the left panel was planned, which would include this feature request. Read this answer in particular: https://github.com/wireapp/wire-webapp/pull/543#issuecomment-268046541.

I also see that quite many duplicate issues are linked to that PR, linked by Wire team, it is a clear indicator that Wire team is aware of people badly wanting such compact mode 🙂

**Comment by viviengarcia** [comment]
Hi @maximbaz thanks for the reply and the added info :). I've read a bit of the thread and I'm happy to see the devs are aware of the problems and intend to adress thos usability problems. So often a pretty good product isn't widely adopted because of a defective UX!
