### ISSUE TITLE
no "Sent" and "Delivered" markers in web version of Wire

### ISSUE THREAD

**Issue by muellert** [wireapp/wire-desktop#689]
Wire Version: <Can be found in the About dialog>
Wire for Web Version:  Version 2017-06-07
OS: Debian GNU/Linux 9.0 amd64 
Do you have an antivirus software installed: n/a - I use FF53.x atm, which has no virus scanner integration.

What steps will reproduce the problem?
1. Log in
2. Select Contact
3. Start Chatting

What is the expected result?

For the last sent line, I expect an indicator whether the message was "Sent" or "Delivered", as I have on the mobile app.

What happens instead?

Nothing - the messages may be getting sent and/or delivered, but I have no idea what is really going on.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by Strit** [comment]
As I recall it's a provacy thing.
The have it on mobile because connectivity can be troublesome on mobile, so it makes sense to see if your messages actually gets sent.

In a web client it's safe to assume you are connected to the internet, since you are connected to the wire website.

**Comment by herrmannplatz** [comment]
We do show delivery receipts in one to one conversations. There is no copy for sent status.

What client is the other party using?

**Comment by Awerick** [comment]
It seems this is the same problem that I encountered on Android (see this [issue](https://github.com/wireapp/wire-android/issues/943) in the android repository):
For old conversations everything works fine (i.e. a delivered status is shown for the last message) however in a (group-)conversation that I created only recently I don't get a delivered status for new messages (not in Android and neither in the desktop (Linux) app).

(Just for clarification: Even if the desktop app works correctly, it does _not_ show a status for each message (as the Android app does) but only which message is the last delivered one – if I am not mistaken.)

**Comment by gregor** [comment]
There are no delivery confirmations in group conversations.
