### ISSUE TITLE
Linux version reports as "Wire for Windows".

### ISSUE THREAD

**Issue by mcg** [wireapp/wire-desktop#69]
After installing the Linux app, a "Wire for Windows" showed up in my devices list. Pretty sure this was the Linux app, but since I couldn't find a way to view the device ID on the Linux client either....

**Comment by lipis** [comment]
It's already fixed and it will be published in the next release of webapp: https://github.com/wireapp/wire-webapp/pull/303

**Comment by gregor** [comment]
The fix has been live for some time.
