### ISSUE TITLE
I don't want Wire to prevent OS to shutdown

### ISSUE THREAD

**Issue by viviengarcia** [wireapp/wire-desktop#692]
**FEATURE REQUEST**

OS: At least OS X

When I shut down my computer, I don't want a Messenger app to prevent shutdown. IM is not critical, sorry. So Id' like at least an opt-in option in the preferences. 
Like, feature can be enabled to prevent shutting the OS down if your IM is *that* important for you, but by default it isn't.

What is the expected result?
More uninterrupted shutdowns, less interrupted shutdowns. Everyone's happy.

**Comment by herrmannplatz** [comment]
We had a similar issue earlier which seemed to be fixed. Could you please run `pmset -g` and check whats causing this.

**Comment by viviengarcia** [comment]
Hi @herrmannplatz,

`pmset -g` returns:

```bash
Active Profiles:
AC Power		-1*
Currently in use:
 hibernatemode        0
 womp                 0
 networkoversleep     0
 sleep                0 (sleep prevented by coreaudiod, mds, Radium, UserEventAgent)
 Sleep On Power Button 1
 ttyskeepawake        1
 hibernatefile        /var/vm/sleepimage
 disksleep            0
 displaysleep         15
```

**Comment by viviengarcia** [comment]
I upgraded to El Capitan and reinstalled Wire (v2.14.2743), issue doesn't happens anymore.
