### ISSUE TITLE
Feature request : automatic answer

### ISSUE THREAD

**Issue by unrealwill** [wireapp/wire-desktop#698]
Redirected to github by [Wire Support]

This is for Linux (not selectable in the Platform box below).

I need to be able to automatically start video conversation when called.
Currently I use skype 4.3 linux, it allows my contacts (and only them) to automatically see/hear my video when they call. Skype is retiring and I need a substitute.

How can I achieve this with wire?

**Comment by bennyn** [comment]
Hi @unrealwill, thanks for sharing your thoughts with us!

We are collecting feature requests here: https://github.com/wireapp/wire/issues
If you don't mind we would be pleased if you can raise your issue there again.

Best from Berlin,

Benny
