### ISSUE TITLE
Take full width with markdown

### ISSUE THREAD

**Issue by tomleb** [wireapp/wire-desktop#699]
Currently the app has two main 'container': contact list on the left and conversation on the right.
The conversation on the right doesn't take the full width it has, so when pasting some code (with markdown) it doesn't take the full width (need to scroll vertically).

**Comment by maximbaz** [comment]
I was against this when such request was brought up last time, but now I changed my mind, I think it is beneficial to use as much space as possible, it creates more condensed design with more context always available. And pasting code is a great example of why this is needed.

**Comment by bhelm** [comment]
This is number one on my Wishlist. The old Skype Linux client had full width, something i really missed with the new clients.

**Comment by gregor** [comment]
Thank you very much for your feature request. We currently have no plans of changing the behavior in this area but will consider it for the future.
