### ISSUE TITLE
Chat with yourself on different devices

### ISSUE THREAD

**Issue by hylkevds** [wireapp/wire-desktop#707]
I often have to send some text snippets or URLs to "my other computer". Would it be possible to start a chat with just myself? I could add a second account just for this, but that seems a bit inconvenient.

**Comment by ConorIA** [comment]
The feature doesn't exist, but a workaround is to start a group chat and then boot the other users. You end up with an empty group in which you are the only member.

**Comment by bennyn** [comment]
We have a workaround for this: https://github.com/wireapp/wire-webapp/issues/576#issuecomment-312294054

**Comment by gregor** [comment]
You can now create conversation with just yourself. Today we released a new version of the webapp with an updated way to create groups. You can skip the step to select participants and can create a conversation with just yourself that way.

**Comment by hylkevds** [comment]
That's great! Much appreciated!
