### ISSUE TITLE
Hidden process won't let me open Wire web app

### ISSUE THREAD

**Issue by DanMercurius** [wireapp/wire-desktop#708]
**I can't get Wire web app to run anymore.**
It was working fine until yesterday afternoon.
What has happened:
- Log in to web app
- chat and work
- Wire stops responding (running it on iOS too)
- I close the tab, reopen app, it states: "Wire is already running in another tab" 
- I restart Chrome, reopen app, it states: "Wire is already running in another tab" 
- I clear browsing data (cookies & hosted apps) reopen app, it states: "Wire is already running in another tab" 
- I try incognito mode: Wire is working.
- I also tried finding the process in Chrome task manager, no luck
- iOS works fine, so I tried removing all other devices from there, still Wire web app is not working

I really need the web app for work, as it's very tedious to use the iphone keyboard for more than 100 word text.
**What can I do?**
<img width="1112" alt="screen shot 2017-06-23 at 9 00 58 am" src="https://user-images.githubusercontent.com/28238969/27470159-dc25ea3a-57f2-11e7-8ab1-dfce66b68584.png">

Best regards 
Dan

**Comment by janhoffmann** [comment]
+1 same problem here.

**Comment by maximbaz** [comment]
Workaround: 

* Go to https://app.wire.com
* Hit <kbd>Ctrl+Shift+J</kbd> (<kbd>Cmd+Opt+J</kbd>) to open Dev tools in console
* Paste `document.cookie = 'app_opened=;expires=Thu, 01 Jan 1970 00:00:01 GMT;Path=/;'`
* Hit <kbd>Enter</kbd>
* Go again to https://app.wire.com and it will let you in.

**Comment by DanMercurius** [comment]
Thanks Maxim, it worked!

**Comment by maximbaz** [comment]
:+1: 

The bug is still valid and needs to be properly fixed, but it is a webapp bug and it is tracked here: https://github.com/wireapp/wire-webapp/issues/1440

**Comment by jarvis-owl** [comment]
No issue appearing anymore! Thanks for fast fixing :) good job
