### ISSUE TITLE
Create "File" menu for Linux version

### ISSUE THREAD

**Issue by lipis** [wireapp/wire-desktop#71]
Because things like settings and stuff are under that menu :/

<img width="169" alt="screen shot 2016-10-11 at 23 00 40" src="https://cloud.githubusercontent.com/assets/125676/19288492/8ecb0a9a-9006-11e6-9f22-5fc2ab7f5c7a.png">

**Comment by ConorIA** [comment]
I had no idea this was missing, but it certainly would greatly improve usability!
