### ISSUE TITLE
Failed to fetch debian repository

### ISSUE THREAD

**Issue by mahdiG** [wireapp/wire-desktop#713]
OS: Debian testing (buster)
Do you have an antivirus software installed: Nope

What steps will reproduce the problem?
1. add wire's debian repository
2. sudo apt update

What is the expected result?
It should fetch the repo

What happens instead?
W: Failed to fetch https://wire-app.wire.com/linux/debian/dists/stable/InRelease  Could not resolve host: wire-app.wire.com

![image](https://user-images.githubusercontent.com/4989445/27496677-4316caec-586c-11e7-8750-30ad054e4cc8.png)

I live in Iran. Could it be that my country's blocked it?

**Comment by mythsunwind** [comment]
Unfortunately that might be the case :( The host is reachable for me here.

As a workaround you can try to use the following URL as repository in your sources.list:
`http://wire-taco.s3-website-eu-west-1.amazonaws.com`

But be aware that this only works with **http** and not **https**. While file integrity is checked through PGP and you are save from manipulation, everyone can see what you are downloading from this url!
