### ISSUE TITLE
Wire freezes/lags when large amounts of characters are pasted

### ISSUE THREAD

**Issue by scarejar** [wireapp/wire-desktop#715]
Wire Version: 2.12.2729
Wire for Web Version: Version 2017-06-22
OS: Windows 8.1
Do you have an antivirus software installed: None

What steps will reproduce the problem?
1. Paste 5000 characters or so onto the client

Please provide any additional information below. Attach a screenshot if
possible.

On a fresh install of Windows, defragged and well maintained. The web version on the browser handles large pastes just fine but the desktop client does not

**Comment by mythsunwind** [comment]
Can you please check if you have spell-checking enabled? You can see this in the title menu under *Edit*. The spell-checker is kind of slow and might cause this problem.

**Comment by scarejar** [comment]
@mythsunwind Oh! Yep, that seemed to be the cause. Closing
