### ISSUE TITLE
Ability disable message preview in notifications - Feature request

### ISSUE THREAD

**Issue by jellea** [wireapp/wire-desktop#72]
Maybe I'm overlooking this, but iOS has this feature and desktop doesn't. 

My concerns:
- My recent messages are plain text available to the system?
- Are messages sent over Apple push notification platform?
- I want to be notified of messages, but I don't want them to be visible (when I'm for example pairing on my computer.)

Do you accept PRs?

**Comment by ConorIA** [comment]
@jellea, I'm not on the Wire team, but I can say from experience that they do accept PRs and are very helpful when you submit one!

**Comment by gregor** [comment]
@jellea We really liked your idea and bumped the priority on our roadmap. You can now choose to hide sender name and content in notifications. Just go to Preferences -> Options after you have restarted your wrapper.
