### ISSUE TITLE
[mac] Pausing iTunes playback in the background while calling mutes the call

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#727]
Wire Version: 2.14.2743
Wire for Web Version: 2017.06.07.1805
OS: MacOS 10.12.5 (16F73)
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Have Music playing in the background via iTunes (in my case via a bluetooth headset)
2. Accept a call via Wire
3. Notice that the Music is not auto stopped and hit the 'stop music' button (F8) on the keyboard

What is the expected result?
The music should stop

What happens instead?
The music stops - but I also cannot hear the person that called me (he can hear me though).

Workaround: Turn down the music volume in iTunes to zero.

**Comment by gregor** [comment]
Thanks for the feature request. We have no immediate plans of implementing this but will consider it for the future.
