### ISSUE TITLE
Connection Loss in Video Call - Audio is Fine (Win 8.1 to Win 8.1)

### ISSUE THREAD

**Issue by DetlevCM** [wireapp/wire-desktop#731]
Wire Version: Assume Latest (no update notification), Windows
Wire for Web Version: NA
OS: Windows 8.1, both ends
KIS on my end, just Windows Defender on the other

Video calls from France to England (Oxfordshire) are interrupted - first loosing the connection (beeping notification) and then dying completely after a couple of minutes.
In contrast, a pure audio call works reliably with good sound quality.

There may also be an issue establishing a video call in the first place. Establishing an audio call works reliably. The audio call can then be changed to a video call and will experience the drop shortly after...

This may be an artefact of a bad connection in the UK - maybe something like a high latency? Low upload? - But I really don't know.

**Comment by DetlevCM** [comment]
Maybe I have an explanation:

I spoke to a family member and couldn't even establish a connection. It appears to me that maybe the versions of Wire were inconsistent? 
Closing Wire manually and then re-opening seems to have enabled calls - and a video call was stable today.

Is it possible that Wire loads early after logon, potentially before a network connection is established and then stays on an older version which has issues? Closing and reopening Wire with an established connection seems to have resolved the issue.

I will have to monitor it in the coming days.

**Comment by gregor** [comment]
Without additional information we are unable to look into this issue. Thus I am going ahead and closing it for now. If audio calls work but video calls disconnect you might simply not have a stable enough connection on one end of your call that support a high enough throughput.
