### ISSUE TITLE
Suggestion: Video Overlay always on top

### ISSUE THREAD

**Issue by DetlevCM** [wireapp/wire-desktop#734]
This is a request/suggestion from a friend:

When video calling in Skype, an overlay window is presented to allow the person to remain visible even when using other applications. (on Windows)
Could a similar feature be implemented in Wire? Maybe alternatively it is possible to offer an "always on top" mode, but then it would be necessary to resize the video depending on one's screen resolution.

**Comment by gregor** [comment]
@DetlevCM Thank you for your suggestion. I will go ahead and close this in favor of the issue it is duplicating though: #447
