### ISSUE TITLE
Incompatible version numbers on Linux desktop

### ISSUE THREAD

**Issue by mikofaur** [wireapp/wire-desktop#7476]
Wire version: 
**3.34.3196**
Wire for web version: 
**2024.01.22.11.30.34**
Operating system: 
**Ubuntu 22**
Which antivirus software do you have installed: 
**None**
What steps will reproduce the problem?

**Just wondering why the version numbers differ on the installed version and the latest Linux release version here. Is this a security concern?**

**How is it possible to verify the Linux install?**

What is the expected result?

[3.32.3079](https://github.com/wireapp/wire-desktop/releases/tag/linux%2F3.32.3079)

What is the actual result?

**3.34.3196**

...

**Comment by tlebon** [comment]
Sorry for the delay on answering this!
Your linux distro may be behind the version we released here? (I guess)

the current version in Jan should have been 3.34.xx. Version 3.35.xx is out now. 

To verify your linux install please check out: https://github.com/wireapp/wire-desktop/wiki/Authenticity

I hope that answers your question!
