### ISSUE TITLE
Prevent Wire from running more than one instance

### ISSUE THREAD

**Issue by ElvisPresly** [wireapp/wire-desktop#75]
Make please setup: To launch no more than one copy of the program.
For example. I use Linux and if Wire is already launched, and I click on an icon the program twice (not in a tray), then one more copy of the program is launched. It is always necessary to go to a tray and from there to tear the Cryptocat window. To tear a window from Dock or from a desktop there is no opportunity.
Thanks

**Comment by ConorIA** [comment]
This has been addressed in #77.  :smile:

**Comment by ConorIA** [comment]
@lipis, this can probably be marked as closed, unless you are keeping it open for something?

**Comment by lipis** [comment]
@ConorIA thanks :) Just missed it..
