### ISSUE TITLE
Latest Linux release source code tag is incorrect

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-desktop#755]
The GitHub source code download link for 2.14.2744 is tagged as 2.14.27424, which means that my PKGBUILD scripts can't find the correct download link. I'd rather not manually tweak them and then reset them next time. Is this something that is easy to fix on the GitHub side?

I refer specifically to the URL; 
https://github.com/wireapp/wire-desktop/archive/release/2.14.27424.tar.gz

Should be:
https://github.com/wireapp/wire-desktop/archive/release/2.14.2744.tar.gz

**Comment by gregor** [comment]
Will do, thanks for pointing it out
