### ISSUE TITLE
Suggestion: Be able to hide/collapse the contact list

### ISSUE THREAD

**Issue by lainy** [wireapp/wire-desktop#762]
The contact list takes up a lot of space and often leads to Wire being in the way when I'm trying to multitask. It would be nice if we could resize it or collapse it into the left edge to save screen real estate.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have heard you loud and clear. Currently there are no immediate plans of changing the app structure. Your feedback will be considered on an ongoing basis so that a change like this might end up on our roadmap.

**Comment by jm3** [comment]
The app “structure”? This sounds like you're saying you won’t change the UI at all based on customer feedback?

**Comment by TomSteinberg** [comment]
+1 from me too. Please consider re-opening this ticket.

**Comment by tlongers** [comment]
+1 to a closer look at contact management.

**Comment by Wdavery** [comment]
Disappointing to see how quickly this was closed without any thought.
Even just resizing it would be great, no need a add in multi-windows or even make it totally collapsible. 

Currently at the window's smallest size, half the space is taken by the account switcher and conversation list.

**Comment by jbaiad** [comment]
+1 this is still an issue.

**Comment by aalexei** [comment]
+1 making it a closable tab like the user details would be useful
