### ISSUE TITLE
Unable to install wire-desktop from Debian repository

### ISSUE THREAD

**Issue by huuhaa** [wireapp/wire-desktop#767]
Wire Version: <Can be found in the About dialog>
Wire for Web Version: <wire-desktop_2.13.2741-125_amd64.deb>
OS: <Bunsenlabs linux, based on debian*, upgraded to stretch base>
Do you have an antivirus software installed: <Sophos Antivirus for Linux>

What steps will reproduce the problem?
1. sudo apt install wire-desktop

What is the expected result?

wire-desktop to be installed

What happens instead?
Error message:

(Reading database ... 184501 files and directories currently installed.)
Preparing to unpack .../wire-desktop_2.13.2741-125_amd64.deb ...
Unpacking wire-desktop (2.13.2741-125) ...
dpkg: error processing archive /var/cache/apt/archives/wire-desktop_2.13.2741-125_amd64.deb (--unpack):
 unable to open '/opt/wire-desktop/resources/app/node_modules/spellchecker/vendor/hunspell/src/hunspell/hunspell.h.dpkg-new': Toiminto ei ole sallittu
Errors were encountered while processing:
 /var/cache/apt/archives/wire-desktop_2.13.2741-125_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by huuhaa** [comment]
I don't know why it doesn't show it,  but I writed to antivirus section: Sophos Antivirus for Linux

**Comment by huuhaa** [comment]
sudo tail -f /var/log/syslog
Jul  8 00:15:30 debian kernel: [   65.437407] tp_smapi 0.42 loading...
Jul  8 00:15:30 debian kernel: [   65.437651] tp_smapi successfully loaded (smapi_port=0xb2).
Jul  8 00:15:30 debian tlp[6356]: Setting battery charge thresholds...done.
Jul  8 00:15:30 debian systemd[1]: Started TLP system startup/shutdown.
Jul  8 00:15:30 debian systemd[1]: Startup finished in 3.856s (kernel) + 1min 1.462s (userspace) = 1min 5.319s.
Jul  8 00:15:55 debian dbus[611]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service'
Jul  8 00:15:55 debian systemd[1]: Starting PackageKit Daemon...
Jul  8 00:15:55 debian PackageKit: daemon start
Jul  8 00:15:55 debian dbus[611]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Jul  8 00:15:55 debian systemd[1]: Started PackageKit Daemon.
Jul  8 00:16:54 debian wpa_supplicant[900]: wlan0: WPA: Group rekeying completed with 00:22:07:59:36:75 [GTK=CCMP]
Jul  8 00:17:01 debian CRON[6674]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul  8 00:17:41 debian savd: savscand.control.log: EXTRA-SCANNER-STARTED
Jul  8 00:17:47 debian savd: savscand.control.log: EXTRA-SCANNER-STOPPED

**Comment by huuhaa** [comment]
Sophos systemLog (never have any problems with sophos and installation of any other app)

sudo /opt/sophos-av/bin/savlog --systemLog --today
Jul  7 15:29:55 debian kernel: [   64.431014] savd (4655): Using fanotify permission checks may lead to deadlock; tainting kernel
Jul  7 22:09:22 debian kernel: [   57.797285] savd (4268): Using fanotify permission checks may lead to deadlock; tainting kernel
Jul  7 22:51:45 debian kernel: [   58.883562] savd (4162): Using fanotify permission checks may lead to deadlock; tainting kernel
Jul  8 00:15:21 debian kernel: [   56.441910] savd (3987): Using fanotify permission checks may lead to deadlock; tainting kernel

**Comment by huuhaa** [comment]
Another Sophos Log (cutted only time period wich covers last installation attempt.

sudo /opt/sophos-av/bin/savlog --today

pe  7. heinäkuuta 2017 23.51.39: update.check         Successfully updated Sophos Anti-Virus from sdds:SOPHOS
la  8. heinäkuuta 2017 00.14.57: savd.daemon          Sophos Anti-Virus daemon started.
la  8. heinäkuuta 2017 00.14.57: savd.daemon          Previous instance of Sophos Anti-Virus daemon did not exit cleanly.
la  8. heinäkuuta 2017 00.15.21: talpa.startup        Unable to load Talpa modules.
la  8. heinäkuuta 2017 00.15.28: savd.daemon          On-access scanning enabled using fanotify.
la  8. heinäkuuta 2017 00.17.41: savscand.control.log Additional scanning thread has been started
la  8. heinäkuuta 2017 00.17.47: savscand.control.log Additional scanning thread has been stopped

**Comment by mythsunwind** [comment]
It seem like apt is unable to open certain parts of the deb file. One file from hunspell cannot be extracted. There is an error message, but I cannot understand it. Can you translate what "Toiminto ei ole sallittu" means?

**Comment by ffflorian** [comment]
Google Translate tells me "Toiminto ei ole sallittu" means "Action is not allowed". I am sure this is a problem on your computer, possibly your anti virus interfering.

**Comment by mythsunwind** [comment]
Because we did not receive an answer from you, I assume this issue was resolved, please feel free to contact us again if you have additional questions.
