### ISSUE TITLE
User Denied to fetch Debian repositories

### ISSUE THREAD

**Issue by AllanDaemon** [wireapp/wire-desktop#771]
OS: <Bunsenlabs with Debian Sid (Unstable)>
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Follow this: https://github.com/wireapp/wire-desktop/wiki/How-to-install-Wire-for-Desktop-on-Linux
2. Successful commands
```
sudo apt-get install apt-transport-https
wget -q https://wire-app.wire.com/linux/releases.key -O- | sudo apt-key add -
echo "deb https://wire-app.wire.com/linux/debian stable main" | sudo tee /etc/apt/sources.list.d/wire-desktop.list
```

3. When I apt update it, it gives an error:
```
# apt update
(...)               
Err:14 https://wire-app.wire.com/linux/debian stable InRelease                                                           
  403  Forbidden [IP: 54.192.59.249 443]
(...)
Fetched 3,675 B in 2s (1,289 B/s)   
Reading package lists... Done
E: Failed to fetch https://wire-app.wire.com/linux/debian/dists/stable/InRelease  403  Forbidden [IP: 54.192.59.249 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

What is the expected result?
`apt update` runs normal getting the file.

What happens instead?
An 403 error when try to get the files from the server

Trying access any file from `wire-app.wire.com` results on 403. Maybe a misconfiguration on the server?

**Comment by x2k13** [comment]
Confirmed. apt update shows the same reult on my end.

**Comment by ffflorian** [comment]
Hi @AllanDaemon, thanks for the report. Until now we didn't have an `InRelease` file, we will create one and change our build scripts accordingly.

**Comment by ffflorian** [comment]
@AllanDaemon, @x2k13
Can you please try updating now?

**Comment by AllanDaemon** [comment]
It's working now. Thanks
