### ISSUE TITLE
Build failure on Linux....

### ISSUE THREAD

**Issue by noci2012** [wireapp/wire-desktop#773]
Wire Version: <Can be found in the About dialog>
Wire for Web Version: <Can be found in the About dialog>
OS: <OS/distribution and version number>
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?
1. npm start
2.
3.

What is the expected result?
A working linux  desktop version 

What happens instead?

ERROR in ./electron/renderer/src/index.js
Module not found: Error: Can't resolve './Index.css' in '/.../wire-desktop/electron/renderer/src'
 @ ./electron/renderer/src/index.js 34:0-21

Please provide any additional information below. Attach a screenshot if
possible.

In this file: wire-desktop/electron/renderer/src/index.js
There is on line 32, an import of './Index.css'
The capital I causes a failure on case sensitive file systems.
Which causes the build to fail on linux.

**Comment by herrmannplatz** [comment]
Should be fixed now with https://github.com/wireapp/wire-desktop/commit/af63233fbd35eeef0c65acb3190995911c93e5a2
