### ISSUE TITLE
[Solved] Wire Desktop Linux : Can't add Gmail contacts > error 400 (OAuth2)

### ISSUE THREAD

**Issue by 1Claude** [wireapp/wire-desktop#774]
Wire Version: 2.14.2744
Wire for Web Version: 2017-07-06
OS: Manjaro Linux 17.02 (Gnome)
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1.Open Wire Desktop App
2. Try to add contacts from Gmail
3. Receive an error

What is the expected result?
The API should be authorized
![wire](https://user-images.githubusercontent.com/19640810/27996628-4a9d33f6-64b4-11e7-8262-1ae9927c2b6b.png)

What happens instead?
400. That’s an error.

Error: invalid_request

Missing required parameter: client_id

Learn more

Request Details
scope=https://www.googleapis.com/auth/contacts.readonly
response_type=code
client_id=
redirect_uri=urn:ietf:wg:oauth:2.0:oob

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ConorIA** [comment]
Did you build the client yourself? There are additional instructions on the readme to make the Google contacts work.

**Comment by 1Claude** [comment]
No. I just install it with Pamac.

**Comment by ConorIA** [comment]
@1Claude. Sorry, I thought I had read Debian somewhere. Same story. See the (second) pinned comment on the [aur entry](https://aur.archlinux.org/packages/wire-desktop/).

**Comment by ConorIA** [comment]
Actually, @lipis, can I just have the PKGBUILD set the necessary enviro entries, or are the client keys you folks use top-secret? I _think_ they're exposed in the Debian packages anyway since asar is disabled.

**Comment by 1Claude** [comment]
@ConorIA 

Sorry, the solution in the [AUR entry](https://aur.archlinux.org/packages/wire-desktop/) is out of my knowledge experience...

**Comment by ConorIA** [comment]
The other solution would be to use the official AppImage released by the Wire team, which has all the keys and such baked-in.

**Comment by 1Claude** [comment]
I try with the AppImage and it works. 

Will it update itself ?

**Comment by ConorIA** [comment]
No, I think you will need to download a new AppImage for each release. Though it also occured to me that the `wire-desktop-bin` package should also contain the keys from the offical Wire release, making the Google contacts functionality work.

**Comment by 1Claude** [comment]
Thanks, @ConorIA 
 
The "wire-desktop-bin" package was the good one ! It works perfectly fine.

**Comment by ffflorian** [comment]
Thanks for the support @ConorIA!
