### ISSUE TITLE
request : extra wire-trayicon.svg

### ISSUE THREAD

**Issue by erikdubois** [wireapp/wire-desktop#78]
I have been using your app on Ipad and Mac (kudos - very good image and sound)
And now I am trying out linux. 

As I create also icons for linux, I have a question.

As you can see in the picture I have your white icon in the panel on linux mint 18 cinnamon.

Could you consider making two icons. 

- One for the application - exists now - and is called wire.png - theming works

- and one for the tray. Mostly called wire-trayicon.png. - how to change this one?

When we have both of them, we can theme our linux desktop the way we like. One icon that differs from all other icons will break the theme. 

![wire](https://cloud.githubusercontent.com/assets/10594806/19319542/93a79fe0-90ad-11e6-90ac-87c1f6debedf.jpg)

**Comment by ConorIA** [comment]
With electron apps, the tray icon is baked right in to the app's resources. Take a look at commit https://github.com/wireapp/wire-desktop/commit/0fadf07c6f2d2f17ddeb8318ee933f3de198a616 to see how it is all put together. As far as I am aware, the icon is baked right into the resources/app.asar file.

**Comment by erikdubois** [comment]
to the developers 
could you not put the icon inside your executable file.
This will not improve your popularity as an application rather the opposite and my experience has been a positive one so far. I intend to use it in the future and even write an article on http://erikdubois.be and google+ if the program stays stable.

**Comment by ConorIA** [comment]
Unless I'm mistaken (I'm not a dev), I think the limitation is in electron, not Wire. The Wire team would have to provide seperate builds for each icon. You could open an issue with electron, maybe.
