### ISSUE TITLE
Feature Request: Browser Share Buttons 

### ISSUE THREAD

**Issue by brezn1** [wireapp/wire-desktop#780]
I know its possible to cut/paste a link into a conversation window but as everyone knows, a simple _share_ button in the browser would be significant ergonomy benefit. 

I don't know if this breaks all the wire-security but a simple bookmarklet or a greasemonkey script might do it?

**Comment by gregor** [comment]
Thank you very much for your feature request. We have no immediate plans of implementing this one but will note it down for future internal evaluation.
