### ISSUE TITLE
Disconnection preventing vid/audio calls (OS X 10.12)

### ISSUE THREAD

**Issue by DaveEveritt** [wireapp/wire-desktop#781]
**Wire Version**: 2.14
Wire for Web Version: n/a
**OS**: OS X 10.12.3
**Do you have an antivirus software installed**: Bitdefender but only when I invoke it, so no background processes

**What steps will reproduce the problem?**

1. voice/video call or be called
2. ringtone if calling, no sound if being called
3. disconnects

**What is the expected result?**

A connection

**What happens instead?**

A disconnection

**Please provide any additional information below. Attach a screenshot if
possible.**

My OS X firewall is allowing incoming from Wire. Ping and message and cam all okay.

**Comment by gregor** [comment]
We have released some major reliability improvements in this area in the past weeks. I will go ahead and close this ticket for now as there is not that much specific information we can act on in this particual ticket. I hope our changes fixed your problem. If not please report back.
