### ISSUE TITLE
Feature request : allow to use external CSS file for UI

### ISSUE THREAD

**Issue by dimitrik-fr** [wireapp/wire-desktop#784]
All Wire desktop interface is based on HTML+CSS, so why simply not allow to use "external" CSS file for at least contact list and text/chat dialog ?.. -- personally I'd prefer to use smaller and different fonts (as many users here mentioned already as well), and maybe different bg/fg colors too, different margins, etc.. Accepting a customized CSS file on startup seems to me the most simple solution here rather adding many new options (as well this is opening a way to users to create and share their own themes, etc.)..

what do you think ?..

Rgds,
-Dimitri

**Comment by bennyn** [comment]
Thanks for your suggestion but we don't plan to add support for custom CSS yet. If you want to customize Wire's look & feel, you are free to checkout our frontend on: https://github.com/wireapp/wire-webapp
