### ISSUE TITLE
Notification in Task not shown

### ISSUE THREAD

**Issue by rehoehle** [wireapp/wire-desktop#793]
Wire Version: 2.14.2743
Wire for Web Version: 2017.07.06.1548
OS: OSX 12.12.5

Everytime i get a message the small notification window comes up and show that there is a new message. That windows is hiding after a few seconds. In the Tastbar is not notification that there is a new version so i can't see that someone has written a message. Is that correct? I would suggest something like the Skype functionality that you can see a short number for a new message. 

![image](https://user-images.githubusercontent.com/223007/28121444-70be718a-671b-11e7-909a-3b8c3f2920de.png)

**Comment by rehoehle** [comment]
Hmm since the update today i think it's working again.

**Comment by gregor** [comment]
Glad to hear. I am going ahead and close this issue then.
