### ISSUE TITLE
Feature request : network camera URL (RTSP)

### ISSUE THREAD

**Issue by PhE** [wireapp/wire-desktop#800]
In conference rooms, you often have network camera.
It would be great if the video source could be a URL supporting RTSP protocol like : rtsp://192.168.8.7:554/live/av1

PS : I know there are tools to turn a network video stream into a pseudo-local webcam. But the setup is not as easy as giving an URL

**Comment by gregor** [comment]
Thank you for your feature request. At this time we have no plans of implementing support for network cameras.
