### ISSUE TITLE
Contact (Call a contact)

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#805]
Wire Version: 2.12.2729
OS: Crossplatform

The problem is that when you call a contact on any device/OS the other devices recieve a call as well after a while. Normally this isn't a problem since it's a good implementation but it should not still call on the other devices if the call is already accepted, that would mean you can accept 2 devices for the same call.

What steps will reproduce the problem?
1. Give a Contact a call
2. Answer the call (Accept the call)
3. Other devices gets the call as well.

Suggestion:
So what could be nice is to add a setting per device or universal where the device will not get a call if another device has answered the call (rejected). This is good for those that does not want all their devices to get the ringtone like a bastardized symphony (by the way, the ones that created the default ringtone.. thumbs up on you guys). Don't conflict this with the problem, you should not be able to get into a call where you already in.

**Comment by gregor** [comment]
This is a known limitation in our current protocol implementation which is on the list of things to be addressed. If you used multiple web based clients they should already behave the way you would expect them to. Our mobile clients need some additional work to catch up.

**Comment by gregor** [comment]
The situation will soon improve on our mobile clients as at least receiving support for the rejection synch across devices is being added to the mobile platforms. Thus I am going ahead with closing this issue as desktop is ready for the synch to happen both sending and receiving.
