### ISSUE TITLE
[Lesser issue] Wrong warning/error message

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#806]
I noticed wrong warning/error message for the end user.
If you have no microphone you get the "don't have a webcam" message if you are trying to call or accept a call. Luckly the link for "read more" goes to the help page for microphone (how I noticed that I needed to plug in my microphone).

**Comment by gregor** [comment]
@Sethox Thanks for the report. An easy fix on the webapp side of the product. This will be part of an upcoming release - not the one we have planned for tomorrow though.

https://github.com/wireapp/wire-webapp/pull/1534
