### ISSUE TITLE
Alt+Shift (switch language) cause Main menu call.

### ISSUE THREAD

**Issue by b0r0dat0r** [wireapp/wire-desktop#808]
Wire Version: 2.14.2744
Wire for Web Version: 2017.07.06.1548
OS: KUbuntu 17.04 (Plasma 5.9.4)
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Open any chat in Wire.
2. Switch to another language(locale) using hot key Alt+Shift

Expected that only language(locale) will be switched and I'll type a text.

Instead of it Main menu of Wire activates every time I switch language using Alt+Shift. Needs to press Esc, to type text in chat.

![image](https://user-images.githubusercontent.com/7407986/28269604-54b11ac6-6b0b-11e7-9d7d-a7f24a12c981.png)

**Comment by ffflorian** [comment]
Hi @b0r0dat0r, sorry I cannot reproduce your issue on Debian + Gnome.

We have a shortcut <kbd>Alt</kbd>+<kbd>⇧ Shift</kbd>+<kbd>↑ Up
</kbd> [for switching chats](https://github.com/wireapp/wire-desktop/blob/91ecb1a382c53398f02d13ff378d71bcbd4ca59a/electron/js/menu/system.js#L321), but AFAIK no shortcut for just <kbd>Alt</kbd>+<kbd>⇧ Shift</kbd>.

Do you have this issue in other apps, too?

**Comment by b0r0dat0r** [comment]
Hi @ffflorian .
I'm using KDE (Plasma). Issue only in WIRE app. 
Attaching animated gif of issue.
![optimised](https://user-images.githubusercontent.com/7407986/28365659-15f2a128-6c92-11e7-9364-ab8cacea754b.gif)

**Comment by b0r0dat0r** [comment]
Same issue on kubuntu 16.10 (KDE plasma 5.7.5, QT 5.6.1) -   Alt+Shift call's main menu.

**Comment by maximbaz** [comment]
I see this issue on someone else's laptop running Arch + KDE, I can't repro it on my Arch + i3. So it's a safe bet that the issue can be reproduced with KDE systems only.

**Comment by maximbaz** [comment]
The bug is not reproducing in other apps that have system menu, only in Wire (tried a few apps like notepad).

**Comment by maximbaz** [comment]
And the hotkeys <kbd>Alt+Shift+↑/↓</kbd> don't work on KDE (neither do <kbd>Shift+Alt+↑/↓</kbd>), the conversations aren't switching - so they are probably the cause of the issue here.

**Comment by tmshlvck** [comment]
Same thing happens on Mate desktop (using Ubuntu Mate 17.04).

**Comment by next-mad-hatter** [comment]
Same here with i3 on Slackware.

**Comment by Kozoft** [comment]
Yep, it's still there. Alt+Shift shows system menu. Only in Wire.
Ubuntu Mate 17.04 (Mate 1.18.0)
Wire 3.0.2816
VirtualBox 5.1.26

**Comment by Vladichka** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/50
It's an electron issue
