### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by mzs114** [wireapp/wire-desktop#81]
Will this run on FreeBSD? 

BSDs lack IM messenger services, perhaps Wire could be the first to support them?
I volunteer to help in case testing is required.  :)

**Comment by ConorIA** [comment]
Given that the app is based on electron, I think this is a non-starter, at least until electron runs on FreeBSD. There is an issue open here: https://github.com/electron/electron/issues/3797

**Comment by lipis** [comment]
Once the support will come to Electron as already mentioned we can take another look.. for now there is not much we can do..

**Comment by macandchief** [comment]
Is there maybe a chance for opening this? I mean Electron seems to be available now - also on OpenBSD. It'd pretty neat if on the download page a BSD section could be added.

**Comment by toghrulgasimov** [comment]
electron13 is available on FreeBSD
