### ISSUE TITLE
Not ideal for high DPI monitor - doesn't allow scaling, waste of space

### ISSUE THREAD

**Issue by DetlevCM** [wireapp/wire-desktop#815]
Wire Version: 2.15.2750
OS: Windows 8.1, 64 Bit
125% DPI scaling on an high resolution screen - 3200x1800 pixels on 14"
Do you have an antivirus software installed: KIS (not relevant for this)

What steps will reproduce the problem?
1. just reopen wire - its an issue with the latest update (whenever the design was changed/'tweaked')

What is the expected result?
Wire to look like all other applications with a reasonable typeset size that compares well with the rest of the items on the screen.

What happens instead?
Wire looks like it is designed for the visually impaired as everything is huge. As a result, my contacts list wastes a lot of screen space and my chat section has become tiny with a huge typeset...
This would be easily resolved if there were a scaling option in Wire (in the same way there is one for browsers - side note, Internet Explorer is also completely broken in this respect for some site...) - similarly to for example Firefox or Opera. However pressing Ctrl and scrolling does nothing.

Please provide any additional information below. Attach a screenshot if
possible. -> Sorry, I don't wish to share my chat publicly.

**Comment by gregor** [comment]
Thanks for your feedback. We are always considering our UI but have no immediate plans of changing it dramatically.
