### ISSUE TITLE
Javascript error occurred in main process

### ISSUE THREAD

**Issue by workrbee** [wireapp/wire-desktop#816]
Wire Version: 2.14.2743
Wire for Web Version: 2017.07.18.1250
OS: MacOS 10.12.5
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. quit app (1 comment indicated, displayed on screen, but not "read" before quit)
2. get error (sometimes)

What is the expected result?
close app, no error

What happens instead?
error message

Please provide any additional information below. Attach a screenshot if
possible.
![image](https://user-images.githubusercontent.com/15026445/28400865-cd31e5c8-6cca-11e7-801e-9798c90889a2.png)

**Comment by gregor** [comment]
Please update to the latest public build and report if the issue still occurs.
