### ISSUE TITLE
Feature Request: Emoji shortcut button in chat

### ISSUE THREAD

**Issue by starkshaw** [wireapp/wire-desktop#828]
Wire Version: 2.15.2750
OS: macOS

It will be much nicer if we could type in emoji more quickly just like on the phone version instead of press Ctrl+Cmd+Space to call the system-wide _Emoji & Symbols_ popup, and that sometimes does not work.

**Comment by ffflorian** [comment]
Hi @starkshaw, thank you for your request. We are already tracking this request at https://github.com/wireapp/wire-desktop/issues/745, so I'm going to close this one here.
