### ISSUE TITLE
Desktop Wire (OSX) Constantly Freezing. Unusuable.

### ISSUE THREAD

**Issue by JamesTheHacker** [wireapp/wire-desktop#831]
Wire Version: 2.15
OS: El Capitan
Do you have an antivirus software installed: None

What steps will reproduce the problem?
1. Click the wire icon
2. Log into account
3. Application freezes

What is the expected result?

Application, and messages, should load. I should be able to send messages to contacts.

What happens instead?

Application loads and freezes. Remains unresponsive or very slow. Clicking a contact takes over 30 seconds to load. If I send a message to the contact it says it's delivered but if I click on another contact, and go back to the previous contact the message I sent isn't shown

As a developer myself I have experienced this exact same issue on any desktop software that is built on browser technologies in my own applications, and in other applications such as Slack, and Atom. I'm not convinced web technologies for desktop applications is the best solution.

**Comment by gregor** [comment]
Thanks for your general feedback.
