### ISSUE TITLE
app.wire.com will not load in Chromium on Ubuntu 16.04

### ISSUE THREAD

**Issue by digital-shokunin** [wireapp/wire-desktop#833]
Wire Version: N/A
Wire for Web Version: Can't tell
OS: Ubuntu 16.04 Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Do you have an antivirus software installed: Nope

What steps will reproduce the problem?
1. go to https://app.wire.com
2.
3.

What is the expected result?
App loads

What happens instead?
Progress bar just displays and that's it.

Please provide any additional information below. Attach a screenshot if
possible.

From the developer console log (javascript errors):

wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:6 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.shimRTCIceServerUrls (wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:6)
    at b.exports (wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:5)
    at Object.<anonymous> (wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:5)
    at Object.d.2../adapter_factory.js (wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:5)
    at e (wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4)
    at a (wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4)
    at wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
    at wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
    at wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
shimRTCIceServerUrls @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:6
b.exports @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:5
(anonymous) @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:5
d.2../adapter_factory.js @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:5
e @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
a @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
(anonymous) @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
(anonymous) @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
(anonymous) @ wire-vendor.min.js?2017-07-18-12-50-prod:sourcemap:4
wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2 Uncaught ReferenceError: platform is not defined
    at Object.is_chrome (wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2)
    at wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2
    at wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2
is_chrome @ wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2
(anonymous) @ wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2
(anonymous) @ wire-app.min.js?2017-07-18-12-50-prod:sourcemap:2
onloadwff.js:59 [Violation] 'setTimeout' handler took 126ms
Service Worker termination by a timeout timer was canceled because DevTools is attached.

**Comment by mythsunwind** [comment]
Something seems to be really wrong with Chromium. What happens when you try opening the page with a new profile or with the official package of chromium from Ubuntu (59.0.3071.109-0ubuntu0.16.04.1291)?

**Comment by digital-shokunin** [comment]
I am using the official package. It started after an update a few months
ago.

**Comment by digital-shokunin** [comment]
I have just opted to use Firefox instead for this. It's possibly a plugin causing an issue, but I don't consider it worth the effort to figure out which one and I'm use all of them.
