### ISSUE TITLE
Support MacBook Pro Touchbar

### ISSUE THREAD

**Issue by BennySamir** [wireapp/wire-desktop#836]
Hello,

i have a feature request. It would be great if you can support the new MacBook Pro Touchbar:
- Shortcuts. For example: Call, Video-Call, Search, Ping, Upload File/Image, times messages
- Emojis
- Or other cool stuff 😎

Thanks and you make a great job 👍

Regards Benny

**Comment by gregor** [comment]
While this would be a nice addition, we currently have no plans to implement this due to the limited set of resources. Now that electron added support for this it might be a viable option for a user contribution though. https://github.com/electron/electron/blob/master/docs/api/touch-bar.md

**Comment by BennySamir** [comment]
@gregor thank you for the feedback. I have start the implementation of the Touchbar support: https://github.com/BennySamir/wire-desktop/commit/18cc383f0f9818c5dcd8f738fb5bfae11258682e

But without documentation it is very hard. I need to know:
* How I detect the current windows status? Because I must know if the user has open a conversation otherwise the touchBar will be always displayed (also on the Login view).
* I have use the send Action from system.js but there are not all actions. How I can call "upload picture" and "upload file"?
* if there an event for "focus in message input"? I need to know this for the Emoji support, because I want display the emoji icon only if the focus is In the input field.

Thanks Regards Benny

**Comment by gregor** [comment]
@BennySamir Sorry for the late reply. Currently the app state of the webapp is not published to the desktop container. Knowing the app state requires additional work on https://github.com/wireapp/wire-webapp. The same goes for the items on your bucket list. Actions from the menu bar are using the ipcRenderer/ipcMain features of electron in combination with electron to be published in the approprioate webview that has the webapp loaded. Hooking this up correctly is a bit tricky and needs work on both components.

**Comment by gregor** [comment]
Thank you very much again for your feature request and trying to go ahead and implementing it. Due to inactivity I am going ahead with closing this issue. We have noted it down for future consideration to implement ourselves.
