### ISSUE TITLE
Support Mac OS Share Extension 

### ISSUE THREAD

**Issue by BennySamir** [wireapp/wire-desktop#837]
Hello,

i have a feature request.
Mac OS has a global Share-Button which will be supported from different Apps.
It would be great if you can add Wire as Share-Target.

Thanks

Regards Benny

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
