### ISSUE TITLE
Incomplete URL preview when sending from desktop app

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#84]
On Wire iOS, a preview of URLs is sent to the recipient (open graph parsing). On the desktop app, there is no such preview sent.

**Comment by herrmannplatz** [comment]
In short, we support them. On the desktop we are a little bit more restrictive in case of link previews. We only allow specific types of open graph meta data. iOS lowered this at some point and we will do the same once there is time. 

If links doesn't work at all, please tell what kind of version you are using and what links are not working (if you can share them). As a test, wire.com should always work.

**Comment by IpsmLorem** [comment]
Links works. I just pointed out the different behavior :)

**Comment by IpsmLorem** [comment]
Here is a difference between the iOS and dekstop one:
![snap](https://cloud.githubusercontent.com/assets/1250795/19455176/71c5b17e-94bc-11e6-8db2-dc5b23310931.png)

**Comment by IpsmLorem** [comment]
Another exemple:
The first message is the link sent from Wire Desktop, the second from Wire iOS:
![cap](https://cloud.githubusercontent.com/assets/1250795/19655381/ed0e6ba0-9a1b-11e6-82eb-ab359daee185.png)

**Comment by IpsmLorem** [comment]
Another one: https://www.microsoft.com/en-us/store/p/heretic/9wzdncrd2909
On desktop it just displays the link, without parsing the OG tags:

~~~xml
    <meta property="og:title" content="Heretic – Games on Microsoft Store" />
    <meta property="og:type" content="product" />
    <meta property="og:url" content="https://www.microsoft.com/en-us/store/p/heretic/9wzdncrd2909" />
    <meta property="og:image" content="//store-images.microsoft.com/image/apps.16067.9007199267166298.1ec79b97-ae81-45e7-99b8-475f6e508cd1.5a4306ce-da06-466f-a688-ccb5cb5183a7?w=150&amp;h=150&amp;q=60" />
    <meta property="og:image:height" content="150" />
    <meta property="og:image:width" content="150" />
    <meta property="og:description" content="Heretic is a dark fantasy first-person shooter game.
~~~

**Comment by gregor** [comment]
We have fixed many of the previously failing cases for URL previews. Thereby closing this. Please report if new issues arise.
