### ISSUE TITLE
Window position not restored correctly (Linux)

### ISSUE THREAD

**Issue by sebastianbauer** [wireapp/wire-desktop#840]
Wire Version: 2.15.2571
OS: Ubuntu 17.04 & 17.10 alpha

What steps will reproduce the problem?
1. Open Wire and position window
2. Close Wire (not minimized to tray or something)
3. Open Wire again

Window should have the same position like before closing the app.

The position is moved down (up to the height of the title bar).

**Comment by mythsunwind** [comment]
What window manager or desktop environment are you using? can you provide a screenshot of before/after?

**Comment by jayarc** [comment]
I have a feeling this is an electron problem. I also run Atom (an electron app) on Linux with Debian Stretch and Jessie, both saw this issue: When I relaunch the app, the windows which are supposed to re-appear in the same place as they were closed in, actually appear down further vertically about the thickness of the top window bar in Gnome, the bar where you have close button etc... I have a feeling it's a bug in window height calculation that doesn't take into account that top bar. I imagine there's probably an electron bug existing for this issue already.

**Comment by Termuellinator** [comment]
an confirm this behaviour on Manjaro KDE.
For me, it's not only the height but the whole size/positioning. I normally have wire on the whole screenhight and about 1/3 the width and on the right of the screen, after restart the window is just a small window with about 4/3 aspect ratio in the lower left quadrant of the screen.

**Comment by madLyfe** [comment]
this happens to me on windows 10. it remembers size and position perfectly on the default monitor(multi monitor setup) but if i have it on another monitor it remembers the position but not the size. same issue with signal desktop app but they dont have it remembering position/size on the default monitor like you guys do.

**Comment by loscamilos** [comment]
Same here - Windows 10 Pro (1713), UHD 1-display. Wire window position not restored after restart/shut down the system. DisplayPort connection.
