### ISSUE TITLE
No reconnection after standby (Linux)

### ISSUE THREAD

**Issue by sebastianbauer** [wireapp/wire-desktop#843]
Wire Version: 2.15.2751
OS: Ubunutu 17.04 / 17.10 alpha

What steps will reproduce the problem?
1. Open Wire
2. Switch PC to standby
3. Start PC

Wire should be usable right now.

Wire doesn't reconnect. Writing a new message ends in a grey message (not transferred). Need to restart Wire. Message is still not sent and must be typed again.

**Comment by Filbuntu** [comment]
Same problem here!
Wire Version: 2.15.2751
OS: Ubunutu 16.04

Wire worked well till this week. For some days I only get a blue window with my picture. No conversation visible, no notifications! The Android wire app seems to work but I prefer the desktop app.
Thanks for working on this as soon as possible!

**Comment by Filbuntu** [comment]
Because of another problem (not all PPAs would update), I changed the DNS-server of my internet connection to OpenDNS (208.67.222.222, 208.67.220.220, [OpenDNS Setup guide](https://www.opendns.com/setupguide/#familyshield)) and the connection to wire works again, too! Really nice side-effect. I am connected again and all the conversations appear (the blue window is filled again.

**Comment by mythsunwind** [comment]
So it seems like a request is waiting for the response or a dns name cannot be resolved. Would you be so kind to open Wire again with your old DNS by running `wire-desktop --devtools`, mark "preserve log", restart with the same parameter and check the network tab for hanging requests?

**Comment by mythsunwind** [comment]
@sebastianbauer would you be so kind to check if this is fixed for you as well when updating to a different DNS-Server?

**Comment by sebastianbauer** [comment]
Already used OpenDNS. But the described issue by @Filbuntu is different to mine.

Wire just can't send the message (stays grey). All is fine after restarting Wire. But those grey messages stays grey and aren't sent.

BTW, a colleague has the very same problem.

**Comment by Filbuntu** [comment]
@mythsunwind Thanks for the commenting. I tried to do what you said but each time I restart it seems not to preserve the log. In the terminal I get this error after restarting wire with devtools:
`Failed to rename log file (/home/.../.config/Wire/logs/2dc85901-ca08-4b14-84a1-9d7c85e32daf/console.log) with error: ENOENT: no such file or directory, rename '/home/..../.config/Wire/logs/2dc85901-ca08-4b14-84a1-9d7c85e32daf/console.log' -> '/home/..../.config/Wire/logs/2dc85901-ca08-4b14-84a1-9d7c85e32daf/console.old'`

Here is what I get when I click on preserve log and hit F5 to get at least something:
![wire-desktop --devtools](https://user-images.githubusercontent.com/12456480/29059198-f6bca528-7c46-11e7-9858-d7037cf5e40d.png)
Not sure if this is of any help.

**Comment by mythsunwind** [comment]
@sebastianbauer Thanks for the detailed explanation. We have ideas to include a resend feature for these cases, but the implementation is currently not scheduled for a development sprint.
