### ISSUE TITLE
Add hotkeys for microphone, camera and screen cast

### ISSUE THREAD

**Issue by kirusyaga** [wireapp/wire-desktop#845]
Wire Version: 2.15.2750
Wire for Web Version: 2017.07.18.1250
OS: Windows 8.1
Do you have an antivirus software installed: yes

Please, add hotkeys for management of microphone, camera and screen cast during the call.

**Comment by gregor** [comment]
Thank you for your feature request. We have no immediate plans of adding these shortcuts but will evaluate the roadmap on an ongoing basis.
