### ISSUE TITLE
HTML styling with copy/paste and CPU impact

### ISSUE THREAD

**Issue by drakelovesbarbie** [wireapp/wire-desktop#848]
Wire Version: 2.15.2750 (but bug is with any)
Wire for Web Version: 2017.07.18.1250 
OS: Windows 10
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. open a website or a text editor (VScode) that saves HTML formatting in the clipboard
2. copy something with CTRL+C
3. paste it inside a chat with CTRL+V and send it, SOMETIMES it carries HTML data and will appear html formatted (only to the sender)
4. CPU will start raising by some % and will stay like that (it does accumulate over time)

What is the expected result?
I get text, unformatted, no CPU impact

What happens instead?
i get HTML badly formatted content with styling and CPU impact

Please provide any additional information below. Attach a screenshot if
possible.
![capture](https://user-images.githubusercontent.com/13280134/28928345-3f7d3cf6-786d-11e7-989a-7d0935d07bd0.PNG)

**Comment by mythsunwind** [comment]
This is actually a feature called markdown syntax. It is activated when a line starts with 4 spaces. To fix this, just use the code syntax of markdown by add ``` on top and bottom of the pasted text. More information can be found here: https://support.wire.com/hc/en-us/articles/115002676029-How-can-I-use-markdown-to-format-text-
