### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by ohmyarch** [wireapp/wire-desktop#85]
http proxy, socks5 proxy

**Comment by agentf90** [comment]
definitely looking for this as well. I use tor for everything personal now a days.

**Comment by ConorIA** [comment]
Electron would appear to support proxying via the command line. I believe these should work with wire. See possible flags [here] (http://electron.atom.io/docs/api/chrome-command-line-switches/).

**Comment by ghsrcgh** [comment]
Telegram for alll platforms (Desktop, iOS, Android) now support SOCKS5 proxy from really beginning of application start. I.e. it may be used with the TOR. It is a native support for the application without any additional tools or even "hacks". I think it is required to analyze that practice and do more user-friendly decision.

**Comment by gregor** [comment]
Thanks again for your feature request. We will continue to track this internally. At this time we do not have any immediate plans to implement this feature. We will continue to evaluate on if and when to put a feature like this on the roadmap.

**Comment by snakyjake1** [comment]
Is this "closed" because it is complete?
If not, is it listed as a feature?

**Comment by jvoisin** [comment]
This would allow to use Wire over Tor, currently, it's simply not possible. A nice side-effect of this would be to completely bypass censorship in a lot of place.

**Comment by snakyjake1** [comment]
Bypassing a corporate network via socks would be ideal.

**Comment by tylerjw** [comment]
@ConorIA Could you give an example of how one would use this?  I'm not familiar with JS or the way you would run Wire from the command line.

**Comment by ConorIA** [comment]
@tylerjw, I tried running from the command line with `wire-desktop --proxy-server="socks5://127.0.0.1:9050"`, which should have run Wire through Tor. I'm not really sure if it worked or not. I had a connection, but I'm not sure whether it was being proxied or not. I tried a couple of different npm modules to ask for my IP, but they all have me my local address, so I gave up. If anyone is in a country where Wire is blocked, they could try the above. Otherwise maybe @gregor could give me a hint as to how to tell if the connection is being proxied or not.

**Comment by tylerjw** [comment]
@ConorIA I'm on OSX so I tried this: 

```bash
 open -n ./Wire.app --args --proxy-server="socks5://127.0.0.1:8009"
```

Yet it doesn't seem to work.  I have a ssh tunnel running on 8009.  I can use the app on Wire's website in firefox with foxyproxy setup correctly to that port.  I'm not doing this over tor, just a normal ssh tunnel started like this (to a machine I own out on the internet):

```bash
ssh -f -D8009 user@url -N
```

**Comment by ConorIA** [comment]
You know, I think this actually is working. As a test, I tried to ask Wire to connect through my server's HTTP port (80), which is not a working proxy. I got a whole bunch of 400 errors in in my server logs similar to:

```
[23/Sep/2017:18:34:38 -0400] "CONNECT app.wire.com:443 HTTP/1.1" 400 173 "-" "-"
```

In that case, the syntax was again:

```
wire-desktop --proxy-server="http://my.server.address:80"
```

**Comment by mythsunwind** [comment]
We recently added the instructions on how to connect through a proxy server on Wire desktop:
https://support.wire.com/hc/en-us/articles/115005697189-How-I-can-connect-through-a-proxy-server-on-desktop-

**Comment by jvoisin** [comment]
It seems that DNS queries won't go through the proxy :/

**Comment by lorenzosu** [comment]
The command-line switch won't work with an (authenticating) http proxy. Also with a socks5 proxy calls don't seem to work.
The first (http proxy) is still a rather common scenario in company setting, not sure how/if this would work in the PRO version.
