### ISSUE TITLE
Wire desktop not synchronizing messages with Wire android client

### ISSUE THREAD

**Issue by dozylynx** [wireapp/wire-desktop#850]
Wire Version: Android 2.38.352 ; Desktop 
Wire for Web Version: 2017-08-04-15-01-prod
OS: Android 5.1, patch level 2016-08-01
OS for Web: Ubuntu 16.04.3 LTS, using Google Chrome | 59.0.3071.109 (Official Build) (64-bit)
Revision | 8d31b54270a793a0f98e76579c8fd0405bbd6ac6-refs/branch-heads/3071@{#805}
OS | Linux
JavaScript | V8 5.9.211.38

Do you have an antivirus software installed: No.

What steps will reproduce the problem?
1. Start the Desktop Wire client
2. Send a 24-hour expire message to a contact using the Android client

What is the expected result?

1. Expected to be able to observe that the Desktop Wire client mirrors the sent message.
2. Expected to be able to observe that replies to the sent message make it to both the Android and Desktop clients.

What happens instead?

1. Desktop Wire client does not mirror the sent message.
2. Replies to the message from the contact, who did receive the message sent, do not make it to _either_ the Android or Desktop Wire clients. (bad!)

**Comment by gregor** [comment]
This is as designed. Timed messages will not show up on your other devices. I will relay your feedback on the specification of this feature to our product team.

Where are the replies to that message sent from? Those certainly should not get lost. Not even seeing a trace of them is something we need to look into. But as we do not have replies per se those messages are just like any other message from that contact to you.

**Comment by dozylynx** [comment]
Have not been able to reproduce the dropped messages behaviour, unfortunately, so closing this as no further action required at this time.
