### ISSUE TITLE
Feature request Shared Media

### ISSUE THREAD

**Issue by Nuruddinjr** [wireapp/wire-desktop#86]
All modern messengers support this option so Wire also should have this feature , I believe

**Comment by lipis** [comment]
Sorry for my ignorance but what is that and what exactly we have to do?

**Comment by Nuruddinjr** [comment]
Sorry for not clarifying, 
This is a feature allows users to see previously shared media(audio, photo) within a conversation.
This feature implemented in FB Messenger, Telegram, Whatsapp ,too

**Comment by herrmannplatz** [comment]
We started working on that. Should land soon on iOS and Android as well.

**Comment by herrmannplatz** [comment]
Happy to close this.
