### ISSUE TITLE
Video links (to youtube) shown in-line with link-preview disabled

### ISSUE THREAD

**Issue by hylkevds** [wireapp/wire-desktop#868]
Wire Version: the current one (please make the number copyable)
Wire for Web Version: the current one (please make the number copyable)
OS: linux
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Disable link preview in preferences
2. Past a link to a youtube video in a chat (a link like https://www.youtube.com/watch?v=NN75im_us4k )

What is the expected result?
Just a text message with a clickable link is sent.

What happens instead?
The video is embedded.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
We have different types of media previews. Inline players are generated on the receiver side and thus not affected by the link preview preference. This is certainly not as straightforward as it could be. We are currently looking at options on how to improve this. We will take your feedback into consideration in this effort.
