### ISSUE TITLE
Bug - Message History

### ISSUE THREAD

**Issue by Nuruddinjr** [wireapp/wire-desktop#87]
OS X Wire application screws up message order, when new message comes, it goes up to my older messages , so that I don't know if it's a new message or no

**Comment by bennyn** [comment]
Hi @Nuruddinjr, thanks for bringing up this topic. What's the timezone on your computer? And is your OS X clock in sync with time servers?

**Comment by Nuruddinjr** [comment]
Hello , I didn't sync my time with servers ,Timezone is GMT +5  Asia/Tashkent.

**Comment by bennyn** [comment]
@Nuruddinjr, it is important that "Set date and time automatically" is turned on in macOS when using Wire:

![unbenannt](https://cloud.githubusercontent.com/assets/469989/19434674/30221d8e-9467-11e6-91dd-b6bc1a81abdb.PNG)

Can you please check if that's the case for you?

You can also sync your time from the terminal using: `ntpdate -u time.apple.com`.

**Comment by Nuruddinjr** [comment]
Thanks , It seems my university wifi blocks 23 port for ntpdate so it didn't work when I switched on "Set date and time automatically",now I synced my time. Not having this issue for now. Let's see.

Thanks for quick resolving the issue, I was having this issue for weeks 😆

**Comment by ConorIA** [comment]
@bennyn, it might be worth adding a troubleshooting section to the readme or to the online help and include this issue.

**Comment by admlko** [comment]
Hi,

I have the same problem with Windows 10, and I have "set time automatically" and "set time zone automatically" checked.

It is quite irritating when I start writing a message, and if the recipient sends something while I'm writing my message, my message still goes before the recipients message, which should obviously be before mine.

Any suggestions?

**Comment by tmikaeld** [comment]
This issue seems to happen between Windows 10 and OS X users even though both have activated automatic time sync. OS X time seems to go a few seconds faster than on Windows 10. Windows 10 have "time.windows.com" as the default.

**Comment by InvisaMage** [comment]
I'm having the same issue.

**Comment by maximbaz** [comment]
Link: #316, https://github.com/wireapp/wire-webapp/issues/600

**Comment by gregor** [comment]
Closing this in favor of #316 to have only one ticket on this repo to keep track of the issue.
