### ISSUE TITLE
unexplained behavior of the experimental Linux version of Wire

### ISSUE THREAD

**Issue by vilde1** [wireapp/wire-desktop#870]
Wire Version: experimental Linux version of Wire
Wire for Web Version: <Can be found in the About dialog>
OS: debian
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?
the mails that have been exchanged with the support team:

me - "Some days ago, during a call (through the experimental Linux version of Wire) , wire suddenly closed and since then i could not open the app again.
I want to note that i am using the same version of wire at the same machine for the last almost 10 month with no problem before this time.
You declare that you do not provide support for the experimental Linux version of Wire, however either i will go back to skype solution (which i would hate) either i will bother you as my last choice
so, the below fields are random
thank you and i apologize in advance"

st - "Hello,
Thanks for writing to Wire to share your feedback.
Are you using the latest version?
Please feel free to contact us again if you have additional questions.
We appreciate your taking the time to send us your comments here."

me - "Hi,

Firstly, i want to thank you for your answer and your interest and
continuing to the subject :
i give this -->
sudo apt dist-upgrade wire
and i take this -->
[...] Calculating upgrade... wire is already the newest version. [...]
so, yes, i had the newest version
if "we" will not be able to find out the reason that this happened
(suddenly!) and come up with a way to solve it, is it possible to inform
me, where are the logs of wire saved in linux?
thank you a lot for your time"

st - "Hello,

thanks for your reply.
We will add a .pdf file as attachment. That's a small guide of how to start Wire with devtools. (supposed to be for Windows, but should be the same on Linux)
/opt/wire-desktop/wire-desktop --devtools
or
./wire*.AppImage --devtools
When you got the logs, we want you to move to github:
https://github.com/wireapp
Please create a new issue there and explain whats going on.
Our developers are active on github and will take a look at your logs for sure!
Best regards,
Wire Support
Attachment(s)
Windowspublicapp-devtools.pdf"

What happens instead?

i didnt find any file named like this, i couldnt find any system logs neither the conversations' logs.
i will be honest, i got a little bit tired, so if you can just inform me where can i find the chats' logs or if they are somewhere at your servers if is it possible to send them to me.
tell me if i can do something more/additionaly. thank you again.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ConorIA** [comment]
```
sudo apt dist-upgrade wire
```

Won't install `wire-desktop`. The Ubuntu/Debian repo has always used the package name `wire-desktop`. The support folks should have caught that.  

My suggestion (provided you have already set up the Wire apt repo): 

```
apt-get remove --purge wire
apt-get install wire-desktop
```

Then you can try running with devtools by `opt/wire-desktop/wire-desktop --devtools`.

**Comment by vilde1** [comment]
solved.

thank you a lot.
