### ISSUE TITLE
multiple accounts - remove account option missing

### ISSUE THREAD

**Issue by Gregory-K** [wireapp/wire-desktop#872]
Wire Version: 2.15.27.50
Wire for Web Version: 2017.08.08.1509
OS: Windows 10 Pro 1703
Antivirus software installed: No

What steps will reproduce the problem?
1. Add Account (secondary)
2. Decide to remove the secondary Account
3. No option to be found

What is the expected result?
Add an extra Account and whenever want to Remove it

What happens instead?
Add an extra Account and not possible to Remove it form list

Please provide any additional information below. Attach a screenshot if
possible.

Referenced feat: #738 

** Actions Taken so far**
1. Removed partition directory of the secondary account. Recreated on app start.
2. Removed Device from another device. Account remained on list displaying the login page.

**Comment by gregor** [comment]
@Gregory-K All you have to do is open the account you want to remove and select the logout option from the Wire application menu at the top. We can certainly improve on the experience. Where did you expect to find the option to remove an account?

**Comment by Gregory-K** [comment]
@gregor thanks for the info and the quick response.

I had the application menu hidden. I searched there, but given the fact that I never had to logout before, I didn't notice it.

From a UX point of view I think that the "Remove Account" option should be where you added the Account and it should be "Remove" not "Logout" as the two words describe a different action (Login/Logout - Add/Remove).

Possible Locations:
a. a mini popup over or beside the Account avatar icon (maybe with a little arrow, like the options per conversation)
b. now that the electron app supports multiple accounts, a menu item "Accounts" on the menu bar with add/remove sub-items
or extra
c. why not a remove account option in Preferences

**Comment by Titanfinger** [comment]
I had a similar Issue.
I create a Account and after i changed my Accountname i had 2 Accounts.
1. With the old Name 
2. With the new Accountname

But i have changed not create a new one.
Now i found the old one an deleted this.

Thanks to the Developer after this issue i found my friends on Wire and the Sound-quality is awsome!!

**Comment by gregor** [comment]
Thank you very much again for your suggestions. We have added a right-click menu to the individual accounts which allow you to log out, immediately remove an account or access the team management if you are using the app for business purposes and are a team owner or admin. This will be part of the next public releases.
