### ISSUE TITLE
Typing indicator not displayed in Wire desktop

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#875]
Wire Version: 2.15.2550
OS: Win10 x64

What steps will reproduce the problem?
1. Start typing a message on mobile device

What is the expected result?
See "xxx is typing" in Wire desktop 

What happens instead?
Nothing.

**Comment by gregor** [comment]
This feature is not implemented in the webapp/desktop apps.

**Comment by tbu-** [comment]
Would implementing it be considered a bug fix or a feature? I.e. would you accept a PR to display the typing notification like on Android?

**Comment by gregor** [comment]
At this point in time it would be considered a feature. It touches the UX, has to heaviliy involve design changes and a PR is thus very likely to be rejected.

**Comment by ArchiveBase** [comment]
https://github.com/wireapp/wire-android/issues/716#issuecomment-466703597
