### ISSUE TITLE
Camera not switching off

### ISSUE THREAD

**Issue by zylden** [wireapp/wire-desktop#879]
Wire Version: <Can be found in the About dialog>
Wire for Web Version: 2.15.2751
OS: Linux - Ubuntu 16.04
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>
No

What steps will reproduce the problem?
1.  Video call contact
2.  Stop camera during call
3.  Camera light still stays on and camera shows as busy from other apps.

What is the expected result?
To release camera

What happens instead?
Camera is not releavsed

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
This is a limitation due to a missing bit in the WebRTC implementation in Chrome as stated in https://github.com/wireapp/wire-desktop/issues/48. The release of that feature was postpooned by Chrome multiple times by now - but I hope it will finally arrive soon. Closing this as a duplicate.
