### ISSUE TITLE
Chat history not synced to new device

### ISSUE THREAD

**Issue by zylden** [wireapp/wire-desktop#880]
Wire Version: 2.15.2751
OS: Linux - Ubuntu 16.04
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>
No

What steps will reproduce the problem?
1.  Use Wire
2.  Install on new device
3.  Old Conversations are not synced only new ones

What is the expected result?
Old Conversations to be synced

What happens instead?
 Old Conversations are not synced only new ones

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
This is a "feature" of the encryption. We currently have no means of a history backup that could then be imported on a new device. We know this is a feature that is requested by a number of users and options are continuously evaluated internally. At this time we have nothing to share if or when a feature like this would be implemented.
