### ISSUE TITLE
YOUR CONNECTION IS NOT PRIVATE, LEARN MORE?

### ISSUE THREAD

**Issue by pitbullwinston** [wireapp/wire-desktop#882]
Wire Version: <2.15.2750>
Wire for Web Version: <Can be found in the About dialog>
OS: <OS/distribution and version number>
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?
1.
2.
3.

What is the expected result?

What happens instead?

Please provide any additional information below. Attach a screenshot if
possible.

I cannot get service.

**Comment by teller** [comment]
Server misconfiguration due to human error. Apologies about the interruption, got fixed roughly 40 minutes ago.
