### ISSUE TITLE
[Win10]Screen share not working

### ISSUE THREAD

**Issue by SFort** [wireapp/wire-desktop#894]
Wire Version: 2.15.2750
Wire for Web Version: 2017.08.08.1509
OS: Windows10
Do you have an antivirus software installed: No

This issue only occurs while in a call with @dogman176.
When either of us try to share screen wire starts beeping as if it lost connection.
This does not happen with video calls and we both have the exact same wire version.

**Comment by zeebok** [comment]
I can confirm this. My friend is using Win10, I am using Linux. I can share my screen but when he tries to it beeps like it lost connection.

**Comment by gregor** [comment]
Screensharing uses a higher resolution than a regular video call and thus requires more bandwidth. (And obviously also a lot more bandwith than an audio call) A beeping sound indicates that your connection might not be stable enough. How are you connected to the internet? Do you know the client the other side of the call was using? Are you screen sharing in an audio call or did you previously have a video call and switched to screensharing from there?

**Comment by FHTheron** [comment]
I have sent some logs and info on a support ticket (49001, handled by Lucy) and for me it seems to have been caused by Virtualbox Host-only adapters. When I removed those virtual network adapters on both sides, screen sharing was perfect and call setup time went from 10 or 20 seconds to about 3 seconds (all over LAN). This may also relate to VPN virtual adapters.

**Comment by SFort** [comment]
Just did some testing again with another person he lives about a kilometer away from me he has 90/10Mbps, i have 100/20Mbps, both connections stable.
He can share screen, I cannot.
What i am sure of is this is not a stability issue.
edit: we are both on Win10 computers(with wired internet connections not wireless)

**Comment by zeebok** [comment]
FHTheron's solution worked. The other person, who was running Windows 10, also had Virtualbox adapters. He disabled those and screen sharing started working for him.
