### ISSUE TITLE
Call completion fails / Call answer fails

### ISSUE THREAD

**Issue by northpoint412** [wireapp/wire-desktop#895]
Wire Version: 2.15.2751
Wire for Web Version: 
OS: Linux Mint 18.1 64bit

wire-desktop fails to complete calls or answer calls after a few minutes of inactivity.

What steps will reproduce the problem?
1. Start wire-desktop
2. Make call after a few minutes
3. Restart wire-desktop to make it work again.

What is the expected result?
Call should complete. Can not complete either receiving or sending calls

What happens instead?
Making a call: Wire rings other person and then drops the call.
Receiving a call: Wire answers call but fails to complete connection 

Please provide any additional information below. Attach a screenshot if
possible.

Started Wire-Desktop in a terminal to capture any error messages and this is the error message when this happens:

**[22710:0822/130307.415164:ERROR:audio_send_stream.cc(93)] Failed to set up send codec state.**

Computer is on PIA (VPN)

**Comment by gregor** [comment]
Please update to the latest available version. A lot of calling fixes have been made in the desktop app and the webapp it relies on for calling purposes. Please open another issue, if your problems reoccur.
