### ISSUE TITLE
Wire fails to connect to server after hibernation

### ISSUE THREAD

**Issue by xtotdam** [wireapp/wire-desktop#898]
Wire Version: 2.15.2750
Wire for Web Version: 2017.08.08.1509
OS: Windows 7 SP 1
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Hibernate computer
2. Start up again
3. There is chance to fail while connecting to servers

What is the expected result?
Connection to servers =)

What happens instead?
![2017-08-24 11 48 26](https://user-images.githubusercontent.com/5108025/29658309-0a0058f4-88c3-11e7-815a-8fdf13ee06b3.png)

The only way to fix it I found is to restart Wire.
It is non trivial to reproduce since this does not occur after every single Hibernation-StartUp cycle. 
May be a duplicate of #843

**Comment by gregor** [comment]
Closing this as a duplicate
