### ISSUE TITLE
How to show main menu after hiding it?

### ISSUE THREAD

**Issue by mnn** [wireapp/wire-desktop#901]
Wire Version: don't know, because I can't show the main menu... It was downloaded from your web and installed today (25.8.2017, the deb package).
OS: Kubuntu LTS 16.04
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. somewhere in options check hide main menu

What is the expected result?
Being able to unhide main menu. I have tried alt hotkey which should work on Windows, but it did nothing.

What happens instead?
Main menu remains hidden. Restart of the application doesn't help.

Please provide any additional information below. Attach a screenshot if
possible.
I don't think it's necessary posting a screenshot with hidden main menu...

**Comment by gregor** [comment]
Unfortunately the ALT key is not reliably showing the menu again once you hid it. We are aware of the issue. Usually you can click the title bar of the application and click the ALT key at the same time to unhide it. Then simply select the menu option again to keep it sticky once more.

**Comment by FHTheron** [comment]
On Windows 10 I can *always* use ALT to show the menu again **if** I am in the Options/Preferences page. In the normal view it doesn't work, in options it does.

**Comment by Steef435** [comment]
^ Observing the same as FHTHeron on dwm (Linux). Is it an option to include the show/hide setting in the preferences page?

**Comment by Jemi9OD** [comment]
This happened to me today on Windows 10.  No amount of clicking Alt + mouse, Alt by itself, or any other keys apparently, will give me the option to "undo" hide main menu.

**Comment by chemistmertkoc** [comment]
![image](https://user-images.githubusercontent.com/39067623/39723236-e0b810b8-524d-11e8-9ee2-7ba490f5b2b8.png)

how can I fix this ? 

Alt key is not working

**Comment by lbriais** [comment]
One year later still no fix ??
On Ubuntu 18.04 same issue... I did hide the menu by mistake and now, no way to have it back...

Is there some kind of suicidal tendencies behind not fixing such obvious stupid bugs ???

**Comment by ffflorian** [comment]
@chemistmertkoc This does not seem to be related to Wire.

@mnn Did you try clicking on the account selector space and then pressing <kbd>Alt</kbd>?

**Comment by maximbaz** [comment]
I found this key combination to be a reliable workaround to show the hidden menu:

1. Hold `Alt`
2. Click with left mouse button anywhere in the window, e.g. on your last message
3. Release `Alt`

Doing steps 1-3 once time will show the menu, repeating 1-3 will hide menu again.

**Comment by Jorilx** [comment]
It looks like "Alt + [a-z]" works too
