### ISSUE TITLE
Add the ability to rename contacts

### ISSUE THREAD

**Issue by ddobrev** [wireapp/wire-desktop#902]
Wire Version: 2.15.2750
Wire for Web Version: 2017.08.24.1057
OS: macOS Sierra 10.12.6
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Add a contact.

What is the expected result?

The contact can be renamed in the list of contacts.

What happens instead?

The contact cannot be renamed in the list of contacts.

Skype and other messenger offer users to rename contacts any way they like. For example, if one uses the Cyrillic script, he might feel more comfortable renaming a contact from a country with a Latin alphabet.

**Comment by gregor** [comment]
Thanks for your feature request. I am linking this to a duplicate and closing it in favor of the other one.

https://github.com/wireapp/wire-desktop/issues/44

**Comment by githubmavin** [comment]
I can't believe this feature hasn't been implemented yet.  It would not be very difficult to add and it would make the application so much better.    Far too many contacts add stupid names or non-descriptive names and you have no idea who they are without any means of correcting it.  Having the ability to rename or alias local contacts is an absolute necessity.   The developers not taking this feature request seriously means they do not want WIRE to propagate and become a useful tool.
