### ISSUE TITLE
Wire doesn't always turn off the webcam after hanging up.

### ISSUE THREAD

**Issue by Farioko** [wireapp/wire-desktop#904]
Wire Version: 2.15.2751-2
Wire for Web Version: 2017.08.24.1057
OS: Linux (Ubuntu, Arch)
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Call someone
2. Hang up

What is the expected result?
Wire stops spying on me by turning off the webcam.

What happens instead?
Wire doesn't turn off the webcam after hanging up.

**Comment by gregor** [comment]
We have added a call log features option in your account preferences. If you still see these problems please get in touch with our customer support providing them with logs. I am going to close the issue here.
