### ISSUE TITLE
v4l2loopback device streams offset to the right

### ISSUE THREAD

**Issue by CrisBRM** [wireapp/wire-desktop#910]
Wire Version: git
OS: Solus Linux

What steps will reproduce the problem?
1. Build v4l2loopback.
2. `modprobe videodev && insmod ./v4l2loopback.ko devices=1 video_nr=2 exclusive_caps=1`
3. Get webcamstudio and open it with the jre.
4. Add webcam, switch to YUV colourspace, click on 'Dummy video device' to start streaming, and then open the previously added webcam, check the resolution and offset are correct and press Play.
5. Open wire and go to settings, Audio and video settings (or attempt to video call the bot after selecting the correct video output).
6. Observe the output.

What is the expected result?
Video shifts to the right.

What happens instead?
Video offsets a few pixels to the right.

Please provide any additional information below. Attach a screenshot if
possible.

![screenshot from 2017-08-31 17-43-07](https://user-images.githubusercontent.com/9098352/29934684-fde1d4ba-8e73-11e7-9ad3-72e66f18ae0b.png)

Problem does not occur on test page https://www.touchdevelop.com/bozca on chrome-62.0.3198.0 (Official Build) dev (64-bit).
![screenshot from 2017-08-31 17-49-19](https://user-images.githubusercontent.com/9098352/29934957-02024b46-8e75-11e7-8cd7-34c906b6848f.png)

Apparently it also works on skype:
![screenshot from 2017-08-31 18-07-51](https://user-images.githubusercontent.com/9098352/29935657-69c97ae0-8e77-11e7-9513-31e95ac333c1.png)

This comment is important: https://github.com/wireapp/wire-desktop/issues/402#issuecomment-325735039

**Comment by gregor** [comment]
Thank you for your report. Our app is based on electron, an approach that is based on Chromium to display a website. Esentially we behave a like a browser website. We get a video stream from this browser and display it. If the content of the video stream is shifted, we do not detect that. We do not touch your video. We do not want to touch your video. Seems like your specific setup is incompatible with the Chromium version app based electron relies upon.

**Comment by CrisBRM** [comment]
@gregor Point being, you should update chromium because the stream is clearly being touched. Skype is electron based and did not have this problem (it's now a lot more severe), and chromium behaves normally as depicted in the picture above.

**Comment by gregor** [comment]
We are updating electron as often and as early as we can. Production releases are currently at 1.6.13/1.7.7/1.7.8 depending on your platform. I hope that one of the next Electron and thus Chromium updates will fix your issue.
