### ISSUE TITLE
Wire Desktop does not build under openSUSE

### ISSUE THREAD

**Issue by ankls** [wireapp/wire-desktop#914]
Wire Version: git commit 97ad839ab2c8499ff5dd56ec55dd3eb005dfe477, Sat Sep 2 11:31:11 2017 +0200, "chore(package): update electron-mocha to version 4.0.2 (#912)"

Wire for Web Version: n/a

OS: openSUSE Leap 42.3 x86-64
> uname -a
Linux jordan 4.4.79-19-default #1 SMP Thu Aug 10 20:28:47 UTC 2017 (2dd03e8) x86_64 x86_64 x86_64 GNU/Linux

Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. git clone https://github.com/wireapp/wire-desktop.git
2. cd wire-desktop/
3. npm install

What is the expected result?
Building wire-desktop

What happens instead?
Build fails

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ankls** [comment]
This happens in shell:

> npm install

> wire-desktop@ preinstall /home/ankls/.apps/Wire/wire-desktop
> cd electron && npm install

/
> node-addressbook@1.2.0 install /home/ankls/.apps/Wire/wire-desktop/electron/node_modules/node-addressbook
> node-gyp rebuild

make: Entering directory '/home/ankls/.apps/Wire/wire-desktop/electron/node_modules/node-addressbook/build'
  CXX(target) Release/obj.target/electron-addressbook/AddressBook.o
  CXX(target) Release/obj.target/electron-addressbook/Person.o
  CXX(target) Release/obj.target/electron-addressbook/wrapper.o
  SOLINK_MODULE(target) Release/obj.target/electron-addressbook.node
  COPY Release/electron-addressbook.node
make: Leaving directory '/home/ankls/.apps/Wire/wire-desktop/electron/node_modules/node-addressbook/build'
winston@2.2.0 node_modules/winston
├── cycle@1.0.3
├── stack-trace@0.0.10
├── eyes@0.1.8
├── isstream@0.1.2
├── async@1.0.0
├── pkginfo@0.3.1
└── colors@1.0.3

node-addressbook@1.2.0 node_modules/node-addressbook
└── nan@2.7.0

> wire-desktop@ install /home/ankls/.apps/Wire/wire-desktop
> cd electron && npm run rebuild-native-modules


> wireinternal@ rebuild-native-modules /home/ankls/.apps/Wire/wire-desktop/electron
> node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"

/home/ankls/.apps/Wire/wire-desktop/electron/rebuild-native-modules.js:37
let args = process.argv.slice(2);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

npm ERR! Linux 4.4.79-19-default
npm ERR! argv "/usr/bin/node4" "/usr/bin/npm4" "run" "rebuild-native-modules"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! wireinternal@ rebuild-native-modules: `node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wireinternal@ rebuild-native-modules script 'node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"'.
npm ERR! This is most likely a problem with the wireinternal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wireinternal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls wireinternal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ankls/.apps/Wire/wire-desktop/electron/npm-debug.log

npm ERR! Linux 4.4.79-19-default
npm ERR! argv "/usr/bin/node4" "/usr/bin/npm-default" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! wire-desktop@ install: `cd electron && npm run rebuild-native-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wire-desktop@ install script 'cd electron && npm run rebuild-native-modules'.
npm ERR! This is most likely a problem with the wire-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd electron && npm run rebuild-native-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wire-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls wire-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ankls/.apps/Wire/wire-desktop/npm-debug.log

**Comment by ankls** [comment]
This is npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node4',
1 verbose cli   '/usr/bin/npm4',
1 verbose cli   'run',
1 verbose cli   'rebuild-native-modules' ]
2 info using npm@2.15.11
3 info using node@v4.8.4
4 verbose run-script [ 'prerebuild-native-modules',
4 verbose run-script   'rebuild-native-modules',
4 verbose run-script   'postrebuild-native-modules' ]
5 info prerebuild-native-modules wireinternal@
6 info rebuild-native-modules wireinternal@
7 verbose unsafe-perm in lifecycle true
8 info wireinternal@ Failed to exec rebuild-native-modules script
9 verbose stack Error: wireinternal@ rebuild-native-modules: `node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm4/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm4/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid wireinternal@
11 verbose cwd /home/ankls/.apps/Wire/wire-desktop/electron
12 error Linux 4.4.79-19-default
13 error argv "/usr/bin/node4" "/usr/bin/npm4" "run" "rebuild-native-modules"
14 error node v4.8.4
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error wireinternal@ rebuild-native-modules: `node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"`
17 error Exit status 1
18 error Failed at the wireinternal@ rebuild-native-modules script 'node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"'.
18 error This is most likely a problem with the wireinternal package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./rebuild-native-modules.js "electron-rebuild" "-f -m ./"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs wireinternal
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls wireinternal
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ankls** [comment]
Added files as comments since uploading them as files didn't work.

**Comment by manasb** [comment]
I have:

```
> node -v
v6.11.2
```
and
```
> npm -v
5.3.0
```

Perhaps try upgrading `node/npm`? I've had issues building wire-desktop when my `node/npm` aren't up to date.

**Comment by ankls** [comment]
> node -v
v4.8.4
> npm -v
2.15.11

So I'll seek out for new versions. Thanks for the hint.

**Comment by ffflorian** [comment]
@ankls Please use at least Node.js 7 for building.
