### ISSUE TITLE
[Enhancement] Button to delete message

### ISSUE THREAD

**Issue by snakyjake1** [wireapp/wire-desktop#922]
I have a lot of messages I want to delete.  I want to reduce the number of steps and click to delete the messages.

Instead of the "...", can we get a simple X to quickly delete the messages with less steps?
Maybe even message check boxes for multiple deletes too.

Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Linux

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
