### ISSUE TITLE
[Wish]  Hide Avatar

### ISSUE THREAD

**Issue by snakyjake1** [wireapp/wire-desktop#923]
I would like to hide the contact's picture from the main chat window.

Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Linux

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
