### ISSUE TITLE
Timed messages

### ISSUE THREAD

**Issue by ehodzic** [wireapp/wire-desktop#928]
Wire Version: Desktop (I guess all?)
OS: Windows 10
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Unfocus main Wire window. Select another application, or taskbar.
2. Have a person send a timed message. For example one that expires in 5 seconds.
3. You will be able to see the message for an indefinite period of time, as long as you don't move focus to Wire application.

What is the expected result?
The message should expire on my client when it does for the sender.

What happens instead?
The message stays on my client until I focus on the window, after which the timed message countdown begins. This poses a security and privacy risk.

On one hand, it's nice that the receiver gets to actually see the message if they missed it at the time it was sent, but the whole idea of timed messages is that sender should be confident that once the timed limit is exceeded, the message is gone, and no one else can read it anymore.
The way it's currently done needs to be changed if users are to feel confident about using timed message feature of Wire.

**Comment by Silun** [comment]
Some testing today revealed another issue, assuming there is one iOS and one Windows desktop client in use: When receiving multiple timed messages while the desktop client is unfocussed, read them on the iOS device and wait until they disappear.
Then, focus the desktop client. Both messages will now simultaneously countdown to their expiration. In my test, the order was reversed: The latter messages disappeared mid-countdown, before the earlier messages vanished. All of them disappeared before the countdown hit zero.

**Comment by gregor** [comment]
This decision was made intentionally. If we remove the message from the view when the counter runs out without the window having focus, it will also be deleted on all your other devices within a short timeframe as the deletion is synced across your devices. Thank you very much for your feedback. We will consider it for changes to the features - but currently it works as intended.

One idea to improve this would be to show the obfuscated content that the sender sees after timeout while the window is not in focus. This would not break the other cases.
