### ISSUE TITLE
[Wish] Hide or resize contact list.

### ISSUE THREAD

**Issue by Thamone** [wireapp/wire-desktop#929]
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Ubuntu 16.04
Do you have an antivirus software installed: No

is it possible to hide, resize the contact list(or separate it from chat window)? I think it take too much space.
![wire_301](https://user-images.githubusercontent.com/28747875/30191874-12259b8c-946e-11e7-918e-4e5a9abcd296.jpg)

**Comment by gregor** [comment]
Thank you very much for your feature request. At this time we do not have any immediate plans to change the general interface structure of the app but your feedback will be taken into consideration whenever we talk about major changes to the design.
