### ISSUE TITLE
Managed to log twice can can't fully log-out.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#932]
![image](https://user-images.githubusercontent.com/388716/30254314-71994580-9664-11e7-8398-94a869f3591c.png)

**Comment by gregor** [comment]
Thank you for your report. We will address this issue by offering a way to remove unwanted accounts.

**Comment by gregor** [comment]
With the latest version you can now remove the accout easily if you right-click and on the account avatar and select "Remove account".

https://github.com/wireapp/wire-desktop/pull/1050
