### ISSUE TITLE
does not display voice message

### ISSUE THREAD

**Issue by jubalh** [wireapp/wire-desktop#933]
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: openSUSE Tumbleweed
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Person A using Wire on iPhone sends voice message while Person B is not online
2. Person B goes online using Wire Desktop (but doesn't see voice message)
    They continue talking and only when Person A sais "did you see my voice message" it get's  apparent that something went wrong.
3. Person B checks on Wire Android at the time the voice message should have arrived.
    There is a loading sign `...` but even after waiting a couple of minutes there is no way to click on play or anything similar.

What is the expected result?
Person B gets the voice message on Wire Desktop and Wire Android and can listen to it.

What happens instead?
Person B doesn't get any sign of a voice message on Wire Desktop.
And sees that there is something but not what on Wire Android.

Sorry, not sure if this is reproducible or works for others :-/

**Comment by gregor** [comment]
@mikeger Sounds like a sending side issue to me. Can you please look into it?

**Comment by mikeger** [comment]
Hey @jubalh , can you confirm that the message appears delivered on the sender side?

**Comment by jubalh** [comment]
@mikeger yes the sender told me that he can see a the voice message in his history.
Left side a play button, time of the voice message (9 seconds) and the graph.

**Comment by jubalh** [comment]
No reason for closing mentioned. No commit for a fix mentioned.

But also of not much interest (to me) anymore because I switched away from Wired.
