### ISSUE TITLE
Install fails on Mageia 6 (neon ERR! spawn cargo ENOENT)

### ISSUE THREAD

**Issue by f4th0m** [wireapp/wire-desktop#935]
Wire Version: current/latest from github
Wire for Web Version: current/latest from github
OS: Linux/Mageia 6 stable latest
Do you have an antivirus software installed: ClamAV (does not interfere)

What steps will reproduce the problem?
1. Try to install
2. Intall fails with:
> wireinternal@ rebuild-neon /home/fathom/Letöltések/wire-desktop/electron
> node ./rebuild-native-modules.js "electron-build-env" "neon build libsodium-neon"

neon info forcing rebuild for new build settings
neon info running cargo
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

What is the expected result?
It installs.

What happens instead?
It does not install.

Please provide any additional information below. Attach a screenshot if
possible.
installed libs/deps:
lib64sodium18-1.0.12-1.mga6
lib64sodium-devel-1.0.12-1.mga6
lib64neon27-0.30.1-2.mga6
rust-1.19.0-1.mga6

**Comment by f4th0m** [comment]
Any info I should post to make debugging easier? Thanks!

**Comment by ffflorian** [comment]
Hi @f4th0m, thanks for reporting. This issue is due to Rust's `cargo` missing on your machine (or not in your `PATH`) but it should even work without Rust. I'll have a look into this.

**Comment by f4th0m** [comment]
Yes it does work without that.
Also after installing cargo it compiles.
Thanks!
