### ISSUE TITLE
How are device fingerprints generated?

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#937]
> Wire gives every device a unique fingerprint. 

How are these device fingerprints generated? IP addresses? MAC addresses? What happens if I combine Wire with Tor? Would this trigger device alerts with my verified conversational partners?

**Comment by gregor** [comment]
No, the fingerprint is based on your cryptographic identity. Using different networks to sign in with the same device will not change it. Please check our whitepaper at https://wire.com/privacy/ if you are interested in more details.
