### ISSUE TITLE
Add option to turn off notifications completely

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#938]
I like the flexibility of customizing how Wire notifies me in the system tray. However, the fourth option "Off" still creates a red notification circle on the Wire icon in the system tray. Could you please add a fifth option which is entirely silent and rename the current "Off" setting to sth like "System-tray dot"?

**Comment by gregor** [comment]
Thanks for your report. We will keep it in mind when revisiting this feature. Currently the dot on the app icon is linked to the content of the browser window title bar. On web you would see unread messages in the browser window title.

@Yorgos-V @raphaelrobert Should we change this moving forward and not show unread messages in the titlebar thus also in the app icon if notifications are set to off? Add another option or keep the behavior as is?

**Comment by baimafeima** [comment]
> Currently the dot on the app icon is linked to the content of the browser window title bar.

I like the dot, this is a nice feature and I think it should definitely be kept as one of these options but when clicking "Off" it should be entirely silent without any notifications.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
