### ISSUE TITLE
Offer option to delete chat log

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#940]
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Launch Wire

What is the expected result?
I would like to have the option to manually delete the entire chat log, not just to archive it. 

What happens instead?
Currently, there is no option to delete the chat log. 

Currently the chat log is always present when using Wire. Could you offer an option in the preferences to delete the chat log or to not log it in the first place? I know there are options to have self-destructing messages but I'd prefer an additional option which can be set in the preferences for the entire application, not just per chat partner.

**Comment by gregor** [comment]
There is. In the conversation list, hover over the conversation you want to delete, click on the little arrow that will open the context menu and select the option to delete.

**Comment by baimafeima** [comment]
@gregor Ah I see, but it is not very intuitive. I initially thought this will remove a previously added contact so I didn't click on it. Any chance to improve this? 
Still, my original point is to have an option in the settings that there are no chat logs in the first place and secondly, to have an option to delete all of them, again in the settings, instead of having to delete them for each chat partner individually.

**Comment by gregor** [comment]
@baimafeima How would you name the option to remove the conversation content instead of "Delete"

**Comment by baimafeima** [comment]
@gregor Perhaps just "Delete chatlog". The user interface at this point is a bit counter-intuitive though, would have to think about how to make this more self-evident.

**Comment by baimafeima** [comment]
#946 Opened new, more specific issue regarding a global option to have all chatlogs disabled by default instead of having to manually remove them.
