### ISSUE TITLE
Support Chinese character-based language input

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#942]
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

What steps will reproduce the problem?

1. Install IBus or any other comparable input method editor. 
2. Launch Wire
3. Switch default language to Chinese. 
4. Messages will only be displayed in romanized pinyin with no option to actually type in Chinese. 

What is the expected result?
I would like to have the option to type in Chinese characters. This is a critical bug as without CJK/IBus support I cannot use Wire. 

What happens instead?
Currently, Wire does not support IBus and CJK (Chinese, Japanese, Korean) language input.

**Comment by cwmke** [comment]
ibus CJK is working for me in Firefox as well as the appimage form on Fedora. Could you be missing one of the ibus packages?

**Comment by baimafeima** [comment]
@cwmke Not that I know of.

**Comment by gregor** [comment]
With the nature of this being a feature request I am going ahead with closing it.
