### ISSUE TITLE
Add Ring and Tox to your technical overview page

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#945]
I especially liked reading through your technical oveview page: https://wire.com/en/privacy/
It would be great to add two of the strongest contenders for privacy to this list to increase transparency and comparability: Tox (https://tox.chat/) and Ring (https://ring.cx/). Both are comparable to Wire in terms of features in that they offer text, voice and video chats.

**Comment by gregor** [comment]
Thank you very much your feedback. This repositories is used to track issues on our desktop apps. Inquieries directed at Wire in general are best filed at https://github.com/wireapp/wire/issues. I will go ahead and forward the apps you mentioned for consideration to be added to the comparison.
