### ISSUE TITLE
Offer global "Disable logging" option via settings

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#946]
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

What is the expected result?
I would like to disable all logs by having an option in the settings. The goal is to have all chat logs disabled by default. 

What happens instead?
Currently, there is no option to do so and instead chat logs must be deleted manually and afterwards instead of having them disabled by default.

**Comment by baimafeima** [comment]
So the idea is to prevent logs globally (per Wire instance) from being created in the first place instead of having to manually delete chat logs per individual contact.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
