### ISSUE TITLE
Sharing message option

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#950]
Wire Version: 2.16.2806
Wire for Web Version: 2017.08.31.1421
OS: 10 pro x64
Do you have an antivirus software installed: N/A
What steps will reproduce the problem?
1. Click on a message option on one of their  own message

What is the expected result?
Having the same option than on Wire mobile (Copy, Like, Modify, Share, Delete)

What happens instead?
Only have: Like, Edit, Delete for me, Delete for everyone and not Share

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
@IpsmLorem Thank you for your request. We are aware of the fact that the share/forward option is not available on the desktop client. It is on our list of missing features. I cannot comment on if/when it will be implemented. I am going ahead with closing this issue as we intend to use github to track actual bugs only.
