### ISSUE TITLE
I'll just leave this here

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#951]
![image](https://user-images.githubusercontent.com/388716/30525521-1bcee8cc-9bd6-11e7-8fe4-3a400f1380b3.png)

![image](https://user-images.githubusercontent.com/388716/30525498-ac434a34-9bd5-11e7-90bf-df1de2212873.png)

**Comment by happyGNU** [comment]
You should probably read this: 

http://www.catb.org/esr/faqs/smart-questions.html#courtesy

I recommend you to read all that page. But start by the courtesy part.

**Comment by jack-cole** [comment]
Here's Wire.
![image](https://user-images.githubusercontent.com/5460372/30559731-7a5910ae-9c6a-11e7-8c33-55279a32ba6b.png)

What's your point @Transisto?

**Comment by Yorgos-V** [comment]
Hello @Transisto, first of all I would like to thank you for your post, we really appreciate your feedback. 
I think you highlight pretty clearly that our starting point for searching for people or creating a new conversation is not aligned with the common design patterns used by our competition. The improvement of the search feature is something that is included in our future plans and we hope that we will soon be able to provide a better experience on this field. 
For the moment, on Wire, you can search for people and conversations when you get to the Start UI screen (right now, by tapping the + icon, something that will change soon) and you can search for content within a conversation by tapping on the magnifying glass icon on the top header of each conversation.
Once again, thank you very much for your contribution.

**Comment by Transisto** [comment]
thanks @Yorgos-V for your reply.

I could have been more clear about what I was referring to.

I was referring to quick contact search. To me any extra steps between opening up the app and texting the right people should be removed.

I think Discord has it right. With their CRTL-K
https://support.discordapp.com/hc/en-us/articles/115000070311-Quick-Switcher-T-A-Y-N-E-

Right now Wire expect us to enter more names when we chose one, expecting us to want build a new groups every-time we're searching for a contact.

**Comment by gregor** [comment]
@Transisto Quick hint for CTRL-N: If you start to search the top match will be entered to the users field if you hit enter. If you hit enter once more without adding new input the conversation with the selected contact will be opened without the need to use your mouse.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
