### ISSUE TITLE
2.15.2750 macOS: `pkg` signature

### ISSUE THREAD

**Issue by commitay** [wireapp/wire-desktop#963]
Wire Version: `2.15.2750`
OS: macOS `10.12.6`
Do you have an antivirus software installed: No

The current Wire macOS `pkg` is signed with an expired certificate.

https://github.com/wireapp/wire-desktop/releases/tag/macos%2F2.15.2750

![wire](https://user-images.githubusercontent.com/26216252/30723597-bf2f757e-9f7b-11e7-89b2-b5ac96833e78.png)

**Comment by gregor** [comment]
@commitay Thanks for your report. We have already updated the certificates on the build machines. The next build to be released soon will be signed with an updated certificate.

**Comment by commitay** [comment]
https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.0.2814

Thanks @gregor!
