### ISSUE TITLE
JavaScript error: Uncaught exception - _useBadgeIcon

### ISSUE THREAD

**Issue by bladex452** [wireapp/wire-desktop#968]
Wire Version: 2.16.2806
Wire for Web Version: 2017.08.31.1421
OS: Windows 10 64bit
Do you have an antivirus software installed: bitdefender

What steps will reproduce the problem?
1. receive message
2. click tray icon to make program active
3. just about anything, pops up all the time

![buggyz0r](https://user-images.githubusercontent.com/32205978/30759905-1134e03c-9fa6-11e7-9816-6be82ac2ff7b.jpg)

**Comment by stlaz** [comment]
Still to be seen in the latest release of the desktop application.

**Comment by MarkoPetteri** [comment]
Is Version 3.0.2816 the latest version? I had a error message like this yesterday, several times and after couple of the the whole app went black. Even after restarting the app it was all black and un-responsive, except for the menu bar at the top.

I'm sorry I didn't copy the error message for bug report. The app is working now after re-booting.

Pop!_OS 17.10 64-bit | GNOME 3.26.2 | AMD Ryzen 5 1400 Quad-Core Processor × 8 | 7,8 GB RAM | 25 GB SSD + 120 GB SSD | GeForce GT 630/PCIe/SSE2 | Focusrite Scarlett 2i2

**Comment by gregor** [comment]
@MarkoPetteri Yes, at this time the version you are using is still the latest we have released. We have made a number of smaller fixes to the code already but are still looking at when to release publicly next.

**Comment by MarkoPetteri** [comment]
My app went black again and disconnected the call I was on at the time. Restarting the app doesn't help.

![screenshot from 2017-12-22 16-44-20](https://user-images.githubusercontent.com/23585660/34305970-72d455a8-e749-11e7-9cac-9f18355d4ddd.png)

**Comment by cardassian-tailor** [comment]
I just had this error last night, and ive had it a few times in the past. Is there anything I can do on my end to further narrow down exactly what is causing this? 

Mine was within 3.0.2828 in the tray.badge.icon, tray.js, main.js, events.js, and a few others.

**Comment by gregor** [comment]
Yes, disable any tools that remove files from your temp folder. That should do the trick while we find some time to fix it.

**Comment by cardassian-tailor** [comment]
I assume your referring to tools like glary utilities, ccleaner, etc? 

I'm not using any of those.

**Comment by gregor** [comment]
Thanks for the info. This seems to be the most common case trackend down with the help of our customer support. We will continue our investigation.

**Comment by terrar** [comment]
Hi! Anything new here?
Same problem same OS.

**Comment by gregor** [comment]
We published a new release today that properly addresses this problem. JavaScript errors stating that an image resource is missing should no longer happen. The catch we put in place was removed in favor of a proper fix since the initial approach had the side effect of not showing notifications properly in some cases.
