### ISSUE TITLE
Images not loading, 

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#969]
Image not loading, 

I get was getting broken image link before after rebooting Wire I only get these loading square : 
![image](https://user-images.githubusercontent.com/388716/30766371-87d19f66-9fc2-11e7-9036-a32221665b60.png)

The older picture loads and it all work fine on android.

**Comment by ffflorian** [comment]
Hi @Transisto, thanks for reporting. Is the image still not loading? Or maybe it was just a server hickup?

**Comment by Transisto** [comment]
Seems fine for now
