### ISSUE TITLE
cannot switch language

### ISSUE THREAD

**Issue by McKanty** [wireapp/wire-desktop#974]
Wire Version: linux 2.15.2751

What steps will reproduce the problem?
1. Menu Wire->Language->Polski
2. (Message: Uruchom ponownie? (close wire & run again)
3.start wire again

What is the expected result?
Interface in Polish language

What happens instead?
still english

on Windows 7 PL this same problem.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
@McKanty Thanks. This is a known issue we recently fixed but has not made it to a public build just yet. Please bear with us a tiny little bit longer. If you want to switch the language right now you can select the option to restart later. Close the app manually and start it again and the language will have switched as desired.

**Comment by gregor** [comment]
@McKanty The fix was part of the release we managed to get out to the public yesterday after all.
