### ISSUE TITLE
Editing a message causes the user to appear above it

### ISSUE THREAD

**Issue by ddobrev** [wireapp/wire-desktop#977]
Wire Version: 2.15.2750
Wire for Web Version: 2017.09.26.1300
OS: macOS Sierra 10.12.6
Do you have an antivirus software installed: No.

What steps will reproduce the problem?
1. Send a message;
2. Send a second message;
3. Edit the second message.

What is the expected result?
The messages are listed one after another with no interruptions except by the other user.

What happens instead?
The user's name appears above the edited message.

**Comment by gregor** [comment]
Thank you very much for your feedback. This is necessary and currently by design as the edit indicator is part of the message header. If we don't show the header including the image and name of the user, the edit indicator will be lost in space.

**Comment by gregor** [comment]
We will definitely consider your input and make design aware of your feedback. There are no plans or an intention to change this any time soon though. Just trying to manage your expectations.

We intend to keep the issues on this repository to track bugs. While we value your feedback and will consider it, I will not reopen the issue.
