### ISSUE TITLE
Missing or B/W emoticons in Win 7

### ISSUE THREAD

**Issue by fichtennadel** [wireapp/wire-desktop#980]
Wire Version: 2.17.2808
Wire for Web Version: 2017.09.26.1300
OS: Win7 64bit

see https://github.com/wireapp/wire-webapp/issues/1733 , emoticons are missing or b/w:
![image](https://user-images.githubusercontent.com/2324670/30898017-83e5a326-a359-11e7-8293-737173557120.png)

**Comment by ffflorian** [comment]
@fichtennadel Please don't open the same ticket multiple times.
Feel free to reopen if this becomes a Wire Desktop specifig issue.

**Comment by fichtennadel** [comment]
This is also an issue in wire-desktop, see screenshot or try yourself.
It's also an issue in web, but in my understanding these two different repos.

**Comment by maximbaz** [comment]
The desktop app is basically just a frame, that opens webapp inside of it 🙂 
Thus, once the bug is fixed in `wire-webapp` repo, it will be automatically fixed here as well.

**Comment by ffflorian** [comment]
Thanks for making it clear @maximbaz.
