### ISSUE TITLE
Linux Update Instructions

### ISSUE THREAD

**Issue by TomSea** [wireapp/wire-desktop#984]
Wire Version: 2.13.2741
Wire for Web Version: 2017.09.26.1300
OS: Mint 18.2
Do you have an antivirus software installed: No

What steps will reproduce the problem?
I see instructions on how to install on Linux but no instructions on how to upgrade to the latest version. Do I need to remove the old version manually to update? Please post update instructions. I'm new to Mint Linux.
Thanks.

**Comment by mythsunwind** [comment]
If you have added the Wire repository to your sources list, your package manager will manage the updates for you. If you run the following commands, you should get the new version:
```
apt-get update
apt-get upgrade
```

**Comment by TomSea** [comment]
This worked only after I add a line to my /etc/hosts file and rebooted:

127.0.0.1 <MyHostName>

It now works perfectly. Can this solution be added to the wiki? Thanks for your help!
