### ISSUE TITLE
Discriminate same device type with number

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#991]
Wire Version: 2.17.2808
Wire for Web Version: 2017.09.26.1300
OS: Windows 10 x64
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Open a 1 on 1 conversation
2. Click on the nickname of your contact / device

What is the expected result?

Having their device discriminated by a number when there are several devices of the same type (eg. "Phone 1" and "Phone 2" instead of Phone and Phone.

The number must not change. For example if the user remove "phone  1", "phone 2" must not become "phone 1" and remains "phone 2".

![image](https://user-images.githubusercontent.com/1250795/31045203-9d227594-a5de-11e7-8afa-2ee5adf5767b.png)

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
