### ISSUE TITLE
User cannot consult their discussion history without network

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-desktop#992]
Wire Version: 2.17.2808
Wire for Web Version: 2017.09.26.1300
OS: Windows 10 x64
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Go on a business fly trip (no network)
2. Open your laptop with Wire desktop to prepare a meeting
3. Expect to

What is the expected result?
- Be able to check meeting appointements and details (conversation and files) previously sent on Wire

What happens instead?
- Wire doesn't start without network.
- Even if Wire would starts, the files/media are not all localy stored in indexdb.

Solution:
- All necessary Wire binary must be stored on the computer
- Be able to choose to store all received media/files locally and not on Wire server

**Comment by gregor** [comment]
Thank you very much for your feature request. We definitely want to improve the offline experience but unfortunatly only making slow progress on the way there.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
