### ISSUE TITLE
"Check Spelling While Typing" option doesn't have any effect on Ubuntu 16.04 (LTS)

### ISSUE THREAD

**Issue by lrenaud** [wireapp/wire-desktop#998]
**Wire Version:** 2.17.2813
**Wire for Web Version:** 2017.09.26.1300
**OS:** Ubuntu 16.04.3 LTS, xenial
**Do you have an antivirus software installed:** No

**What steps will reproduce the problem?**
1. Launch wire, navigate to Edit -> "Check Spelling While Typing" and ensure the option is checked
2. Type a misspelled message into the text entry for the current selected chat
3. Misspelled words will not be highlighted, or indicated.
4. Uncheck the option Edit -> "Check Spelling While Typing"
5. delete and retype a misspelled message in the text entry section. No change in behavior.

**What is the expected result?**
Misspelled words should be highlighted, underlined, or indicated in some fashion when the option is enabled.

**What happens instead?**
Wire's behavior is invariant under the option. 

**Please provide any additional information below. Attach a screenshot if possible.**
Package was installed via the Ubuntu PPA repository.

Screenshot showing option enabled with spelling errors not indicated:
![wire_016](https://user-images.githubusercontent.com/836281/31238613-5a1122ee-a9af-11e7-965c-28dadabdf825.png)

**Comment by mythsunwind** [comment]
Can you check if you have installed `hunspell`? hunspell is the spellchecker that is used by wire-desktop when it is installed. We have set it as optional dependency, because it should not be necessary for users to install wire-desktop. Please also make sure to restart wire-desktop and that you installed the required dictionary for the language you use, usually the package is called something like `hunspell-en-us`. If this does not help, please reopen the ticket.

**Comment by lrenaud** [comment]
Reopen this bug please.

I have hunspell-en-us, and hunspell installed as required.

```
$ apt search hunspell-en-us
hunspell-en-us/xenial,xenial,now 20070829-6ubuntu3 all [installed,automatic]
  English_american dictionary for hunspell
```

**Comment by lrenaud** [comment]
It looks like the issue is very specific to the state of the setting when launching wire. The behavior is likely related to caching of the setting state. If enable the setting, relaunch the application then misspelled words are indicated as expected. Disabling the setting in this state has no effect however.

**Comment by gregor** [comment]
Thanks for the update.

**Comment by ffflorian** [comment]
Closed due to the removal of the spellchecker in https://github.com/wireapp/wire-desktop/pull/2023.
