### ISSUE TITLE
Wire Desktop is a "screen hog" - i.e. occupies too much of the screen

### ISSUE THREAD

**Issue by DetlevCM** [wireapp/wire-desktop#999]
Wire Version: 2.17.2813
OS: OpenSUSE Tumbleweed (same on Leap, same on Windows)

What steps will reproduce the problem?
1. Use the software

I've had a little rant about this before as this wound me up on my high DPI display on the Ultrabook. Unfortunately, the issue is even worse on a more "normal" 1920*1080 display.
Wire occupies an inordinate amount of screen space which makes it less useful as a messenger which is meant to sit unobtrusively in the background until needed.
(In fact, I'm better off using my phone for wire as a messenger...)
This issue becomes even worse for those burdened with the dreadful 1376*768 resolution.

However, there is a very real issue associated with this too: Besides filling too much of the screen, parts of the settings become obscured too. I only see a part of the webcam test image for example unless I go into full screen mode.

The response "back then" was that there are no plans of changing the wire user interface, however I recommend this is looked at. I can think back a good 10 years to a program called "QIP" which was an ICQ-client, that had a very small window that could sit unobtrusively in the lower corned of the screen. However since, all messengers seem to have worked on having bigger and bigger windows which really isn't great.

**Comment by Transisto** [comment]
I suggest making the contact panel resizable. 

I also don't think many people use quick identity switch on the left for it to take this much space for everyone.

![image](https://user-images.githubusercontent.com/388716/31289522-017fd81c-aa97-11e7-9dee-7723b38de736.png)

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
